### ISSUE TITLE
Скрипт на молитву

### ISSUE THREAD

**Issue by Kor-Angar** [dosinabox/g2nr_unofficial_update#100]
А можно сделать какую нибудь команду через консоль что бы герой ходил молиться в монастыре:
Например подошел помолился возле статуи на 10 золотых, пошле спать и так далее. 

Интересно сколько молитвы займут игрового времени. А самого меня хватит на пол часа максимум 🙂 а золоту у мага много, так как маг то воин 🙂

**Comment by Kor-Angar** [comment]
Сотый топик ⏳

**Comment by dosinabox** [comment]
> А можно сделать какую нибудь команду через консоль что бы герой ходил молиться в монастыре:
> Например подошел помолился возле статуи на 10 золотых, пошле спать и так далее.

Нельзя. Можно имитировать саму молитву скриптом в какой-нибудь книге, доступной через консоль.
