### ISSUE TITLE
Дробящие(?) оружие

### ISSUE THREAD

**Issue by Kor-Angar** [dosinabox/g2nr_unofficial_update#102]
Оружие которое наносит дополнительный ущерб по големам, каменнным стражам и т..п.

Одноручного оружия достаточно много. А вот двуручного, кроме посохов не припомню. Оно есть?

**Comment by dosinabox** [comment]
Перечень двуручного оружия с дробящим уроном ():
- Посох мага Огня
- Посох мага Воды
- Магический посох
- Посох Ультара
- Тайфун (но у него лезвия, поэтому изменю на режущий)
- Дубинка бури
- Посох 'Кольца Воды'
- Боевой посох
- Краш Каррок (орочий молот Хош-Пака и орков-нежити)
- Палица
- Священный молот

**Comment by Kor-Angar** [comment]
Получается что мощного двурочного оружя нет

**Comment by dosinabox** [comment]
Ну, можно что-то и добавить в продажу) Новое, красивое, мощное и дорогое. Двуручный молот какой-нибудь, например. Их в игре практически нет.

**Comment by Kor-Angar** [comment]
Тут нужна практическая сторона. Типа того как у меня получилось на стриме когда герой не убивал шпагой с одного удара каменных стражей, но убивал их молотком с одного удара.

**Comment by Kor-Angar** [comment]
![image](https://user-images.githubusercontent.com/49514764/65961639-abfcac80-e45f-11e9-9f3f-f6b26eda714e.png)
180+40=220

110 ущерба , требует 110 силы
или 
120 ущерба, требует 100 силы
или
100 ущерба, требует 120 силы

вообщем что бы в сумме было 220

*****************

в принципе "Дубинка бури" подходит для этого дела. у нее 115/115 и штраф на навык.
как вариант можно ей сделать ущерб 120 и требование силы 100, тогда можно будет "оправдать" штраф на двуручный.

**Comment by Kor-Angar** [comment]
> Краш Каррок (орочий молот Хош-Пака и орков-нежити)

у него в игре по моему ущерб даже меньше чем у топора? ;-)

**Comment by dosinabox** [comment]
> у него в игре по моему ущерб даже меньше чем у топора? ;-)

65

> вообщем что бы в сумме было 220

Кому и когда её добавить в продажу?

**Comment by Kor-Angar** [comment]
Может пиратам? Или бандитам?

**Comment by dosinabox** [comment]
Ты скажи, как эксперт) А я и оружие сделаю, и модель найду, и в скрипты добавлю.

**Comment by Kor-Angar** [comment]
я не эксперт, но скажу :-)
Тогда пиратам. Оружие будет полезно как против болотных големов  так и каменых стражей. Как сделаешь напиши и я потестирую.

Так же можно его добавить в продажу Паладину в Миненталь.

**Comment by Kor-Angar** [comment]
Можно опять же подумать насчёт двуручного молотка который будет хорошо пробивать голема. т.е. есть к примеру одноручный молоток 120 ущерба, соответственно по голему он наносит дополнительных 50 ущерба, т.е. бьет как бы 170, это при том что лучший 1р в 4 главе это самокованный меч из руды с ущербом 140. исходя из такой же логики можно сделать молоток двуручный например на 170 или 180 ущерба, он будет хуже топора берсеркера(200) и грозы драконов(190), но голему будет наносить дополнительный ущерб.

Можно добавить в продажу ОНД в замке в 4 главе

**Comment by Kor-Angar** [comment]
Для ярика в принципе подходит дубина бури. Вот только у нее штраф на 2р. Ах.. я это уже писал :-)

> в принципе "Дубинка бури" подходит для этого дела. у нее 115/115 и штраф на навык.
> как вариант можно ей сделать ущерб 120 и требование силы 100, тогда можно будет "оправдать" штраф на двуручный


Вообщем что хочу сказать: молоток против оедяных големов в 4 главе будет большинству игррков пооезнее. Мне так какжется :-)
.

**Comment by dosinabox** [comment]
Двуручный молот 1: 110у/110с/60р/1100з в продаже у Гаретта с 2 главы у пиратов.
Двуручный молот 2: 170у/170с/90р/2000з в продаже у Ретона с 4 главы в замке.

Как тебе?

**Comment by Kor-Angar** [comment]
> Как тебе?

хотелось бы что бы силы требовал больше чем ущерб

> Двуручный молот 1: 110у/110с/60р/1100з в продаже у Гаретта с 2 главы у пиратов.

радиус маленький. может 105/115с/90р или 110/120с/90р

> Двуручный молот 2: 170у/170с/90р/2000з в продаже у Ретона с 4 главы в замке.

170у/180с/90р/2000з

**Comment by dosinabox** [comment]
> хотелось бы что бы силы требовал больше чем ущерб

Почему? Такое оружие обычно просто разбросано по миру и не особо продается. Полезным и дорогим считается только то, у которого хотя бы равно требование и урон.

**Comment by dosinabox** [comment]
> 180с

Столько силы не требует ни одно оружие в игре, максимум 170 у топора берсеркера.

**Comment by Kor-Angar** [comment]
> Почему? Такое оружие обычно просто разбросано по миру и не особо продается. Полезным и дорогим считается только то, у которого хотя бы равно требование и урон.

пытался делать табличку и анализировать 
https://docs.google.com/spreadsheets/d/1svDbXAiYe7PLCQ7G0Arjh_njRiDabsRC-9GuLt7APsQ/edit#gid=1292287472

**Comment by Kor-Angar** [comment]
Неправильно посчитал. Привык в экселе

**Comment by Kor-Angar** [comment]
Ледяной Голем  450 / 2 = 225 + 110 = 345
Огненный голем 400 / 2 = 200 + 100 = 300
Болотный голем 250+75(?) = 325 325 ущерба
Обычный голем 250+50=300 300 ущерба
Steinwächter 180+40 = 220 220 ущерба

**Comment by Kor-Angar** [comment]
Значит с молотком должно быть у героя 345 ущерба

Двуручный молот 2: ущерб / сила
165 / 180
170 / 175
175 / 170
180 / 165

**Comment by Kor-Angar** [comment]
> Столько силы не требует ни одно оружие в игре, максимум 170 у топора берсеркера.


можно подойти с другой стороны. со стороны математики:

Ледяной Голем  450 / 2 = 225 + 110 = 335 ущерба
Огненный голем 400 / 2 = 200 + 100 = 300 ущерба
Болотный голем 250+75(?) = 325 ущерба
Обычный голем 250+50=300  ущерба
Steinwächter 180+40 = 220  ущерба

Значит с молотком должно быть у героя 335 ущерба

Варианты Двуручного молота : ущерб / сила
- 155 / 180
- 160 / 175
- **165 / 170**
- **170 / 165**
- 175 / 160
- 180 / 155

**Comment by Kor-Angar** [comment]
С планшета писал. Надо математику перепроверить

**Comment by dosinabox** [comment]
![2](https://user-images.githubusercontent.com/39790055/66274263-540ddd80-e885-11e9-8640-f538d2bea3f5.jpg)
![1](https://user-images.githubusercontent.com/39790055/66274264-56703780-e885-11e9-8187-4333365e6c5e.jpg)

**Comment by Kor-Angar** [comment]
Ледяного голема при 170 силе с двух ударов убивает? Каменного с одного?

**Comment by dosinabox** [comment]
да
