### ISSUE TITLE
Товары Сенграта /  миненталь

### ISSUE THREAD

**Issue by Kor-Angar** [dosinabox/g2nr_unofficial_update#103]
в оригинале было так: все товары Сенграта pal_267_sengrath оказывались в его трупе. таким образом ему можно было продать мечи, стрелы, болты, а потом поднять их с трупа.
конечно же использование такого бага позволяло удвоить капитал через стрелы и болты. это плохо.

сейчас в трупе вообще нет товаров и это тоже плохо, так как у Сенграта есть не только свитки но и _кольцо с защитой от огня и пояс с защитой от огня, а так же **единственный** в игре пояс к силе +10._ 

т.е. если игрок не выкупил  по незнанию или забывчивости пояс к силе то усё.. конечно бытует мнение что пояс к силе дескать не нужен, а если уж совсем прибило то можно вставить через консоль, но на мой взгляд это не очень серьезные аргументы, особенно учитывая что Пираньи давали возможность поднять ассортимент с трупа :-)

на мой взгляд стало хуже чем было, так как пострадали непродвинутые игроки.

***************************************

если взять твой метод "запоминания" товаров который ты используешь у Беннета и Кроноса и применить его к Сенграту. 

```
var int Sengrath_ItemsGiven_Chapter_1;
var int Sengrath_ItemsGiven_Chapter_2;
var int Sengrath_ItemsGiven_Chapter_3;
var int Sengrath_ItemsGiven_Chapter_4;
var int Sengrath_ItemsGiven_Chapter_5;

func void B_GiveTradeInv_Sengrath(var C_Npc slf)
{
	if((Kapitel >= 1) && (Sengrath_ItemsGiven_Chapter_1 == FALSE))
	{
		Sengrath_ItemsGiven_Chapter_1 = TRUE;
	};
	if((Kapitel >= 2) && (Sengrath_ItemsGiven_Chapter_2 == FALSE))
	{
//		CreateInvItems(slf,ItMi_Gold,200);
		CreateInvItems(slf,ItPo_Mana_01,10);
		CreateInvItems(slf,ItPo_Mana_02,5);
		CreateInvItems(slf,ItSc_Zap,3);
		CreateInvItems(slf,ItSc_SumWolf,1);
		CreateInvItems(slf,ItSc_Sleep,2);
		CreateInvItems(slf,ItSc_IceCube,2);
		CreateInvItems(slf,ItSc_Windfist,3);
		CreateInvItems(slf,ItSc_MediumHeal,5);
		CreateInvItems(slf,ItSc_LightningFlash,2);
		CreateInvItems(slf,ItRi_Prot_Fire_02,1);
		CreateInvItems(slf,ItBe_Addon_STR_10,1);
		CreateInvItems(slf,ItBe_Addon_Prot_FIRE,1);
		Sengrath_ItemsGiven_Chapter_2 = TRUE;
	};
	if((Kapitel >= 3) && (Sengrath_ItemsGiven_Chapter_3 == FALSE))
	{
//		CreateInvItems(slf,ItMi_Gold,100);
		CreateInvItems(slf,ItPo_Mana_01,10);
		CreateInvItems(slf,ItPo_Mana_02,5);
		Sengrath_ItemsGiven_Chapter_3 = TRUE;
	};
	if((Kapitel >= 4) && (Sengrath_ItemsGiven_Chapter_4 == FALSE))
	{
//		CreateInvItems(slf,ItMi_Gold,150);
		CreateInvItems(slf,ItPo_Mana_01,10);
		CreateInvItems(slf,ItPo_Mana_02,5);
		Sengrath_ItemsGiven_Chapter_4 = TRUE;
	};
	if((Kapitel >= 5) && (Sengrath_ItemsGiven_Chapter_5 == FALSE))
	{
//		CreateInvItems(slf,ItMi_Gold,200);
		CreateInvItems(slf,ItPo_Mana_01,10);
		CreateInvItems(slf,ItPo_Mana_02,5);
		Sengrath_ItemsGiven_Chapter_5 = TRUE;
	};
};

```
то можно в труп Сенграту в 4 главе вставить то, что осталось от его изначального ассортимента в конце 3 главы(MIS_ReadyforChapter4 ).
в принципе в труп можно так же добавить еще что нибудь, например пару свитков заклинаний Паладинов.

**Comment by dosinabox** [comment]
В какой главе Сенграт оказывается за пределами замка и погибает?

**Comment by Kor-Angar** [comment]
в 3 главе Сенграт живой
в 4 главе не живой

**Comment by dosinabox** [comment]
А товары на 4 и 5 главу прописаны: по 10 штук ItPo_Mana_01 и по 5 штук ItPo_Mana_02.

**Comment by dosinabox** [comment]
> то можно в труп Сенграту в 4 главе вставить то, что осталось от его изначального ассортимента в конце 3 главы(MIS_ReadyforChapter4 ).

А ничего страшного, если при этом у него не будет товаров, скупленных у ГГ?

**Comment by Kor-Angar** [comment]
> А ничего страшного, если при этом у него не будет товаров, скупленных у ГГ?

в этом то и суть. это наоборот хорошо;-) 

> А товары на 4 и 5 главу прописаны: по 10 штук ItPo_Mana_01 и по 5 штук ItPo_Mana_02

Пираньи видимо работали как на производстве: сначала черновая обработка, а потом чистовая :-) видимо это остатки от черновой обработки. можно убрать или в комментарии добавить что он по сюжету уже мертв в 4 и 5 главах

**Comment by dosinabox** [comment]
> **единственный** в игре пояс к силе +10

Второй можно купить у Джоры в четвертой главе! Причем даже в чистом оригинале Г2НВ)

- второе кольцо можно купить у Сэмюэля (глава 2) и у Кйорна (глава 4)
- второй пояс огненного человека можно купить у Константино (глава 3)

Значит ли это, что на товары мертвого Сенграта можно вообще забить? На кольцо так точно, потому что оно сразу же появляется в продаже в замке. А два пояса, получается, достанутся ГГ на халяву...

**Comment by dosinabox** [comment]
В общем, всё готово, осталось только определиться что именно подкладывать в его труп.

**Comment by Kor-Angar** [comment]
> Второй можно купить у Джоры в четвертой главе! Причем даже в чистом оригинале Г2НВ)

Разве?

**Comment by dosinabox** [comment]
> Разве?

Именно так. Можешь перепроверить)

**Comment by dosinabox** [comment]
```
if((Kapitel >= 4) && (Jora_ItemsGiven_Chapter_4 == FALSE))
{
	...
	CreateInvItems(slf,ItBe_Addon_STR_10,1);
	Jora_ItemsGiven_Chapter_4 = TRUE;
};
```

**Comment by Kor-Angar** [comment]
О как :-) а я думал он один в игре

**Comment by Kor-Angar** [comment]
> В общем, всё готово, осталось только определиться что именно подкладывать в его труп.

Остатки ассортимента?

**Comment by dosinabox** [comment]
Можно просто 10 ItPo_Mana_01 и 5 ItPo_Mana_02, которые ему прописаны на четвертую главу. Чтобы не заморачиваться. Да и с зельями маны в Минентале всегда проблемы, очень мало их.

**Comment by Kor-Angar** [comment]
давай еще закинем пару паладинских свитков лечения

**Comment by Kor-Angar** [comment]
а куда его товары делись с точки зрения ЛОРа? в замке остались? :-)

**Comment by dosinabox** [comment]
> а куда его товары делись с точки зрения ЛОРа? в замке остались? :-)

Думаю, что орки растащили с трупа.

> давай еще закинем пару паладинских свитков лечения

В продажу или только в труп?

**Comment by Kor-Angar** [comment]
В труп

**Comment by dosinabox** [comment]
Почему в труп без продажи? Сенграт отказывался продавать их ГГ, когда был в замке? Стратегический запас? И зачем ему нужны свитки, если паладины, по идее, должны владеть рунами?

**Comment by dosinabox** [comment]
Пока что у мертвого Сенграта будет 3 паладинских свитка "Малое исцеление", 5 экстрактов маны и 10 эликсиров маны.

**Comment by Kor-Angar** [comment]
> И зачем ему нужны свитки, если паладины, по идее, должны владеть рунами?

не знаю зачем Паладины у себя держать свитки. но у них их можно украсть из чего следует что они у них есть. 

> Почему в труп без продажи? Сенграт отказывался продавать их ГГ, когда был в замке?

потому что можно добавить остаток ассортимента в котором есть свитки, а можно добавить просто эликсиры. ты решила добавить просто эликсиры, что бы это не выглядела совсем скупо я предложил добавить в труп ещё и свитки лечения, а что бы не было пересечения с ассортиментом, списки лечения паладинов. получилось и логично и лаконично и полезно.

**Comment by Kor-Angar** [comment]
а почему Пираньи используют отдельную инстанцию на труп Sengrath? почему они его просто не стали убивать?

**Comment by dosinabox** [comment]
Пираньи убивали. Отдельная инстанция моя.

**Comment by Kor-Angar** [comment]
А в чем смысл? 😀0:29, 19 сентября 2020 г., dosinabox <notifications@github.com>:
Пираньи убивали. Отдельная инстанция моя.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
-- Отправлено из мобильного приложения Яндекс.Почты

**Comment by dosinabox** [comment]
Так проще и надежнее управлять инвентарем.
