### ISSUE TITLE
Ледяные големы

### ISSUE THREAD

**Issue by dosinabox** [dosinabox/g2nr_unofficial_update#114]
Если ледяной голем сможет заморозить ГГ ледяным блоком, то после этого будет просто стоять и смотреть. Это можно исправить, чтобы голем бил ГГ в заморозке, но это практически всегда заканчивается смертью. Может, разработчики сделали такое поведение специально, потому что удары големов по ГГ в заморозке не оставляют ему никаких шансов?
Что делать?

**Comment by Kor-Angar** [comment]
Обычно они после заморозки атакует. По моему у меня как то герой с полными жизнями выживал против одного голема.
Можно перепроверить.

**Comment by dosinabox** [comment]
Попробуй. Наверное, при определенных условиях могут тупить, но это можно исправить.

**Comment by dosinabox** [comment]
Короче, можно просто ответить на вопрос и даже не делать никаких проверок:

> ОК ли, если ледяные големы **всегда** будут бить ГГ в ледяной глыбе?

**Comment by Kor-Angar** [comment]
ок

**Comment by dosinabox** [comment]
Будут всегда бить. Нужно будет проверить, чтобы не тупили.

**Comment by dosinabox** [comment]
Не получается заставить их подходить к ГГ, который оказался заморожен.
Что если они будут стрелять в него заклинанием ледяной стрелы или ледяного копья, как скелеты-маги?
Что опаснее - удары големов в ближнем бою с силой 225 или 100 магического урона ледяного копья?

**Comment by dosinabox** [comment]
> Что опаснее - удары големов в ближнем бою с силой 225 или 100 магического урона ледяного копья?

Тест показал, что удары значительно опаснее.

https://youtu.be/SWWAft2w4mM

Мне нравится вариант с ледяным копьем) В ближнем бою они всё равно размазывают ГГ по земле, но при заморозке хотя бы больше шансов выжить.
Если ты согласен, то оставлю так, как в видео.

**Comment by Kor-Angar** [comment]
> Тест показал, что удары значительно опаснее.

это потому что ты в мантии мага. а ты попробуй Паладином или ОнД ;-)

**Comment by Kor-Angar** [comment]
![image](https://user-images.githubusercontent.com/49514764/66227205-5f2a0780-e6e5-11e9-9057-497812541975.png)

**Comment by Kor-Angar** [comment]
Маг огня по идеи ледяных големов может убить издалека. надо проверить идёт ли на них двойной ущерб от Minecrawler 
![image](https://user-images.githubusercontent.com/49514764/66227618-35bdab80-e6e6-11e9-9186-b45d1be55110.png)

идея заключалась в том что воин должен был успеть подбежать к ним в плотную. а если големы морозят ГГ то они его убивают.

если герой одет на защиту от оружия то они наносят ему 225-150=75 ущерба. сколько будет наносить копьё будет зависеть от того как  оденется герой. 25 доспех + 20 глаз инноса. может быть пояс у героя есть +10. кольцо может быть +5. таким образом копьё будет наносить 40-75 ущерба в зависимости от шмота. далее идёт скорость удара или скорость каста. с какой скоростью кастуют Ледяные големы  я не знаю.

**Comment by dosinabox** [comment]
> с какой скоростью кастуют Ледяные големы я не знаю.

Примерно как и бьют. На видео видно.

В любом случае им нужно что-то дальнобойное, потому что они не могут подходить к замерзшему игроку, который находится вне зоны ближнего боя. Просто не знают что делать. По-моему, ледяное копье вполне годится и ничего не ломает.

> идея заключалась в том что воин должен был успеть подбежать к ним в плотную.

Можно и не совсем вплотную. Просто увернуться от пары кастов ледяного блока и подойти настолько, чтобы големы переключились в режим ближнего боя.

**Comment by Kor-Angar** [comment]
надо тестить

**Comment by dosinabox** [comment]
> надо тестить

[g2a_nr_scriptpatch_v22_hotfix_04.10.zip](https://github.com/dosinabox/g2nr_unofficial_update/files/3691756/g2a_nr_scriptpatch_v22_hotfix_04.10.zip)

**Comment by dosinabox** [comment]
https://github.com/dosinabox/g2nr_unofficial_update/commit/3e05a75157397e69c4346f3db4fffacec4ce673e

**Comment by Kor-Angar** [comment]
тарам парам. в целом с ледяным копьём идея отличная. даже при защите от магии 50, а у среднестатического ОНД и Пала мне кажется будет меньше, ледяное копьё пробивает.  иногда голем тупит после первого каста ледяного копья. так же обрати внимание что в одном случае голем сначало кастовал копьё а потом пошёл в атаку ближнем боем. у него закончилась мана? :-) он глюканул? герой разморозился но был слишком близко?

https://www.youtube.com/watch?v=7rSe57HdUOQ&feature=youtu.be

Можно опять же подумать насчёт двуручного молотка который будет хорошо пробивать голема. т.е. есть к примеру одноручный молоток 120 ущерба, соответственно по голему он наносит дополнительных 50 ущерба, т.е. бьет как бы 170, это при том что лучший 1р в 4 главе это самокованный меч из руды с ущербом 140. исходя из такой же логики можно сделать молоток двуручный например на 170 или 180 ущерба,  он будет хуже топора берсеркера(200) и грозы драконов(190), но голему будет наносить дополнительный ущерб.


*******************

теперь про магию. 
1. Фаербол наносит минимальный урон по ледяному голему, хотя по идем от магии минимального урона нет. т.е. если защита от магии больше или ровна урону от магии то урон = 0.

2. Большой огненный шар не убивает ледяного голема с одного заряда. возможно так и было задумано авторами что герой кастует большой огненный шар у голема остаётся 10 жизней и герой кидает малый огненный шторм добивая его. а может это ошибка.

3. проработать момент когда герой атакует героя магией, а голем его как бы "не видят".

**Comment by dosinabox** [comment]
> так же обрати внимание что в одном случае голем сначало кастовал копьё а потом пошёл в атаку ближнем боем.

Бывает. С каждой анимацией каста голем чуть-чуть подвигается вперед. Вот и постепенно оказался в радиусе ближнего боя.
