### ISSUE TITLE
201 сила. баг

### ISSUE THREAD

**Issue by Kor-Angar** [dosinabox/g2nr_unofficial_update#115]
> и что то там не так. силе учителя учат до 201, а должны до 200.

> Это как?

Дело в "пламенной нарезке". если съесть "пламенную нарезку" которая даёт +1 силы  то учителя поднимут силу до 201.

вот сейв, герой стоит перед Торлофом, у героя есть ЛП, герой не ел бонусы к силе, у героя есть пламенная нарезка и иные бонусы к силе
https://yadi.sk/d/HzTbxkd4-Q8oNg

**Comment by dosinabox** [comment]
Исправлено.

**Comment by Kor-Angar** [comment]
а в чём проблема была?

**Comment by dosinabox** [comment]
Переписывала функцию начисления бонусов пламенной нарезки и забыла про добавку к реальному значению.

**Comment by Kor-Angar** [comment]
проверил. всё ок
