### ISSUE TITLE
Ренгару генерация денег

### ISSUE THREAD

**Issue by Kor-Angar** [dosinabox/g2nr_unofficial_update#118]
После того как Ренгару отобрал у героя золото у него сгенерилось лишнее золото

было
![image](https://user-images.githubusercontent.com/49514764/66259189-ba77fa80-e7b6-11e9-95a5-13fa19ea7bbe.png)

стало
 ![image](https://user-images.githubusercontent.com/49514764/66259176-9a483b80-e7b6-11e9-9875-30fde84a4ef9.png)

https://youtu.be/HpWhXQtxbAU?t=6408

**Comment by dosinabox** [comment]
Странно очень. Украл у него 5 монет до этого?

**Comment by Kor-Angar** [comment]
> Странно очень. Украл у него 5 монет до этого?

наверное

**Comment by UnresolvedExternal** [comment]
Тот же баг с `Npc_HasInvItems`. Там даже 2 логических бага в движке.

Воспроизведение:
1. Смотрим в инвентаре на свои 150 золотых.
2. Сохраняемся.
3. Получаем 50 золотых через диалог.
4. Сохраняемся.
5. Получаем люлей и обидчик забирает 150 + 150 + 50 = 350 золотых.

Что происходит в движке:
1. Создается воб со значением 150.
2. Воб превращается в строку `ITMI_GOLD:150`
3. Имеем воб со значение 50 и строку `ITMI_GOLD:150`
4. Получаем строку `ITMI_GOLD:150,ITMI_GOLD:50`
5. В `ZS_RansackBody_End` идет первый вызов `Npc_HasInvItems(other, ItMi_Gold)`:
    создаётся воб со значением 150 и остается строка `ITMI_GOLD:50`, функция возвращает 150.
    Идет второй вызов `Npc_HasInvItems(other, ItMi_Gold)`:
    -берется значение 150 воба
    -строка превращается в воб со значением 50
    -этот воб добавляется в инвентарь, склеиваясь с вобом со значением 150 (имеем воб-200)
    -возвращаемый результат: 150+200=350

То есть 2 бага:
-Неправильно достается значение золота из строки `ITMI_GOLD:150,ITMI_GOLD:50`
-Не учитывается склеивание старого воба, и нового, воссозданного из строки

**Comment by dosinabox** [comment]
Видимо, и здесь то же самое:
https://github.com/dosinabox/g2nr_unofficial_update/issues/78

**Comment by dosinabox** [comment]
Требуются правки на уровне движка, пока закрыто

**Comment by dosinabox** [comment]
исправлено в Union
