### ISSUE TITLE
Появление Грега в лагере Декстера

### ISSUE THREAD

**Issue by Kor-Angar** [dosinabox/g2nr_unofficial_update#121]
это я для себя уточняю. для понимания :-)

**************
Добавил условие на разговор "как дела". Теперь его можно прослушать на следующий день после того как Грег пришёл на ферму

if((GregLocation == Greg_Bigcross) && (Npc_GetDistToWP(self,"BIGCROSS") < 1000) && (MIS_Addon_Greg_Bigcross <= (Wld_GetDay() - 1)))

**************
Добавил вызов Грега при диалоге "Тебе нужна моя голова? Что ж, попробуй ее взять!"

```
instance DIA_Dexter_Kopf(C_Info)
{
	npc = BDT_1060_Dexter;
	nr = 5;
	condition = DIA_Dexter_Kopf_Condition;
	information = DIA_Dexter_Kopf_Info;
	permanent = FALSE;
	description = "Тебе нужна моя голова? Что ж, попробуй ее взять!";
};


func int DIA_Dexter_Kopf_Condition()
{
	if(Npc_KnowsInfo(other,DIA_Dexter_Hallo))
	{
		return TRUE;
	};
};

func void DIA_Dexter_Kopf_Info()
{
	AI_Output(other,self,"DIA_Addon_Dexter_Add_15_00");	//Тебе нужна моя голова? Что ж, попробуй ее взять!
	AI_Output(self,other,"DIA_Addon_Dexter_Add_09_01");	//Ну, если ты так хочешь...


	if(GregLocation == Greg_Bigcross) // проверка на ферме ли Грег	
	{
		Greg_Rejected = TRUE;
		B_Greg_ComesToDexter(); // вызов Грега
	};


	DIA_Dexter_Kill_ENDE();
};
```
**************

Проверка на то на ферме ли  Грег при его вызове

```
instance DIA_Dexter_Kill(C_Info)
{
	npc = BDT_1060_Dexter;
	nr = 2;
	condition = DIA_Dexter_Kill_Condition;
	information = DIA_Dexter_Kill_Info;
	permanent = FALSE;
	important = TRUE;
};


func int DIA_Dexter_Kill_Condition()
{
	if(Npc_IsInState(self,ZS_Talk) && ((Dexter_NoMoreSmallTalk == TRUE) || (Knows_Dexter == FALSE)))
	{
		return TRUE;
	};
};

func void DIA_Dexter_Kill_Info()
{
	if(Knows_Dexter == TRUE)
	{
		AI_Output(self,other,"DIA_Addon_Dexter_Add_09_02");	//Ты сам напросился...
	}
	else
	{
		AI_Output(self,other,"DIA_Dexter_Kill_09_01");	//Ох, тебе не стоило показываться здесь. Ты оказался не в то время и не в том месте.
	};
	MIS_Steckbriefe = LOG_OBSOLETE;
	B_CheckLog();

	

	if(GregLocation == Greg_Bigcross) // проверка на ферме ли Грег	
	{
		Greg_Rejected = TRUE;
		B_Greg_ComesToDexter(); // вызов Грега
	};

	Info_ClearChoices(DIA_Dexter_Kill);
	Info_AddChoice(DIA_Dexter_Kill,Dialog_Ende,DIA_Dexter_Kill_ENDE);
};

func void DIA_Dexter_Kill_ENDE()
{
//	var C_Item itm;
	AI_StopProcessInfos(self);
	B_Attack(self,other,AR_SuddenEnemyInferno,1);
/*	itm = Npc_GetEquippedArmor(Greg_NW);
	if(!Hlp_IsItem(itm,ITAR_PIR_H_Addon))
	{
		AI_EquipArmor(Greg_NW,ITAR_PIR_H_Addon);
	};*/
};
```

**************

снял условия с диалога "И что ты собираешься делать сейчас? Убить меня?"

```
instance DIA_Dexter_Vor(C_Info)
{
	npc = BDT_1060_Dexter;
	nr = 5;
	condition = DIA_Dexter_Vor_Condition;
	information = DIA_Dexter_Vor_Info;
	permanent = FALSE;
	description = "И что ты собираешься делать сейчас? Убить меня?";
};


func int DIA_Dexter_Vor_Condition()


{
	return TRUE;
};


/*
{
	if(Npc_KnowsInfo(other,DIA_Addon_Dexter_missingPeople))
	{
		return TRUE;
	};
};*/

func void DIA_Dexter_Vor_Info()
{
	AI_Output(other,self,"DIA_Dexter_Vor_15_00");	//И что ты собираешься делать сейчас? Убить меня?
	AI_Output(self,other,"DIA_Dexter_Vor_09_01");	//Да. Но ты освободил нас всех. Вот почему я даю тебе еще один шанс. Сваливай - исчезни, сделайся невидимым. Уходи и больше не попадайся мне на пути.
	AI_Output(other,self,"DIA_Addon_Dexter_Vor_15_00");	//Я должен узнать, куда ты отправил людей.
	AI_Output(self,other,"DIA_Addon_Dexter_Vor_09_01");	//(смеется) Ты мог бы попробовать силой заставить меня говорить...
	AI_Output(self,other,"DIA_Addon_Dexter_Vor_09_02");	//(угрожающе) Думаю, тебе лучше уйти.
	AI_Output(self,other,"DIA_Dexter_Vor_09_02");	//Если я увижу тебя еще раз, то без колебаний убью! Я предупредил тебя.
	Dexter_NoMoreSmallTalk = TRUE;
	AI_StopProcessInfos(self);
};
```

**************
убрал у Декстера вариант "конец" в Диалогах

```
/*
instance DIA_Dexter_EXIT(C_Info)
{
	npc = BDT_1060_Dexter;
	nr = 999;
	condition = DIA_Dexter_EXIT_Condition;
	information = DIA_Dexter_EXIT_Info;
	permanent = TRUE;
	description = Dialog_Ende;
};


func int DIA_Dexter_EXIT_Condition()
{
	return TRUE;
};

func void DIA_Dexter_EXIT_Info()
{
	AI_StopProcessInfos(self);
};*/
```

таким образом в конце остаётся всего два варианта:

- Тебе нужна моя голова? Что ж, попробуй ее взять!
- И что ты собираешься делать сейчас? Убить меня?

**************

```

func void B_Greg_ComesToDexter()
{
	if(Greg_Rejected == TRUE)
	{
		if(Hlp_GetInstanceID(self) == Hlp_GetInstanceID(Dexter))
		{
			itm = Npc_GetEquippedArmor(Greg_NW);
			if(!Hlp_IsItem(itm,ITAR_PIR_H_Addon))
			{
				AI_EquipArmor(Greg_NW,ITAR_PIR_H_Addon);
			};
			if(B_Greg_ComesToDexter_OneTime == FALSE)
			{
				Dexter.aivar[AIV_EnemyOverride] = FALSE;
				BanditGuard.aivar[AIV_EnemyOverride] = FALSE;
				Npc_SendPassivePerc(Dexter,PERC_ASSESSFIGHTSOUND,Dexter,hero);
				GregLocation = Greg_Dexter;
				B_StartOtherRoutine(Greg_NW,"Dexter");
				B_StartOtherRoutine(BanditGuard,"Attack");
				B_StartOtherRoutine(BDT_1067_Bandit_L,"Attack");
				B_StartOtherRoutine(BDT_1068_Bandit_L,"Attack");
				B_Greg_ComesToDexter_OneTime = TRUE;
			};
		};
	};
};
```

**Comment by dosinabox** [comment]
Не исчезнут только если у них есть сердце или кровь.

**Comment by Kor-Angar** [comment]
Ну ясно. Спасибо

**Comment by Kor-Angar** [comment]
А если после убийства болотного дракона, при разговоре с Родом в трупе дракона создать что то уникальное, труп болотного дракона не пропадёт?

**Comment by Kor-Angar** [comment]
Подскажи пожалуйста а какая переменная отвечает за появление Грега в лагере Декстера? как это можно отключить?

**Comment by dosinabox** [comment]
Если 
Greg_Rejected == TRUE
то Грег не появится в лагере Декстера до смерти всех 19 бандитов

Если 
Greg_Rejected == FALSE
то Грег появится в лагере Декстера как в оригинале

**Comment by dosinabox** [comment]
> как это можно отключить?

Чтобы Грег появился в лагере, ничего не нужно делать.
Чтобы Грег не появился в лагере до смерти всех 19 бандитов, нужно сказать ему "Я думаю, что тебе нужен человек по имени Декстер.", а потом "Ну, я просто предположил.".

**Comment by Kor-Angar** [comment]
Привет. Хочу что бы диалог про Наёмников было доступен не сразу у Грега, а спустя пару дней.

в файле Грега
GregLocation = Greg_Bigcross;
заменил на 
GregLocation = Greg_Bigcross;
MIS_Addon_Greg_Bigcross = Wld_GetDay();

в проверку на "как дела" добавил условие
(MIS_Addon_Greg_Bigcross <= (Wld_GetDay() - 2)
```
instance DIA_Addon_Greg_NW_Bigcross(C_Info)
{
	npc = PIR_1300_Addon_Greg_NW;
	nr = 5;
	condition = DIA_Addon_Greg_NW_Bigcross_Condition;
	information = DIA_Addon_Greg_NW_Bigcross_Info;
	description = "Как дела?";
};


func int DIA_Addon_Greg_NW_Bigcross_Condition()
{
	if(((GregLocation == Greg_Bigcross) && (Npc_GetDistToWP(self,"BIGCROSS") < 1000))||(MIS_Addon_Greg_Bigcross <= (Wld_GetDay() - 2)))
	{
		return TRUE;
	};
};

func void DIA_Addon_Greg_NW_Bigcross_Info()
{
	AI_Output(other,self,"DIA_Addon_Greg_NW_Bigcross_15_01");	//Как дела?
	if((MIS_Addon_Greg_BringMeToTheCity == LOG_FAILED) || (MIS_Addon_Greg_RakeCave == LOG_FAILED))
```

так можно? или это делается как то по другому?

**Comment by dosinabox** [comment]
Нужна новая переменная. В Story/Story_Globals.d:
`var int Greg_Bigcross_Day;`

Во всех упоминаниях GregLocation = Greg_Bigcross (как минимум четыре):
`Greg_Bigcross_Day = Wld_GetDay();`

А какая задумка? Что Грег не сразу контактирует с наемниками? Вот эти фразы только через пару дней?
```
AI_Output(self,other,"DIA_Addon_Greg_NW_Bigcross_01_02");	//Так себе. От наемников оказалось мало пользы.
AI_Output(self,other,"DIA_Addon_Greg_NW_Bigcross_01_03");	//Я ожидал, что они - храбрые ребята.
AI_Output(self,other,"DIA_Addon_Greg_NW_Bigcross_01_04");	//Но на поверку оказалось, что это всего лишь болтливые хвастуны.
```
В таком случае нужно так:
```
func void DIA_Addon_Greg_NW_Bigcross_Info()
{
	AI_Output(other,self,"DIA_Addon_Greg_NW_Bigcross_15_01");	//Как дела?
	if((MIS_Addon_Greg_BringMeToTheCity == LOG_FAILED) || (MIS_Addon_Greg_RakeCave == LOG_FAILED))
	{
		AI_Output(self,other,"DIA_Addon_Greg_NW_Bigcross_01_00");	//Это же наш господин Ненадежность!
	};
	if(Greg_Bigcross_Day <= (Wld_GetDay() - 2))
	{
		AI_Output(self,other,"DIA_Addon_Greg_NW_Bigcross_01_02");	//Так себе. От наемников оказалось мало пользы.
		AI_Output(self,other,"DIA_Addon_Greg_NW_Bigcross_01_03");	//Я ожидал, что они - храбрые ребята.
		AI_Output(self,other,"DIA_Addon_Greg_NW_Bigcross_01_04");	//Но на поверку оказалось, что это всего лишь болтливые хвастуны.
	};
	if((MIS_Addon_Greg_RakeCave == LOG_Running) && (Greg_SuchWeiter == TRUE))
	{
		AI_Output(self,other,"DIA_Addon_Greg_NW_Bigcross_01_05");	//Ну что, ты нашел мои вещи?
		if((RAKEPLACE[1] == FALSE) || (RAKEPLACE[2] == FALSE) || (RAKEPLACE[3] == FALSE) || (RAKEPLACE[4] == FALSE) || (RAKEPLACE[5] == FALSE))
		{
			AI_Output(other,self,"DIA_Addon_Greg_NW_Bigcross_15_06");	//Нет, еще не все.
			AI_Output(self,other,"DIA_Addon_Greg_NW_Bigcross_01_07");	//Так поторопись! Не так уж это и сложно.
		};
	};
};
```

**Comment by Kor-Angar** [comment]
> В таком случае нужно так:
> if(Greg_Bigcross_Day <= (Wld_GetDay() - 2))

сначала думал так, но может получится пустой диалог.

**Comment by Kor-Angar** [comment]
> Нужна новая переменная. В Story/Story_Globals.d:
> var int Greg_Bigcross_Day;
> Во всех упоминаниях GregLocation = Greg_Bigcross (как минимум четыре):
> Greg_Bigcross_Day = Wld_GetDay();

это я учел :-)

**Comment by Kor-Angar** [comment]
> А какая задумка? Что Грег не сразу контактирует с наемниками? Вот эти фразы только через пару дней?

да. а то получается пока герой ушел он уже успел и с наемниками поговорить :-)

**Comment by dosinabox** [comment]
> сначала думал так, но может получится пустой диалог.

Только если ГГ уже принес ему все вещи. Можно и вставить что-нибудь на такой случай:
```
if(Greg_Bigcross_Day <= (Wld_GetDay() - 2))
{
	AI_Output(self,other,"DIA_Addon_Greg_NW_Bigcross_01_02");	//Так себе. От наемников оказалось мало пользы.
	AI_Output(self,other,"DIA_Addon_Greg_NW_Bigcross_01_03");	//Я ожидал, что они - храбрые ребята.
	AI_Output(self,other,"DIA_Addon_Greg_NW_Bigcross_01_04");	//Но на поверку оказалось, что это всего лишь болтливые хвастуны.
}
else
{
	AI_Output(self,other,"DIA_Addon_Greg_NW_PERM_01_02");	//Мы поговорим попозже. Понятно?
};
```

**Comment by dosinabox** [comment]
```
if(((GregLocation == Greg_Bigcross) && (Npc_GetDistToWP(self,"BIGCROSS") < 1000))||(MIS_Addon_Greg_Bigcross <= (Wld_GetDay() - 2)))
```
Неправильная проверка. Правильная такая:
```
if((GregLocation == Greg_Bigcross) && (Npc_GetDistToWP(self,"BIGCROSS") < 1000) && (MIS_Addon_Greg_Bigcross <= (Wld_GetDay() - 2)))
```
положение **И** расстояние **И** день. Но лучше проверять по моему варианту в самом диалоге, а не запрещать игроку вопрос. Наверное, так и сделаю в моде, норм замечание.

**Comment by Kor-Angar** [comment]
>  Наверное, так и сделаю в моде, норм замечание.

смысла нет. этот диалог нужен что бы выйти на диалог про Декстера. а ты его разблокировала сняв все условия.

**Comment by dosinabox** [comment]
Там, кстати, ещё в следующем диалоге упоминаются наемники, нужно и там проверять день:
```
func void DIA_Addon_Greg_NW_WhatWantFromSLD_Info()
{
	AI_Output(other,self,"DIA_Addon_Greg_NW_WhatWantFromSLD_15_00");	//Что тебе было нужно от наемников?
	if(SC_KnowsGregsSearchsDexter == FALSE)
	{
		B_Greg_Search_Dexter();
	}
	else
	{
		AI_Output(self,other,"DIA_Addon_Greg_NW_WhatWantFromSLD_01_01");	//Я тебе уже говорил. Я ищу человека в красной броне.
		AI_Output(self,other,"DIA_Addon_Greg_NW_WhatWantFromSLD_01_02");	//Но эти кретины даже не поняли, о ком я говорю.
	};
};
```

**Comment by Kor-Angar** [comment]
> Там, кстати, ещё в следующем диалоге упоминаются наемники, нужно и там проверять день

диалог про Наёмников  вытекает из "как дела". если ты переделываешь "как дела" то тогда диалог про наёмников должен быть доступен после того как воспроизвёлся вот этот диалог
```
	AI_Output(self,other,"DIA_Addon_Greg_NW_Bigcross_01_02");	//Так себе. От наемников оказалось мало пользы.
	AI_Output(self,other,"DIA_Addon_Greg_NW_Bigcross_01_03");	//Я ожидал, что они - храбрые ребята.
	AI_Output(self,other,"DIA_Addon_Greg_NW_Bigcross_01_04");	//Но на поверку оказалось, что это всего лишь болтливые хвастуны.
```

**Comment by Kor-Angar** [comment]
> Неправильная проверка. Правильная такая:

спасибо. Получилось!

**Comment by Kor-Angar** [comment]
**Декстер** мои правки
- снял условия с диалога "И что ты собираешься делать сейчас? Убить меня?"
- убрал у Декстера вариант "конец" в Диалогах

таким образом в конце остаётся всего два варианта:
- Тебе нужна моя голова? Что ж, попробуй ее взять!
- И что ты собираешься делать сейчас? Убить меня?

Если Грег на ферме то в случае агрессии со стороны Декстера, Грег вызывается. во всех остальных случаях нет.


**Грег** мои правки
Диалог про Дектстера доступен после диалога про наёмников
Диалог про наёмников доступен после того как Грег говорит что у них был
О том что Грег был у Наёмников можно узнать от Грега на следующий день после его прибытия на ферму

https://www.youtube.com/watch?v=zlCUfKcNEm8&feature=youtu.be

***



Логики я придерживаться такой: появление Грега это не наказание игрока, а помощь ему. Помощь должна происходить при каких то условиях. Условие весьма простое и логичное: грег находится на ферме.

******
Как Грег с точки зрения Лора, оказывается у Декстера:
* узнал инфу от героя
* узнал инфу от крестьян на ферме онара
* проследить за героем 😀

Может ли Грег оказаться в башне Декстера, если секунду назад он был в городе / таверне? Скорее нет, чем да.

*****
У Декстера есть диалог про то что он его отпускает. При этом есть диалог "конец". Если нажать "конец" то можно ещё не раз ходить к Декстера. Если нажать про "отпускает" то можно уйти, а при следующей встрече Декстера агрится. Мне показалось что один из них лишний. Поэтому разговор с Декстером заканчивается или агрессией или отпусканием, т. е. Надо сделать выбор, а не выбрать "конец" и уйти думать на неделю, а потом опять прийти и продолжить разговор с Декстером.
