### ISSUE TITLE
Бифф в команде

### ISSUE THREAD

**Issue by dosinabox** [dosinabox/g2nr_unofficial_update#122]
На подумать. Сейчас в игре нет возможности прогнать Биффа из команды, если предложить ему путешествие в Минентале. Нужна ли она? Пусть, наверное, атакует в случае отказа и уходит на ферму.

**Comment by Kor-Angar** [comment]
> На подумать. Сейчас в игре нет возможности прогнать Биффа из команды, если предложить ему путешествие в Минентале. Нужна ли она? Пусть, наверное, атакует в случае отказа и уходит на ферму.

а Гириона можно прогнать, если ГГ согласился что он будет в команде?

**Comment by dosinabox** [comment]
> а Гириона можно прогнать, если ГГ согласился что он будет в команде?

нет

**Comment by Kor-Angar** [comment]
так если нельзя Гириона прогнать и нельзя Бифа прогнать, то тогда почему 
"Биф не Ок, а Гирион Ок" ?

**Comment by dosinabox** [comment]
Мы уже вроде решили, что Гирион не совсем член команды, а на корабль он идет просто чтобы его вернуть обратно, а не мир спасать.
А Бифф просто наемник за деньги.

**Comment by Kor-Angar** [comment]
подожди, подожди, подожди. там не только Гирион особенный и. Там и Ватрас особенный. и Ли особенный и кто то еще особенные. на то она и Готика что НПС были особенными. 
дала лучше их классифицируем по поведению

- Ватрас, может уйти из команды сам (когда он уходит кол-во экипажа уменьшается?)
- Гирион/Биф не может уйти из команды
- НПС уходят/приходят из команды  
- НПС уходят/приходят, а потом обижаются и не приходят
- НПС уходят/приходят, а потом атакуют, есть такие?
- ещё какие то НПС?


upd
а почему Гирион не совсем член команды? он же учит, учит. орков убивает, убивает. Капитан его считает "матросом", считает.

**Comment by dosinabox** [comment]
Нельзя выгнать из команды только Гириона и Биффа. Почему нельзя выгнать Гириона я понимаю. А почему нельзя выгнать Биффа - не понимаю. Вот и всё)

**Comment by Kor-Angar** [comment]
А я вот наоборот. Не понимаю почему нельзя выгнать Гириона, а почему нельзя выгнать Бифа понимаю :-)

**Comment by dosinabox** [comment]
и почему же Биффа нельзя, по-твоему?

**Comment by Kor-Angar** [comment]
Завтра напишу :-)

**Comment by dosinabox** [comment]
> Завтра напишу :-)

ну шо?

**Comment by Kor-Angar** [comment]
Не написал. На что то отвлёкся и забыл.

**Comment by Kor-Angar** [comment]
Про команду корабля. Команда корабля у героя состоит из его друзей, большинство из них - уголовники. По ЛОРу идёт речь о том что герой должен взять в команду тех кого знает, кому доверяют.

Гирион Паладин, который настаивает на том что герой должен его взять в команду. Каких либо отношений у героя с Гирионом нет.

Биф ОнД, авантюрист. С героем бегал по Миненталю ради бабла, рисковал жизнью. Герой ему предлагает отправится в путешествие и выводит его из Миненталя в порт.

Если сравнивать Гирион и Биф, то скорее герой должен выгонять Гириона нежели Бифа.

Кстати в случае конфликта с Гирионом, почему команда не нападает на Гириона?
Если герой маг и отказывается взять Гириона в команду, тот так же атакует высшего мага огня?

**Comment by Kor-Angar** [comment]
> Нельзя выгнать из команды только Гириона и Биффа. Почему нельзя выгнать Гириона я понимаю. А почему нельзя выгнать Биффа - не понимаю. Вот и всёНельзя выгнать из команды только Гириона и Биффа. Почему нельзя выгнать Гириона я понимаю. А почему нельзя выгнать Биффа - не понимаю. Вот и всё))

Почему нельзя их выгнать обоих?

**Comment by Kor-Angar** [comment]
То есть понятно если их выгнать обоих, понятно если обоих не выгонять. Непонятно, когда Гирион "особенный", так как он ничем особенным не выделяется. Бифф или Ватрас более "особенные" и с точки зрения ЛОРа и с точки зрения игровых процессов.

**Comment by Kor-Angar** [comment]
P. S. 
Напомни условия появления Гириона в обновление

**Comment by dosinabox** [comment]
> Если герой маг и отказывается взять Гириона в команду, тот так же атакует высшего мага огня?

да

> Почему нельзя их выгнать обоих?

У них просто нет таких диалогов.

**Comment by dosinabox** [comment]
> Напомни условия появления Гириона в обновление

1) Маг - уболтать стражников пропустить ГГ на корабль
2) Паладин - приказать стражникам пропустить ГГ на корабль
3) ОнД - показать стражникам письменное разрешение от судьи
4) Любая гильдия - открыть ворота замка, сообщить об этом Хагену, который отзовет всю стражу с корабля

Можно ли открыть ворота замка до пятой главы?

**Comment by Kor-Angar** [comment]
Открыть ворота можно с 5 главы. Раньше нельзя.

**Comment by dosinabox** [comment]
https://github.com/dosinabox/g2nr_unofficial_update/issues/218
