### ISSUE TITLE
Трофеи. Разное

### ISSUE THREAD

**Issue by Kor-Angar** [dosinabox/g2nr_unofficial_update#123]
- Рауль / Шкура троля #33
- Гаан учит выдерать рога. не стесняюсь спросить #119
- Когти Особого Снеппера / Когти Вожака Снепперов #124
- Кровь и Чешуя Дракона с мёртвы драконов #130

*****

- некоторые краулеры (панцири для доспехов)?
- рога мракориса?

**Comment by Kor-Angar** [comment]
А у тролей сердца достаются? Или у демонов и големов?


А если после убийства болотного дракона, при разговоре с Родом в трупе дракона создать что то уникальное, труп болотного дракона не пропадёт?

**Comment by dosinabox** [comment]
> А у тролей сердца достаются?

нет

> Или у демонов и големов?

ну да, это же целый отдельный навык

> А если после убийства болотного дракона, при разговоре с Родом в трупе дракона создать что то уникальное, труп болотного дракона не пропадёт?

Разговор с Родом - необязательно и негарантированное событие, поэтому создавать что-то уникальное нужно в момент смерти дракона. Но и это не поможет, если игрок сразу заберет это. То же самое и с разговором с Родом, если он всё же состоится - можно сразу вернуться к дракону и всё забрать.

**Comment by Kor-Angar** [comment]
> поэтому создавать что-то уникальное нужно в момент смерти дракона. Но и это не поможет, если игрок сразу заберет это.

поэтому я спрашиваю про Рода(или Сайфера). так герой убивает дракона,  забирает сердце. потом говорит с Сайфером/Рода у дракона генерится уникальный лут.

после этого герой идёт дальше. к примеру у Гештата учится спускать кровь дракона и в этот момент если болотный дракон мёртв в его трупе можно сгенерировать кровь.

такое с точки зрения логики/скриптов возможно?

**Comment by dosinabox** [comment]
> такое с точки зрения логики/скриптов возможно?

Да, но... тут всё зависит от игрока. Ты рассматриваешь его сферическим в вакууме, а все игровые ситуации и прохождения уникальны.

> после этого герой идёт дальше.

Или разворачивается и забирает уникальный трофей у дракона. Или вообще не брал Рода с собой в поход на дракона. Или убивает Рода до диалога / до похода на дракона / в Хоринисе. Или телепортируется в замок до диалога. Или дракон убивает Рода. Или диалог не начинается, потому что Род отвлекся на шершня. Или Рода убивают люди-ящеры на подходе к болоту.
Вот и получается, что идеальная ситуация, при которой труп дракона не исчезнет с уникальным трофеем в инвентаре - вообще редкость.

**Comment by dosinabox** [comment]
Вот на примере Гримбальда. Парой строк кода мне удалось его телепортировать и создавать шкуру в трупе - окей. Далее идут нюансы:
- его телепортация может произойти на глазах игрока и это выглядит тупо - сделать нчиего нельзя, ладно, стерпим;
- после телепортации он уходит на свою начальную позицию - значит нужно создание нового распорядка дня в пещере тролля и начало новой игры;
- после телепортации он стоит спиной к игроку - чтобы развернуть точку нужна правка мира и начало новой игры, при этом правка не сработает, если у игрока другой мир из какого-нибудь текстурно-модельного пака.

Вот столько всего нужно сделать, чтобы было по уму. А игрок всё равно сможет потерять шкуру, если просто отклониться от задуманного идеального плана - телепорт, другие монстры, смерть Гримбальда, другой маршрут.

**Comment by Kor-Angar** [comment]
я с этим даже не пытаюсь спорить. ты тему про лут мертвых подняла, я наткнулся на эту возможность. теперь думаю как её можно использовать в игре. не факт что оно будет применимо. 

но понять на уровне логики и зафиксировать эту мысль на мой взгляд нужно.

а можно сгенерить мертвого троля с лутом?

**Comment by dosinabox** [comment]
> а можно сгенерить мертвого троля с лутом?

можно

**Comment by Kor-Angar** [comment]
Здорово

**Comment by Kor-Angar** [comment]
А мертвого дракона с лутом? :-)

**Comment by Kor-Angar** [comment]
Т.е. тогда при изучение навыка выпустить кровь дракона у Гештата можно:
сделать проверку убит ли болотный дракон и если он убит вставить его труп с кровью дракона?

**Comment by Kor-Angar** [comment]
А кровь дракона нужна для ковки супермеча ;-)

**Comment by dosinabox** [comment]
> А мертвого дракона с лутом? :-)

В теории да, но на практике вставка любого дракона в Хоринисе приводит к вылету. Нужно проверить вставку в Минентале и разобраться с ошибкой в Хоринисе.

**Comment by Kor-Angar** [comment]
> Нужно проверить вставку в Минентале

вставляется ;-)

потрошить драконов учит DIA_DJG_711_Godar.d и DIA_VLK_4148_Gestath.d

**Comment by Kor-Angar** [comment]
Расскажешь как вставить труп  дракона с кровью дракона? 😀

**Comment by dosinabox** [comment]
Надо подумать, чтобы не появлялось три трупа одновременно - с сердцем, с кровью и с чешуей.

**Comment by Kor-Angar** [comment]
Навык слития крови
Проверка на заряжен ли глаз Инноса: Если глаз Инноса заряжен, то сердца нет.
Проверка на снятие чешуи: Если навыка снятие чешуи нет, то при изучение крови вставка мертвого дракона  с кровью, иначе вставка крови в труп.

Навык снятие шкуры по такой же логике 😀

**Comment by Kor-Angar** [comment]
предлагаю реализовать возможность потрошить мертвых животных отдельной опцией через помощника. 

тогда это коснется квестовых событий:
- Драконов (кровь)
- Черный Тролль (шкура)
- некоторые краулеры (панцири для доспехов)
- Вожак Снепперов (когти)

**Comment by dosinabox** [comment]
Для снятия когтей вожака не требуется навык.

**Comment by Kor-Angar** [comment]
> Для снятия когтей вожака не требуется навык.

не требуется. хотя по идеи должен требоваться. и эту ситуация теперь можно исправить 
Внёс правки в скрипт и все почти получилось
https://www.youtube.com/watch?v=MjJDfmFyT9s
обрати внимание что есть даже диалог про то что снял ли герой когти и варианты не снял.

Сам снеппер , убраны когти
```
instance NewMine_LeadSnapper(Mst_Default_Snapper)
{
	name[0] = "Вожак стаи";
	level = 16; // 12
	B_SetVisuals_Snapper();
	Npc_SetToFistMode(self);
	Mdl_SetModelScale(self,1.1,1.1,1.1);
	attribute[ATR_HITPOINTS_MAX] = 160;
	attribute[ATR_HITPOINTS] = 160;
//	CreateInvItems(self,ItAt_ClawLeader,1); //
};
```

Билгот при добавления Лидера Снепперов, проверка на навык снятия когтей
```
instance DIA_Bilgot_KNOWSLEADSNAPPER(C_Info)
{
	npc = VLK_4120_Bilgot;
	nr = 4;
	condition = DIA_Bilgot_KNOWSLEADSNAPPER_Condition;
	information = DIA_Bilgot_KNOWSLEADSNAPPER_Info;
	permanent = FALSE;
	description = "Расскажи мне, что ты знаешь. И я вытащу тебя отсюда!";
};


func int DIA_Bilgot_KNOWSLEADSNAPPER_Condition()
{
	if(Npc_KnowsInfo(other,DIA_Bilgot_Hilfe) && (MIS_Fajeth_Kill_Snapper == LOG_Running))
	{
		return TRUE;
	};
};

func void DIA_Bilgot_KNOWSLEADSNAPPER_Info()
{
	AI_Output(other,self,"DIA_Bilgot_KNOWSLEADSNAPPER_15_00");	//Расскажи мне, что ты знаешь. И я вытащу тебя отсюда!
	AI_Output(self,other,"DIA_Bilgot_KNOWSLEADSNAPPER_05_01");	//Я знал, что могу рассчитывать на тебя. Так что будь внимателен. Я довольно долго наблюдаю за снепперами.
	AI_Output(self,other,"DIA_Bilgot_KNOWSLEADSNAPPER_05_02");	//Они очень хитры и могут, ну, как бы... общаться. Они никогда не ходят поодиночке и нападают только стаей.
	AI_Output(self,other,"DIA_Bilgot_KNOWSLEADSNAPPER_05_03");	//Но есть еще кое-что. Среди них есть один особенный. Он редко показывается, но я видел его.
	AI_Output(self,other,"DIA_Bilgot_KNOWSLEADSNAPPER_05_04");	//Другие снепперы низко кланяются, когда проходят мимо него, но никогда не отходят далеко.
	AI_Output(self,other,"DIA_Bilgot_KNOWSLEADSNAPPER_05_05");	//Пока этот зверь не тронется с места, ни один снеппер поблизости даже не шевельнется.
	AI_Output(other,self,"DIA_Bilgot_KNOWSLEADSNAPPER_15_06");	//Где мне найти этого кровожадного зверя?
	AI_Output(self,other,"DIA_Bilgot_KNOWSLEADSNAPPER_05_07");	//Я видел его на ступенях старой сторожевой башни.
	AI_Output(other,self,"DIA_Bilgot_KNOWSLEADSNAPPER_15_08");	//Отлично. Мне кажется, я понял. Спасибо!
	AI_Output(self,other,"DIA_Bilgot_KNOWSLEADSNAPPER_05_09");	//Помни, ты дал мне слово!
	NewMine_LeadSnapper_Spawned = TRUE;
	Wld_InsertNpc(NewMine_LeadSnapper,"OW_ORC_LOOKOUT_2_01");			
	if (PLAYER_TALENT_TAKEANIMALTROPHY[TROPHY_Claws] == TRUE)
	{
		CreateInvItems(NewMine_LeadSnapper,ItAt_ClawLeader,2); // добавляем когти Снеппера
	};

	B_LogEntry(TOPIC_FajethKillSnapper,"Билгот рассказал мне о вожаке стаи снепперов. Он должен быть у старой сторожевой башни.");
	Log_CreateTopic(TOPIC_BilgotEscort,LOG_MISSION);
	Log_SetTopicStatus(TOPIC_BilgotEscort,LOG_Running);
	B_LogEntry(TOPIC_BilgotEscort,"Билгот хочет, чтобы я вывел его из долины.");
};
```
Jergan при изучение навыка проверка на смерть Лидера Снепперов
```
instance DIA_Jergan_Teach(C_Info)
{
	npc = VLK_4110_Jergan;
	nr = 9;
	condition = DIA_Jergan_Teach_Condition;
	information = DIA_Jergan_Teach_Info;
	permanent = TRUE;
//	description = B_BuildLearnString("Покажи мне, как отделять когти",B_GetLearnCostTalent(other,NPC_TALENT_TAKEANIMALTROPHY,TROPHY_Claws));
	description = B_BuildLearnString(NAME_TROPHY_Claws,B_GetLearnCostTalent(other,NPC_TALENT_TAKEANIMALTROPHY,TROPHY_Claws));
};


func int DIA_Jergan_Teach_Condition()
{
	if(Npc_KnowsInfo(other,DIA_Jergan_Claw) && (PLAYER_TALENT_TAKEANIMALTROPHY[TROPHY_Claws] == FALSE))
	{
		return TRUE;
	};
};

func void DIA_Jergan_Teach_Info()
{
	AI_Output(other,self,"DIA_Jergan_Teach_15_00");	//Покажи мне, как отделять когти.
	if(B_TeachPlayerTalentTakeAnimalTrophy(self,other,TROPHY_Claws))
	{
		AI_Output(self,other,"DIA_Jergan_Teach_13_01");	//Когти нужно отрубить одним точным и резким ударом. Тут нельзя колебаться, иначе ты испортишь трофей.
		AI_Output(self,other,"DIA_Jergan_Teach_13_02");	//Таким образом ты можешь отделять не только когти снепперов, но также ящеров и мракорисов.


	if((Npc_IsDead(NewMine_LeadSnapper)) && (NewMine_LeadSnapper_Spawned == TRUE))
	{
		Wld_InsertNpc(NewMine_LeadSnapper,"OW_ORC_LOOKOUT_2_01");
		CreateInvItems(NewMine_LeadSnapper,ItAt_ClawLeader,2); // добавляем когти Снеппера
		B_KillNpc(NewMine_LeadSnapper);	
	};		
		

	};
};

```

**Comment by Kor-Angar** [comment]
вот только меня беспокоит монетка.. можно ли скопировать функцию(?)  B_KillNpc, переименовать её и что бы вместо "старой монетки " появлялся  например уникальный кусок мяса со стоимостью 0?

**Comment by dosinabox** [comment]
Не скопировать, а создать новую, в которой монетка добавляться не будет. Можно в том же файле (Story/B_Story/B_KillNpc.d):

```
instance ItMi_OldBone(C_Item)
{
	name = "Косточка";
	mainflag = ITEM_KAT_NONE;
	flags = ITEM_MULTI | ITEM_MISSION;
	value = 0;
	visual = "ItAt_SkeletonBone.3DS";
	material = MAT_WOOD;
	description = name;
};

func void B_KillAnimal(var int animalInstance)
{
	var C_Npc animal;
	animal = Hlp_GetNpc(animalInstance);
	if(Hlp_IsValidNpc(animal) && !Npc_IsDead(animal))
	{
		animal.flags = 0;
		CreateInvItem(animal,ItMi_OldBone);
		Npc_ChangeAttribute(animal,ATR_HITPOINTS,-animal.attribute[ATR_HITPOINTS_MAX]);
	};
};
```

**Comment by Kor-Angar** [comment]
что то видимо я не то сделал

![image](https://user-images.githubusercontent.com/49514764/67198817-71f04c00-f408-11e9-8742-6cf747931a8d.png)

**Comment by dosinabox** [comment]
У Джергана - так?
```
B_KillAnimal(NewMine_LeadSnapper);
```

**Comment by Kor-Angar** [comment]
я поменял "B_KillNpc" на "B_KillAnimal" и у всех у кого поменял вылезли ошибки.

> Не скопировать, а создать новую, в которой монетка добавляться не будет. Можно в том же файле (Story/B_Story/B_KillNpc.d):

это добавил

**Comment by dosinabox** [comment]
Совершенно непонятно. Попробуй так:
```
func void B_KillAnimal(var C_Npc animalInstance)
{
	...
```

**Comment by Kor-Angar** [comment]
Работает
![image](https://user-images.githubusercontent.com/49514764/67205346-3d848c00-f418-11e9-883a-b7269b6ba45e.png)
![image](https://user-images.githubusercontent.com/49514764/67205373-46755d80-f418-11e9-9f26-6f3f42189f39.png)

**Comment by Kor-Angar** [comment]
итак.. у нас есть появился прецедент с трупами драконов. они не пропадает. предлагаю это дело ещё   раз проверить и попытаться выявить закономерность :-) возможно этот опыт удастся перенести на Чёрного тролля.
