### ISSUE TITLE
Гаррет пояс. Золотой компас.

### ISSUE THREAD

**Issue by Kor-Angar** [dosinabox/g2nr_unofficial_update#128]
вопрос с поясом решили? т.е. если Гаретта избить то Гаретт ничего в награду за компас не даёт?

```
instance DIA_Addon_Garett_GiveKompass(C_Info)
{
	npc = PIR_1357_Addon_Garett;
	nr = 6;
	condition = DIA_Addon_Garett_GiveKompass_Condition;
	information = DIA_Addon_Garett_GiveKompass_Info;
	permanent = FALSE;
	description = "Вот твой компас.";
};


func int DIA_Addon_Garett_GiveKompass_Condition()
{
	if((Npc_HasItems(other,ItMI_Addon_Kompass_Mis) >= 1) && (MIS_ADDON_GARett_BringKompass == LOG_Running))
	{
		return TRUE;
	};
};

func void DIA_Addon_Garett_GiveKompass_Info()
{
	AI_Output(other,self,"DIA_Addon_Garett_GiveKompass_15_00");	//Вот твой компас.
	B_GiveInvItems(other,self,ItMI_Addon_Kompass_Mis,1);
	Npc_RemoveInvItem(self,ItMI_Addon_Kompass_Mis);
	AI_Output(self,other,"DIA_Addon_Garett_GiveKompass_09_01");	//(радостно) Да, это он! Вот уж не думал, что снова его увижу.
	AI_Output(self,other,"DIA_Addon_Garett_GiveKompass_09_02");	//Спасибо, приятель!
	if(Npc_HasItems(self,ItBe_Addon_Prot_EdgPoi))
	{
		AI_Output(self,other,"DIA_Addon_Garett_GiveKompass_09_03");	//На этот раз Грег его не получит.
		AI_Output(self,other,"DIA_Addon_Garett_GiveKompass_09_04");	//Возьми в награду этот пояс. Это одна из самых ценных моих вещей.
		B_GiveInvItems(self,other,ItBe_Addon_Prot_EdgPoi,1);
	}
	else if(self.aivar[AIV_DefeatedByPlayer] == FALSE)
	{
		AI_Output(self,other,"DIA_Addon_Garett_GiveKompass_09_05");	//Помнишь, ты купил у меня пояс.
		AI_Output(self,other,"DIA_Addon_Garett_GiveKompass_09_06");	//Ты заплатил за него порядочную сумму... Нет, конечно он стоит этих денег. В общем, можешь взять их обратно.
		B_GiveInvItems(self,other,ItMi_Gold,Value_ItBE_Addon_Prot_EdgPoi);
	};
	B_LogEntry(TOPIC_Addon_Kompass,"Гаретт был очень рад, когда я вернул ему компас.");
	MIS_ADDON_GARett_BringKompass = LOG_SUCCESS;
	B_GivePlayerXP(XP_ADDON_Garett_Bring_Kompass);
};
```

**Comment by dosinabox** [comment]
да

**Comment by dosinabox** [comment]
- если ГГ купил пояс, то Гаретт возвращает деньги
- если ГГ не купил пояс, то Гаретт дарит пояс
- если ГГ избил Гаретта, то Гаретт не дает ничего

**Comment by dosinabox** [comment]
И в чем хитрость? Избиваем Гаретта, забираем пояс, приносим компас, получаем второй пояс?)

**Comment by Kor-Angar** [comment]
>  Избиваем Гаретта, забираем пояс, приносим компас, получаем второй пояс?)

так с пояса же сняли флаг "для мисси". он теперь не забирается у Гаретта, а просто пропадает. 
https://youtu.be/grkbQXDQmw4?t=2922

или уже опять вернули?:-)

**Comment by dosinabox** [comment]
> ак с пояса же сняли флаг "для мисси". он теперь не забирается у Гаретта, а просто пропадает.

Да, точно.

Но задумка такая, что Гаретт запоминает драку с ГГ и поэтому обижается и ничего не дает) А если применить на нем Забвение (нужно проверить), то забывает про драку, замечает пропажу пояса, думает что это ГГ его купил и возвращает деньги.

**Comment by dosinabox** [comment]
Проверь, пожалуйста. Если после Забвения отдаст деньги, то нужно будет править награду на пояс по твоей схеме. Наверное.

**Comment by Kor-Angar** [comment]
Тут дело так же в самом поясе.В оригинале его можно было1) купить и получить деньги за компас. Т. Е. получить бесплатно2) получить за компас3) отобратьСейчас же пояс может просто пропасть. Т. Е. Герой его не получит. А он во второй главе только у Гаррета.

**Comment by Kor-Angar** [comment]
Про забвению проверю. Но это не ришит вопрос с самим поясом который пропадёт

**Comment by dosinabox** [comment]
Можно сделать новый пояс, чуть хуже того, который пропадает у Гаретта в случае избиения. Такой вот штраф для игрока-агрессора)

**Comment by Kor-Angar** [comment]
мне вот любовь "штрафовать" героя по поводу и без повода честно говоря не понятно. сдаётся что мне дать в морду у Пиратов есть нормальный этикет общения. вроде как они должны после этого зауважать героя. ровно как и наёмники.

получается что в оригинале герой бьет в морду и получает пояс, а в моде герой бъёт в морду и получает "штраф" потому что бить в морду это плохо :-) хотя в оригинальной игре я не припомню мысль от Пираний что бы пираты/наёмы/онд налагали некие санкции за битьё морды.

добрался до компа сейчас проверю заклинание забвение.

**Comment by Kor-Angar** [comment]
за выкопанный компас не дают опыт?

**Comment by Kor-Angar** [comment]
> Проверь, пожалуйста. Если после Забвения отдаст деньги, то нужно будет править награду на пояс по твоей схеме. Наверное.

после забвения ничего не дал

https://www.youtube.com/watch?v=r3cH2mYSJWg

**Comment by dosinabox** [comment]
> после забвения ничего не дал

Мне кажется, или его нужно применять строго тогда, когда цель стоит на ногах?

**Comment by Kor-Angar** [comment]
> Мне кажется, или его нужно применять строго тогда, когда цель стоит на ногах?

так тоже можно. всегда так на Сагитте делал.

**Comment by dosinabox** [comment]
> а если схитрить и сделать так?

готово
