### ISSUE TITLE
Минск

### ISSUE THREAD

**Issue by Kor-Angar** [dosinabox/g2nr_unofficial_update#131]

**Comment by dosinabox** [comment]
Ну и дела. А я сейчас в другом городе живу (в Гродно). Временно. Так что в другой раз(

**Comment by dosinabox** [comment]
Могу подсказать куда сходить, что посмотреть.

**Comment by Kor-Angar** [comment]
Значит в другой раз 😀

**Comment by Kor-Angar** [comment]
Я думаю что мы недолго будем. Посидим в каком нибудь ресторане возле ж/д вокзала. А потом поедим в аэропорт

**Comment by dosinabox** [comment]
А вас сколько?

**Comment by Kor-Angar** [comment]
Двое.

**Comment by Kor-Angar** [comment]
что то странное происходит. Билетов не было. одни билеты на самолет брали через старших товарищей, другие через знакомых.. в продаже в открытом доступе просто нет. даже на поезд не было :-)
![image](https://user-images.githubusercontent.com/49514764/68021195-ce2d5880-fcb1-11e9-9a6d-9d7ac8edfcce.png)
пришлось беспокоить  коллег. что бы сделали бронь.

опасное время наступает :-)

**Comment by dosinabox** [comment]
Если нужно прямо у вокзала, то заходите в тц Галилео, там есть и местная кухня (Васильки), и всякие суши, кофейни, пиццерии. И фудкорт есть с быстрой едой. И макдональдс.

**Comment by dosinabox** [comment]
На любой вкус и кошелек, в общем)

**Comment by Kor-Angar** [comment]
В Васильки почти каждый раз ходим 😀

**Comment by dosinabox** [comment]
На Зыбицкой улице были? На Октябрьской улице? В Троицком предместье? На улице Карла Маркса?

**Comment by Kor-Angar** [comment]
Сложно сказать. Где то наверное точно ыбли 😀

**Comment by dosinabox** [comment]
Как прошло?)

**Comment by Kor-Angar** [comment]
Как обычно попили кофе в кфс. Потом пошли в Васильки поели. Потом вызвали такси и поехали в аэропорт :)

**Comment by dosinabox** [comment]
Нужно больше прогулок!)

**Comment by Kor-Angar** [comment]
Это факт 😀-- Отправлено из мобильного приложения Яндекс.Почты

**Comment by Kor-Angar** [comment]
а ты когда в Минск возвращаешься ?

**Comment by dosinabox** [comment]
А вот не знаю. Наверное, только в следующем году. А пока здесь работа. В идеале хотелось бы перейти на удаленку.

**Comment by Kor-Angar** [comment]
я на следующей недели наверное опять поеду :-|

**Comment by Kor-Angar** [comment]
во вторник, 26 буду в Минске. на этот раз рейс поздно вечером:-/

**Comment by dosinabox** [comment]
а ты в Москве живешь?

**Comment by Kor-Angar** [comment]
Последние время в Москве

**Comment by Kor-Angar** [comment]
Подскажи какой нибудь сайт по аренде квартир в Минске? Какой примерно порядок цен на жильё?

**Comment by dosinabox** [comment]
А тебе на какой срок и сколько комнат?

**Comment by Kor-Angar** [comment]
Наверное три. Или две. От планировки зависит. На год.

**Comment by dosinabox** [comment]
http://realt.by
http://neagent.by

1 доллар = 2 белорусских рубля

Цены очень разные, но средние вот такие:
![c8601d37384f540e81e32af17ec7eacc](https://user-images.githubusercontent.com/39790055/69606927-2e0aeb00-1035-11ea-9437-cd898d92c6bb.png)

Если дороже, то должно быть чем-то хорошим, с современным ремонтом, техникой, расположением...

**Comment by Kor-Angar** [comment]
Ясно. Спасибо большое.

**Comment by dosinabox** [comment]
что, переезжаешь?)

**Comment by Kor-Angar** [comment]
Пока нет. Но решил рассмотреть Минск как запасной аэродром :-)

**Comment by Kor-Angar** [comment]
Это за 100 тысяч $ можно 3 комнатную квартиру купить что ли?

**Comment by dosinabox** [comment]
> Это за 100 тысяч $ можно 3 комнатную квартиру купить что ли?

Да, запросто) Тысяч за 80 даже можно, если в простом районе.

**Comment by Kor-Angar** [comment]
Ну это весьма и весьма интересный вариант. Надо в следующий раз приехать на пару дней раньше приехать и дня три по Минску походить 😀Как там твоя работа? Кипит?

**Comment by dosinabox** [comment]
Кипит, кипит. Думаю, скоро уже вернусь. А ты сейчас в Минске?

**Comment by Kor-Angar** [comment]
Угу. Сижу в васильках, жду когда коллега прилетит. Поздно  вечером полетим.Вернёшься в Минск? Или вернёшься к Готике? 😀

**Comment by dosinabox** [comment]
В Минск, а Готика всегда со мной) Почти каждый день что-нибудь делаю по скриптам, сейчас ещё помогаю Квинциусу с доработкой миров, а в ближайшие недели выпущу новый стим-фикс.

**Comment by dosinabox** [comment]
> В Минск, а Готика всегда со мной) Почти каждый день что-нибудь делаю по скриптам, сейчас ещё помогаю Квинциусу с доработкой миров, а в ближайшие недели выпущу новый стим-фикс с SP 1.8.

**Comment by Kor-Angar** [comment]
Гуд. Может в следующий раз увидимся 😀

**Comment by dosinabox** [comment]
уж постараюсь

**Comment by dosinabox** [comment]
https://realt.onliner.by/2019/11/22/podeshevel
)

**Comment by Kor-Angar** [comment]
Это не с проста 😀12:19, 26 ноября 2019 г., dosinabox <notifications@github.com>:https://realt.onliner.by/2019/11/22/podeshevel
)

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
-- Отправлено из мобильного приложения Яндекс.Почты

**Comment by Kor-Angar** [comment]
А у меня запрет на выезд сняли. Я теперь через Минск не езжу. Сразу напрямую из Москвы в Стамбул. Ты в Минск вернулась?

**Comment by dosinabox** [comment]
> Ты в Минск вернулась?

Нет. В следующем году уже.
