### ISSUE TITLE
Пионер на мосту правки

### ISSUE THREAD

**Issue by Kor-Angar** [dosinabox/g2nr_unofficial_update#136]
а можно тебя попросить написать тут код пионера(разбойник на мосту) из последней версии неофициального обновления.

играл в Готику 2 оригинал пытался отдать ему оружие но что то не получилось. ты вроде бы писала что это исправляла. так же получился дубль диалогов про дать денег(один за то что бы пройти, второй за инфу о послушнике)
https://youtu.be/wjA0DCiRH7Q?t=3912
![image](https://user-images.githubusercontent.com/49514764/69337651-6ba4f800-0c72-11ea-8793-f39640c48e97.png)

**Comment by dosinabox** [comment]
> играл в Готику 2 оригинал пытался отдать ему оружие но что то не получилось

А там это и не реализовано никак - ГГ огрызается и ничего ему не отдает.

> так же получился дубль диалогов про дать денег

Исправлено.

> а можно тебя попросить написать тут код пионера(разбойник на мосту) из последней версии неофициального обновления

https://github.com/dosinabox/g2nr_unofficial_update/blob/work/PrjGOTHIC/Story/Dialoge/DIA_BDT_1020_Bandit_L.d

**Comment by dosinabox** [comment]
Интересно, что в Г2 оригинал этот бандит появляется там сразу с началом игры, а в аддоне его появление перенесли на начало второй главы у Хагена. Может, чтобы не конфликтовать с Ларесом при походе на раскопки. Так что в Г2НВ этот диалог про послушника вообще стал недоступным) А во второй главе его можно вообще пропустить и встретить только в третьей, во время поисков Глаза - и убить его с пары ударов.

**Comment by dosinabox** [comment]
Поэтому предлагаю вставлять этого бандита в мир не только при начале второй главы, но и при начале Испытания Огнем - для послушника он всё ещё может быть серьезным соперником, да и диалог будет задействован.

**Comment by Kor-Angar** [comment]
Хорошее дело 😀Можно так же вставлять его после разговора с Сатурасом ( там как раз респаун падальщиков происходит).

**Comment by dosinabox** [comment]
> Можно так же вставлять его после разговора с Сатурасом

Тогда подходить к разбойнику будем со спины, а требовать плату он будет с ГГ, который уже стоит на мосту. Наверное, можно сделать другой распорядок дня на этот случай, чтобы стоял он на другой стороне. Но тут много "если".

**Comment by Kor-Angar** [comment]
Гм.. Но от Сатураса же ГГ идёт через телепорт..Можно озадачится этим вопросом и расписать разные варианты его появления.

**Comment by dosinabox** [comment]
В теории можно вообще с начала игры его вставлять. Я же делала систему, чтобы он прятался неподалеку, если ГГ идет с Ларесом. Только там ещё гоблины...

**Comment by Kor-Angar** [comment]
Так гоблинов в оригинале не было. Это разве не ты их добавила?

**Comment by dosinabox** [comment]
Я, для охраны арбалета.
Всё, разобралась. Будет вставляться с началом игры) При подходе Лареса спрячется. Вернется, когда Ларес доведет ГГ до раскопок.

**Comment by Kor-Angar** [comment]
А как же гоблин? 😀 Уберешь?

**Comment by dosinabox** [comment]
Их разбойник "убьет", когда будет прятаться (скрипт их уберет).

**Comment by Kor-Angar** [comment]
Понятно. Хочу протестить, послушником отдать ему молоток вместо денег и посмотреть получится ли у него убить магического голема.

**Comment by dosinabox** [comment]
Попробуй, начав новую игру (только для релизной версии v23 от 16.11):
[g2a_nr_scriptpatch_v23_hotfix.zip](https://github.com/dosinabox/g2nr_unofficial_update/files/3876808/g2a_nr_scriptpatch_v23_hotfix.zip)

Заодно можно проверить все комбинации с Ларесом, гоблинами и сторонами подхода, вопрос про послушника, золото, передачу оружия, реплики и т.д.
Использование предмета **d36testrune** включит переменную, которая позволит задать вопрос про послушника.

**Comment by dosinabox** [comment]
Это к Г2НВ, если что.

**Comment by Kor-Angar** [comment]
Пионер не агрится на магического голема

вот тут
```
AI_Output(other,self,"DIA_BDT_1020_Wegelagerer_FirstWarn_GiveWeapon_15_00");	//Вот, возьми мое оружие.
	if(!Npc_HasReadiedWeapon(other))
	{
		AI_Output(self,other,"DIA_BDT_1020_Wegelagerer_SecondWarn_GiveMoney_06_01");	//Ох, как мы заговорили.
		AI_EquipBestMeleeWeapon(self);
		self.aivar[AIV_PASSGATE] = TRUE;
		AI_StopProcessInfos(self);
	}
```
добавить второй вариант ответа, если ГГ спрашивал про послушника, т.е. по подобию вот этого диалога

```
AI_Output(other,self,"DIA_BDT_1020_Wegelagerer_FirstWarn_GiveMoney_15_00");	//Хорошо, вот деньги.
	if(Wegelagerer_Surprise == FALSE)
	{
		AI_Output(self,other,"DIA_BDT_1020_Wegelagerer_FirstWarn_GiveMoney_06_01");	//(насмешливо) Скажу тебе, 20 золотых - это не такая уж большая плата за жизнь. Ты можешь проходить.
	}
	else
	{
		AI_Output(self,other,"DIA_BDT_1020_Wegelagerer_FirstWarn_GiveMoney_06_02");	//Хорошо, этот послушник прошел здесь около часа назад.
		AI_Output(self,other,"DIA_BDT_1020_Wegelagerer_FirstWarn_GiveMoney_06_03");	//По-моему, он немного торопился, все время оглядывался... А теперь проваливай.
	};
```

**Comment by dosinabox** [comment]
> Пионер не агрится на магического голема

Возможно, нужен не агр, а бегство) Нужно проверить как разные существа регируют на этого голема и подумать. 

> добавить второй вариант ответа, если ГГ спрашивал про послушника

Готово.

**Comment by Kor-Angar** [comment]
А зачем бегства если его таким образом можно задействовать в убийстве Магического Голема? 😀

**Comment by dosinabox** [comment]
> А зачем бегства если его таким образом можно задействовать в убийстве Магического Голема? 😀

Это странная идея) Почему кто-либо не должен убегать от магического голема, как убегает от обычного голема?
Скорее всего, пионер не реагирует на голема, потому что является "стражником" и должен стоять на своем посту. Все стражники чего-либо (например, на проходе) не реагируют на монстров, чтобы их нельзя было выманить. Но мне кажется, что конкретно пионер должен реагировать, а от сильных монстров убегать.

**Comment by Kor-Angar** [comment]
А убегать это новая фишка? Разве раньше НПС убегали?

**Comment by Kor-Angar** [comment]
Ульф за мостом который стоит не убегает, а атакует его.  Этот то точно должен убегать так как знает что его не победить.
