### ISSUE TITLE
Гарод и Меч Элитного орка

### ISSUE THREAD

**Issue by Kor-Angar** [dosinabox/g2nr_unofficial_update#137]
я вот думал в прошлом году и позапрошлом о том что можно давать какой то бонус если герой даёт Гароду Меч Элитного Орка. 
как миниму больше опыта. или например кольцо к силе. или поднимать +1 к силе, если у героя силы меньше 30. т.е. какую то такую штуку что бы не влияло на баланс, но в тоже время было приятной неожиданностью :-)

**Comment by dosinabox** [comment]
Что если этой штукой будет одежда кузнеца или новая одежда подмастерья?

**Comment by Kor-Angar** [comment]
Хорошая идея в принципе приёме в подмостерье 😀

**Comment by dosinabox** [comment]
Продумай статы - сделаю)

**Comment by dosinabox** [comment]
Ещё есть восстановленный орочий молот из Г1, которым вооружены орки-нежить на Ирдорате, шаман-предводитель в Яркендаре и Хош-Пак. По идее за этот молот должна полагаться бОльшая награда.

**Comment by Kor-Angar** [comment]
Так Молота же в Хориносе нет

**Comment by dosinabox** [comment]
Поступить в ученики к Гараду можно и во второй главе, после Яркендара и/или Миненталя.

**Comment by Kor-Angar** [comment]
Так игру и без доспехов пройти можно с палкой ;-)

**Comment by Kor-Angar** [comment]
вообщем я к чему всё это писал и тему начинал. Элитного орка можно убить с Ларесом. и возможно что кузнец может это оценить. про это мой первый пост.

то что кузнец своему ученику даёт одежду помощника кузнеца это хорошая идея. ровно как и Боспер и Константино могут давать своему ученику одежду.

а вот про молоток который дали оркам-шаманам я сказать ничего не могу, т.к. мне это не очень  понятна. не уверен поймет ли кузнец что это оружие орков.  

да и сама идея давать этот молоток шаманам была на мой взгляд не самая понятная идея. лучше бы им заклинание дали "малый огненный шторм".

**Comment by Kor-Angar** [comment]
> а вот про молоток который дали оркам-шаманам я сказать ничего не могу, т.к. мне это не очень понятна. не уверен поймет ли кузнец что это оружие орков.

молотка-орков у лидера Шаманов в Ярике не было. убрала?

**Comment by dosinabox** [comment]
у него и не было, как оказалось

**Comment by Kor-Angar** [comment]
В прошлых версиях неофицильного обновления кажется был

**Comment by dosinabox** [comment]
нет, это специально чтобы он не был копией Хош-Пака

**Comment by dosinabox** [comment]
За меч элитного орка, топор предводителя орков или молот Хош-Пака ГГ получит в три раза больше опыта (200*3).

**Comment by Kor-Angar** [comment]
> топор предводителя орков

Это который ItMw_2H_OrcSword_01 или который ItMw_2H_Orcaxe_04?
