### ISSUE TITLE
Добивание НПС когда он без сознания 

### ISSUE THREAD

**Issue by Kor-Angar** [dosinabox/g2nr_unofficial_update#140]
Сейчас НПС без сознания можно добить только мечем. Может сделать что бы его можно было добить так же и магией и из Лука?

**Comment by dosinabox** [comment]
Луком точно нет - ограничения движка. В Г1 ещё нельзя было добивать оружием с дробящим уроном. В Г2 рыбки на это забили и ГГ протыкает всех топорами-булавами-молотами с анимацией меча.
Магией - не знаю. Можно попробовать отключить ограничения в скриптах, но точно будут проблемы с анимацией, а кроме скриптовых ограничений могут быть ограничения движковые.
