### ISSUE TITLE
Руга не учит послушника

### ISSUE THREAD

**Issue by Kor-Angar** [dosinabox/g2nr_unofficial_update#141]
забыли про послушника. сейчас Руга откажется учить послушника и..  предложит ему вступить в ополчение :-) 

судя по "логике" фракций Руга должен учить в том числе и Послушника. 

```
instance DIA_Ruga_Train(C_Info)
{
	npc = MIL_317_Ruga;
	nr = 5;
	condition = DIA_Ruga_Train_Condition;
	information = DIA_Ruga_Train_Info;
	permanent = TRUE;
	description = "Ты можешь потренировать меня?";
};


func int DIA_Ruga_Train_Condition()
{
	if(Ruga_TeachCrossbow == FALSE)
	{
		return TRUE;
	};
};

func void DIA_Ruga_Train_Info()
{
	AI_Output(other,self,"DIA_Ruga_Train_15_00");	//Ты можешь потренировать меня?
	if((hero.guild == GIL_MIL) || (hero.guild == GIL_PAL) || (hero.guild == GIL_KDF))
	{
		AI_Output(self,other,"DIA_Ruga_Train_11_01");	//Конечно. Если у тебя достаточно опыта, я готов помочь тебе.
		AI_Output(self,other,"DIA_Ruga_Train_11_02");	//Но нужно понимать, что ловкость и стрельба неотделимы друг от друга, как арбалет и стрела. Одно...
		AI_Output(other,self,"DIA_Ruga_Train_15_03");	//... ничего не стоит без другого. Я понял.
		Ruga_TeachCrossbow = TRUE;
		Ruga_TeachDEX = TRUE;
	}
	else if((hero.guild == GIL_SLD) || (hero.guild == GIL_DJG))
	{
		AI_Output(self,other,"DIA_Ruga_Train_11_04");	//(презрительно) Убирайся с глаз моих, наемник.
		AI_StopProcessInfos(self);
	}
	else
	{
		AI_Output(self,other,"DIA_Ruga_Train_11_05");	//Нет. Я тренирую только людей, состоящих на службе у короля. Больше никого.
		AI_Output(self,other,"DIA_Ruga_Train_11_06");	//Но нам всегда нужны хорошие люди. Так что, если хочешь поступить в ополчение, поговори с лордом Андрэ.
	};
};
```

**Comment by dosinabox** [comment]
А разве послушники состоят на службе у короля? Я так не думаю. Нужно просто ограничить эту реплику только для нейтрала:
```
AI_Output(self,other,"DIA_Ruga_Train_11_06");	//Но нам всегда нужны хорошие люди. Так что, если хочешь поступить в ополчение, поговори с лордом Андрэ.
```

**Comment by Kor-Angar** [comment]
Тогда что он будет говорить послушнику? А разве маги состоят на службе у короля? Если. Маги состоят на службе короля то значит состоит на службе короля святая церковь Инноса значит и послушнику состоят на службе у короля :-) 10:39, 20 декабря 2019 г., dosinabox <notifications@github.com>:А разве послушники состоят на службе у короля? Я так не думаю. Нужно просто ограничить эту реплику только для нейтрала:
AI_Output(self,other,"DIA_Ruga_Train_11_06");	//Но нам всегда нужны хорошие люди. Так что, если хочешь поступить в ополчение, поговори с лордом Андрэ.


—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
-- Отправлено из мобильного приложения Яндекс.Почты

**Comment by dosinabox** [comment]
> Тогда что он будет говорить послушнику?
```
AI_Output(self,other,"DIA_Ruga_Train_11_05");	//Нет. Я тренирую только людей, состоящих на службе у короля. Больше никого.
```

> Маги состоят на службе короля то значит состоит на службе короля святая церковь Инноса значит и послушнику состоят на службе у короля :-)

Не знаю, не знаю. Для меня "послушники" не равно "церковь", "маги", "служба".

**Comment by Kor-Angar** [comment]
в целом то это не существенно так как герой послушником проводит мало времени. гильдия послушников весьма и весьма короткая :-) но с точки зрения игровой логики не очень понятно так как у ментов три учителя Руга / ловкость / арбалетВульфгар / 1р и 2рМортис / Сила при этом они все по разному учат Маг Огня / Послушника.   Вот например Мага Огня учит Руга и Вульфгар, по моему даже у них на него есть специальные реплики, а Мортис почему то Мага Огня не учит. Послушника Вульфгар учит, а Руга и Мортис нет :-)      **********тут нет варианта для гильдии Паладин  instance DIA_PAL_263_PERM_CIV(C_Info){    npc = PAL_263_Wache;    nr = 2;    condition = DIA_PAL_263_PERM_CIV_Condition;    information = DIA_PAL_263_PERM_CIV_Info;    permanent = TRUE;    description = "Как обстановка?";}; func int DIA_PAL_263_PERM_CIV_Condition(){    if((hero.guild == GIL_SLD) || (hero.guild == GIL_DJG) || (hero.guild == GIL_NONE))    {        return TRUE;    };}; func void DIA_PAL_263_PERM_CIV_Info(){    AI_Output(other,self,"DIA_PAL_263_PERM_OTH_15_00");    //Как обстановка?    AI_Output(self,other,"DIA_PAL_263_PERM_OTH_04_01");    //Мы держим ситуацию под контролем. Тебе не о чем беспокоиться, гражданский. Все будет хорошо.}; instance DIA_PAL_263_PERM_OTH(C_Info){    npc = PAL_263_Wache;    nr = 2;    condition = DIA_PAL_263_PERM_OTH_Condition;    information = DIA_PAL_263_PERM_OTH_Info;    permanent = TRUE;    description = "Кто командует здесь?";}; func int DIA_PAL_263_PERM_OTH_Condition(){    if((hero.guild == GIL_MIL) || (hero.guild == GIL_NOV) || (hero.guild == GIL_KDF))    {        return TRUE;    };}; func void DIA_PAL_263_PERM_OTH_Info(){    AI_Output(other,self,"DIA_WACHE_PERM_15_00");    //Кто командует здесь?    AI_Output(self,other,"DIA_WACHE_PERM_10_01");    //Наш командующий Гаронд и два его советника, паладины Орик и Парсиваль.    AI_Output(self,other,"DIA_WACHE_PERM_10_02");    //Днем ты можешь застать их в тронном зале на первом этаже.};
