### ISSUE TITLE
ключи от башен Хориноса

### ISSUE THREAD

**Issue by Kor-Angar** [dosinabox/g2nr_unofficial_update#142]
может вот эти ключи в игре подписать?

> ItKe_City_Tower_06
> ItKe_City_Tower_01
> ItKe_City_Tower_02
> ItKe_City_Tower_03
> ItKe_City_Tower_04
> ItKe_City_Tower_05

например "ключ от башни (был у Пека)"

**Comment by dosinabox** [comment]
Они существуют в единственных экземплярах только в инвентарях? В мире или сундуках их нет?

**Comment by Kor-Angar** [comment]
Пять из шести в инвентаря у НПС. 10:36, 20 декабря 2019 г., dosinabox <notifications@github.com>:Они существуют в единственных экземплярах только в инвентарях? В мире или сундуках их нет?

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
-- Отправлено из мобильного приложения Яндекс.Почты

**Comment by dosinabox** [comment]
А где шестой?

**Comment by Kor-Angar** [comment]
а вот шестой в сундуке в казарме.20.12.2019, 14:34, "dosinabox" <notifications@github.com>:А где шестой?

**Comment by Kor-Angar** [comment]
тут главное, на мой взгляд, подписать те пять что у Ополченцев. а они только в их инвентаре.

**Comment by dosinabox** [comment]
готово

**Comment by Kor-Angar** [comment]
Отлично
