### ISSUE TITLE
Gothic High Resolution FONT (Cyrillic/Latin)

### ISSUE THREAD

**Issue by Kor-Angar** [dosinabox/g2nr_unofficial_update#143]
а почему ты в сборку не добавишь шрифты?
https://worldofplayers.ru/threads/25865/

**Comment by dosinabox** [comment]
Потому что для использования с модом им не требуется никакая адаптация с моей стороны.

**Comment by Kor-Angar** [comment]
я имел ввиду в стим фикс. т.е. после того как я обновляю твой стим фикс у меня слетают эти шрифты. а без них тексты и субтитры при большом разрешение  выглядят плохо
