### ISSUE TITLE
Каваларон запись про одежду

### ISSUE THREAD

**Issue by Kor-Angar** [dosinabox/g2nr_unofficial_update#145]
Каваларон говорит о том что ГГ должен купить доспехи и даёт золото. При этом записи в дневнике соответствующей нет

**Comment by Kor-Angar** [comment]
if(!Npc_HasEquippedArmor(other) && (hero.guild == GIL_NONE))
	{
		AI_Output(self,other,"DIA_Addon_Cavalorn_VatrasBrief_08_11");	//А, да, и еще одно. Сначала купи приличную одежду у какого-нибудь фермера.
		AI_Output(self,other,"DIA_Addon_Cavalorn_VatrasBrief_08_12");	//Иначе тебя могут принять за бандита. Вот пара монет.
		CreateInvItems(self,ItMi_Gold,50);
		B_GiveInvItems(self,other,ItMi_Gold,50);
	};

**Comment by dosinabox** [comment]
А куда должна добавляться запись?

**Comment by Kor-Angar** [comment]
![image](https://user-images.githubusercontent.com/49514764/71675149-3a016f80-2d8e-11ea-996d-6f4b945c7510.png)
наверное сюда

**Comment by dosinabox** [comment]
добавлено
