### ISSUE TITLE
тест. версия 24

### ISSUE THREAD

**Issue by Kor-Angar** [dosinabox/g2nr_unofficial_update#147]
пиши что надо протестить

**Comment by Kor-Angar** [comment]
жду тестовую сборку :-)

**Comment by dosinabox** [comment]
Пока вот. Файл .mod - в папку Data\ModVDF. Нужна установленная релизная версия 23 от 16.11.2019.

[g2a_nr_scriptpatch_v24_test1_02.01.19.zip](https://github.com/dosinabox/g2nr_unofficial_update/files/4016307/g2a_nr_scriptpatch_v24_test1_02.01.19.zip)

**Comment by dosinabox** [comment]
> пиши что надо протестить

Талбин, его квест и переход до Прохода.
Разбойник у моста и диалоги с ним.
Ключи, их положение в инвентаре, правильная работа.

Список изменений будет завтра. Ещё допилю немного и объявлю о тестировании официально.

**Comment by Kor-Angar** [comment]
![image](https://user-images.githubusercontent.com/49514764/71675548-083cd880-2d8f-11ea-81d0-9e3cdd292333.png)

**Comment by dosinabox** [comment]
Гуд. В идеале бы начать новую игру, но таких изменений не очень много. Отмечу их в списке завтра.

**Comment by Kor-Angar** [comment]
> Ключи, их положение в инвентаре, правильная работа.

какие могут с ними глюки возникнуть?

**Comment by dosinabox** [comment]
Полный список изменений и сегодняшняя сборка:
https://github.com/dosinabox/g2nr_unofficial_update/releases/tag/v24.1

**Comment by Kor-Angar** [comment]
напомни как там хитро может послушник вернуть статуэтку инноса, вместо 1000 золотых?

**Comment by Kor-Angar** [comment]
если квест не брался на быстрое вступление в монастырь

**Comment by Kor-Angar** [comment]
Очень сложно получилось. Точнее маловероятно. Что бы это произошло нужно:
1) стать послушником
2) тут же, не выполняя квестов монастыре уйти в город (хотя там делать нечего и причин туда идти нет. 
3) в городе поговорить с Дароном
4) найти статуэтку
5) вернуться в город ещё раз с поговорить Дароном
6) пойти в монастырь поговоритьс Педро. 
7) поговорить с мастером Игарац(?).

****

Я бы предложил, если герой становится послушником, перенести Дарона в монастырь, что бы он там выдал задание на пропавшую статуэтку. Тогда игроку стало бы понятно, что есть вариант не платить 1000 монет а сбегать за статуэткой, по крайней мере был бы намёк на это. При той ситуации что сейчас шанса сэкономить 1000 золотых, минимально, стреиящийся к нули. Намёка нет. О такой возможности в игре не узнать. Послушника в город отправляет маг, после того как он попадает в библиотеку. А в библиотеку он попадает после того как отсыпал 1000 золотых и выполнил квесты на доступ в библиотеку😀

**Comment by Kor-Angar** [comment]
Не могу тпик найти про статуэтку 🙃

**Comment by dosinabox** [comment]
релиз - 21 февраля
