### ISSUE TITLE
Доспехи. Разное

### ISSUE THREAD

**Issue by Kor-Angar** [dosinabox/g2nr_unofficial_update#150]
//	name = "Тяжелые доспехи стражника";
	name = "Доспехи стражи Ворона";

Rüstung von Ravens Garde

правильно будет "Доспехи гвардии Равена".

**Comment by dosinabox** [comment]
Торус говорит так:
```
AI_Output(self,other,"DIA_Addon_BDT_10014_Thorus_Armor_12_01");	//Нигде. Эти доспехи сделаны специально для охранника Ворона.
```

**Comment by Kor-Angar** [comment]
а в немецкой версии? 
 это я уже для лучшего понимаю ЛОРа интересуюсь :-)

**Comment by dosinabox** [comment]
> а в немецкой версии?

Gar nicht. Die Rьstungen sind Ravens Garde vorbehalten.

**Comment by Kor-Angar** [comment]
а я вот про этот доспех как то спрашивал ITAR_Beggar 
он откуда взялся? :-)

**Comment by dosinabox** [comment]
из Сиквела
