### ISSUE TITLE
вопросы по НПС Бандитам

### ISSUE THREAD

**Issue by Kor-Angar** [dosinabox/g2nr_unofficial_update#153]
Подскажи пожалуйста в файле
\PrjGOTHIC\Story\Startup.d
закомментированы бандиты
```
//	Wld_InsertNpc(BDT_1000_Bandit_L,"NW_FARM1_BANDITS_CAVE_06");
//	Wld_InsertNpc(BDT_1001_Bandit_L,"NW_FARM1_BANDITS_CAVE_07");
//	Wld_InsertNpc(BDT_1002_Bandit_L,"NW_FARM1_BANDITS_CAVE_08");
	Wld_InsertNpc(BDT_1001_Bandit_L,"NW_FARM1_BANDITS_CAVE_03");
	Wld_InsertNpc(BDT_1017_Bandit_L,"NW_FARM1_BANDITS_CAVE_06");
	Wld_InsertNpc(BDT_1012_Bandit_L,"NW_FARM1_BANDITS_CAVE_07");
	Wld_InsertNpc(BDT_1018_Bandit_L,"NW_FARM1_BANDITS_CAVE_08");
```
это одних бандитов на других поменяли? и где это место? :-)

и вот тут идут, тоже понять не могу куда их вставляют..
	```
Wld_InsertNpc(BDT_1000_Bandit_L,"OW_WOODRUIN_FOR_WOLF_SPAWN");
	Wld_InsertNpc(BDT_1001_Bandit_L,"OW_WOODRUIN_FOR_WOLF_SPAWN");
	Wld_InsertNpc(BDT_1002_Bandit_L,"OW_WOODRUIN_WOLF_SPAWN");
	Wld_InsertNpc(BDT_1003_Bandit_M,"PATH_OC_NC_14");
```

**Comment by dosinabox** [comment]
Чтобы узнать где находится какая-либо точка, в консоли пиши **goto waypoint PATH_OC_NC_14**.
Конкретно в этих случаях мне понадобилось изменить одинаковых бандитов на уникальных. чтобы правильно работал скрипт атаки главаря из квеста Малета. По сути ничего не поменялось, это те же бандиты на старых местах, но с другими идентификаторами.
