### ISSUE TITLE
Жарим мясо. / плита / сковородка

### ISSUE THREAD

**Issue by Kor-Angar** [dosinabox/g2nr_unofficial_update#158]
Сейчас я как понимаю есть два варианта:
*Пожарить все мясо
*конец

При этом "конец" это фактически "пожарить одно мясо"

Может вместо "конец" тогда  сделать надпись "пожарить одно мясо"? ;-)

**Comment by dosinabox** [comment]
Нельзя из-за технических ограничений анимации.

**Comment by Kor-Angar** [comment]
а какой файл за это отвечает? наверное я просто неправильно мысль донёс:-)

**Comment by dosinabox** [comment]
Сложно сказать. Как только ГГ начинает взаимодействие с плитой, то один кусок сырого мяса у него сразу пропадает. А когда нажимаем на "конец", то в инвентарь добавляется один кусок жареного мяса (которое ГГ только что пожарил на сквородке - в анимации видно).

**Comment by Kor-Angar** [comment]
ну да. я про то и говорю. просто "конец" переименовать в "пожарить одно мясо". в итоге будет два варианта

- пожарить одно мясо
- пожарить всё мясо

**Comment by dosinabox** [comment]
Короче говоря - мясо является пожаренным еще до завершения взаимодействия.

**Comment by Kor-Angar** [comment]
я это понял:-) именно поэтому этот топик и завёл :-) ElderGamer тоже почему то конец не убрал :-)
![image](https://user-images.githubusercontent.com/49514764/74595560-0df73080-5054-11ea-95a4-171784e84356.png)

**Comment by Kor-Angar** [comment]
так будет работать?
**SmithWeapon.d**
```
instance PC_PAN_CANCEL(C_Info)
{
	npc = PC_Hero;
	nr = 999;
	condition = pc_pan_cancel_condition;
	information = pc_pan_cancel_info;
	important = FALSE;
	permanent = TRUE;
//	description = Dialog_Ende;
	description = "Пожарить один кусок сырого мяса";

};


func int pc_pan_cancel_condition()
{
	if(PLAYER_MOBSI_PRODUCTION == MOBSI_PAN)
	{
		return TRUE;
	};
};

func void pc_pan_cancel_info()
{
	AI_PrintScreen("Мясо пожарено",-1,YPOS_GoldGiven,FONT_ScreenSmall,2);
	b_endproductiondialog();
};
```

**Comment by Kor-Angar** [comment]
> так будет работать?

получилось :-)

![image](https://user-images.githubusercontent.com/49514764/75733619-df8d7c80-5d06-11ea-9e3b-bbe19933db9d.png)

**Comment by Kor-Angar** [comment]
для того что бы готовить на плите сковородка не нужна?

**Comment by dosinabox** [comment]
Не нужна, но в планах есть такое требование. Даже в скриптах уже готовы нужные функции, осталось связать их с объектами в мирах.

Плиты - сковорода
Наковальня - кузнечный молот
Рунный стол - щипцы
