### ISSUE TITLE
Карлас рано выходит 

### ISSUE THREAD

**Issue by Kor-Angar** [dosinabox/g2nr_unofficial_update#161]
Карлас слишком рано выходит на место убиенного Франко, начальника охотников.

Там в диалоге Рамон говорит что Торус кого нибудь пошлёт на место Франко. И пока идёт диалог с Рамоном мимо проходит Карлос. 
1 час 54 минута
https://youtu.be/JWNony8yKs0

***

Может Карлосу менять расписание например после разговора с Санчо?

**Comment by dosinabox** [comment]
лучше не трогать
