### ISSUE TITLE
Флетчер. Упоминание в коде

### ISSUE THREAD

**Issue by Kor-Angar** [dosinabox/g2nr_unofficial_update#162]
Только сегодня первый раз обратил внимание, что в диалоге упоминается Флетчер, стражника старого лагеря из Готики 1.

Он случайно где нибудь в коде ещё не упоминается?

**Comment by dosinabox** [comment]
> Он случайно где нибудь в коде ещё не упоминается?

Нет.

А ещё он написал записку, прикрепленную к хижине на болотах.
