### ISSUE TITLE
Меч Фероса. 4 глава

### ISSUE THREAD

**Issue by Kor-Angar** [dosinabox/g2nr_unofficial_update#163]
Посмотри пожалуйста когда в 3 главе появляется Меч Фероса.
ItMW_1H_FerrosSword_Mis

Кажется он появляется после диалога с Феросом, хотя по логике должен появляться просто в 3 главе.

**Comment by dosinabox** [comment]
Сам Феррос появляется только в главе 4: B_ENTER_OLDWORLD_Kapitel_4.
Его меч тоже будет появляться на своем обычном месте в главе 4, вместе со вставкой Ферроса.

**Comment by Kor-Angar** [comment]
> когда в 3 главе

Описался. Конечно в 4 😀

**Comment by Kor-Angar** [comment]
> Его меч тоже будет появляться на своем обычном месте в главе 4, вместе со вставкой Ферроса

Отлично 😀
