### ISSUE TITLE
MIS_Addon_Cavalorn_GetOrnamentFromPAL / 1 глава

### ISSUE THREAD

**Issue by Kor-Angar** [dosinabox/g2nr_unofficial_update#172]
Получается что не вступив во фракцию нельзя забрать у Лорда Хагена орнамент
MIS_Addon_Cavalorn_GetOrnamentFromPAL ?

**Comment by dosinabox** [comment]
можно

**Comment by Kor-Angar** [comment]
а как к ниму пройти? Паладины не пускают..

**Comment by dosinabox** [comment]
Ну, это само собой. Но если пройти к нему багоюзом или читом, то диалог всё равно будет доступен, потому что ограничений по гильдии в скриптах нет.

**Comment by dosinabox** [comment]
А если ты про режим прохождения без гильдии, то нейтрал получает доступ к Хагену через Ли, передавая его предложение мира.

**Comment by Kor-Angar** [comment]
Я логику пытаюсь понять 😀 подразумевал авторы возмржность сдачи квеста в первой главе или нет 😀
