### ISSUE TITLE
Гримбальд. Охота на Снепперов

### ISSUE THREAD

**Issue by Kor-Angar** [dosinabox/g2nr_unofficial_update#175]
Гримбальд стал давать опыт за убийство снепперов. в оригинале такого не было. давно добавили?:-)

Может так же  сделать что бы после убийства снепперов он их обыскивал(потрошил)?:-) он же охотник:-)

**Comment by dosinabox** [comment]
> Гримбальд стал давать опыт за убийство снепперов. в оригинале такого не было. давно добавили?:-)

Когда-то до меня. Не думаю, что это неправильно.

> Может так же сделать что бы после убийства снепперов он их обыскивал(потрошил)?:-) он же охотник:-)

Слишком муторно. И пусть не отвлекается - ему нужно сообщить ГГ о завершении охоты.

**Comment by Kor-Angar** [comment]
Это смотря с какой стороны смотреть на это. Раньше были случаи когда ГГ получал опыт за убийство монстров сторонним НПС, а были когда не получал.Скоро останется вариант когда он только получает 😀
