### ISSUE TITLE
Том. El Bastardo	

### ISSUE THREAD

**Issue by Kor-Angar** [dosinabox/g2nr_unofficial_update#179]
а Тома El Bastardo сразу вооружили давно? :-)

**Comment by Kor-Angar** [comment]
В оригинальной игре у Тома Эль Бастардо появлялся когда он перемещаться в таверну. И при попытки отобрать у него этот мечь агрилось много бандитов. Теперь же Тома можно прирезать в пещере пока он там один и получить этот меч.  

Этот меч есть только у Тома. Купить же его нельзя(или можно? Кажется он был в продаже у Беннета в 6 главе?) .

Можно выковать будучи учеником кузнец в Хориносе(суммарно это обойдётся в 30ЛП(2+4+6+8+10).

**Comment by dosinabox** [comment]
> В оригинальной игре у Тома Эль Бастардо появлялся когда он перемещаться в таверну.

На самом деле всегда, со старта:
```
instance PIR_1389_Addon_Tom(Npc_Default)
{
	name[0] = "Tom";
	guild = GIL_PIR;
	id = 1389;
	voice = 11;
	flags = 0;
	npcType = npctype_main;
	B_SetAttributesToChapter(self,3);
	fight_tactic = FAI_HUMAN_STRONG;
	EquipItem(self,ItMw_ElBastardo);
	...
```

**Comment by dosinabox** [comment]
> а Тома El Bastardo сразу вооружили давно? :-)

Был с оригинала Г2НВ 2.6.

**Comment by dosinabox** [comment]
> Этот меч есть только у Тома. Купить же его нельзя(или можно? Кажется он был в продаже у Беннета в 6 главе?) .

Да, только на Ирдорате у Беннета.

**Comment by Kor-Angar** [comment]
Стало ещё не понятнее.. А почем Тома два? 😀
![Screenshot_20200131_221315_com ghisler android TotalCommander](https://user-images.githubusercontent.com/49514764/73559469-eb232480-4476-11ea-907e-4bbfe3d7772c.jpg)

Bdt_1080
PIR_1389

**Comment by Kor-Angar** [comment]
Bdt_1080
PIR_1389

**Comment by dosinabox** [comment]
Том-пират - неиспользуемый и недоделанный.

**Comment by Kor-Angar** [comment]
Злую шутку играет с человеком память Был с оригинала Г2НВ 2.6.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
-- Отправлено из мобильного приложения Яндекс.Почты

**Comment by dosinabox** [comment]
Будем заменять на что-то другое?

**Comment by Kor-Angar** [comment]
Это оригинальный баланс. Его лучше не править. Слишком это дело не предсказуемо. Правки в одном месте из лучших побуждений могут выйти боком в другом 😀Единственное надо вернуть в продажу оружие, сейчас в первой и второй главе ассортимент судный. По этому  приходится бегать его искать или отбирать у НПС.  В то время как хотелось бы все таки иметь возможность его купить.3:51, 6 февраля 2020 г., dosinabox <notifications@github.com>:Будем заменять на что-то другое?

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
-- Отправлено из мобильного приложения Яндекс.Почты

**Comment by dosinabox** [comment]
> Единственное надо вернуть в продажу оружие, сейчас в первой и второй главе ассортимент судный.

Нужно отдельное исследование, как мы делали с луками и арбалетами.

> Это оригинальный баланс. Его лучше не править.

Баланс не пострадает, если заменить Эль-бастардо на обычный меч с такими же параметрами, но без бонуса (наверное). А бонус останется для ковки, в которой теперь появится больше смысла. Сейчас учить ковку Эль-бастардо вообще не имеет смысла.

**Comment by Kor-Angar** [comment]
> Баланс не пострадает, если заменить Эль-бастардо> на обычный меч с такими же параметрами, но без> бонуса (наверное). А бонус останется для ковки, > в которой теперь появится больше смысла. > Сейчас учить ковку Эль-бастардо вообще не имеет смысла.Другого меча 120/110 в игре нет. Или оставлять как есть или давать ему меч 110/110. В принципе можно дать Инквизитор 110/110 у него идёт доп урон по големам и каменным стражам, что будет весьма актуально и позволит убивать големов с двух ударов, а стражей с одного. В соседнем топике про баланс есть видео с клювом Ворона 😀 клюв Ворона я находил в Минентале. Но параметры у них одинаковые с Инквизитором. *****Это оригинальный баланс. Его лучше не править.
Баланс не пострадает, если заменить Эль-бастардо на обычный меч с такими же параметрами, но без бонуса (наверное). А бонус останется для ковки, в которой теперь появится больше смысла. Сейчас учить ковку Эль-бастардо вообще не имеет смысла.

**Comment by Kor-Angar** [comment]
> Баланс не пострадает, если заменить Эль-бастардо на обычный меч с такими же параметрами, но без бонуса (наверное). А бонус останется для ковки, в которой теперь появится больше смысла. Сейчас учить ковку Эль-бастардо вообще не имеет смысла.

Другого меча 120/110 в игре нет. Или оставлять как есть или давать ему меч 110/110. В принципе можно дать Инквизитор 110/110 у него идёт доп урон по големам и каменным стражам, что будет весьма актуально и позволит убивать големов с двух ударов, а стражей с одного. Видео с клювом Ворона 😀 
https://youtu.be/ualhwYdAB2I 
клюв Ворона я находил в Минентале. Но параметры у них одинаковые с Инквизитором. 

![Screenshot_20200206_194342](https://user-images.githubusercontent.com/49514764/73947370-2317e500-4919-11ea-8dc7-64c0d5f2a347.jpg)

**Comment by Kor-Angar** [comment]
> Нужно отдельное исследование, как мы делали с луками и арбалетами.

так ещё в июне для 2р сделал 
https://docs.google.com/spreadsheets/d/1svDbXAiYe7PLCQ7G0Arjh_njRiDabsRC-9GuLt7APsQ/edit#gid=1292287472

может просто опционально сделать включения продажи как в Готики 2 НВ? я заметил что простые решения даются проще чем сложные :-)

**Comment by dosinabox** [comment]
Эль-бастардо у Тома заменен на новый меч Эль-чапо. Единственное отличие от Эль-бастардо - 5% бонуса вместо 8%. Цена Эль-бастардо повышена с 1300 до 1400.

**Comment by Kor-Angar** [comment]
Тогда можно ему сделать и требование к силе выше ;-) 

Сделать 120/120/5

А рунный меч 110/110 (на картинка выше) в мире игры есть?

**Comment by Kor-Angar** [comment]
Runenschwert

**Comment by dosinabox** [comment]
> А рунный меч 110/110 (на картинка выше) в мире игры есть?

Продает Мартин с первой главы.

**Comment by dosinabox** [comment]
> Сделать 120/120/5

ок

**Comment by Kor-Angar** [comment]
А кроме этого?

**Comment by dosinabox** [comment]
В скриптах больше ни у кого нет. В мирах тоже нет.

**Comment by Kor-Angar** [comment]
Отличный повод, что бы подумать как его задействовать 😀 можно кому нибудь дать 😎21:31, 15 февраля 2020 г., dosinabox <notifications@github.com>:В скриптах больше ни у кого нет. В мирах тоже нет.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
-- Отправлено из мобильного приложения Яндекс.Почты

**Comment by Kor-Angar** [comment]
> Эль-бастардо у Тома заменен на новый меч Эль-чапо.

> Тогда можно ему сделать и требование к силе выше ;-)
> Сделать 120/120/5

> ок

как то не очень получилось. Плохое предложение у меня вышло :-) лучше всё таки что то с требованием 110 силы.
