### ISSUE TITLE
оригинальные скрипты Г2НВ

### ISSUE THREAD

**Issue by Kor-Angar** [dosinabox/g2nr_unofficial_update#182]
Посмотреть оригинальный код Г2НВ можно по этой ссылке:

Пираньи
https://github.com/Kor-Angar/G2_NotR_MDK

Акелла
https://github.com/dosinabox/g2nr_unofficial_update/tree/98e37682c9eaece0a90dfd2aec76977c1a7656a9

**Comment by Kor-Angar** [comment]
привет. а можно тебя попросить собрать оригинальный код игры в виде отдельного мода? :-) что бы было удобнее проверять... :-/

**Comment by dosinabox** [comment]
Хм. Покажи что у тебя в папках Data и Data/ModVDF.

**Comment by Kor-Angar** [comment]
![image](https://user-images.githubusercontent.com/49514764/74136480-27851c00-4bff-11ea-9b3f-d01e32f9c979.png)
![image](https://user-images.githubusercontent.com/49514764/74136500-31a71a80-4bff-11ea-8cc3-8b9cbb331f47.png)

**Comment by dosinabox** [comment]
Запуск через стартер или с gothic2.exe?

**Comment by Kor-Angar** [comment]
я взял стимовскую версию. на неё поставил твой стимфиксбикс что то там. и когда я запускаю
![image](https://user-images.githubusercontent.com/49514764/74137071-391af380-4c00-11ea-80c0-ddc0cc4f1bc3.png)
у меня запускается сразу с неофициальным обновлением
![image](https://user-images.githubusercontent.com/49514764/74137128-564fc200-4c00-11ea-8d3c-3d63421c13d4.png)

**Comment by dosinabox** [comment]
1) удали файл Data/g2a_nr_scriptpatch.vdf
2) проверь, чтобы в папке _work/Data/Scripts/_compiled был gothic.dat оригинала (см. дату создания / изменения)
3) запускай GothicStarter.exe (GothicStarter_mod.exe только для модостроителей)
4) 30.01.2020 вышла новая тестовая сборка обновления: https://github.com/dosinabox/g2nr_unofficial_update/releases/tag/v24.2

**Comment by Kor-Angar** [comment]
> 30.01.2020 вышла новая тестовая сборка обновления: https://github.com/dosinabox/g2nr_unofficial_update/releases/tag/v24.2

эту я ставил. кажется

**Comment by dosinabox** [comment]
> эту я ставил. кажется

v23_hotfix у тебя старый - от 06.01. Это первая тестовая сборка. Второй не вижу.

**Comment by Kor-Angar** [comment]
Не совсем по сабжу.. А где можно скачать декомпилированные скрипты Готики 1? А так же скрипты  твоего мод фикса к Готике 1?

**Comment by dosinabox** [comment]
> А где можно скачать декомпилированные скрипты Готики 1?

Не знаю. У меня нету.

> А так же скрипты твоего мод фикса к Готике 1?

Постараюсь на днях загрузить сюда. Давно пора.

**Comment by Kor-Angar** [comment]
спс

**Comment by Kor-Angar** [comment]
видос про решальщика видела? :-) 
[Граво решаем вопрос с Гомезом за 100 руды](https://www.youtube.com/watch?v=W8v5o7VXNP4)

**Comment by dosinabox** [comment]
Ага, а что?

**Comment by Kor-Angar** [comment]
> 
> По-настоящему чистые исходные скрипты Г1 и Г2 существуют только в GMDK полных версий и только немецкие. Там даже комментарии разработчиков есть и всякие отключенные строки. Всё остальное это переведенные декомпиляции с исправлением ошибок, мешающих повторной компиляции (возвращаемые значения, синтаксис, переопределения переменных, порядок чтения, битые имена файлов).
> https://www.worldofgothic.de/dl/download_94.htm

**Comment by Kor-Angar** [comment]
у Пираней  оформление кода понятнее :-) жаль что их методу всё подписывать не взяли на вооружение :-/

в архивах папки $OUTDIR со скриптами из распакованного экзешника 
[g2mdk-2.6.zip](https://github.com/dosinabox/g2nr_unofficial_update/files/4208674/g2mdk-2.6.zip)
[g2mdk-2.6_small.zip](https://github.com/dosinabox/g2nr_unofficial_update/files/4208675/g2mdk-2.6_small.zip)

***

**Comment by Kor-Angar** [comment]
ошибка(описка) в коде :-)))


```
if (slf.HitChance[NPC_TALENT_1H] >=0)		{	Npc_SetTalentSkill (slf, NPC_TALENT_2H, 0);		};
if (slf.HitChance[NPC_TALENT_2H] >=30)		{	Npc_SetTalentSkill (slf, NPC_TALENT_2H, 1);		};
if (slf.HitChance[NPC_TALENT_2H] >=60)		{	Npc_SetTalentSkill (slf, NPC_TALENT_2H, 2);		};
```
проверь у себя плиз

**Comment by dosinabox** [comment]
> проверь у себя плиз

Это где?

**Comment by Kor-Angar** [comment]
**B_AddFightSkill.d**

во втором блоке про 2h, проверка идет по 1h

**Comment by Kor-Angar** [comment]
**B_AddFightSkill.d**
во втором блоке про 2h, проверка идет по 1h
![image](https://user-images.githubusercontent.com/49514764/74591557-f4d98a00-5029-11ea-9313-583f0af01bf9.png)

**Comment by dosinabox** [comment]
Вроде правильно, но расписано по другому:
```
if(talent == NPC_TALENT_2H)
{
	slf.HitChance[NPC_TALENT_2H] += percent;
	if(slf.HitChance[NPC_TALENT_2H] > 100)
	{
		slf.HitChance[NPC_TALENT_2H] = 100;
	};
	if(slf.HitChance[NPC_TALENT_2H] < 0)
	{
		slf.HitChance[NPC_TALENT_2H] = 0;
	};
	if(slf.HitChance[NPC_TALENT_2H] >= 60)
	{
		Npc_SetTalentSkill(slf,NPC_TALENT_2H,2);
		Mdl_ApplyOverlayMds(slf,"humans_2hST2.mds");
	}
	else if(slf.HitChance[NPC_TALENT_2H] >= 30)
	{
		Npc_SetTalentSkill(slf,NPC_TALENT_2H,1);
		Mdl_ApplyOverlayMds(slf,"humans_2hST1.mds");
	}
	else
	{
		Npc_SetTalentSkill(slf,NPC_TALENT_2H,0);
		Mdl_RemoveOverlayMds(slf,"humans_2hST1.MDS");
		Mdl_RemoveOverlayMds(slf,"humans_2hST2.MDS");
	};
};
```

**Comment by Kor-Angar** [comment]
Вот кстати, а. Почему продвинутый НПС в начале игры атакует героя с  NPC_TALENT_1H,0 как крестьяне?

**Comment by dosinabox** [comment]
> продвинутый НПС в начале игры атакует героя с  NPC_TALENT_1H,0 как крестьяне

Где? В оригинале или моде?

**Comment by Kor-Angar** [comment]
В  обновление.  В оригинале такого не помню. Давно в оригинал не играл 🙃

**Comment by Kor-Angar** [comment]
Выходит Пираньи выкатили свои скрипты после того как вышел аддон. А ребята начали ковырять скрипты ещё когда была Готики 2 классик. Поэтому и декомпилятор писали сами. 

А ещё я понял что у Акеллы  в аддоне есть куски  кода из Готика 2 версии 1.28. В частности это касается заклинания "сна", которые пираньи переделали в 1.29 😀 наверное  связано с тем что Акелла локализовала не немецкую версию, а английскую 🙃

Где то в скриптах Готики 2 классик, есть наверное и ответ на мой вопрос, почему Ян перестал учить ковке в Минентале Пала и Мага 😀 а у Беннета на Ирдорате на ковке появилось(?) условие из Хориносе.

**Comment by Kor-Angar** [comment]
> в архивах папки $OUTDIR со скриптами из распакованного экзешника
> g2mdk-2.6.zip
> g2mdk-2.6_small.zip


Может оригинальные скрипты пираней мне разложить по папочкам, а ты залитьешь на ГитХаб?

**Comment by Kor-Angar** [comment]
исходники моего мод-фикса для Г1 от Руссобит. Теперь они доступны здесь: 

https://github.com/dosinabox/g1_russobit-m_fix

**Comment by Kor-Angar** [comment]
Исходники ElderGamer https://yadi.sk/d/anxKyTQcJZKi5A 

[Мод-фикс исходники 2019 12.zip](https://github.com/dosinabox/g2nr_unofficial_update/files/4273079/-.2019.12.zip)

**Comment by Kor-Angar** [comment]
А с кодировкой что то можно сделать на GitHub? 😀

**Comment by dosinabox** [comment]
> А с кодировкой что то можно сделать на GitHub? 😀

Попробую изменить кодировку какого-нибудь отдельного файла и посмотрю как это повлияет на историю изменений и возможность сравнения разных версий проекта.

**Comment by Kor-Angar** [comment]
там какой то командой можно сделать что бы ГитХаб отображал файлы в другой кодировке. но я в этом два по пять как ты понимаешь :-)

**Comment by Kor-Angar** [comment]
Скрипты из MDK
https://github.com/Kor-Angar/G2_NotR_MDK

**Comment by Kor-Angar** [comment]
а есть где нибудь оригинальные скрипты Готики 2 без НВ ? мне кажется у ряда НПС просто забыли поменять инстанции и они ходят с параметрами из Готики 2 :-)

**Comment by dosinabox** [comment]
Чистые декомпилированные скрипты классики от Акеллы:
https://github.com/dosinabox/g2_classic/tree/b74a75bae468a3c6c5c72382fd6eb3182a98ce46

**Comment by Kor-Angar** [comment]
А пираней нет? 13:42, 28 сентября 2020 г., dosinabox <notifications@github.com>:
Чистые декомпилированные скрипты классики от Акеллы:
https://github.com/dosinabox/g2_classic/tree/b74a75bae468a3c6c5c72382fd6eb3182a98ce46

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
-- Отправлено из мобильного приложения Яндекс.Почты

**Comment by dosinabox** [comment]
у меня нет
