### ISSUE TITLE
Меч Альрика / Альрик

### ISSUE THREAD

**Issue by Kor-Angar** [dosinabox/g2nr_unofficial_update#184]
Меч Альрика стал продовать я с начало игры. Если его купить то появятся возможность его сдать до драки с Альриком. При этом там же будет и вариант диалога про то кому Альрик продал этот меч.

Это так задумано? Или ошибка?

**Comment by dosinabox** [comment]
Ошибка. Исправлено.

**Comment by Kor-Angar** [comment]
Теперь меч можно будет купить после того как Альрик даёт квест? Или до? 3:30, 6 февраля 2020 г., dosinabox <notifications@github.com>:Ошибка. Исправлено.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
-- Отправлено из мобильного приложения Яндекс.Почты

**Comment by dosinabox** [comment]
С этим без изменений. Но теперь нельзя спросить у Альрика, кому он продал свой меч, если этот меч уже есть в инвентаре ГГ (опции вопроса и передачи меча не доступны одновременно).

**Comment by Kor-Angar** [comment]
а можешь полностью расписать правки про этот меч? на самом деле весьма хороший для самого начало игры, очень дешёвый и к тому же еще  и квестовый одновременно. в оригинале что бы его получить нужно было сначала побить Альрика, теперь его можно купить сразу и им же побить Альрика. (прям как Торус в Готике 1 говорил они воруют у нас товар и продают его нашим же людям). таким образом если вы хотите продовать его сразу, то ему надо сделать адекватную цену, при это сохранив возможность его получить в рамках квеста Джоры бесплатно(если герой вернул золото) или купить за 50 золотых (при каком условие?).  и ещё, хотел давно написать. меч этот по ЛОРу простенький и неброский, т.е. визуально самый такой обычный. об этом говорит сам Альрик. а вы ему поставили уникальную иконку(картинку) и он сразу выделяется и бросается в глаза.     06.02.2020, 10:02, "dosinabox" <notifications@github.com>:С этим без изменений. Но теперь нельзя спросить у Альрика, кому он продал свой меч, если этот меч уже есть в инвентаре ГГ (опции вопроса и передачи меча не доступны одновременно).

**Comment by dosinabox** [comment]
> и ещё, хотел давно написать. меч этот по ЛОРу простенький и неброский, т.е. визуально самый такой обычный. об этом говорит сам Альрик.

Он называет его просто старым:

```
AI_Output(self,other,"DIA_Alrik_WannaFight_09_03");	//Мне несколько дней назад пришлось продать свой меч.
AI_Output(self,other,"DIA_Alrik_WannaFight_09_04");	//С ним я непобедим! Если ты вернешь его мне, я готов опять сражаться с тобой!
```
```
AI_Output(self,other,"DIA_Alrik_WerSchwert_09_04");	//Это старый меч. Он вряд ли много за него запросит. Просто думай об этих деньгах, как о дополнительной ставке. (ухмыляется)
```

> а можешь полностью расписать правки про этот меч? на самом деле весьма хороший для самого начало игры, очень дешёвый и к тому же еще  и квестовый одновременно. в оригинале что бы его получить нужно было сначала побить Альрика, теперь его можно купить сразу и им же побить Альрика.

Джора вставляется в мир с уже экипированным мечом Альрика и в оригинале без аддона, и в оригинале с аддоном:
```
instance VLK_408_Jora(Npc_Default)
{
	name[0] = "Джора";
	guild = GIL_VLK;
	id = 408;
	voice = 8;
	flags = 0;
	npcType = npctype_main;
	B_SetAttributesToChapter(self,2);
	fight_tactic = FAI_HUMAN_COWARD;
	EquipItem(self,ItMw_AlriksSword_Mis);
```

**Comment by dosinabox** [comment]
> а вы ему поставили уникальную иконку(картинку) и он сразу выделяется и бросается в глаза.

Он и так сразу бросается в глаза, потому что прямо называется "Меч Альрика" - сразу понятно, что он квестовый.

**Comment by Kor-Angar** [comment]
Но купить то его можно было только через диалог.  Т. е. в оригинале его можно было купить(получить) у Джоры после того как Альрик даёт квест в рамках диалога  или попытаться отобрать?

**Comment by Kor-Angar** [comment]
> Он и так сразу бросается в глаза, потому что прямо 
> называется "Меч Альрика" - сразу понятно, 
> что он квестовый.


Нет. Не так. Название высвечивается если его выбрать. Т.е. надо было зайти в раздел хлама, который уидет там где ржавые мечи и посмотреть что же это ха хлам. Именно поэтому игроки часто его случайно продовали потому что он шёл в самом низу среди хлама, вместе с ржавыми мечами.

**Comment by dosinabox** [comment]
> Но купить то его можно было только через диалог.

Только потому, что в оригинале экипированное оружие не снимается для продажи. Но купить или отобрать не проблема. Можно продать ему что-то более мощное и что он наденет вместо меча Альрика. Можно убить каким-нибудь свитком. Можно выманить за город и избить самому. Можно спровоцировать на атаку угрозой оружием, чтобы его побили стражники. Можно натравить Лареса. Можно отвести к стае волков или в пещеру с орком)
В любом случае, в оригинале нет прямого запрета на получение меча Альрика на нулевом уровне. А если повышать цену на меч, то её не получится снизить до 50 после квеста Джоры. Будет так, что покупка через диалог и через инвентарь окажется с разной ценой при одинаковой игровой ситуации и отношении Джоры к ГГ.

**Comment by Kor-Angar** [comment]
Запустил Готика 2 оригинал. Продал более мощное оружие. Он его не стал менять. Так с ним и ходит. Может быть и можно как то убить на нулевом уровне Джору на рыночной плошади что бы снять с его трупа меч Альрика, но проще все таки выкупить его или получить бесплатно в рамках квеста Альрика. А вот сейчас получается что его можно просто купить за 50 золотых в самом начале игры🖖 более худшие варианты будут стоить по 300, а этот 50.Может просто его добавлять  Джоре после соответствующего диалога про меч Альрика? 16:57, 6 февраля 2020 г., dosinabox <notifications@github.com>:
Но купить то его можно было только через диалог.

Только потому, что в оригинале экипированное оружие не снимается для продажи. Но купить или отобрать не проблема. Можно продать ему что-то более мощное и что он наденет вместо меча Альрика. Можно убить каким-нибудь свитком. Можно выманить за город и избить самому. Можно спровоцировать на атаку угрозой оружием, чтобы его побили стражники. Можно натравить Лареса. Можно отвести к стае волков или в пещеру с орком)
В любом случае, в оригинале нет прямого запрета на получение меча Альрика на нулевом уровне. А если повышать цену на меч, то её не получится снизить до 50 после квеста Джоры. Будет так, что покупка через диалог и через инвентарь окажется с разной ценой при одинаковой игровой ситуации и отношении Джоры к ГГ.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
-- Отправлено из мобильного приложения Яндекс.Почты

**Comment by Kor-Angar** [comment]
Можно получить люлей от Джоры, заплатить штраф Андре, после чего Джора переоденется и меч Альрика появится в продаже.

**Comment by Kor-Angar** [comment]
У Джоры есть вариант реплики что у него нет этого меча и он его уже продал 😀

**Comment by dosinabox** [comment]
> Продал более мощное оружие. Он его не стал менять. Так с ним и ходит.

> Можно получить люлей от Джоры, заплатить штраф Андре, после чего Джора переоденется и меч Альрика появится в продаже.

Достаточно просто уйти подальше, чтобы он пропал из области видимости. При повторном появлении в области видимости у него обновится оружие на самое лучшее, которое он может взять.

**Comment by dosinabox** [comment]
> У Джоры есть вариант реплики что у него нет этого меча и он его уже продал 😀

Ну да. На случай, если покупка произошла до наводки от Альрика.

**Comment by Kor-Angar** [comment]
В любом случае сложилась такая ситуация что раньше была такая возможность и ей мог воспользоваться тот кто в теме. Сейчас же у него просто есть в продаже этот меч. Меч даёт бонус 10 к 1р, а стоит всего 50 золотых. В рамках квеста это понятная цена, потому что квест ещё надо взять, а что бы его взять надо попить Альрика 😀Я тут просто на ноуте играл силачём и как раз ходил на волков/гоблинов с этим мечем 😎 очень получается здорово. И Альрика им же избил 😀Альрика всегда можно было бесконечное кол-во раз вызывать на дуэль и получать +50 золотых? Или стояло ограничение на раз в день?

**Comment by Kor-Angar** [comment]
> Если его купить то появятся возможность его сдать до драки с Альриком. 

> Ошибка. Исправлено.

***

Диалог про меч доступен до первой драки.
![image](https://user-images.githubusercontent.com/49514764/76136905-d3c3f200-6047-11ea-8f00-a23dc6e8d8ff.png)

```
instance DIA_Alrik_HaveSword(C_Info)
{
	npc = VLK_438_Alrik;
	nr = 1;
	condition = DIA_Alrik_HaveSword_Condition;
	information = DIA_Alrik_HaveSword_Info;
	permanent = TRUE;
	description = "Я принес твой меч!";
};


func int DIA_Alrik_HaveSword_Condition()
{
	if(Npc_HasItems(other,ItMw_AlriksSword_Mis))
	{
		return TRUE;
	};
};
```

***

Альрик бьётся много раз в день. Разве раньше он бился не раз в день?

**Comment by dosinabox** [comment]
Исправлена была возможность задать вопрос о торговце, если меч уже есть у ГГ.
Почему возможность отдать меч до первой драки это неправильно?

**Comment by Kor-Angar** [comment]
А откуда герой знает что это меч Альрика? А откуда герой знает что Альрику нужен меч? А когда и почему Альрик понимает что ему нужен меч?

**Comment by dosinabox** [comment]
> Разве раньше он бился не раз в день?

Вроде нет. В коде оригинала дни не назначаются и не проверяются. Можно подряд:
![image](https://user-images.githubusercontent.com/39790055/76139717-1bf10d80-6064-11ea-9dfd-45192e744177.png)

Три драки в первой и второй главе, три в третьей и четвертой, три в пятой. Итого девять. Наверное, после этих реплик диалог можно закрывать, а Альрика перемещать в другое место:
```
AI_Output(self,other,"DIA_Alrik_Add_09_04");	//Кроме того, я сегодня заработал уже достаточно денег.
AI_Output(self,other,"DIA_Alrik_Add_09_05");	//С меня хватит. Я собираюсь подыскать себе другое местечко в городе...
AI_Output(self,other,"DIA_Alrik_Add_09_06");	//Кто знает, может, я открою оружейную лавку...
```

**Comment by dosinabox** [comment]
А вот для этой реплики нужно учитывать фактические победы ГГ:
```
AI_Output(self,other,"DIA_Alrik_WannaFight_09_05");	//Мне кажется, ты побеждаешь слишком часто.
```
Потому что можно все 9 драк проиграть)

**Comment by Kor-Angar** [comment]
> В коде оригинала дни не назначаются и не проверяются

А в Готике 2 классик? Там тоже несколько боев подряд в один день? 

У него же после драки жизни не восстанавливаются и он будет падать с одного удара?

**Comment by dosinabox** [comment]
Если здоровье Альрика меньше максимального, то перед боем он выпивает чистое здоровье.

**Comment by Kor-Angar** [comment]
Это сейчас так?

**Comment by dosinabox** [comment]
Да, а в оригинале он пьет зелье лечения вместо чистого здоровья.

**Comment by Kor-Angar** [comment]
Понятно, спасибо.

**Comment by dosinabox** [comment]
Теперь вернуть Альрику его меч можно будет только после одной из этих реплик:
```
AI_Output(self,other,"DIA_Alrik_WannaFight_09_02");	//Нет, нет. Прежде, чем выйти против тебя еще раз, мне нужно раздобыть оружие получше!
AI_Output(self,other,"DIA_Alrik_WannaFight_09_03");	//Мне несколько дней назад пришлось продать свой меч.
AI_Output(self,other,"DIA_Alrik_WannaFight_09_04");	//С ним я непобедим! Если ты вернешь его мне, я готов опять сражаться с тобой!
```
```
AI_Output(self,other,"DIA_Alrik_DuWohnst_09_04");	//И вот я пытаюсь опять разбогатеть. Мне даже пришлось продать свой меч.
```

**Comment by Kor-Angar** [comment]
спасибо.

Но Альрик продолжает тупить. 
https://youtu.be/LLlfFK4l_eU?t=3481 59  минута
![image](https://user-images.githubusercontent.com/49514764/76163407-d9f4c400-6156-11ea-88f6-f539664cad20.png)

**Comment by dosinabox** [comment]
Анимация убирания оружия в ножны не успела завершиться и прервалась. Ничего не поделать.

**Comment by dosinabox** [comment]
Вот так достаточно непримечательно?
![20210313173107_2](https://user-images.githubusercontent.com/39790055/111033706-9dbc0980-8423-11eb-860d-8abce62df58d.jpg)

И, может, убрать информацию о бонусе? Неспроста её нет ни в классике, ни в аддоне.

**Comment by Kor-Angar** [comment]
В аддоне её нет потому что её нет в классике 😀 в аддоне инфу можно добавить, а в классике убрать. Этот намного  лучше, но было бы прекрасно если бы он имел оригинальную модельку 😀17:44, 13 марта 2021 г., dosinabox ***@***.***>:
Вот так достаточно непримечательно?

И, может, убрать информацию о бонусе? Неспроста её нет ни в классике, ни в аддоне.

—You are receiving this because you modified the open/close state.Reply to this email directly, view it on GitHub, or unsubscribe.
-- Отправлено из мобильного приложения Яндекс.Почты

**Comment by dosinabox** [comment]
> в аддоне инфу можно добавить, а в классике убрать

так и есть сейчас
