### ISSUE TITLE
Доспехи. СистемПак

### ISSUE THREAD

**Issue by Kor-Angar** [dosinabox/g2nr_unofficial_update#185]
Это я как понял из-за свежого СистемПака? 
![IMG_20200204_002353](https://user-images.githubusercontent.com/49514764/73684660-722a0400-46e6-11ea-8c52-d05f57e88553.jpg)

А броню скриптом нельзя удалить? 😀

**Comment by dosinabox** [comment]
> Это я как понял из-за свежого СистемПака?

Да. Мое исправление:
https://worldofplayers.ru/threads/36519/post-1057778

> А броню скриптом нельзя удалить?

Нет. Броню должен удалять движок.

**Comment by Kor-Angar** [comment]
Тогда может снимать бессмертие в Каваларон с доп условием: после вступления в Кольцо Воды.

**Comment by Kor-Angar** [comment]
А Каваларон не может броню отдать Ларесу?

**Comment by Kor-Angar** [comment]
У меня кстати Гаан стоял возле водопода в броне КВ

**Comment by dosinabox** [comment]
> А Каваларон не может броню отдать Ларесу?

Что ты имеешь в виду?

> У меня кстати Гаан стоял возле водопода в броне КВ

Нужны подробности о церемонии у Орлана.

**Comment by Kor-Angar** [comment]
ну сейчас же у  Кавалорна можно  отобрать броню. вот я и уточняю нельзя ли эту ситуацию как то исправить, например передавать во время диалоги лишнюю броню от Кавалорна Ларесу.

**Comment by dosinabox** [comment]
Это проблема СП и я не буду её обходить, городя костыли в скриптах. Многие используют СП прошлых версий. Многие используют стим-фикс с моим исправлением. Некоторые используют мое исправление отдельно. Некоторые не используют СП вообще. Некоторые используют Юнион, где такой проблемы нет.

**Comment by Kor-Angar** [comment]
честно говоря я окончательно запутался. у тебя в топике написано что надо ставить последнюю версию СистемПак
![image](https://user-images.githubusercontent.com/49514764/75023366-c126b600-54a8-11ea-9b2b-c5698ac7eda1.png)
если при этом нужно еще скачать вот этот патч, 
https://worldofplayers.ru/threads/36519/page-97#post-1057778
то надо добавить эту информацию в шапку, а так  очень сложно понять:-) а уж тем более найти эту информацию:-)

**Comment by Kor-Angar** [comment]
Гаан в доспехах КВ
![Uploading image.png…]()

**Comment by Kor-Angar** [comment]
Гаан в доспехах КВ

![image](https://user-images.githubusercontent.com/49514764/75782159-89085880-5d6f-11ea-9eb9-5622194da445.png)

**Comment by dosinabox** [comment]
Нужны подробности и предыстория

**Comment by Kor-Angar** [comment]
вступление в КВ
https://youtu.be/jjgZykCFGpU?t=9874

**Comment by Kor-Angar** [comment]
у меня опять эти доспехи снимать можно :-)
