### ISSUE TITLE
Игнац. Эксперемент

### ISSUE THREAD

**Issue by Kor-Angar** [dosinabox/g2nr_unofficial_update#186]
Квест не засчитывпется, если на Кантара успешно применить заклинание "забыть"

**Comment by dosinabox** [comment]
После чего он обиделся на ГГ?

**Comment by Kor-Angar** [comment]
Избиение

**Comment by Kor-Angar** [comment]
Атаковал его

**Comment by Kor-Angar** [comment]
Само Заклинание сработало

**Comment by dosinabox** [comment]
> Атаковал его

Где?

**Comment by Kor-Angar** [comment]
В городе.  То ли на площади, то ли в гостинице. Уже не помню.

**Comment by dosinabox** [comment]
Значит, могли быть свидетели.
