### ISSUE TITLE
Факелы

### ISSUE THREAD

**Issue by Kor-Angar** [dosinabox/g2nr_unofficial_update#188]
Сейчас в игре факел фактически многорозавобесконечный. 

Зажженый факел можно сложить обратно в инвентарь, а потом опять вытащить и снова использовать. 

Можно ли сделать что бы если герой факел прячет в инвентарь то факел становился бы сгоревшим?

Тогда факелы станут конечными 😀 их можно будет докупать хотя бы теоретически 😀

**Comment by dosinabox** [comment]
без скриптовых расширителей с этим ничего не сделать

**Comment by Kor-Angar** [comment]
А сделать что бы при нажатие на факелы в инвентаре, если у героя в руках факел, он его просто выкидывал и зажигала(доставал) новый?

**Comment by dosinabox** [comment]
тоже нет

**Comment by Kor-Angar** [comment]
Ну и ладно. Все равно это не на что не влияет по большому счету 😀21:10, 10 февраля 2020 г., dosinabox <notifications@github.com>:тоже нет

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
-- Отправлено из мобильного приложения Яндекс.Почты

**Comment by dosinabox** [comment]
Плагин для Union, добавляющий возможность доставать факелы по нажатию на клавишу T:
[UNION_TORCHHOTKEY.zip](https://github.com/dosinabox/g2nr_unofficial_update/files/4753327/UNION_TORCHHOTKEY.zip)
