### ISSUE TITLE
Руна телепортации в Круг Солнца / продажа Горакс

### ISSUE THREAD

**Issue by Kor-Angar** [dosinabox/g2nr_unofficial_update#190]
Мы уже по моему обсуждали, что руну телепортации в круг Солнца можно добавлять Гораксу в продажу после того как герой нашёл Глаз Инноса. что бы герой имел возможность в последующем телепортироваться сразу туда.

**Comment by dosinabox** [comment]
Тогда непонятно, почему Пирокар идет восстанавливать Глаз пешком. А делать его телепортацию слишком сложно.

**Comment by Kor-Angar** [comment]
не понятно почему Ксардас, Пирокар, Ватрас не телепортируются в свою башню/монастырь/город.

Ксардас сам дал руну телепортации через Лестера, Пирокар дал руну телепортацию герою. но при этом они всё равно ходят пешком;-)

т.е. я к тому что если вводить эту руну, то пусть от неё хотя бы будет толк. а то руну в игру добавили, а толка с неё нет - герою приходится все равно бегать в круг солнца :-)

**Comment by Kor-Angar** [comment]
однако :-))
![image](https://user-images.githubusercontent.com/49514764/74151661-b56fff80-4c1d-11ea-95ff-2e7e0ee256a4.png)

**Comment by Kor-Angar** [comment]
в этом мод-фиксе https://worldofplayers.ru/threads/36812/page-136#post-1074433 ?

**Comment by dosinabox** [comment]
> в этом мод-фиксе https://worldofplayers.ru/threads/36812/page-136#post-1074433 ?

Вопрос непонятен. Это же для Г1. А у Г2НВ ничего такого нет.

**Comment by Kor-Angar** [comment]
я понял. хотел посмотреть как Милтен телепортируется 

> было реализовано в мод-фиксах для Г1 с Милтеном у горы руды Нового лагеря

мод-фикс от ElderGamer?

**Comment by dosinabox** [comment]
> я понял. хотел посмотреть как Милтен телепортируется

А, понятно. Я вот здесь делала: https://worldofplayers.ru/threads/39062/

> мод-фикс от ElderGamer?

У него, вроде, тоже такое есть. Но я не играла.

**Comment by Kor-Angar** [comment]
так стрёмно? : )

https://www.youtube.com/watch?v=i8q_1KpOuhg

```
	Npc_ExchangeRoutine(self,"RitualInnosEyeRepair");
	AI_Output(self,other,"DIA_Xardas_RITUALREQUEST_14_05");	//Не стоит заставлять Ватраса ждать. Я отправляюсь немедленно. А ты должен выполнить свою задачу, а затем присоединиться ко мне опять.
//	AI_GotoWP(self,"NW_XARDAS_START");
//	AI_Output(self,other,"DIA_Xardas_Hello_14_15");	//(задумчиво) У нас очень мало времени.
	AI_PlayAni  (self,"T_MAGRUN_2_HEASHOOT");	
	Info_AddChoice(DIA_Xardas_EXIT,"...",DIA_Xardas_Teleport);
};

func void DIA_Xardas_Teleport()
{
//	AI_Output(other,self,"DIA_Xardas_DMTSINDDA_DMT_15_00");	//Меня атаковали маги в черных мантиях.
//	AI_Output(self,other,"DIA_Xardas_DMTSINDDA_DMT_14_01");	//У врага много обличий. Ищущие - одно из них. Они те, кто подготавливает плацдарм для врага.
	Wld_PlayEffect("SPELLFX_TELEPORT",  self, self, 0, 0, 0, FALSE );
	AI_StopProcessInfos(self);
	AI_Teleport(self,"NW_TROLLAREA_RITUAL_01");	
};
```

**Comment by dosinabox** [comment]
Руна появится в продаже у Горакса после сообщения Пирокару о поломке Глаза Инноса.

> так стрёмно? : )

Ну, неплохо)

**Comment by Kor-Angar** [comment]
Можно попробовать доработать. Там есть ещё синий круг вокруг колдующего, но я что то не смог найти код на форуме. 

так стрёмно? : )

Ну, неплохо)

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
-- Отправлено из мобильного приложения Яндекс.Почты

**Comment by Kor-Angar** [comment]
> Сдерживать_Магию_В_Теле S_FEASHOOT
> Сдерживать_Магию_Одна_Рука T_WNDCAST
> Сдерживать_Магию_Две_Руки S_FIBCAST
> Телепортация T_MAGRUN_2_HEASHOOT

**Comment by Kor-Angar** [comment]
> Там есть ещё синий круг вокруг колдующего, но я что то не смог найти код на форуме. 

Wld_PlayEffect("spellFX_Teleport_RING",  self  , self    , 0, 0, 0, TRUE);

**Comment by Kor-Angar** [comment]
и так пробовал и эдак :-) 
https://www.youtube.com/watch?v=5LP1B26tz0k&feature=youtu.be


```
func int DIA_Xardas_Teleport_Condition()
{
//	if(Xardas_GoesToRitualInnosEye == TRUE)
	if(Xardas_GoesToRitualInnosEye == FALSE) // для теста
	{
		return TRUE;
	};
};

func void DIA_Xardas_Teleport_Info()
{
//	AI_GotoWP(self,"NW_XARDAS_START");
	Npc_ExchangeRoutine(self,"RitualInnosEyeRepair");
	AI_PlayAni  (self,"T_MAGRUN_2_HEASHOOT");
	Wld_PlayEffect("spellFX_Teleport_RING",  self  , self    , 0, 0, 0, TRUE);
	AI_Output(self,other,"DIA_Xardas_Hello_14_15");	//(задумчиво) У нас очень мало времени.

//	Info_AddChoice(DIA_Xardas_Teleport,"Подожди минутку!",DIA_Xardas_TeleportGO);
//	Info_AddChoice(DIA_Xardas_Teleport,"...",DIA_Xardas_TeleportGO);
	Info_AddChoice(DIA_Xardas_Teleport,"Я немедленно отправляюсь в путь!",DIA_Xardas_TeleportGO);

};

func void DIA_Xardas_TeleportGO()
{
	B_Say_Overlay(other,other,"DIA_Xardas_FirstEXIT_15_00");  //Я немедленно отправляюсь в путь!
//	B_Say_Overlay(other,other,"$SC_HeyWaitASecond");          //Подожди минутку!
	AI_StopProcessInfos(self);
	Wld_PlayEffect("SPELLFX_TELEPORT",  self, self, 0, 0, 0, FALSE );	
	AI_Teleport(self,"NW_TROLLAREA_RITUAL_01");	
};
```

**Comment by Kor-Angar** [comment]
как вариант с вариантами, что бы игрок сам принял решение :-))

```
func int DIA_Xardas_Teleport_Condition()
{
//	if(Xardas_GoesToRitualInnosEye == TRUE)
	if(Xardas_GoesToRitualInnosEye == FALSE) // для теста
	{
		return TRUE;
	};
};

func void DIA_Xardas_Teleport_Info()
{
//	AI_GotoWP(self,"NW_XARDAS_START");
	Npc_ExchangeRoutine(self,"RitualInnosEyeRepair");
	AI_PlayAni  (self,"T_MAGRUN_2_HEASHOOT");
	Wld_PlayEffect("spellFX_Teleport_RING",  self  , self    , 0, 0, 0, TRUE);
	AI_Output(self,other,"DIA_Xardas_Hello_14_15");	//(задумчиво) У нас очень мало времени.

	Info_AddChoice(DIA_Xardas_Teleport,"Подожди минутку!",DIA_Xardas_TeleportGO1);
	Info_AddChoice(DIA_Xardas_Teleport,"Я немедленно отправляюсь в путь!",DIA_Xardas_TeleportGO2);
//	Info_AddChoice(DIA_Xardas_Teleport,"...",DIA_Xardas_TeleportGO);


};

func void DIA_Xardas_TeleportGO1()
{
	B_Say_Overlay(other,other,"$SC_HeyWaitASecond");          //Подожди минутку!
	AI_StopProcessInfos(self);
	Wld_PlayEffect("SPELLFX_TELEPORT",  self, self, 0, 0, 0, FALSE );	
	AI_Teleport(self,"NW_TROLLAREA_RITUAL_01");	
};

func void DIA_Xardas_TeleportGO2()
{
	B_Say_Overlay(other,other,"DIA_Xardas_FirstEXIT_15_00");  //Я немедленно отправляюсь в путь!
	AI_StopProcessInfos(self);
	Wld_PlayEffect("SPELLFX_TELEPORT",  self, self, 0, 0, 0, FALSE );	
	AI_Teleport(self,"NW_TROLLAREA_RITUAL_01");	
};
```
