### ISSUE TITLE
звук повышения характеристик ГГ при успешных молитвах Инносу

### ISSUE THREAD

**Issue by Kor-Angar** [dosinabox/g2nr_unofficial_update#191]
если не секрет, а почему ты не использовала звук и анимацию с молитвы паладина?
https://www.youtube.com/watch?v=l5CNq7iOJvE&feature=youtu.be
меня не покидает чувство что твой звук с Героев 3 :-) пришлось героев перепроходить :-))

**Comment by dosinabox** [comment]
> если не секрет, а почему ты не использовала звук и анимацию с молитвы паладина?

Так там же очистка, а не повышение статов. Нужно было что-то особенное.

> меня не покидает чувство что твой звук с Героев 3 :-)

Это из Сиквела. Но не исключено, что Пираньи взяли этот звук откуда-то.
