### ISSUE TITLE
Торлоф смертный капитан

### ISSUE THREAD

**Issue by Kor-Angar** [dosinabox/g2nr_unofficial_update#193]
после того как ГГ Торлофа берёт капитан в случае его гибели нельзя взять другого капитана. и игра не проходится.

Может Торлофа делать бессмертным?

**Comment by Kor-Angar** [comment]
> Может Торлофа делать бессмертным?

после того как ГГ назначил его капитанам

**Comment by dosinabox** [comment]
Это точно возможно? Попробуй воспроизвести на видео.

**Comment by Kor-Angar** [comment]
https://youtu.be/MJHkXMYoOKI 1 час 39 минут9:13, 11 февраля 2020 г., dosinabox <notifications@github.com>:Это точно возможно? Попробуй воспроизвести на видео.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
-- Отправлено из мобильного приложения Яндекс.Почты

**Comment by dosinabox** [comment]
Интересно. Ему устанавливается бессмертие, но в твоем случае:
- у него осталось 1 хп
- при ударе его состояние обновилось и он перешел в режим нокаута
- в состоянии нокаута его стало возможным добить

Решение: восстанавливать здоровье всем персонажам одновременно с установкой бессмертия.

**Comment by Kor-Angar** [comment]
> Решение: восстанавливать здоровье всем персонажам одновременно с установкой бессмертия.

эликсир выпьет? :-)

**Comment by Kor-Angar** [comment]
> можно снять бессмертие с капитана из монастыря (Иорган?) если взят в капитаны Торлоф или Джек

вот кстати заодно и с Йоргана можно бессмертие снимать, если Торлоф становится бессмертным :-)

**Comment by dosinabox** [comment]
> эликсир выпьет? :-)

Просто добавлять 1 хп, если у НПЦ 1 хп на момент установки бессмертия.

Исправлено. Относится к Джеку, Торлофу и Талбину.

**Comment by Kor-Angar** [comment]
Ангар и Горна посмотри тоже в 5 главе

**Comment by dosinabox** [comment]
Тоже поправлены.

**Comment by Kor-Angar** [comment]
Зер гуд!
