### ISSUE TITLE
Одержимый Фернандо в тюрьме

### ISSUE THREAD

**Issue by Kor-Angar** [dosinabox/g2nr_unofficial_update#195]
а Фернандо должен в тюрьме быть одержимым?

в **B_Enter_NewWorld** идёт проверка на смерть Фернандо
```
	if(!Npc_IsDead(Fernando))
	{
		CreateInvItems(Fernando,ITWR_DementorObsessionBook_MIS,1);
	};
```
 может добавить так же проверку и на то не сидит ли он в тюрьме? :-)

**Comment by dosinabox** [comment]
пусть будет как есть, его почти все сажают
