### ISSUE TITLE
Усиленный полковник орков. Ирдорат.

### ISSUE THREAD

**Issue by Kor-Angar** [dosinabox/g2nr_unofficial_update#201]
усиленный полковник орков на ирдорате имеет 45 уровень. а в Хориносе был 50.

**Comment by dosinabox** [comment]
включал/выключал?

**Comment by Kor-Angar** [comment]
Играл за Мага. Были усиленные. за усиленного в Хориносе дали 500 опыта, за усиленного на Ирдорате дали 450 опыта.

**Comment by dosinabox** [comment]
Не удалось ни воспроизвести, ни найти какую-либо ошибку

**Comment by Kor-Angar** [comment]
что то Полковник орков с бригадой на Ирдорате меня игнорили пока какой то триггер не сработал
![image](https://user-images.githubusercontent.com/49514764/106289956-f1e7a180-625a-11eb-89c5-b6759a8727bd.png)

**Comment by dosinabox** [comment]
Так и есть, там действительно триггер от разработчиков. Он активирует этих орков, делает запись в дневник, перемещает Марио и начинает атаку на корабль. См. evt_orkoberst().

**Comment by Kor-Angar** [comment]
Готика прекрасно. можно всю жизнь играть и всё равно что то новое узнаешь при двухсотом прохождение :-) 

***

 у Педро есть проверка на смерть Полковника?

**Comment by Kor-Angar** [comment]
я вот думаю в своей версии Полковнику дать улу-мулу.. там случайно модельки  с текстуркой в НВ нет?

**Comment by Kor-Angar** [comment]
> Он активирует этих орков, делает запись в дневник, перемещает Марио и начинает атаку на корабль

при атаке на корабль, если Ватраса нет орка который вставляется в коморку Ватраса можно вставлять в другое место, а то они всей командой спотыкаясь и падая бегут во внутрь корабля убивать несчастного орка

**Comment by dosinabox** [comment]
> я вот думаю в своей версии Полковнику дать улу-мулу.. там случайно модельки с текстуркой в НВ нет?

нет



>  у Педро есть проверка на смерть Полковника?

Только такой диалог:

```cpp
func void DIA_Pedro_DI_ArrivedAtShip_OrkOberst()
{
	AI_Output(other,self,"DIA_Pedro_DI_ArrivedAtShip_OrkOberst_15_00");	//Что там насчет этого полковника орков?
	AI_Output(self,other,"DIA_Pedro_DI_ArrivedAtShip_OrkOberst_09_01");	//Он отнял у меня последний лучик надежды когда-либо увидеть мою родную землю.
	AI_Output(self,other,"DIA_Pedro_DI_ArrivedAtShip_OrkOberst_09_02");	//С тех пор, как я прибыл сюда, он допрашивал меня о стратегическом размещении паладинов на Хоринисе.
	AI_Output(self,other,"DIA_Pedro_DI_ArrivedAtShip_OrkOberst_09_03");	//Конечно, я не мог рассказать ему много. Откуда мне знать об этом, черт возьми? Я послушник Огня.
	if(Npc_IsDead(AntiPaladin_DI))
	{
		Info_AddChoice(DIA_Pedro_DI_ArrivedAtShip,"Полковник орков мертв.",DIA_Pedro_DI_ArrivedAtShip_OberstTot);
	};
};

func void DIA_Pedro_DI_ArrivedAtShip_OberstTot()
{
	AI_Output(other,self,"DIA_Pedro_DI_ArrivedAtShip_OberstTot_15_00");	//Полковник орков мертв.
	AI_Output(self,other,"DIA_Pedro_DI_ArrivedAtShip_OberstTot_09_01");	//Мертв? Хвала Инносу. Я никогда не забуду его ужасное лицо.
};
```

**Comment by Kor-Angar** [comment]
я вот как раз про это
```D
	if(Npc_IsDead(AntiPaladin_DI))
	{
		Info_AddChoice(DIA_Pedro_DI_ArrivedAtShip,"Полковник орков мертв.",DIA_Pedro_DI_ArrivedAtShip_OberstTot);
	};
```
Педро сидит в запертой комнате.  Ключ у Полковника :-)

**Comment by dosinabox** [comment]
типа - лишняя проверка?

**Comment by Kor-Angar** [comment]
получается что лишняя, но может быть изначально предполагалось что герой может поговорить с Педро до убийства  Орка Полковника.
