### ISSUE TITLE
Ирдорат.  Разное

### ISSUE THREAD

**Issue by Kor-Angar** [dosinabox/g2nr_unofficial_update#204]
на Ирдорате там где алхимической стол нету пробирки. алхимический стол есть а пробирок нет. а мне глаз инноса надо было зарядить. пришлось возвращаться на корабль. может пару пробирок кинуть что бы героя не гонять на корабль ради пробирок?

**Comment by dosinabox** [comment]
в сундук ученика добавлены две мензурки

**Comment by Kor-Angar** [comment]
Это который возле алхимического стола? 11:11, 20 февраля 2020 г., dosinabox <notifications@github.com>:в сундук ученика добавлены две мензурки

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
-- Отправлено из мобильного приложения Яндекс.Почты

**Comment by dosinabox** [comment]
Да. И ещё одна появится здесь:

![1](https://user-images.githubusercontent.com/39790055/74958633-4fa02680-541a-11ea-8260-ff2736d228b7.jpg)

**Comment by Kor-Angar** [comment]
Ли и Ангар на Ирдорате не пошли на корабль
Нашёл черную жемчужину на Ирдорате

**Comment by dosinabox** [comment]
> Ли и Ангар на Ирдорате не пошли на корабль

Ошибок не вижу. Может, проблема в твоей сборке.

**Comment by Kor-Angar** [comment]
```D
	AI_Output(self,other,"DIA_Lee_DI_UndeadDragonDead_04_08");	//Может быть, когда-нибудь наши пути пересекутся вновь...
	AI_StopProcessInfos(self);
	Npc_ExchangeRoutine(self,"Start");
```
https://youtu.be/ADWilNB_L1c?t=4119

**Comment by Kor-Angar** [comment]
проверь у себя в скриптах

```D
FUNC VOID Rtn_StartDI_800 ()
{
	TA_Smalltalk				(08,00,23,00,"SHIP_CREW_01");
//	TA_Stand_Guarding			(08,00,23,00,"SHIP_CREW_01");
	TA_Sleep					(23,00,08,00,"SHIP_IN_06");
};
```

**Comment by Kor-Angar** [comment]
по хорошему бы их всех привести к  StartDI

**Comment by Kor-Angar** [comment]
по хорошему бы всю команду привести к StartDI что бы не было путаницы и было единообразие :-)

**Comment by dosinabox** [comment]
Новые распорядки требуют начала новой игры. Может, ты добавил их по ходу прохождения? А так - все их точки существуют.

**Comment by dosinabox** [comment]
А что если вставлять эликсир ловкости на Ирдорате для всех игроков, не проверяя ловкость? Вроде, обсуждали когда-то?

**Comment by Kor-Angar** [comment]
> Новые распорядки требуют начала новой игры. Может, ты добавил их по ходу прохождения? А так - все их точки существуют.


а. всё. понял. это у меня ошибка.

у меня айди у Ли на острове 800, а в оригинале 8000. я соответственно FUNC VOID Rtn_Start_8000 () поменял на FUNC VOID Rtn_StartDI_800 ()
а в диалоге поменять забыл. извини, 

что тень на плетень навёл :-)

**Comment by Kor-Angar** [comment]
> А что если вставлять эликсир ловкости на Ирдорате для всех игроков, не проверяя ловкость? Вроде, обсуждали когда-то?

давай сначало:
на Ирдорате нужен лук
лук лежит в сундуке у дракона
лук требует ловкости, если ловкости не хватает скрипт вставляет эликсир ловкости

***

предлагалось: 
- дать простой лук / арбалет в продажу Диего
- поменять лук в сундуке
- бросить куда нибудь простой лук
- бросить труп с луком

**Comment by dosinabox** [comment]
> * бросить труп с луком

Просто мысли вслух: а что если этим трупом будет охотник на демонов или охотник на орков в соответствующих доспехах из Сиквела?)

> * поменять лук в сундуке

Не хочется ради этого трогать хорошо проверенный мир.

> * дать простой лук / арбалет в продажу Диего

Не подходит, потому что Диего может не быть в команде или погибнет при атаке орков.

> * бросить куда нибудь простой лук

А вот это легко. Просто сегодня нашла подходящую пустую точку, около огненных варанов у корабля.

Хочется уже закрыть этот вопрос)

**Comment by Kor-Angar** [comment]
> Не подходит, потому что Диего может не быть в команде или погибнет при атаке орков.

это вопрос вероятность. какова вероятность что у героя такая низкая ловкость и он при этом не взял Диего :=) 


> Просто мысли вслух: а что если этим трупом будет охотник на демонов или охотник на орков в соответствующих доспехах из Сиквела?)

> А вот это легко. Просто сегодня нашла подходящую пустую точку, около огненных варанов у корабля.

можно туда попробовать бросить труп. посмотреть что из этого получится. можно два трупа бросить посмотреть какой лучше смотрится. 
а вообще странно что на корабле нет лука :-)

**Comment by Kor-Angar** [comment]
> Хочется уже закрыть этот вопрос)

тебя эликсир ловкости напрягает? :-)

**Comment by dosinabox** [comment]
> тебя эликсир ловкости напрягает? :-)

Появилась возможность заблокировать его появление при помощи свитка превращения в овцу. Что делать?

Правильно проверять ловкость ГГ, а не овцы?
Вставлять зелье в мир для всех игроков без проверки ловкости?
Добавить зелье в продажу Милтену?
Добавить зелье в продажу Ватрасу?

**Comment by Kor-Angar** [comment]
Невставляй его вообще удали. У кого нет Лука тот купит / найдёт его. То есть техническая возможность пройти игру есть. Это зелье решает конкретную задачу в Готики 2 классик: одеть лук для прохождения игры если у героя непрокаченная ловкость и нет с собой Лука. В Готики 2 НВ это зелья вообще никакую задачу не решает. Возможные проблемы с прохождением без прокаченной ловкости мы решили комплексно: вставили  простой лук не требующий ловоусти, добавлена бежутерия в продажу на ловкость, что то там еще. В Готике 2 НВ силач ходит с арбалетом, в игре гора бонусов к ловкости и так далее, в том числе скрижали. Проблемы что игрок дошёл на Ирдорате до ворот и не смог чего то там вообще не возникала ни разу. Точнее у меня такое было один раз, но я тут же нашёл лук в сундуке и одел его. В связи с выше изложенным, считаю вопрос с зельем ловкости деконструктивным 😀22:28, 30 апреля 2021 г., dosinabox ***@***.***>:

тебя эликсир ловкости напрягает? :-)

Появилась возможность заблокировать его появление при помощи свитка превращения в овцу. Что делать?
Правильно проверять ловкость ГГ, а не овцы?
Вставлять зелье в мир для всех игроков без проверки ловкости?
Добавить зелье в продажу Милтену?
Добавить зелье в продажу Ватрасу?

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
-- Отправлено из мобильного приложения Яндекс.Почты
