### ISSUE TITLE
Говорят, ты всё уладил...

### ISSUE THREAD

**Issue by dosinabox** [dosinabox/g2nr_unofficial_update#209]
В игре есть такие фразы:
![Screenshot_1](https://user-images.githubusercontent.com/39790055/74558357-3c510f00-4f73-11ea-82cc-90d9b134caab.jpg)

Также в файлах озвучки есть фразы-продолжения, которые в игре **никак не используются**:
![image](https://user-images.githubusercontent.com/39790055/74558429-5ab70a80-4f73-11ea-9b7c-9efba80c5986.png)

Удалось их применить:
![Screenshot_2](https://user-images.githubusercontent.com/39790055/74558489-6f939e00-4f73-11ea-9817-bdd05eff435a.jpg)

Нужно проверить в новой версии. Применимо только к жителям монастыря, фермы Онара и замка в Минентале. Для городских жителей такой озвучки нет.

Пример: бьем фермера, говорим с ним после драки, получаем отказ от разговора, идем к Ли, платим штраф, возвращаемся к фермеру, говорим с ним, слушаем восстановленные реплики.

**Comment by dosinabox** [comment]
14 голосов, по 3 вариации (ферма + замок + монастырь), по 1 одобрению ("Это хорошо"). Итого 56 восстановленных реплик :). Хотя не все голоса применяются, и некоторые одобрения уже были использованы.

**Comment by dosinabox** [comment]
Ещё нужно подумать о людях, которые могут менять свою принадлежность. Например, Дуриан, Рози, Тилл, рыцари Маркоса.

**Comment by dosinabox** [comment]
Для тестирования:
https://dropmefiles.com/2T3JA

**Comment by Kor-Angar** [comment]
А то за новый файлообменник? 😀Для тестирования:
https://dropmefiles.com/2T3JA

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.
-- Отправлено из мобильного приложения Яндекс.Почты

**Comment by dosinabox** [comment]
Сюда уже не проходят по размеру после добавления обновленного мира Хориниса. А на яндексе лень логиниться.

**Comment by Kor-Angar** [comment]
> Ещё нужно подумать о людях, которые могут менять свою принадлежность. Например рыцари Маркоса.

а вот тут можно поподробнее?  это два НПС пала которые уходят к Маркосу, после доклада Гаранту?

**Comment by Kor-Angar** [comment]
про грехи и отца Парлана, я где то ранее писал про то что в игре слабо задействована история про воровство святого молотка. и по моему никак не отработана, если его ворует Наём/ ОнД в рамках квеста Судьи.

**Comment by dosinabox** [comment]
> про грехи и отца Парлана, я где то ранее писал про то что в игре слабо задействована история про воровство святого молотка. и по моему никак не отработана, если его ворует Наём/ ОнД в рамках квеста Судьи.

Вряд ли можно что-то сделать.

> это два НПС пала которые уходят к Маркосу, после доклада Гаранту?

Да. В таком случае они уже не должны комментировать оплату штрафа.

**Comment by dosinabox** [comment]
Если всё будет хорошо, то можно будет сделать такие фразы и для городских жителей, вырезав из существующих реплик упоминания Ли или Гаронда.

Типа:

"Так значит, ты утряс все проблемы с командующим" ->
"Так значит, ты утряс все проблемы"

"Так ты ходил к Ли и все уладил" ->
"Так ты все уладил"

**Comment by Kor-Angar** [comment]
Там ещё ест фразы у Константино и кого то из торговцев. Возможно их тже можно как то использовать.

**Comment by dosinabox** [comment]
> Если всё будет хорошо, то можно будет сделать такие фразы и для городских жителей, вырезав из существующих реплик упоминания Ли или Гаронда.

Готово. Теперь нужно подумать о людях, которые могут переставать быть городскими жителями, которые жалуются на преступления Андрэ или Хагену. Например, Гербрандт сбегает в портовый квартал вместе со своей женой, Корнелиус убегает из города, а Ульф уходит в монастырь. Такие ситуации нужно учитывать.

**Comment by Kor-Angar** [comment]
Давай информацию обобщим в первом посте.  что бы понять что проверять. а то я читал несколько раз вообщем то мысль понял, а в частности всё равно не понял :-)

**Comment by Kor-Angar** [comment]
возможно эти фразы можно воспроизводить если герой пытается попасть в верхний портал, его туда не пускают Паладины и посылают к Лорду Андре заплатить штраф. тогда после того как герой заплатил штраф и повторно заходит в верхний квартал паладины могут сказать:

> "Так значит, ты утряс все проблемы с командующим" ->
> "Так значит, ты утряс все проблемы"

**Comment by Kor-Angar** [comment]
> это два НПС пала которые уходят к Маркосу, после доклада Гаранту?

я их избивал вместе с Маркосом и они не обижались и продолжали говорить с героем Паладином. По моему раньше Маркос обижался и не говорил с ГГ.
