### ISSUE TITLE
Проверка на смерть Мелькома / Пираты

### ISSUE THREAD

**Issue by Kor-Angar** [dosinabox/g2nr_unofficial_update#21]
Проверка на смерть Мелькома в диалоге с PIR_1367_Addon_Owen происходит через скрижальку

```
instance DIA_Addon_Owen_MalcomDead(C_Info)
{
	npc = PIR_1367_Addon_Owen;
	nr = 3;
	condition = DIA_Addon_Owen_MalcomDead_Condition;
	information = DIA_Addon_Owen_MalcomDead_Info;
	description = "Твой приятель Мальком мертв.";
};


func int DIA_Addon_Owen_MalcomDead_Condition()
{
	if(Npc_KnowsInfo(other,DIA_Addon_Owen_MalcomStunt) && (MIS_Owen_FindMalcom == LOG_Running) && !Npc_HasItems(Malcom,ItWr_TwoHStonePlate3_Addon))
	{
		return TRUE;
	};
};
```
в оригинальных скриптах можно было ItWr_TwoHStonePlate3_Addon у живого Мелькома отобрать и в последующем не находя  труп Мелькома  сообщить  Овену о смерти Мелькома.
мы с тобой это обсудили и ты исключила такую возможность, убрав у живого Мелькома скрижальку.

есть у меня предложение скрижальку живому Мелькому вернуть, а проверку делать не через скрижаль, а через какую нибудь уникальную безделушку, например серебряное/золотое кольцо или еще какой то бесполезный лут.

**Comment by dosinabox** [comment]
- скрижаль будет у Малькома со старта
- после смерти в пещере в его инвентаре появится старая монетка
- Оуэну можно будет сообщить о смерти Малькома, если забрать монетку
- Оуэну можно будет сообщить о смерти Малькома, если убить одного из луркеров в пещере (они появляются там вместе с трупом)

**Comment by Kor-Angar** [comment]
уникальная старая монета?

**Comment by dosinabox** [comment]
> уникальная старая монета?

Самая обычная. Они используются разработчиками чтобы трупы не исчезали.

**Comment by Kor-Angar** [comment]
так если монетка обычная то у героя таких полно. или надо что бы и Луркер был убит и была монетка?

**Comment by dosinabox** [comment]
- Мальком убивается скриптом и телепортируется в пещеру;
- Чтобы его труп не исчез, ему подкладывается старая монетка (как и любым другим трупам);
- В пещере появляются луркеры;
- Если убить одного из луркеров или забрать с трупа монетку, то Оуэну можно сообщить об обнаружении мертвого Малькома.

**Comment by Kor-Angar** [comment]
неясно. монетка же старая обычная. она же не уникальная. или проверка идёт не по монетке а по отсутствию её в трупе?:-)

**Comment by dosinabox** [comment]
У монетки флаг ITEM_MISSION. С такими предметами в инвентаре трупы не исчезают. Здесь нечего обсуждать, это абсолютно стандартное поведение. Если у мертвого Малькома её нет, значит ГГ нашел его труп и может сообщить об этом Оуэну.
