### ISSUE TITLE
Восстановление товаров торговца после избиения торговца

### ISSUE THREAD

**Issue by Kor-Angar** [dosinabox/g2nr_unofficial_update#210]
Отпишись что думаешь
https://rpgrussia.com/threads/gothic-mod-fix.6520/page-24
Для неофициального обновления вопрос тоже актуальный 😀

**Comment by dosinabox** [comment]
меня полностью устраивает пополнение новыми товарами в начале каждой главы

**Comment by dosinabox** [comment]
https://worldofplayers.ru/threads/36812/post-1079037

**Comment by Kor-Angar** [comment]
а с амулеом с защитой от магии который продаёт Кантар, в случае его посадке решили?

**Comment by dosinabox** [comment]
нет

**Comment by Kor-Angar** [comment]
> В момент вхождения торговца в бессознательное состояние в игровой мир вставляется подставной персонаж "хранитель вещей", соответствующий данному торговцу. Вещи из инвентаря торговца перекладываются в инвентарь "хранителя" и лежат там до момента возобновления торговли. При возобновлении торговли вещи перекладываются обратно в инвентарь торговца, а "хранитель" удаляется из игрового мира.

https://worldofplayers.ru/threads/36812/page-140#post-1079271
