### ISSUE TITLE
Сертификат на землю. Лестер

### ISSUE THREAD

**Issue by Kor-Angar** [dosinabox/g2nr_unofficial_update#214]
А можно создать докумет "сертификат на землю" из Готики 1?

![IMG_20200219_022250](https://user-images.githubusercontent.com/49514764/74984908-850f3900-5447-11ea-80a1-2fe8f1af6175.jpg)

**Comment by Kor-Angar** [comment]
Сертификат

Я, Бергмар, граф Западных Полей, властью, врученной мне лордом Тиморизина, что вокруг Хориниса, заявляю что я отдать и продать предъявителю сего документа и дому Инноса горный форт (вкупе с положенной мне десятиной и доходами от тамошних шахт) за 400 едениц золота.

**Comment by dosinabox** [comment]
Можно. А зачем?

**Comment by Kor-Angar** [comment]
можно будет подумать как его задействовать. 
например положить в Форте.или дать Лестеру. он в конце игры становится смертным и герой сможет его у него отобрать. или дать возможность его украсть у Лестера.

**Comment by dosinabox** [comment]
Проблема в том, что существует два перевода этого текста из первой части - от Руссобит и от Snowball. Могут быть непонятки. Ты предлагаешь один вариант, а вот мне привычнее другой.

**Comment by Kor-Angar** [comment]
Можно вставить немецкий текст 😎***Закинь версию от Руссобит М.
