### ISSUE TITLE
Закрыть возможность прокачки с / 29-34 / 59-64 / 89-94 / 119-124

### ISSUE THREAD

**Issue by Kor-Angar** [dosinabox/g2nr_unofficial_update#215]
а ещё такой вопрос, что бы закрыть возможность прокачки с 29 до 34 я вот так написал

```
		Info_AddChoice(DIA_Cord_Teach,B_BuildLearnString(PRINT_Learn2h1,B_GetLearnCostTalent(other,NPC_TALENT_2H,1)),DIA_Cord_Teach_2H_1);
		
		if((other.HitChance[NPC_TALENT_2H] >= 10) && (other.HitChance[NPC_TALENT_2H] <= 25))
		{
			Info_AddChoice(DIA_Cord_Teach,B_BuildLearnString(PRINT_Learn2h5,B_GetLearnCostTalent(other,NPC_TALENT_2H,5)),DIA_Cord_Teach_2H_5);
		}
		else if((other.HitChance[NPC_TALENT_2H] >= 30) && (other.HitChance[NPC_TALENT_2H] <= 55))
		{
			Info_AddChoice(DIA_Cord_Teach,B_BuildLearnString(PRINT_Learn2h5,B_GetLearnCostTalent(other,NPC_TALENT_2H,5)),DIA_Cord_Teach_2H_5);
		}
		else if((other.HitChance[NPC_TALENT_2H] >= 60) && (other.HitChance[NPC_TALENT_2H] <= 85))
		{
			Info_AddChoice(DIA_Cord_Teach,B_BuildLearnString(PRINT_Learn2h5,B_GetLearnCostTalent(other,NPC_TALENT_2H,5)),DIA_Cord_Teach_2H_5);
		};
```
можно это сделать как то более элегантно?

_Originally posted by @Kor-Angar in https://github.com/dosinabox/g2nr_unofficial_update/issues/187#issuecomment-583855567_

**Comment by Kor-Angar** [comment]
**ПОСТ D36**
> а ещё такой вопрос, что бы закрыть возможность прокачки с 29 до 34 я вот так написал

Ну да, логично, правильно.

> можно это сделать как то более элегантно?

В идеале нужно делать точный расчет очков при обучении с такими значениями и переключатель у помощника ("честный расчет стоимости обучения"). Слишком привычная механика, не стоит её ломать для всех.

**Comment by Kor-Angar** [comment]
>  переключатель у помощника ("честный расчет стоимости обучения"). Слишком привычная механика, не стоит её ломать для всех.

ну это то  понятно. я вот сам много лет не использовал лазейку 29-34, 59-64.  ну а потом как то потихоньку стал сам использовать и уже совсем привык :-) в целом это серьезное кол-во опыта выпилиться. так на вскидку думаю что от 2 до 5 уровней. поэтому вопрос серьёзный конечно.

**Comment by Kor-Angar** [comment]
**ПОСТ KOR-ANGAR**

>  переключатель у помощника ("честный расчет стоимости обучения"). Слишком привычная механика, не стоит её ломать для всех.

ну это то  понятно. я вот сам много лет не использовал лазейку 29-34, 59-64.  ну а потом как то потихоньку стал сам использовать и уже совсем привык :-) в целом это серьезное кол-во опыта выпилиться. так на вскидку думаю что от 2 до 5 уровней. поэтому вопрос серьёзный конечно.

***

> В идеале нужно делать точный расчет очков при обучении с такими значениями

мне кажется это уже перфекционизм. и это работать **на практике** не будет, так как у героя в большинстве случаев не окажется необходимого кол-ва ЛП, так как оно уже будет отличаться от ровного (5/10/15) значения. т.е. условно говоря герой поднял уровень у него 10 ЛП пришел к учителю, а тут  у него за прокачку 1 силы просит 2 ЛП, а за прокачку 5 силы 11 ЛП или 12 ЛП или 13 ЛП. и герой будет вынужден качать силу по 1, так как на прокачку 5 силы ЛП всё равно не будет хватать. Конечно бывает ситуация что есть лишний 1 ЛП, дают новый уровень у героя 11 ЛП и учитель тоже просит 11 ЛП. но я думаю это очень и очень частные ситуации. 

опять же игроку сложно будет осознать что прокачка на 1 требует условно говоря 2 ЛП, а прокачка на 5 требует условно  11 ЛП. он может решит что авторы "переработали баланс" ввидя какую то сложную схему прокачки. 

далее тут так же может возникнет ситуация и с учителем который условно учит до 30 / 60, т.е. учитель опять же условно говоря будет предлагать поднять параметр на 5 единиц за 11 ЛП, а потом сообщать герою что он не может его выучит так как учит до 60.

Я думаю могут вылезти и ещё какие то штуку, например автоподнятие арбалета при обучению луку.

**Comment by Kor-Angar** [comment]
на WOP по моему эту историю тоже поддержали? или нет?

**Comment by dosinabox** [comment]
Будет обсуждаться и исправляться здесь:
https://github.com/dosinabox/g2nr_unofficial_update/issues/225
