### ISSUE TITLE
Найм Биффа

### ISSUE THREAD

**Issue by Kor-Angar** [dosinabox/g2nr_unofficial_update#218]
```
instance DIA_Biff_ARBEITEN(C_Info)
{
	npc = DJG_713_Biff;
	nr = 8;
	condition = DIA_Biff_ARBEITEN_Condition;
	information = DIA_Biff_ARBEITEN_Info;
	permanent = TRUE;
	description = "Ты бы не хотел поработать на меня?";
};


func int DIA_Biff_ARBEITEN_Condition()
{
//	if((DJG_BiffParty == FALSE) && Npc_KnowsInfo(other,DIA_Biff_HALLO) && (DJG_Biff_Stay == FALSE))
	if((DJG_BiffParty == FALSE) && Npc_KnowsInfo(other,DIA_Biff_WASHIERIMTAL) && (DJG_Biff_Stay == FALSE))
	{
		return TRUE;
	};
};
```

может сделать этот диалог недоступным если герой взял Бифа в команду? :-)

**Comment by Kor-Angar** [comment]
пересмотрел запись. вот на этот диалог наверное надо сделать ограничение :-)

```
instance DIA_Biff_WASHIERIMTAL(C_Info)
{
	npc = DJG_713_Biff;
	nr = 7;
	condition = DIA_Biff_WASHIERIMTAL_Condition;
	information = DIA_Biff_WASHIERIMTAL_Info;
	description = "Что ты надеешься найти здесь, в Долине Рудников?";
};


func int DIA_Biff_WASHIERIMTAL_Condition()
{
	if(Npc_KnowsInfo(other,DIA_Biff_HALLO))
	{
		return TRUE;
	};
};
```

**Comment by Kor-Angar** [comment]
а может быть наоборот: сделать возможность взять Бифа на корабль, при условие что он уже работал с ГГ:-)

**Comment by Kor-Angar** [comment]
а может быть наоборот: сделать возможность взять Бифа на корабль, при условие что он уже работал с ГГ:-) 

[t=9792](https://youtu.be/1QMiWLgEC0M?t=9792)

**Comment by dosinabox** [comment]
Много чего сделано, проверишь потом. Нужно будет начало новой игры, сообщи когда соберешься на новое прохождение.

**Comment by dosinabox** [comment]
В частности, теперь его можно прогнать и в долине, и в Хоринисе. А после принятия в команду нельзя брать его с собой в поход по долине, когда он уже уходит к проходу.

**Comment by Kor-Angar** [comment]
> Много чего сделано, проверишь потом. Нужно будет начало новой игры, сообщи когда соберешься на новое прохождение.

а я жду как будет готово  https://github.com/dosinabox/g2nr_unofficial_update/issues/187 :-)

**Comment by Kor-Angar** [comment]
сегодня проверю

**Comment by Kor-Angar** [comment]
что то он агрится если ему отказать в Хориносе. и "забыть" не помогает :-)

Ты как это дело планировала? :-)

**Comment by Kor-Angar** [comment]
что то он агрится если ему отказать в Хориносе. и "забыть" не помогает :-)

Ты как это дело планировала? :-)

https://youtu.be/xemWfW3h2YU?t=365

**Comment by dosinabox** [comment]
> Ты как это дело планировала? :-)

да

**Comment by Kor-Angar** [comment]
Ну значит Бифф работает 🙃

**Comment by Kor-Angar** [comment]
позвал бифа, отказал бифу. биф бессмертный в минентале остался
