### ISSUE TITLE
Яйца для Беннета

### ISSUE THREAD

**Issue by Kor-Angar** [dosinabox/g2nr_unofficial_update#221]
Когда квест закрывается? если Беннет говорит что яиц наверное больше не осталось, запись в дневник добавляется?

**Comment by dosinabox** [comment]
Вот здесь:
```
AI_Output(self,other,"DIA_Bennet_EierBringen_06_06");	//Я не думаю, что ты найдешь еще яйца. К тому же, мне и этих достаточно. Я даже не знаю, что я буду делать со всеми ними.
TOPIC_END_DRACHENEIER = TRUE;
```

> запись в дневник добавляется?

нет

**Comment by dosinabox** [comment]
> Когда квест закрывается?

Когда Беннет получит 12 яиц.
Ну, или с началом шестой главы.

**Comment by Kor-Angar** [comment]
может запись добавить? :-)

**Comment by dosinabox** [comment]
Обычно такие записи в закрываемые квесты не добавляются. Новые записи - только для текущих квестов.

**Comment by Kor-Angar** [comment]
а он закрывается? у меня после этой реплики в активных висел

**Comment by dosinabox** [comment]
Пропал бы после сна или получения любого квестового опыта, но я добавлю обновление дневника и он закроется сразу.

**Comment by Kor-Angar** [comment]
Спасибо. А можно в тот момент когда квест закрывается делать такой эффект будто герой что то записывает? 😀
