### ISSUE TITLE
NPC убивают Овечку

### ISSUE THREAD

**Issue by Kor-Angar** [dosinabox/g2nr_unofficial_update#222]
а можешь подсказать кто из НПС убивает овцу,а к то нет. и от чего это зависит? от гильдии?

были ли правка этой истории в неофициальном обновление?

**Comment by dosinabox** [comment]
ты про людей или животных/монстров?

**Comment by Kor-Angar** [comment]
Про людей

**Comment by dosinabox** [comment]
не представляю, из-за чего кто-либо может убить овцу и не думаю, что это менялось

**Comment by Kor-Angar** [comment]
бандиты убивают

**Comment by dosinabox** [comment]
это где такое было?

**Comment by Kor-Angar** [comment]
Вчера проверял в последней версии. Лагерь Бандитов, ярик

**Comment by dosinabox** [comment]
А разве у них там есть овцы?

**Comment by Kor-Angar** [comment]
так.. герой в овцу превратился :-)

**Comment by dosinabox** [comment]
Интересно. Но, наверное, не страшно. Голодные...
