### ISSUE TITLE
v25 тест

### ISSUE THREAD

**Issue by Kor-Angar** [dosinabox/g2nr_unofficial_update#226]
Плейлист 1H=Crossbow=310 Dmg / Gil = Pal / Gothic II: NotR
https://www.youtube.com/playlist?list=PLqe88GB0Po9zZGYCfJSvJSaxy46Ka_dbg

Неофициальное обновление V.24 от D36
https://steamcommunity.com/sharedfiles/filedetails/?id=757500304

Save 1H=Crossbow=310 Dmg / Gil = Pal
https://yadi.sk/d/4IJJlRVDJn0CFA

***

Также в ближайшем прохождении прошу обратить внимание на квест "Пей до дна" в различных комбинациях ситуаций. Предпринимались попытки исправить его блокировку в 4 главе, когда Рэндольф становится одержимым или начинает страдать от похмелья. И прочее, и прочее.

- Исправлена возможность начать квест 'Пей до дна' в четвертой главе как заведомо невыполнимый;
- Добавлена возможность сообщить Рухару в четвертой главе о том, что Рэндольф не сможет прийти в таверну;
- Рухар и Рэндольф уйдут из таверны с началом четвертой главы, а Орлан объявит результаты соревнования;
- Рэндольф отдаст ГГ деньги за выигрыш в соревновании и после четвертой главы, если не станет одержимым;

Также нужно проверить Биффа.

Также нужно проверить новые реплики жителей города, монастыря, фермы и замка о преступлениях и оплате штрафов (обижаем - разговариваем - платим штраф главному - разговариваем).

_Originally posted by @dosinabox in https://github.com/dosinabox/g2nr_unofficial_update/issues/41#issuecomment-594174967_

**Comment by Kor-Angar** [comment]
можно запускаться или подождать ещё какой то файл с правками?

**Comment by dosinabox** [comment]
Начинай. Всё остальное очень долго делать. Потом проверить можно будет отдельно.

**Comment by dosinabox** [comment]
Также прошу проверить Биффа.

**Comment by Kor-Angar** [comment]
Дракона не получилось?

**Comment by dosinabox** [comment]
Получилось, вот:
[g2a_nr_scriptpatch_v25_test_04.03.2020.zip](https://github.com/dosinabox/g2nr_unofficial_update/files/4289116/g2a_nr_scriptpatch_v25_test_04.03.2020.zip)

В амулете тестировщика должно быть 4 марта.

**Comment by Kor-Angar** [comment]
Какие то настройки включать для дракона надо?

**Comment by dosinabox** [comment]
Нет.
Скачай ещё раз, пожалуйста - подчистила кое-что после тестов:
[g2a_nr_scriptpatch_v25_test_04.03.2020.zip](https://github.com/dosinabox/g2nr_unofficial_update/files/4289249/g2a_nr_scriptpatch_v25_test_04.03.2020.zip)

**Comment by Kor-Angar** [comment]
скачал. установил

**Comment by Kor-Angar** [comment]
Фонари опять не горят в Хориносе

**Comment by Kor-Angar** [comment]
А нет. Работают

**Comment by Kor-Angar** [comment]
> Дракона не получилось? 

бессмертный был :-)

**Comment by Kor-Angar** [comment]
а можно тебя попросить что то с драконом сделать? :-))

**Comment by Kor-Angar** [comment]
> а можно тебя попросить что то с драконом сделать? :-))

хочу в очередной(четвертый) раз сначала начать. пытаюсь играть гибридчиком так как Диего1987 говорит что это вообще имба/читерство. но вот без той опции при которой учителя начинают игнорят бонусы это тяжко. поэтому приходится снова и снова начинать сначало.

прихожу к выводу что читерство это есть само по себе наличие опции при которой учителя игнорят бонусы :-)

**Comment by dosinabox** [comment]
А что именно нужно сделать? Эта опция ведь уже была, нет?

**Comment by Kor-Angar** [comment]
Я хотел бы иметь возможность убить Дракона во второй главе как в оригинальной Готике 2 НВ. Хочу попытаться понять, разработчики закомментировали ему бессмертие случайно или осознанно :-)

https://github.com/dosinabox/g2nr_unofficial_update/issues/224

**Comment by Kor-Angar** [comment]
> Хочу попытаться понять

для самого себя  понять :-)

**Comment by dosinabox** [comment]
Это понятно. А что с опцией?

**Comment by Kor-Angar** [comment]
> А что с опцией?

я с ней ни разу не играл, так как она на мой взгляд нарушает баланс игры. а так с опцией всё нормально наверное. 
просто на форуме когда пишут про оригинальный баланс почему то не уточняют, что играют с этой опцией:

- с такой опцией  "да", шпага мастера имба, всё ловкостное оружие надо резать
- с такой опцией "да", ловкачу, выгодно качать силу на "20" за ЛП
- с такой опцией "да", силачу выгодно качать ловкость на "20" за ЛП
- с такой опцией "да", арбалет даёт быстрый старт и становится имбой
- с такой опцией "да", гибридчик это читер

И там много чего становится выгодно и появляется(усиливается) "имба", потому что с такой опцией в целом происходит "ребаланс" игры. 

всё что пишет Диего про баланс есть истина, если включить эту опцию.

**Comment by Kor-Angar** [comment]
всё что пишет Диего про баланс есть истина, если включить эту опцию.

**Comment by dosinabox** [comment]
Значит, пока просто снять бессмертие с дракона?

**Comment by Kor-Angar** [comment]
Сними пожалуйста. Или сделай это опционально. И шлем с Лорда Андре сними плиз в этой сборке.

**Comment by dosinabox** [comment]
а с Хагена?

**Comment by Kor-Angar** [comment]
ну и с Хагена :-)

**Comment by Kor-Angar** [comment]
можно и Лотара одеть в легкие доспехи паладина :-) процесс переодевания он перманентный.

напиши плиз код доспехов гвардейца про которые ты на стрими говорила

**Comment by dosinabox** [comment]
> напиши плиз код доспехов гвардейца про которые ты на стрими говорила

Для Хагена, что ли?
Будет ITAR_PAL_S. Для теста сделаю.

**Comment by Kor-Angar** [comment]
просто что бы можно было вставить. хочу посмотреть как он выглядит в игре

**Comment by dosinabox** [comment]
[g2a_nr_scriptpatch_v25_test_08.03.2020.zip](https://github.com/dosinabox/g2nr_unofficial_update/files/4303367/g2a_nr_scriptpatch_v25_test_08.03.2020.zip)

**Comment by Kor-Angar** [comment]
Спасибо

**Comment by Kor-Angar** [comment]
> Будет ITAR_PAL_S. Для теста сделаю.

доспех красивый, но визуально  тяжелый доспех паладина мне кажется имеет большую защиту :-)

даже не знаю кому он в игре может подойти по статусу. Лорд Андре и Лорд Хаген паладины и должны быть во фракционных доспехах. Губернатор вроде как не Лорд и даже не генерал-губернатор. 

может попробовать Лорда Инубиса в него одеть?:-)

**Comment by dosinabox** [comment]
Для Инубиса/Архола он уж очень новый и нетронутый. А портить грязью и ржавчиной не хочется.
Но в целом мне хотелось бы одеть их во что-то, что отличало бы их от обычных теневых воинов.

**Comment by dosinabox** [comment]
> Губернатор вроде как не Лорд и даже не генерал-губернатор.

И у него уже есть новая отдельная одежда.

**Comment by Kor-Angar** [comment]
> Но в целом мне хотелось бы одеть их во что-то, что отличало бы их от обычных теневых воинов.

или теневых войнов переодеть в легкие доспехи паладина

**Comment by dosinabox** [comment]
рецепт грибного экстракта - ItWr_MushroomMana

**Comment by Kor-Angar** [comment]
Он во вчерашее сборке есть?

**Comment by dosinabox** [comment]
да

**Comment by dosinabox** [comment]
даже у Константино появится когда следует

**Comment by Kor-Angar** [comment]
Пойду к Кости в ученики 😀

**Comment by Kor-Angar** [comment]
в 5 главе появился Дракон Снеппер который съел охотника
https://youtu.be/xemWfW3h2YU?t=283

**Comment by Kor-Angar** [comment]
Добавил в первый пост ссылки на сейвы и на плейлист. 

С Рандольфом проблем не было. и квест "пей до дна" выполнил и квест "похмелье".

Так же выполнил квест  "лунный свет" в 3 главе играя за Пала
https://github.com/dosinabox/g2nr_unofficial_update/issues/154

**Comment by dosinabox** [comment]
> Так же выполнил квест "лунный свет" в 3 главе играя за Пала

Это правильно или нет?

**Comment by Kor-Angar** [comment]
Да фиг его знает. Сейчас этот Лунный Свет через одно место работает.

**Comment by Kor-Angar** [comment]
https://dropmefiles.com/R5uTQ
список изменений в гугл-доке

**Comment by Kor-Angar** [comment]
глянь всё ли верно про неофициальный патч написал 
https://vk.com/@kor.angar-gothic2-render-d3d11

**Comment by dosinabox** [comment]
> Перво наперво ставим патч Gothic2_Fix-1.30.0.0.exe

Ошибка в тексте - по ссылке файл gothic2_fix-2.6.0.0-rev2.exe.

> до сих пор нет чего то простого, типа скачал большой файл запустил и он сам всё сделал

Как это нет) Я уже четыре года поддерживаю Gothic Steam Fix / Gothic 2 Steam Fix, которые включают в себя и русификации, и СистемПак, и лаунчер модов, и неофициальное обновление / мод-фиксы. 
Если использовать такой сборник для Г2НВ, то останется только упомянуть настройки неофициального обновления, рендер DX11, нормалмапы и новые шрифты. Всё остальное там уже есть. А в ближайшее время эти сборники будут обновлены, я добавлю Юнион с новым СистемПаком 1.9 и патч 4 ГБ (кстати, важно упомянуть в тексте, что он только для 64-битных систем).

**Comment by Kor-Angar** [comment]
Буду пытаться твою версию поставить. Пару раз ставил были какие то заморочки, в т. ч. невозможность запустить оригинальную игру:-(Ты планируешь в сборку добавить Готика 2 классик?

**Comment by Kor-Angar** [comment]
А топик по правкам характеристик у учителей есть?

**Comment by dosinabox** [comment]
> А топик по правкам характеристик у учителей есть?

https://github.com/dosinabox/g2nr_unofficial_update/commit/bb0e3a46e7bb4379d59be2ff0e3cdb533a74ba21

> Буду пытаться твою версию поставить. Пару раз ставил были какие то заморочки, в т. ч. невозможность запустить оригинальную игру:-(

Единственная заморочка в том, что Стим запускает не стартер модов, а сразу основную игру. Но поскольку ты запускаешь стартер сам и не через Стим, то для тебя этой проблемы нет. Просто при установке сборника сними галочку с пункта неофициального обновления и установи его потом отдельно. И запускай из стартера, как всегда. И как всегда можно будет накатывать разные тестовые сборки новых версий. И оригинал отдельно останется.

> Ты планируешь в сборку добавить Готика 2 классик?

Нет, пока Стим не начнет пользоваться стартером модов. Общаюсь с издателем, готовлю им разные фиксы, советую. Может, послушаются.

**Comment by dosinabox** [comment]
Новая тестовая сборка:
https://dropmefiles.com/65JEA

- Паладины и маги будут лечиться только если противник мертв, избит, спит или находится достаточно далеко;
- Исправлены бонусы Вульфгара, Сержио и книг Лютеро к навыкам владения оружием;
- Взаимодействие с алхимическим столом не будет прекращаться после каждого изготовленного зелья;

**Comment by Kor-Angar** [comment]
> Нет, пока Стим не начнет пользоваться стартером модов

а какая связь?

>  Просто при установке сборника сними галочку с пункта неофициального обновления и установи его потом отдельно.

а смысл тогда его ставить? :-) что тебе мешает грубо говоря сейчас добавить оригинальную Готику 2 НВ(без неоф. патча) и Готику 2 Классик  в этот "стим фикс" в качестве модов, что бы их можно было через Стартер запустить? ничего не мешает;-)

я запарился с ним. под него специально Готику в Стиме покупал. Думал будет всё по уму. Ставил его. потом удалял. потом опять ставил. а в итоге всё равно приходится руками всё это делать, на примере твоего же фикса на броню для SystemPack или оригинальной игры Готики 2 НВ.

уже дожили до того что просто архив с установленной игрой люди друг другу скидывают, так как у них просто не получается все эти танцы с бубнами пройти. маразм.

**Comment by dosinabox** [comment]
> что тебе мешает грубо говоря сейчас добавить оригинальную Готику 2 НВ(без неоф. патча) и Готику 2 Классик в этот "стим фикс" в качестве модов, что бы их можно было через Стартер запустить?

Только тот факт, что для пользователей стима стартер не запускается из самого стима. Ты запускаешь его отдельно, и тебе не считается время в игре, нет фирменного оверлея стима, встроенных скриншотов и чатов. А простому обывателю всё это нужно) Поэтому для стима у меня отдельная версия классики в формате vdf. И поэтому неофициальное обновление для стима у меня тоже в формате vdf. Всё это позволяет пользоваться ими, не требуя стартера. Но при этом запускаемая игра может быть или только оригинальной, или только классической, или только с неофициальным обновлением: в зависимости от того, какие файлы vdf сейчас в папке Data.
А у тебя возможностей больше, потому что к стиму и его функциям ты не привязан. Можешь свободно использовать стартер и ставить любые моды. Но тогда нужно отказываться от vdf файлов, которые затрагивают весь контент игры. А это буквально один клик при установке.
При этом такой проблемы нет с Г1, потому что как раз там из стима запускается стартер модов. И обыватель там сразу видит оригинал и мод-фикс, из которых может выбирать без каких-либо манипуляций.

**Comment by Kor-Angar** [comment]
вот твой стим факс скачивают люди. часть его запускают через стартер, часть его запускают через стим. статистики ты не знаешь, её у тебя нет, потому что ты её не собираешь. Далее у тебя появляется тот самый сферический конь под названием  "простой обыватель" и вырисовывается целая концепция работы с ним и ради него. Вопрос, а вот непростой обыватель, а ирок который игру запускает через стартер с ним что? почему нельзя добавить оригинальную Готику 2 НВ  в качестве мода, что бы его можно запускать через стартер. 

- повредить ли как нибудь это "простой пользователь"? нет.
- поможет ли это как то "непростой пользователь"? да.
- станет ли Стим Фикс лучше? да.

> А у тебя возможностей больше, потому что к стиму и его функциям ты не привязан.

не только у меня. вот у  меня есть человек 50 с которыми я общаюсь во вконтактике. вот у них всех стим версия и они все запускают игру через стартер. если ты говоришь про массы людей, то надо обратную связь статистическую получают не через форум. на форуме будет 50 человек, в ВК 1000 человек. Выборка будет больше, картинка реальнее.

**Comment by dosinabox** [comment]
> почему нельзя добавить оригинальную Готику 2 НВ в качестве мода, что бы его можно запускать через стартер.

Потому что с ним будут конфликтовать vdf файлы, которые нужны игрокам без стартера.
Попробую собрать свой кастомный стартер, специально под стим. Хорошо, что Нико "NicoDE" Бендлин выкладывал его исходники в общий доступ. И плохо, что я не знаю Си.

**Comment by Kor-Angar** [comment]
> Потому что с ним будут конфликтовать vdf файлы, которые нужны игрокам без стартера.

каким образом? ты же под них сделаешь файл ini
вот у тебя файл ini для Готики 2 НВ, там ты указываешь файл скриптов.mod ну и вроде всё. мир у тебя идёт общий, текстуры общие, что то там ещё общие.

> Попробую собрать свой кастомный стартер, специально под стим. Хорошо, что Нико "NicoDE" Бендлин выкладывал его исходники в общий доступ. И плохо, что я не знаю Си.

мне кажется ты усложняешь некоторые процессы, пытаясь сделать как правильно по ГОСТу, которого просто нет.

**Comment by Kor-Angar** [comment]
у тебя какой список vdf файлов получается после установки _Gothic 2 Steam Fix_?

**Comment by Kor-Angar** [comment]
а почему у меня при запуске через стим запускается стартер? 
![image](https://user-images.githubusercontent.com/49514764/86476606-89315880-bd4f-11ea-801b-c8c10a0d802b.png)

**Comment by Kor-Angar** [comment]
ага.. всё вспомнил. в прошлом году делал:

- файл Gothic2 переименовал в Gothic2_steam_de
- файл GothicStarter переименовал в Gothic2

**Comment by Kor-Angar** [comment]
и это заметьте,  без знания c++ ;-)

**Comment by Kor-Angar** [comment]
знаешь, а это вся дискуссия она не конструктивная. в ней смысла по большому счёту нет. есть такой Gothic 2 Steam Fix ну и как говорится  и замечательно. кому то он не подходит, ну такое бывает. всё же конечном итоге разные и что то универсальное сделать всё равно не получится.

**Comment by dosinabox** [comment]
> а почему у меня при запуске через стим запускается стартер?

Разве он полноценно работает? Одного переименования мало:
<img width="397" alt="Screenshot_1" src="https://user-images.githubusercontent.com/39790055/86482076-e0d4c180-bd59-11ea-913a-62fad0fa429a.png">

А иначе я бы уже давно так сделала)

**Comment by Kor-Angar** [comment]
переустановил и у меня стал тоже выдавать ошибку. видимо у меня был неоригинальный стартер :) не помню как я делал, т.к. это было больше года назад.

**Comment by dosinabox** [comment]
В общем, вчера удалось собрать собственный стартер. Теперь всё будет как надо)

**Comment by Kor-Angar** [comment]
https://github.com/dosinabox/g2_steam_fix/issues/1
