### ISSUE TITLE
Герой будет НПС

### ISSUE THREAD

**Issue by Kor-Angar** [dosinabox/g2nr_unofficial_update#228]
играл в Готику 1 мод фикс и там была отдельная фраза когда герой "будил" НПС  который спит в кровати. не встречала такое?

**Comment by Kor-Angar** [comment]
а реплики героя нет?

**Comment by dosinabox** [comment]
Если ты про "Проснись", то нет. Это снежки так перевели "Пробудись" (приветствие сектантов).
