### ISSUE TITLE
Барток / VLK_440_Bartok

### ISSUE THREAD

**Issue by Kor-Angar** [dosinabox/g2nr_unofficial_update#229]
Никак не могу понять почему у Бартока пропал лук. вроде всегда у него был, а тут стрелы воруется, а лука нет. пропадает при избиение? :-)

Барток вооружен Мачете 100 / 90 / 3. Я теперь с мачетом этим играю и скажу что это очень круто для Бартока. Получает что у него самое крутое оружие в городе. Предлагаю подумать над тем что бы дать ему старое Мачете  60 / 60 / 2. 

-- | -- | -- | --
60 | 70 | 60 | +2
100 | 75 | 90 | +3

Что в результате получится
- Старое Мачете вполне играбельно и его можно будет использовать в первой/второй главе, если отобрать у Бартока или снять с его трупа. В оригинальной игре старое мачете можно купить только в Ярике, а к тому времени оно уже не нужно.
- у Бартока не будет супероружия по с равнению с другими НПС, в т.ч. Паладинами
- у Бартока не будет сверх высокий ущерб, но при этом ущерб будет  достаточный высокий
- обычное мачете герой так же будет иметь возможность получить в первой главе купив его у Мартина(оно есть в продаже).

**Comment by dosinabox** [comment]
Лука нет, потому что по словам Боспера Барток забил на охоту. Зачем ему таскать лук, если он бухает на площади и не ходит на охоту?
Мачете - принято.

**Comment by Kor-Angar** [comment]
Так все же НПС лук тоскают. И Ярвис сидит в таверне с луком и Сильвио. И Волк на ловачке.

Сейчас пропала возможность у Бартока отобрать лук. У него его нет и в инвентаре.

**Comment by dosinabox** [comment]
Он ещё и в городскую одежду одет и переодевается в кожаные доспехи на время охоты. Лук с городской одеждой не смотрится)

**Comment by dosinabox** [comment]
Мачете заменено на старое мечете.

**Comment by Kor-Angar** [comment]
> Он ещё и в городскую одежду одет и переодевается в кожаные доспехи на время охоты. Лук с городской одеждой не смотрится)

тогда и Каваларону надо убирать лук в городе?

**Comment by dosinabox** [comment]
Можно убрать. Если после города он уже никуда не уходит.
