### ISSUE TITLE
Охранник на складе

### ISSUE THREAD

**Issue by Kor-Angar** [dosinabox/g2nr_unofficial_update#230]
Может охраннику на складе добавить арбалет, что бы нельзя его было безнаказанно расстрелять залазя на  ящики?

**Comment by dosinabox** [comment]
Это не гарантирует, что он будет им пользоваться) Места там мало и он скорее просто опять попрет в рукопашную.

**Comment by Kor-Angar** [comment]
> Это не гарантирует, что он будет им пользоваться) Места там мало и он скорее просто опять попрет в рукопашную.

жаль. кстати а когда НПС имеют и лук и оружие при погони за ГГ нельзя сделать что бы в тот момент когда они останавливались и кричали "эй трус" они в догонку в сторону ГГ постреляли ещё из лука?

**Comment by dosinabox** [comment]
Думаю, нет. Или крайне сложно.
