### ISSUE TITLE
Сентенза воровоство

### ISSUE THREAD

**Issue by Kor-Angar** [dosinabox/g2nr_unofficial_update#231]
у Сентензы пропадает опция воровства если у него спросить "как дела"

**Comment by Kor-Angar** [comment]
![image](https://user-images.githubusercontent.com/49514764/76163485-89319b00-6157-11ea-8fc8-c646df37c285.png)

**Comment by dosinabox** [comment]
Не вижу никакой связи между этими диалогами в скриптах. Запиши видео.

**Comment by Kor-Angar** [comment]
видимо не из-за этого глючит. вот тут пропадает
https://youtu.be/LLlfFK4l_eU?t=5758

**Comment by dosinabox** [comment]
совершенно непонятно

**Comment by Kor-Angar** [comment]
Видимо просто пропадает тот предмет что ворует герой.

**Comment by UnresolvedExternal** [comment]
"ITFO_APPLE:1,ITFO_BOOZE:2,ITFO_SAUSAGE:1,ITPL_HEALTH_HERB_01:1,ITMI_GOLDRING:1"
Движок в этой строке, пытаясь найти "ITMI_GOLD", находит "ITMI_GOLDRING". Удаляет подстроку "ITMI_GOLDRING:1", а вместо нее вставляет в инвентарь воб золотой монеты.

Таким образом, золотое кольцо заменяется на золотую монету и украсть его становится нельзя.

**Comment by dosinabox** [comment]
Интересно. А где это такой перебор и замена?

**Comment by Kor-Angar** [comment]
> Движок в этой строке, пытаясь найти

это не Движок. Это Сентенза пытается заныкать колечко :-))

**Comment by dosinabox** [comment]
Это так работает проверка Npc_HasItems?

**Comment by UnresolvedExternal** [comment]
> Это так работает проверка Npc_HasItems?

Ну, тут более глубокий баг в движке. Но да, он может быть спровоцирован этой функцией. Как и любой другой, которой потребуется у себя внутри узнать количество предметов в инвентаре. Баг редкий, так как надо чтобы имена предметов одинаково начинались и совпадающий предмет должен быть в конце списка. В качестве костыля. попробуй кольцо добавлять раньше других предметов.

**Comment by dosinabox** [comment]
Большое спасибо, но изменение порядка добавления не помогло, кольцо всё равно превращается в монету при загрузке сохранения. Лучше сменить это кольцо на что-то другое. И надо иметь в виду на будущее.

Интересный факт. У Сентензы есть неиспользуемый распорядок дня следования за ГГ:
```
func void Rtn_Follow_814()
{
	TA_Follow_Player(8,0,22,0,"NW_BIGFARM_VORPOSTEN1_02");
	TA_Follow_Player(22,0,8,0,"NW_BIGFARM_VORPOSTEN1_02");
};
```

**Comment by dosinabox** [comment]
Получается, что в качестве замены не подходят золотой подсвечник (**ItMi_Gold**CandleHolder), золотое ожерелье (**ItMi_Gold**Necklace), золотая тарелка (**ItMi_Gold**Plate и неиспользуемая **ItMi_Gold**Plate_MIS), золотой кубок (**ItMi_Gold**Cup), золотая чаша (**ItMi_Gold**Chalice) и шкатулка (**ItMi_Gold**Chest).

**Comment by Kor-Angar** [comment]
Это не через него Сентенща очень долго приследует героя?

**Comment by dosinabox** [comment]
нет

**Comment by dosinabox** [comment]
пока заменено на серебряное кольцо, проблемы больше нет

**Comment by Kor-Angar** [comment]
Так он же ничего не стоит 😀 в оригинале  у Сентензы сколько золото воровалась? Давайте что нибудь полезное лучше поставим, например Экстракт жизни или  3 болотной травы или 3 яблока 😀

**Comment by dosinabox** [comment]
> в оригинале  у Сентензы сколько золото воровалась?

65
