### ISSUE TITLE
Булко диалог про Пепе

### ISSUE THREAD

**Issue by Kor-Angar** [dosinabox/g2nr_unofficial_update#232]
После избиения булко если сказать "я НЕ собираюсь уходить" пропадёт диалог про Пепе

![image](https://user-images.githubusercontent.com/49514764/76163507-b8480c80-6157-11ea-8937-b2da807c9b9a.png)

https://youtu.be/LLlfFK4l_eU?t=6247

**Comment by dosinabox** [comment]
Это происходит только если сначала избить Буллко:
```
func void B_WontLeave()
{
	AI_Output(other,self,"DIA_Bullco_WontLeave_15_00");	//Я НЕ СОБИРАЮСЬ уходить отсюда!
	if(self.aivar[AIV_DefeatedByPlayer] == FALSE)
	{
		AI_Output(self,other,"DIA_Bullco_WontLeave_06_01");	//(вздыхает) Похоже, нам придется обсудить этот вопрос опять.
		AI_StopProcessInfos(self);
		B_Attack(self,other,AR_NONE,1);
	}
	else
	{
		AI_Output(self,other,"DIA_Bullco_WontLeave_06_02");	//(ворчливо) Да, да, иди, расскажи это кому-нибудь, кому это интересно.
		Bullco_scharf = FALSE;
		AI_StopProcessInfos(self);
	};
};
```
В таком случае диалог про Пепе становится не нужен, поскольку угроза от Буллко уже миновала. 

Пояснение:
Оба этих диалога доступны только когда ГГ получил угрозу от Буллко (Bullco_scharf == TRUE):
```
func void DIA_Bullco_PleaseLeave_Info()
{
	AI_Output(self,other,"DIA_Bullco_PleaseLeave_06_00");	//Нам нужно поговорить. Тебе и мне.
	AI_Output(other,self,"DIA_Bullco_PleaseLeave_15_01");	//Что тебе нужно?
	AI_Output(self,other,"DIA_Bullco_PleaseLeave_06_02");	//Я думаю, будет лучше для всех, если твоя физиономия больше не будет маячить на этой ферме.
	AI_Output(self,other,"DIA_Bullco_PleaseLeave_06_03");	//Чтобы завтра утром тебя здесь не было. Мы поняли друг друга?
	Bullco_Leave_Day = B_GetDayPlus();
	Bullco_scharf = TRUE;
	AI_StopProcessInfos(self);
	Npc_ExchangeRoutine(self,"PEE");
};
```
и делают одно и то же - отменяют эту угрозу (Bullco_scharf = FALSE):
```
func void B_AboutPepe()
{
	AI_Output(other,self,"DIA_Bullco_PepesSchafe_15_00");	//Тебе имя Пепе говорит о чем-нибудь?
	AI_Output(self,other,"DIA_Bullco_PepesSchafe_06_01");	//Я абсолютно не понимаю, о чем ты говоришь, но твой тон мне не нравится!
	AI_Output(other,self,"DIA_Bullco_PepesSchafe_15_02");	//Ты должен был охранять овец.
	AI_Output(self,other,"DIA_Bullco_PepesSchafe_06_03");	//Какое мне дело до овец?
	AI_Output(other,self,"DIA_Bullco_PepesSchafe_15_04");	//До них есть дело Ли.
	AI_Output(self,other,"DIA_Bullco_PepesSchafe_06_05");	//На что ты намекаешь?
	AI_Output(other,self,"DIA_Bullco_PepesSchafe_15_06");	//Если ты продолжишь действовать мне на нервы, я позабочусь, чтобы тебе пришлось заплатить за овец.
	AI_Output(other,self,"DIA_Bullco_PepesSchafe_15_07");	//Так что если тебя волнует твое жалование, оставь меня в покое!
	AI_Output(self,other,"DIA_Bullco_PepesSchafe_06_08");	//(в ярости) Ты, ты...
	AI_Output(other,self,"DIA_Bullco_PepesSchafe_15_09");	//(спокойно) Да?
	AI_Output(self,other,"DIA_Bullco_PepesSchafe_06_10");	//(себе под нос) Мерзкий коварный ублюдок...
	Bullco_scharf = FALSE;
	B_GivePlayerXP(XP_Ambient);
	AI_StopProcessInfos(self);
};
```
Получается два варианта решения проблемы: силовой и мирный.

**Comment by Kor-Angar** [comment]
Напоминает диалог что Бронко. Там можно или от тырить его или пригрозить Наемниками.

**Comment by Kor-Angar** [comment]
по идеи диалог про Пепе должен быть доступен в определённый момент для выполнения конкретной задачи(не получить люлей от Булко). По сути мы его просто перенесли на более подходящий момент(за мгновение до того как Булко достанет оружие ).

Соответственно старый диалог DIA_Bullco_PepesSchafe можно просто закомментировать.

**Comment by dosinabox** [comment]
Не нужно - этот вариант остается для тех, кто не избил Буллко. Возможность сказать о Пепе доступна и за мгновение до атаки, и в обычном диалоге.

**Comment by dosinabox** [comment]
Следует отметить, что мирное решение через Пепе приносит опыт, а силовое через драку - нет)

**Comment by Kor-Angar** [comment]
> Следует отметить, что мирное решение через Пепе приносит опыт, а силовое через драку - нет)

оно тоже приносит опыт. 400 ;-) просто авторы не думали что Готику заиграют додыр и будут  пытаться выжить максимально возможный опыт из игры. Сначало поговорить, а потом еще и избить :-)

**Comment by Kor-Angar** [comment]
тогда надо убрать возможность сказать про Пепе, если герой уже избил Булко.
