### ISSUE TITLE
Получение акробатики при молитве

### ISSUE THREAD

**Issue by Kor-Angar** [dosinabox/g2nr_unofficial_update#233]
При получения бонуса +1 к ловкости и изучения акробатики во время молитвы герой без анимации переходит из состояния "молитва" в "стоять".  Наверное ты это заметила

**Comment by dosinabox** [comment]
Знаю, особенность оверлеев анимации. То же самое может произойти, когда у ГГ закончится состояние опьянения. Пока с этим ничего сделать нельзя.

**Comment by Kor-Angar** [comment]
Ясно21:11, 9 марта 2020 г., dosinabox <notifications@github.com>:Знаю, особенность оверлеев анимации. То же самое может произойти, когда у ГГ закончится состояние опьянения. Пока с этим ничего сделать нельзя.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
-- Отправлено из мобильного приложения Яндекс.Почты
