### ISSUE TITLE
Продажа отмычек

### ISSUE THREAD

**Issue by Kor-Angar** [dosinabox/g2nr_unofficial_update#235]
Предлагаю подумать и добавить кому то в продажу отмычке на ферме Онара. Например Сайферу

**Comment by dosinabox** [comment]
сколько?

**Comment by Kor-Angar** [comment]
давай столько же сколько и Торбену там же у него по главам идёт?

**Comment by dosinabox** [comment]
У Торбена каждую главу по 12 отмычек, но если добавлять столько же Сиферу, то будет как-то слишком много для общего игрового баланса.

**Comment by Kor-Angar** [comment]
а как кол-во отмычек может повлиять на обще игровой баланс? :-) я их к примеру продаю. и по моему даже не покупаю.

Вопрос в том где их можно купить / найти. Вот есть локация на ферме там их купить нельзя. а в городе можно. в 3 глава когда появляются телепорты это становится уже не существенно. в 1 -2 главе отмычки могут закончится в районе фермы и прийдётся за ними двигаться в город.

**Comment by dosinabox** [comment]
> в 1 -2 главе отмычки могут закончится в районе фермы и прийдётся за ними двигаться в город.

Вот я про это) Неудобства и поиск ресурсов - тоже часть игры и отчасти баланс. И обычно удовлетворение потребности в ресурсах приносит удовольствие. И если дать игроку слишком много отмычек, то такого удовольствия он будет лишен.

Поэтому я добавлю Сиферу 6 отмычек в первой главе и 6 отмычек во второй.

**Comment by Kor-Angar** [comment]
Ты их можешь перераспределить. Или сделать к ним доступ так же через "знак вора".

**Comment by Kor-Angar** [comment]
а у пирата Гаретта отмычки в продаже не повявляются? 
![20210116051548_1](https://user-images.githubusercontent.com/49514764/104799476-7b6d8d00-57e0-11eb-8ce1-e3f1f17da759.jpg)

**Comment by dosinabox** [comment]
Добавлялись Сэмюэлю

**Comment by Kor-Angar** [comment]
Вилмо мало 😀12:26, 16 января 2021 г., dosinabox <notifications@github.com>:
Добавлялись Сэмюэлю

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
-- Отправлено из мобильного приложения Яндекс.Почты

**Comment by Kor-Angar** [comment]
уже говорили про отмычки. отмычки пираты продают в том числе бандитам. пока до бандитов герой не дошёл приходится бегать в Хоринис(если ловкость низкая то отмычки ломаются) за отмычками. у Сэмюэля выкупал, но у него было немного, вроде 7.
