### ISSUE TITLE
Лотар: диалог про то что Лотар был у Хагена

### ISSUE THREAD

**Issue by Kor-Angar** [dosinabox/g2nr_unofficial_update#236]
бывает что после разговора с героем Лотар тут же говорит что он был у Хагена. хотя он стоял на месте и никуда не ходил :-)

**Comment by dosinabox** [comment]
Не тут же, а только после диалогов DIA_Lothar_MESSAGE или DIA_Lothar_Hagen, после которых должен пройти минимум один день. За этот день он вполне может сходить в ратушу.

```
func int DIA_Lothar_Reported_Condition()
{
	if((Npc_KnowsInfo(other,DIA_Lothar_MESSAGE) || Npc_KnowsInfo(other,DIA_Lothar_Hagen)) && (LordHagen.aivar[AIV_TalkedToPlayer] == FALSE))
	{
		if(Lothar_Day < Wld_GetDay())
		{
			return TRUE;
		};
	};
};

func void DIA_Lothar_Reported_Info()
{
	AI_Output(self,other,"DIA_Lothar_Add_01_48");	//Я доложил лорду Хагену, что ты желаешь поговорить с ним...
	AI_Output(other,self,"DIA_Lothar_Add_15_49");	//И? Что он сказал?
	AI_Output(self,other,"DIA_Lothar_Add_01_50");	//Он никогда не слышал о тебе.
	if(Player_TalkedAboutDragons == TRUE)
	{
		AI_Output(other,self,"DIA_Lothar_Add_15_51");	//Конечно нет. Ты сказал ему о драконах?
		AI_Output(self,other,"DIA_Lothar_Add_01_52");	//Разве я не говорил тебе, чтобы ты прекратил нести этот вздор?!
	};
	AI_StopProcessInfos(self);
};
```

**Comment by dosinabox** [comment]
В крайнем случае может пройти два часа и одна минута игрового времени:
```
Lothar_Day = Wld_GetDay();
if(Wld_IsTime(22,0,23,59))
{
	Lothar_Day += 1;
};
```

**Comment by Kor-Angar** [comment]
https://youtu.be/LLlfFK4l_eU?t=8891

**Comment by Kor-Angar** [comment]
наверное надо  попробовать склеить два диалога что бы не было такой истории

**Comment by Kor-Angar** [comment]
или добавить на **DIA_Lothar_Reported** условие  (other.guild == GIL_NONE) || (other.guild == GIL_NOV)

судя по  **DIA_Lothar_Hagen_Info**  этот диалог предназначается как раз нейтралу и послушнику

**Comment by dosinabox** [comment]
понятно, там два important диалога доступны одновременно, сейчас поправлю

**Comment by dosinabox** [comment]
исправлено
