### ISSUE TITLE
Големы в пещере с ползунами

### ISSUE THREAD

**Issue by Kor-Angar** [dosinabox/g2nr_unofficial_update#238]
Стрелял по ползунам, попал в "труп" голема. Голем ожил и убил. по моему эту тему мы уже подымали:-)

**Comment by dosinabox** [comment]
на уровне скриптов с этим ничего не сделать

**Comment by Kor-Angar** [comment]
вот в этой версии они не оживали и их нельзя было убить(и получить опыт) до того как не откроется сундук. просто срабатывала анимация при ударе по ним, но не более того.
[G2_Classic-1.1.zip](https://github.com/dosinabox/g2nr_unofficial_update/files/4311337/G2_Classic-1.1.zip)

сейчас же они  не представляют серъёзной опасности, так как убиваются по одному, до того как они "включатся"

**Comment by Kor-Angar** [comment]
на мёртвых големов агрятся вызванные гоблины скелеты

https://www.twitch.tv/videos/571802462

**Comment by dosinabox** [comment]
Плагин для Union с исправлением флага noFocus:
[UNION_NOFOCUSFIX.zip](https://github.com/dosinabox/g2nr_unofficial_update/files/4753317/UNION_NOFOCUSFIX.zip)
