### ISSUE TITLE
Тяжелые доспехи ополчения в Хоринисе

### ISSUE THREAD

**Issue by dosinabox** [dosinabox/g2nr_unofficial_update#24]
Продумать условия и требования покупки тяжелых доспехов ополчения у Пека в Хоринисе.
Заготовка диалога создана в 22 версии, в релизе 23 версии не потребуется начало новой игры:
```
instance DIA_Peck_ARMOR(C_Info)
{
	npc = MIL_324_Peck;
	nr = 3;
	condition = DIA_Peck_ARMOR_Condition;
	information = DIA_Peck_ARMOR_Info;
	permanent = TRUE;
	description = "А как насчет доспехов получше?";
};
```

Текущие предложения:

1) Продавать доспехи в Хоринисе с изначальной ценой 4500 (против 2500 в Минентале).

2) Начинать продажу доспехов:
- если ГГ вернулся из Миненталя и передал лорду Хагену письмо от Гаронда
- если ГГ вернулся из Яркендара и сообщил лорду Андрэ об освобождении всех рабов

3) Запрещать продажу доспехов:
- если на ГГ висят неоплаченные штрафы за любое преступление в городе

4) Снижать цену доспехов:
- за посадку Ренгару (-100)
- за посадку Халвора (-100)
- за посадку Нагура (-100)
- за посадку Кантара/Сары (-100)
- за посадку Фернандо (-100)
- за рекомендательное письмо Мартина (-100)
- за все квесты ополченца (-500)
- за наводку на местоположение гильдии воров (-500)
- за уничтожение гильдии воров (-1000)

5) Повышать цену доспехов:
- за кляузу на Пека (+500)

**Comment by dosinabox** [comment]
Заготовка диалога создана в 22 версии, в релизе 23 версии не потребуется начало новой игры.

**Comment by Kor-Angar** [comment]
цена у доспехов будет статичная или будет меняться?

**Comment by dosinabox** [comment]
Цена покупки может меняться (как у Хуно от скидок Фиска). Цена продажи всегда статичная.

**Comment by Kor-Angar** [comment]
ну и какой ты разброс в цене хочешь сделать?

**Comment by dosinabox** [comment]
> ну и какой ты разброс в цене хочешь сделать?

Это не главное, можно и без снижения. Сначала нужно продумать условия доступности.

**Comment by dosinabox** [comment]
> Сначала нужно продумать условия доступности.

Есть идеи?

**Comment by Kor-Angar** [comment]
> Есть идеи?

с точки зрения логики это просто вторая глава, т.е. после того как герой получил задание от Лорда Хагена.

изначальную цену лучше сделать завышенную, а за квесты уже снижать. т.е. изначально что бы она была  выше чем в Минентале. например 3000 или 3500.

*******
в какой то переписке мы обсуждали за что теоретически можно её снизить.например

- квест про тюк - 100 золотых
- квест про траву - 100 золотых
- квест про полевых жуков - 100 золотых
- посадка Ренгару - 100
- посадка Халвор - 100
- посадка Нагур - 100
- посадка Кантар / Сара - 100
- ликвидация гильдия воров - 500 золотых

думаю что для среднестатического игрока который не задался целью ликвидировать преступность цена доспехов в Хориносе всё равно будет выше чем в Минентале.

**Comment by dosinabox** [comment]
> с точки зрения логики это просто вторая глава, т.е. после того как герой получил задание от Лорда Хагена.

Не соглашусь. Просто по факту начала второй главы продавать их будет странно, потому что ГГ-ополченец мог ничего не сделать к этому времени (ещё не заслужил).

Мои идеи.

1) Продавать доспехи в Хоринисе с изначальной ценой 4000 (против 2500 в Минентале).

2) Начинать продажу доспехов:
- если ГГ выполнил все квесты ополченца (тюк, трава, жуки)
- если ГГ уничтожил гильдию воров
- если ГГ принес Хагену письмо Гаронда

3) Снижать цену доспехов:
- за посадку всех возможных преступников (-500)
- за все квесты ополченца (-500)
- за уничтожение гильдии воров (-1000)

Итог: ленивый или невнимательный игрок сможет купить доспехи только после Миненталя и по завышенной цене, а прилежный - до Миненталя и значительно дешевле.

**Comment by Kor-Angar** [comment]
я же пишу про логику сюжета:
Лорд Хаген отправил ополченца в долину рудников. Ополченец должен быть укомплектован. с точки зрения  логики сюжета это нормально. с точки зрения баланса это может быть "жирно".

то что ополченец вместо выполнения суперважного задания Лорда Хагена бегает по канализации и разбирается с жуками что бы "заслужить" доспехи это с точки зрения логики сюжета неправильно. а с точки зрения баланса "норм".

вот каждая правка которая происходит должна взвешиваться и с точки зрения баланса и с точки зрения сюжета. а если её не получается вписать в происходящее, то может и не стоит её вводить.

представь себе Лорда Андре.. что он там постоянно говорит герою? :-)
```
func void B_ReportToHagenNow()
{
	AI_Output(self,other,"DIA_Andre_PERM_08_03");	//С этого времени ты должен докладывать непосредственно лорду Хагену. Иди, поговори с ним.
};
```
хоть у кого то в игре есть понимание субординации :-)

*******

> И ещё: нужно ли запрещать Пеку продавать доспехи ГГ, который сдал его Андрэ? Или это не в его "юрисдикции", скажем так?

тут нужно понимать кто принимает решения. Пек принимает решения? или Лорд Андре? на основание чего Пек может послать героя? и может ли он его вообще послать? подкозлить конечно может. и он козлит. а вот просто послать, это наврятли. 

*********
> Итог: ленивый или невнимательный игрок сможет купить доспехи только после Миненталя и по завышенной цене, а прилежный - до Миненталя и значительно дешевле.

что то  я не понял.. а что мне мешает их купить в Минентале?

**Comment by dosinabox** [comment]
> хоть у кого то в игре есть понимание субординации :-)

Такие реплики - для ГГ-паладина)

> подкозлить конечно может. и он козлит.

О. Может, тогда просто повышать цену?

> что то я не понял.. а что мне мешает их купить в Минентале?

Ничего) У обсуждаемого изменения два назначения:
- позволять купить доспехи раньше положенного **за заслуги**, а чтобы это не слишком влияло на баланс, заслуги должны быть достаточно серьезными
- не заставлять ГГ бегать в Миненталь за доспехами в третьей главе, если он забыл или не смог купить их раньше

**Comment by dosinabox** [comment]
> Ополченец должен быть укомплектован. с точки зрения логики сюжета это нормально. с точки зрения баланса это может быть "жирно".

Но, насколько я знаю, на халяву ему ничего не выдается. Можно начинать продажу доспехов со второй главы - прямо перед походом. Типа Хаген распорядился продавать их ГГ вне очереди. Но в таком случае цена должна быть максимальной - для баланса. Покупать - покупай, но если заслуг нет, то по большой цене.

**Comment by Kor-Angar** [comment]
> О. Может, тогда просто повышать цену?

конечною повышай. можно кстати за хорошее отношение Пека подогнать доспех+пояс

> позволять купить доспехи раньше положенного за заслуги

при твоих условиях я куплю в Минентале их раньше и дешевле чем в Хориносе ;-) 

> не заставлять ГГ бегать в Миненталь за доспехами в третьей главе, если он забыл или не смог купить их раньше

в третей главе герой приходит ва Хоринос, выполняет квест про Беннета и становится Паладином, получая доспехи Паладина бесплатно.

> Но, насколько я знаю, на халяву ему ничего не выдается. Можно начинать продажу доспехов со второй главы - прямо перед походом. Типа Хаген распорядился продавать их ГГ вне очереди. Но в таком случае цена должна быть максимальной - для баланса. Покупать - покупай, но если заслуг нет, то по большой цене.

ну как бы я про то и говорю. Ополченец идёт на задание вот доспех - покупай. если проявил себя то вот скидка. не хочешь не покупай :-)

> хоть у кого то в игре есть понимание субординации :-)
> Такие реплики - для ГГ-паладина)
так и я о том. Лорд Андре разбирается в вопросах субординации :-)

**Comment by Kor-Angar** [comment]
только мне кажется такую возможность надо делать опциональной

**Comment by dosinabox** [comment]
Подытожим.

1) Продавать доспехи в Хоринисе с изначальной ценой 4000 (против 2500 в Минентале).

2) Начинать продажу доспехов:
- если ГГ выполнил все квесты ополченца (тюк, трава, жуки)
- если ГГ уничтожил гильдию воров
- если ГГ получил миссию от Хагена

3) Снижать цену доспехов:
- за посадку всех возможных преступников (-500)
- за все квесты ополченца (-500)
- за уничтожение гильдии воров (-1000)

4) Повышать цену доспехов:
- за кляузу на Пека (+500)

**Comment by Kor-Angar** [comment]
> если ГГ выполнил все квесты ополченца (тюк, трава, жуки)

лишние условие, так как это будет 2 глава, а сначала второй главы срабатывает условие
"если ГГ получил миссию от Хагена" ;-)

**Comment by Kor-Angar** [comment]
> за посадку всех возможных преступников (-500)

давай распишем:
- посадка Ренгару
- посадка Халвор
- посадка Нагур 
- посадка Кантар / Сара 

еще кто то есть?

может лучше по факту отнимать по 100 золотых?

**Comment by Kor-Angar** [comment]
если ГГ уничтожил гильдию воровТ. Е. в первой главе? 😀

**Comment by dosinabox** [comment]
> если ГГ уничтожил гильдию воровТ. Е. в первой главе? 😀

Ну да. А что, жирновато? Между вступлением в ополчение и началом второй главы могут пройти считанные минуты - буквально пройти от казарм до ратуши. Так что не думаю, что жирновато)

**Comment by dosinabox** [comment]
Вступает и сразу может купить доспех за 3000 (4000 - 1000).

**Comment by Kor-Angar** [comment]
давай конечную версию добавим в первый пост. и было бы не плохо реплику у Андре найти про доспех;-)

**Comment by dosinabox** [comment]
> лишние условие, так как это будет 2 глава, а сначала второй главы срабатывает условие
> "если ГГ получил миссию от Хагена" ;-)

Не совсем. Это можно сделать и в первой главе (как и уничтожить гильдию воров). Не вижу ничего плохого в тяжелых доспехах в первой главе после вступления в ополчение.

**Comment by dosinabox** [comment]
> может лучше по факту отнимать по 100 золотых?

Нет, потому что игрок получает деньги за каждого преступника. Нужна награда "за всех" (Ренгару, Халвор, Нагур, Кантар/Сара).

**Comment by dosinabox** [comment]
Можно сообщить Андрэ о том, что гильдия воров находится в канализации, но никого из них не убивать. За это тоже нужно снижать цену.

- сообщение о местоположении (-500) + позже сообщение о ликвидации (-500)
- сообщение о ликвидации, включающее сообщение о местоположении (-1000)

То есть:
- находим, сообщаем, не убиваем, позже ополчение зачищает канализацию (-500)
- находим, сообщаем, позже убиваем, сообщаем (-1000)
- находим, сразу убиваем, сообщаем (-1000)

**Comment by Kor-Angar** [comment]
Но в готике всегда был диффиринцированный подход. Не факт что получится выгрести прям всех. Тем более в начале второй главы. Опять же герой кого то может бонально убить. На пример того же вызова Ярвеса, нодо оттырить трех человек, а можно и 4 и 5.А так получается что я квест про Кантара или не возьму или Сару убью и из-за этого не получу скидку на доспех, хотя при этом у Андре буду на хорошем счету.

**Comment by Kor-Angar** [comment]
Разве на квест про Жуков не стоит ограничение на 2 главу?

**Comment by dosinabox** [comment]
> Разве на квест про Жуков не стоит ограничение на 2 главу?

нет

**Comment by dosinabox** [comment]
> Но в готике всегда был диффиринцированный подход. Не факт что получится выгрести прям всех. Тем более в начале второй главы. Опять же герой кого то может бонально убить. На пример того же вызова Ярвеса, нодо оттырить трех человек, а можно и 4 и 5.А так получается что я квест про Кантара или не возьму или Сару убью и из-за этого не получу скидку на доспех, хотя при этом у Андре буду на хорошем счету.

Тогда, наверное, надо давать скидку за каждого

**Comment by Kor-Angar** [comment]
> за посадку Ренгару (-200)
> за посадку Халвора (-200)
> за посадку Нагура (-200)
> за посадку Кантара/Сары (-200)
> за все квесты ополченца (-500)

Может за людей по 100, а за все квесты 600? Тогда в сумме будет 1000

**Comment by dosinabox** [comment]
окей

**Comment by dosinabox** [comment]
Перечитай первый пост, как тебе сейчас? Если ок, то вечером начну делать.

**Comment by Kor-Angar** [comment]
Есть ещё Мартин и квест про Фернандо. По ЛОРу Фернандо сдаёт Мартиан. Но в принципе Мартин тоже может повлиять на цену.

**Comment by dosinabox** [comment]
окей, посадка Фернандо будет тоже давать скидку -100

**Comment by dosinabox** [comment]
Готово, проверить позже

**Comment by Kor-Angar** [comment]
можно добавить скидку в 500 золотых если Корнелиус в тюрьме :-)

**Comment by Kor-Angar** [comment]
тут такое дело. вчера играл и думал что сегодня куплю доспехи. 
в результате понял, что тяжелые доспехи в ополчения могут быть серьезно повлиять на баланс, так как герой сможет их купить в самом самом начале игры. Тогда такие монстры как волки, падальщики, крысы, шершни, полевые жуки, гоблины просто не будут пробивать героя.

предлагаю еще раз крепко подумать на эту тему. и проверить как это будет отражаться на балансе когда герой 3-5 уровня выходит из города Хоринос в таких доспехах.

**Comment by Kor-Angar** [comment]
в качестве альтернативного варианта можно сделать продажу этих доспехов после вступления в Кольцо Воды через Мартина.

вступление в Кольцо Воды подразумевает выполнения ряда квестов и убийство Декстера.

**Comment by dosinabox** [comment]
Пока что чистая цена повышена с 4000 до 4500. Минимальная возможная цена теперь 1900 вместо 1400.

> герой сможет их купить в самом самом начале игры.

Мы уже обсуждали, что это в любом случае уже вторая глава и ГГ-ополченец может просто сходить в Миненталь и купить их там. Это 10 минут разницы, а в Хоринисе они намного дороже. Теперь будут ещё дороже.

**Comment by Kor-Angar** [comment]
> Мы уже обсуждали, что это в любом случае уже вторая глава и ГГ-ополченец может просто сходить в Миненталь и купить их там. Это 10 минут разницы, а в Хоринисе они намного дороже. Теперь будут ещё дороже.
при нормальной игре это так и есть. 

Но я описал  ситуацию про низкоуровнего героя, который просто пришел в город, сделал быстрое вступление в милицию и тут же перешел во вторую главу. В таком случае он может став помощником кузница просто наковать мечей, продать их и купить крутой доспех. вот тут и есть дисбаланс.

если же низкоуровневый герой пойдет в миненталь, то ему до замка предстоит ещё дойти, там по дороге будут монстры, луркеры и прочее.

т.е. речь не об опытном игроке, а наоборот о неопытном. для него игра значительно будет упрощена.

**Comment by Kor-Angar** [comment]
![image](https://user-images.githubusercontent.com/49514764/71853352-2cc8e580-30ec-11ea-8668-a7b299edc3a5.png)

96 брони через час-полтора-два игры это перебор :-) я про это собственно и писал.

выучил ковку 2+4+6=12 лп в принципе можно было и меньше ЛП вложить, но я решил играть по гайду из интернета :-) 

- посадил несколько человек
- квесты мента не выполнял
- пека сдал
- что бы это компенсировать рассказал про гильдию воров :-)

после того как одел броню сходил за сталью к Онару, что бы купить амулет защиты от оружия (вспомнил что Диего1984 категорически настаивает что его надо одевать сразу).

- 70 броня
- 10 пояс
- 10 амулет
- 6 два кольца по 3
ИТОГО 96

Сейв
https://yadi.sk/d/uPGBXDiHczNBlw

****************



https://www.youtube.com/watch?v=DGY66uj6alE

**Comment by Kor-Angar** [comment]
96 брони через час-полтора-два игры это перебор :-) я про это собственно и писал.

выучил ковку 2+4+6=12 лп в принципе можно было и меньше ЛП вложить, но я решил играть по гайду из интернета :-) 

- посадил несколько человек
- квесты мента не выполнял
- пека сдал
- что бы это компенсировать рассказал про гильдию воров :-)

после того как одел броню сходил за сталью к Онару, что бы купить амулет защиты от оружия (вспомнил что Диего1984 категорически настаивает что его надо одевать сразу).

- 70 броня
- 10 пояс
- 10 амулет
- 6 два кольца по 3
ИТОГО 96

Сейв
https://yadi.sk/d/uPGBXDiHczNBlw

****************

**Comment by dosinabox** [comment]
"Я не знаю что мне делать с этою бедой..."
Можно и правда сделать доспехи доступными только после возвращения из Миненталя или после обнаружения приказов Декстера (Ватрас передал Мартину, чтобы тот замолвил словечко). А за все остальные условия только снижать цену.

**Comment by Kor-Angar** [comment]
> Можно и правда сделать доспехи доступными только после возвращения из Миненталя
вроде как и смысла уже нет, т.к. в Минентале они продаются :-)

у Ingmar есть ещё такой диалог про снаряжение
func void DIA_Ingmar_Hallo_Info()
```
{
	if((EnterOW_Kapitel2 == FALSE) && (LordHagen.aivar[AIV_TalkedToPlayer] == TRUE))
	{
		AI_Output(self,other,"DIA_Ingmar_Hallo_06_00");	//Согласно полученным мной сообщениям, Долина Рудников - опасное место.
		AI_Output(self,other,"DIA_Ingmar_Hallo_06_01");	//Позаботься о своем снаряжении, прежде чем отправляться туда.
	}
	else if((MIS_OLDWORLD == LOG_SUCCESS) && (LordHagen.aivar[AIV_TalkedToPlayer] == TRUE))
	{
		AI_Output(self,other,"DIA_Ingmar_Hallo_06_02");	//Обстановка в Долине Рудников очень тревожит меня. Но мы разработаем план, чтобы преодолеть все опасности и вытащить наших парней оттуда вместе с рудой.
		DIA_Ingmar_Hallo_permanent = TRUE;
	}
	else
	{
		AI_Output(self,other,"DIA_Ingmar_Hallo_06_03");	//Я думал, ты пришел поговорить с лордом Хагеном. Так иди же к нему.
	};
};
```

**Comment by Kor-Angar** [comment]
> "Я не знаю что мне делать с этою бедой..."

надо сформулировать задачу. Какой  ты пытаешься решить вопрос этими доспехами. т.е. для чего ты хочешь их продавать в Хориносе?

**Comment by dosinabox** [comment]
А ещё следует запрещать продажу, пока на ГГ висят штрафы.

> для чего ты хочешь их продавать в Хориносе?

Кажется странным, что их не продают в городе, где куча занятий и возможностей для заслуг, а в осажденном изолированном замке - продают просто по факту.

**Comment by Kor-Angar** [comment]
> Кажется странным, что их не продают в городе, где куча занятий и возможностей для заслуг, а в осажденном изолированном замке - продают просто по факту.

это скорее из области ощущений. из-за этого не стоит трогать баланс игры. 

Ополчение находится на службе у короля. По приказу Лорда Хагена, Лорд Андре принимает в ополчение всех граждан. 
Т.е. ополчение до прибытия Паладинов выполняло роль Милиции и подчинялось губернатору. Когда прибыли Паладины ополчение перешло в прямое подчинение паладинов и начали набираться новые рекруты. 
Отряд Паладинов с ополчением ушёл в Миненталь. С собой они взяли припасы, в т.ч. оружие, магию и доспехи. По большому счёту герой получает возможность купить доспехи в Минентале у Паладинов в рамках работы (службы) на них. 
и вот тут  и есть ответ на "где куча занятий и возможностей для заслуг", т.к. в городе возможности "выслужится" перед Паладинами нет ;-) ну да, можно помочь Лорду Андре утрясти какие то его вопросы.  но эти вопросы, они скорее рабочие. ну есть вопрос по гильдии воров, но и тут стоит отметить что он не принимает героя в ополчения за то что он просто нашёл гильдию воров, нужно её именно ликвидировать. 
у него из диалогов только вот этот значимый
```
	AI_Output(other,self,"DIA_Addon_Andre_ReturnedMissingPeople_15_00");	//Мне удалось спасти часть пропавших людей.
	if(other.guild == GIL_MIL)
	{
		AI_Output(self,other,"DIA_Addon_Andre_ReturnedMissingPeople_08_01");	//А я-то думал, где ты был все это время!
		AI_Output(self,other,"DIA_Addon_Andre_ReturnedMissingPeople_08_02");	//Ты - солдат ополчения! И ты не получал приказа заниматься поисками пропавших!
		AI_Output(other,self,"DIA_Addon_Andre_ReturnedMissingPeople_15_03");	//Но...
	};
	AI_Output(self,other,"DIA_Addon_Andre_ReturnedMissingPeople_08_04");	//Как много людей ты спас?
	AI_Output(other,self,"DIA_Addon_Andre_ReturnedMissingPeople_15_05");	//Всех тех, кто был еще жив...
	AI_Output(self,other,"DIA_Addon_Andre_ReturnedMissingPeople_08_06");	//Всех?! Я... Э-э-э...
	if((other.guild == GIL_MIL) || (other.guild == GIL_PAL))
	{
		AI_Output(self,other,"DIA_Addon_Andre_ReturnedMissingPeople_08_07");	//Я тобой горжусь! И я рад, что принял тебя в наши ряды.
		B_AndreSold();
	};
	AI_Output(self,other,"DIA_Addon_Andre_ReturnedMissingPeople_08_08");	//Ты сделал великое дело!
```
можно например выдавать от Лорда Андре тяжёлые доспехи ополчения бесплатно, за спасение жителей Хориноса. на баланс это ни как не повлияет :-)

***

**Comment by dosinabox** [comment]
- Пек будет продавать доспехи только после передачи приказов Ватрасу или письма Гаронда Хагену
- Пек не будет продавать доспехи, если на ГГ висят неоплаченные штрафы за любое преступление в городе
- Добавлена скидка за рекомендательное письмо Мартина (-100)
- Добавлена скидка за сообщение Андрэ о спасенных людях (-200)

**Comment by Kor-Angar** [comment]
у Пека кстати пропал диалог про доспехи после того как я купил их в Минентале.

**Comment by dosinabox** [comment]
Ну да, правильно. Так и с другими одинаковыми доспехами. Зачем тебе вторые?

**Comment by Kor-Angar** [comment]
У Наемника можно двое сделать. Одни через Ли вторые такие же через Горна.Мне в принципе не надо. Просто обратил внимание и отписался 😀

**Comment by dosinabox** [comment]
> У Наемника можно двое сделать. Одни через Ли вторые такие же через Горна.

Вроде правилось. Посмотрю.

**Comment by dosinabox** [comment]
- Пек будет продавать доспехи только после сообщения Андрэ о спасенных людях или передачи письма Гаронда Хагену
- Отменена скидка за сообщение Андрэ о спасенных людях (-200)

**Comment by Kor-Angar** [comment]
давай первый пост обновим
