### ISSUE TITLE
Орлан / Посох Мага Воды

### ISSUE THREAD

**Issue by Kor-Angar** [dosinabox/g2nr_unofficial_update#240]
у Орлана в 3 главе появился в продаже посох магов воды. а зачем он в третей главе? почему не во 2(после вступления в КВ)? а почему у Орлана, а не у Кроноса?

**Comment by dosinabox** [comment]
Кстати, Орлану можно выдать какой-нибудь хороший новый посох для силовиков/ловкачей, а посох мага Воды перенести Кроносу.

**Comment by Kor-Angar** [comment]
Это как? Новый тип посохов?

**Comment by dosinabox** [comment]
Просто новый посох. Для разнообразия или баланса.

**Comment by Kor-Angar** [comment]
Для этих целей можно задействовать и то оружие что есть в игре. Какой смысл добавлять ещё одно одноружие, когда на гору оружия стоит ограничение на продажи по главам?

**Comment by Kor-Angar** [comment]
> Просто новый посох. Для разнообразия или баланса.

замечательная идея. очень важно что бы было что то новое. ведь это так здорово когда ты пришёл смотришь, а у НПС что то новое в продаже есть. сразу игра становится интереснее. можно посмотреть и что нибудь взять из мода "возвращение" или "ребаланс". там много всякого оружия. а еще можно супер лук сделать из кости дракона который будет стрелять например стрелами смерти, которые с одного выстрела будут убивать паладина, но при этом не носить вреда нежити. а против нежити можно сделать специальные стрелы которые ловкач сделать окунув даэдрическую стрелу в "слёзы инноса" и тогда она будет наносить дополнительный урон по нежити.

**Comment by dosinabox** [comment]
> замечательная идея. очень важно что бы было что то новое. ведь это так здорово когда ты пришёл смотришь, а у НПС что то новое в продаже есть. сразу игра становится интереснее.

Ну что же так) Вот новые молоты зашли. Может и посохами есть какая-то необходимость.

**Comment by Kor-Angar** [comment]
Надо смотреть в сравнение. С учётом ущерба, бонусов, требований к силе. А как сравнивать если большая часть оружия появляется в 3 главе?

**Comment by dosinabox** [comment]
> а зачем он в третей главе? почему не во 2(после вступления в КВ)? а почему у Орлана, а не у Кроноса?

У Орлана он появляется при вступлении ГГ в КВ. У Кроноса в Яркендаре тоже есть.

**Comment by Kor-Angar** [comment]
пока не будет таблицы с оружием из которой будет видно, что и когда у кого появляется ничего не будет ясно. ты одной рукой  даёшь, а другой забираешь. у одних ассортимент полный у других отсутствует.  большинство оружия оказывается не задействовано.

**Comment by dosinabox** [comment]
да, полная картина станет ясна позднее
