### ISSUE TITLE
Опыт за плавающих и падающих врагов

### ISSUE THREAD

**Issue by Kor-Angar** [dosinabox/g2nr_unofficial_update#241]
убивал Шныга в воде и не дали опыт. Глюк?

**Comment by dosinabox** [comment]
Проблема известна. Также можно добавить сюда отсутствие опыта за убийства "кулаком ветра", когда цель погибает от падения.

**Comment by Kor-Angar** [comment]
Раньше такого не было17:01, 18 марта 2020 г., dosinabox <notifications@github.com>:
Проблема известна. Также можно добавить сюда отсутствие опыта за убийства "кулаком ветра", когда цель погибает от падения.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
-- Отправлено из мобильного приложения Яндекс.Почты

**Comment by dosinabox** [comment]
Было даже в Г1, вроде бы.

**Comment by Kor-Angar** [comment]
Сегодня проверю. 17:17, 18 марта 2020 г., dosinabox <notifications@github.com>:
Было даже в Г1, вроде бы.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
-- Отправлено из мобильного приложения Яндекс.Почты

**Comment by Kor-Angar** [comment]
> Также можно добавить сюда отсутствие опыта за убийства "кулаком ветра", когда цель погибает от падения.

а зачем за это давать опыта?

**Comment by Kor-Angar** [comment]
> убивал Шныга в воде и не дали опыт. Глюк?

перепроверил. дают.попытаюсь найти этот момент на стриме

**Comment by Kor-Angar** [comment]
5.45
https://youtu.be/8uOJ2noZoy0?t=340
и
6.30
https://youtu.be/8uOJ2noZoy0?t=389

они провалились что ли? :-)

**Comment by dosinabox** [comment]
> перепроверил. дают.

?

**Comment by Kor-Angar** [comment]
Я игру запустил. И убил из Арбалета Луркера который был в воде. Опыт дали. На видео сострима Луркер куда то девается, то ли умирает и тонит, то ли пропадает.

**Comment by dosinabox** [comment]
животинка или человек должны **плыть**, тогда опыта не будет

**Comment by Kor-Angar** [comment]
Так я проверял когда Луркер плыл 😀

**Comment by Kor-Angar** [comment]
(+) Двойной урон от молнии в воде работает.

**Comment by Kor-Angar** [comment]
(+) Двойной урон от молнии в воде работает. Опыт дают.

Вопрос. От молнии когтя в воде идёт двойной ущерб? :-)

**Comment by dosinabox** [comment]
> Вопрос. От молнии когтя в воде идёт двойной ущерб? :-)

Похоже, нет.

**Comment by dosinabox** [comment]
Про пловцов от Slavemaster:
> Про ZS_Dead в принципе понятно. Когда хп опустилось до нуля и контроллер анимаций решил, что НПЦ уже всё, то дальнейшей обработки уже не просходит. В том числе, не обрабатываются функции состояния. Например, когда NPC уже лежит на земле ZS_DEAD_LOOP не вызывается. В случае с водой, непись сразу в нужную анимацию переводится и там даже не доходит до вызова ZS_Dead. Вставлю принудительный вызов DoAIState, когда персонаж мёртв и дальнейшая обработка движком уже не предполагается.

[zDeadDoAIState.patch](https://worldofplayers.ru/threads/43009)
