### ISSUE TITLE
Сортировка Инвентарь

### ISSUE THREAD

**Issue by Kor-Angar** [dosinabox/g2nr_unofficial_update#242]
Напомни пожалуйста , а где настраивается сортировка в инвентаре что за чем идёт?

Можно ли ключи перенести как то в самый низ, так как они совсем не нужны, а так их приходится пролистывать.

Возможно ли объединить скрижали в отдельную группу? сейчас они идут в перемешку с книгами и записками..

**Comment by dosinabox** [comment]
> Можно ли ключи перенести как то в самый низ, так как они совсем не нужны, а так их приходится пролистывать.

В gothic.ini у параметра invCatOrder можно перенести раздел DOCS подальше - тогда ключи будут в самом низу инвентаря.
```
invCatOrder=COMBAT,POTION,FOOD,ARMOR,MAGIC,RUNE,OTHER,DOCS,NONE
```
Но книги и записки будут ещё ниже, потому что ключи находятся именно в этой категории. Новые категории добавлять нельзя.

> Возможно ли объединить скрижали в отдельную группу?

Можно перенести их в категорию MAGIC, тогда они будут идти сразу за рунам и свиткам "отдельной" категорией. Но привязка к посторонней категории всё равно остается. Новые категории добавлять нельзя.

**Comment by dosinabox** [comment]
![image](https://user-images.githubusercontent.com/39790055/76749167-2068a500-678d-11ea-8640-02e0af379f83.png)

**Comment by Kor-Angar** [comment]
> Можно перенести их в категорию MAGIC, тогда они будут идти сразу за рунам и свиткам "отдельной" категорией. Но привязка к посторонней категории всё равно остается. Новые категории добавлять нельзя.

только скрижали будут идти или книги тоже?

**Comment by Kor-Angar** [comment]
а в игре есть возможность понять какой ключ уже был использован?

**Comment by dosinabox** [comment]
> а в игре есть возможность понять какой ключ уже был использован?

нет

> только скрижали будут идти или книги тоже?

Я говорю только про скрижали, но можно так сделать и с книгами. Но тогда они будут смешиваться со скрижалями, потому что у всех префикс в названии инстанции ItWr_.

**Comment by Kor-Angar** [comment]
а скрижали нельзя перенести в  POTION?

**Comment by dosinabox** [comment]
можно, будут после всех зелий

**Comment by Kor-Angar** [comment]
давай попробуем перенести

- скрижали в POTION
- а книги в MAGIC

и посмотрим как это будет выглядеть у героя в середине игры

**Comment by dosinabox** [comment]
а зачем отделять книги от записок, писем и рецептов?

**Comment by Kor-Angar** [comment]
> а зачем отделять книги от записок, писем и рецептов?

а они вместе идут? я думал это всё одно :-) можно тогда их к MAGIC попробовать поднять

**Comment by dosinabox** [comment]
если я вынесу скрижали в отдельную категорию, то где должны находиться обычные старые таблички и табличка вызова Куарходрона?

**Comment by Kor-Angar** [comment]
Это не принципиально. Можно со скрижалямии. Можно в документах. 23:53, 17 марта 2020 г., dosinabox <notifications@github.com>:
если я вынесу скрижали в отдельную категорию, то где должны находиться обычные старые таблички и табличка вызова Куарходрона?

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
-- Отправлено из мобильного приложения Яндекс.Почты

**Comment by dosinabox** [comment]
> Возможно ли объединить скрижали в отдельную группу? сейчас они идут в перемешку с книгами и записками..

Готово, будут после рун и свитков. Обычные старые таблички и табличка вызова Куарходрона остаются в документах.

**Comment by dosinabox** [comment]
<img width="598" alt="Screenshot_1" src="https://user-images.githubusercontent.com/39790055/79702369-1f0b2a80-82ad-11ea-83c1-948c3b4fe4d7.png">

**Comment by Kor-Angar** [comment]
Вот ещё могу сказать что факел было бы здорово поднять. Я в Готику 1 пока катаю обнаружил что его дольше всего искать. И когда я его добавил в пюнапитки стало играть лучше 😀 звучит конечно дико, но факт 😀
