### ISSUE TITLE
NAME_SPL_Teleport_Maya

### ISSUE THREAD

**Issue by Kor-Angar** [dosinabox/g2nr_unofficial_update#243]
а это что?
const string NAME_SPL_Teleport_Maya = "Телепорт зодчих";

руна телепорта в Яркендаре? куда телепортирует?

**Comment by UnresolvedExternal** [comment]
Можешь сам посмотреть.
goto waypoint ADW_VALLEY_SHOWCASE1_04

**Comment by dosinabox** [comment]
Этот свиток будет у одного из каменных стражей за разрушенным мостом, там где магический лук. Чтобы выбраться на другую сторону, если нет акробатики.
А если акробатика есть, то свитка не будет.
