### ISSUE TITLE
Доспехи из брони Ползунов

### ISSUE THREAD

**Issue by Kor-Angar** [dosinabox/g2nr_unofficial_update#246]
Может сделать ограничение на это квест ? 

что бы диалог про доспехи был доступен в 1-3 главах, а сам квест отменялся с наступлением 4 главы.

![image](https://user-images.githubusercontent.com/49514764/76704317-29a03600-66e9-11ea-9131-6d818163a398.png)

**Comment by dosinabox** [comment]
> а сам квест отменялся с наступлением 4 главы.

Потому что в 4 главе в этих доспехах уже нет смысла?

**Comment by Kor-Angar** [comment]
Да. Доспехи для 2,3 главы. 23:50, 17 марта 2020 г., dosinabox <notifications@github.com>:

а сам квест отменялся с наступлением 4 главы.

Потому что в 4 главе в этих доспехах уже нет смысла?

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
-- Отправлено из мобильного приложения Яндекс.Почты

**Comment by dosinabox** [comment]
Но ведь новичок может и не знать, что эти доспехи бесполезны после определенного момента игры. А квест почему-то пропадет. Тогда уже не в четвертой, а в пятой, когда точно не до этого.

**Comment by Kor-Angar** [comment]
можно делать проверку на навык, если навыка на начало 4 главы нет, то квест закрыть. если навык есть то не закрывать.

**Comment by Kor-Angar** [comment]
кстати квест появляется про доспехи после разговора с Волком, а по идеи должен появляться после разговора с Гештатом :-)

**Comment by dosinabox** [comment]
можно ли собрать нужное количество пластин без изучения навыка снятия?

**Comment by Kor-Angar** [comment]
Нет
