### ISSUE TITLE
Будет ITAR_PAL_S. Для теста сделаю.

### ISSUE THREAD

**Issue by Kor-Angar** [dosinabox/g2nr_unofficial_update#247]
> Будет ITAR_PAL_S. Для теста сделаю.

доспех красивый, но визуально  тяжелый доспех паладина мне кажется имеет большую защиту :-)

даже не знаю кому он в игре может подойти по статусу. Лорд Андре и Лорд Хаген паладины и должны быть во фракционных доспехах. Губернатор вроде как не Лорд и даже не генерал-губернатор. 

может попробовать Лорда Инубиса в него одеть?:-)

_Originally posted by @Kor-Angar in https://github.com/dosinabox/g2nr_unofficial_update/issues/226#issuecomment-596225999_

**Comment by Kor-Angar** [comment]
![image](https://user-images.githubusercontent.com/49514764/76708542-a4c51480-6708-11ea-8d4d-a0fa30e9afad.png)
![image](https://user-images.githubusercontent.com/49514764/76708551-abec2280-6708-11ea-8943-36b8a6f4f20b.png)
![image](https://user-images.githubusercontent.com/49514764/76708555-b0b0d680-6708-11ea-96ff-227a06014cc0.png)
![image](https://user-images.githubusercontent.com/49514764/76708560-ba3a3e80-6708-11ea-9415-2ef34871927c.png)
![image](https://user-images.githubusercontent.com/49514764/76708566-c0301f80-6708-11ea-9d8b-1c400bae03b6.png)

**Comment by Kor-Angar** [comment]
Я нашёл кто по ЛОРу игры подходит :-)

**Comment by Kor-Angar** [comment]
рядом только не хватает наемника телохранителя :-)

**Comment by dosinabox** [comment]
ужас какой)

**Comment by Kor-Angar** [comment]
Очень мило 😀

**Comment by Kor-Angar** [comment]
Если честно, никогда не воспринимал Онара. Но в этих доспехах его диалоги стали намного брутальнее  :-) 

https://www.youtube.com/watch?v=Vkx1PQi0DPk

**Comment by Kor-Angar** [comment]
а тут мнение разделилось :-)
![image](https://user-images.githubusercontent.com/49514764/76765641-c4f7e080-67a7-11ea-8a2f-c3c7bff51140.png)
https://vk.com/wall-5819093_820830

***

![image](https://user-images.githubusercontent.com/49514764/76765647-c7f2d100-67a7-11ea-8c73-3dccac661d55.png)
https://vk.com/wall464685805_483

**Comment by dosinabox** [comment]
У него уже есть новая одежда)
