### ISSUE TITLE
Руны в продаже. Маг Огня

### ISSUE THREAD

**Issue by Kor-Angar** [dosinabox/g2nr_unofficial_update#248]
после вступления в Маги Огня руны в продаже не появляются. может добавлять в продажу при условие что герой выучил руническую формулу? или просто добавить пару рун в 1 главе в продажу Каррасу.

**Comment by Kor-Angar** [comment]
https://github.com/dosinabox/g2nr_unofficial_update/issues/87

**Comment by dosinabox** [comment]
появление пустых рун привязано ко второй главе, предлагаешь перенести их пораньше, ко вступлению в маги?

**Comment by Kor-Angar** [comment]
Да. У героя всего одна чистая руна. А заклинаний можно сделать много. Я выучил дополнительно два заклинания а сделать смог только одну.

**Comment by Kor-Angar** [comment]
как вариант добавлять их в продажу при изучение заклинания, по аналогии как это реализовано со свитками заклинаний.

**Comment by dosinabox** [comment]
> У героя всего одна чистая руна. А заклинаний можно сделать много.

А может это специально баланс такой)

**Comment by Kor-Angar** [comment]
Это система из Готики 2 классик.  Тогда что бы не нарушать баланс нельзя добавлять свитки в продаже при изучение заклинания ;-) -- Отправлено из мобильного приложения Яндекс.Почты

**Comment by dosinabox** [comment]
> Это система из Готики 2 классик.

не помню такого

**Comment by Kor-Angar** [comment]
ну ты пишишь про баланс. а я пишу что это история из Готики 2 классик. а баланс Готики 2 классик сильно отличается от Готики 2 НВ. В классике руны были мощнее. в НВ руны слабее и их больше. дополнительные руны появляются в Ярике и в Минентале. а в Ярик надо ещё как то попасть :-) а до этого у героя есть два чистых рунических камня, один в первой главе и один во второй. а остальные рунические камни есть и в Ярике и в Минентале.

**Comment by Kor-Angar** [comment]
в первой и второй главе в Хориносе рун не хватает. при том что каких то там сильных заклинаний нет. в 3 главе чистых рун больше чем доступно заклинаний.

в Хориносе в первой главе доступна 1  чистая руна.
в Хориносе во второй главе доступна еще 1 чистая руна.

в результате что бы создать руны с заклинанием свет и с заклинанием сон пришлось сходить в Миненталь за чистыми руническими камнями.

**Comment by Kor-Angar** [comment]
тут такая же ситуация: кому сильно надо тот через марвин рунический камень добавит. а в яркендаре как будто бы найдёт.

**Comment by dosinabox** [comment]
Предлагаю добавлять чистые руны Гораксу и Исгароту сразу после вступления ГГ в маги, не дожидаясь второй главы.

**Comment by Kor-Angar** [comment]
А Исгароту зачем? У него же ассортимент для гостей 😀

**Comment by Kor-Angar** [comment]
Лучше тогда тому Магу который специализируется на призыве.

**Comment by dosinabox** [comment]
Да, ему. Перепутала имена Карраса и Исгарота.

**Comment by dosinabox** [comment]
Хм. А что, чистые руны продают только Кронос, Горакс, Лютеро и Милтен на Ирдорате?

**Comment by dosinabox** [comment]
Появление **двух** чистых рун в продаже у Горакса перенесено с начала второй главы на момент вступления в маги.
Сколько чистых рун следует добавить в продажу Каррасу?

**Comment by Kor-Angar** [comment]
> Хм. А что, чистые руны продают только Кронос, Горакс, Лютеро и Милтен на Ирдорате?

да. но они есть в мире и их так же дают в награду за квесты. 

> Появление двух чистых рун в продаже у Горакса перенесено с начала второй главы на момент вступления в маги.

одна появлялась. проверь плиз.

> Сколько чистых рун следует добавить в продажу Каррасу?

две наверное.

**Comment by dosinabox** [comment]
> одна появлялась. проверь плиз.

В скриптах прописаны две:
```
if((Kapitel >= 2) && (Gorax_ItemsGiven_Chapter_2 == FALSE))
{
//	CreateInvItems(slf,ItMi_Gold,100);
	CreateInvItems(slf,ItMi_Sulfur,2);
	CreateInvItems(slf,ItMi_Quartz,2);
	CreateInvItems(slf,ItMi_Pitch,1);
	CreateInvItems(slf,ItSc_Icebolt,5);
	CreateInvItems(slf,ItPo_Health_01,7);
	CreateInvItems(slf,ItPo_Health_02,2);
	CreateInvItems(slf,ItPo_Mana_01,14);
	CreateInvItems(slf,ItSc_InstantFireball,5);
	CreateInvItems(slf,ItSc_SumWolf,5);
	CreateInvItems(slf,ItSc_Windfist,4);
	CreateInvItems(slf,ItSc_Sleep,2);
	CreateInvItems(slf,ItAm_Prot_Edge_01,1);
	if((hero.guild != GIL_NOV) && (hero.guild != GIL_NONE))
	{
		CreateInvItems(slf,ItMi_RuneBlank,2);
	};
	if((hero.guild == GIL_PAL) || (hero.guild == GIL_MIL))
	{
		CreateInvItems(slf,ItWr_Map_Shrine_MIS,1);
	};
	Gorax_ItemsGiven_Chapter_2 = TRUE;
};
```

В оригиналах Г2 и Г2НВ тоже:
```
CreateInvItems(slf,ItMi_RuneBlank,2);
```

**Comment by Kor-Angar** [comment]
И правда две 😀

**Comment by dosinabox** [comment]
![image](https://user-images.githubusercontent.com/39790055/77313445-efe8b400-6d14-11ea-9428-7e2ed4b4d56b.png)

**Comment by dosinabox** [comment]
> И правда две 😀

С учетом этого - Каррасу нужна одна руна или две?

**Comment by Kor-Angar** [comment]
Ага. Тоже залез на стрим пролестал 😀

**Comment by Kor-Angar** [comment]
> С учетом этого - Каррасу нужна одна руна или две?

Думаю две. Так как на баланс это никак не влияет, а ограничивать игрока в создание рун в начале игры смысла нет.  Пусть имеет возможность  сделать "свет" или "сон" 😀

**Comment by dosinabox** [comment]
Дело такое, что перенос двух рун Горакса ни на что не влияет, потому что общее количество рун в игре не меняется. А две новые руны у Карраса позволят создавать дополнительные мощные руны в поздних главах. А вот это уже влияет на баланс. Плюс обесцениваются квестовые и запрятанные руны.
Что думаешь об этом?

**Comment by Kor-Angar** [comment]
думаю что можно просто составить список всех рун в табличке и переложить пару рун из 3 главы в 1 главу. думаю что среднестатистический маг не покупает руны, так как кол-во созданных рун < количество найденных рун. Думаю сами по себе запрятанные и квестовые руны не могут обесценится так как не несут какой то ценности, так как опять же есть в продаже. Сколько рунических камней появляется у Кроноса во 2  главе и сколько в 3 главе?  23.03.2020, 15:25, "dosinabox" <notifications@github.com>: Дело такое, что перенос двух рун Горакса ни на что не влияет, потому что общее количество рун в игре не меняется. А две новые руны у Карраса позволят создавать дополнительные мощные руны в поздних главах. А вот это уже влияет на баланс. Плюс обесцениваются квестовые и запрятанные руны.Что думаешь об этом?—You are receiving this because you modified the open/close state.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by dosinabox** [comment]
Кронос:
2 глава - 2
3 глава - 2
5 глава - 1

Горакс:
2 глава - 2 (переносим на 1 главу)
3 глава - 1
5 глава - 1

Лютеро:
5 глава - 1

Милтен:
6 глава - 1

**Comment by Kor-Angar** [comment]
давай у Кроноса с 3 главы 1 перенесём.

если герой пришёл в Ярик во 2 главе, то у Кроноса будет так же 2 руны, если герой пришёл в Ярик 3 главе(а это уже есть руны телепорта в Хориносе), то у Кроноса будет 3 рунических камня.

**Comment by dosinabox** [comment]
А зачем, собственно, Каррас? Просто добавить Гораксу ещё одну руну от Кроноса, и перенести его руны со второй главы. Итого **три** руны продаже в монастыре после вступления в маги. Вместо нуля.

**Comment by Kor-Angar** [comment]
потому что у Карраса ассортимент скудный. а так у него будет рунический камень. будет стимул ходить и смотреть что у него есть в продаже.  не появилось ли чего.

**Comment by Kor-Angar** [comment]
https://github.com/dosinabox/g2nr_unofficial_update/issues/87

**Comment by dosinabox** [comment]
Итог:
- одна руна Кроноса перенесена из третьей главы Каррасу в первую;
- две руны Горакса перенесены из второй главы в первую;
- все три руны появятся в продаже у Горакса и Карраса сразу после вступления ГГ в маги.
