### ISSUE TITLE
Дракон-нежить и огненный дождь

### ISSUE THREAD

**Issue by dosinabox** [dosinabox/g2nr_unofficial_update#25]
На форуме пишут:

> И баг с драконом-нежитью. Если скастовать на нём огненный дождь, то сам дракон-нежить зависает. А после того, как ГГ его добивает, не появляется кат-сцена

Воспроизвести не удалось. Нужно тестирование.

**Comment by dosinabox** [comment]
Зависание после огненного дождя применимо ко всем драконам.

**Comment by Kor-Angar** [comment]
ещё проскакивает двойной урон иногда. вроде уже обсуждали это,

**Comment by dosinabox** [comment]
зависания исправлены

**Comment by Kor-Angar** [comment]
а если например сократить время действия заморозки от ледяной волны на последнего дракона? такое возможно или сложно технически ?

**Comment by dosinabox** [comment]
это возможно и даже не сложно

**Comment by Kor-Angar** [comment]
ну вот про это можно подумать и для ледяного дракона и для неживого.
