### ISSUE TITLE
Амулет защиты от Магии в продаже у Кантара

### ISSUE THREAD

**Issue by Kor-Angar** [dosinabox/g2nr_unofficial_update#250]
ввиду того что вопрос кому передать в продажу амулет к защите от магии который есть в продаже у Кантара подзатянулся на года есть предложение просто поменять местами амулеты у продавцов. 

 Готика 2 НВ | 40 к жизни. 400 золото | 30 к жизни, 10 к мане. 1300 золото | 10 к защите от магии. 700 золото
-- | -- | -- | --
сейчас | Бальтрам | Цурис | Кантар
предложение | Кантар | Бальтрам | Цурис

Амулет к защите от магии один из самых ценных, но необходимость в нё возникает только в 3 главе. в тоже время Кантар первый торговец в игре которого встречает в игре. покупка у него бесполезного и ненужного амулета к жизни, может вполне заинтересовать какого нибудь игрока :-) опять же если игрок купит амулет к жизням у Кантара это хорошо, так как этот амулет игрок всё равно поменяет на другой (амулет к жизни и к мане или амулет целителей или амулет защиты), таким образом мы будем мотивировать игрока в начале игры деньги так сказать спустить в унитаз :-)

***

что тут ещё нужно понимать. этот амулет к защите от магии, его в продаже в Готике 2 классик не было. его можно было получить только от Serpentes при игре за мага. и может быть его можно вообще переложить в продажу в монастырь.

***
у Исгарота появляется в продаже амулет +10 к мане в 4 главе. его можно перенести в продажу в первую главу. или передать этот амулет на +10 маны в город, а из города забрать более ценный амулет +10 к мане и +30 к жизни.

**Comment by dosinabox** [comment]
не избивать Кантара настолько сложно?)

**Comment by Kor-Angar** [comment]
ты имеешь ввиду не садить Кантара в тюрьму? или не убивать Кантара в тюрьме? :-)

я прихожу в город. мне надо или посадить Кантара или посадить Сару. я сажаю Кантара :-) видимо я просто должен садить Сару? :-)

**Comment by dosinabox** [comment]
Может, просто дать второй амулет Кроносу в Яркендаре?
Или сделать его лутом с запрятанного болотного трупа.

**Comment by Kor-Angar** [comment]
> Может, просто дать второй амулет Кроносу в Яркендаре?

можно и так. твой консерватизм играет с неофициальным обновлением злую шутку ;-)

**Comment by dosinabox** [comment]
> его можно было получить только от Serpentes при игре за мага

А что дает Серпентес в Г2НВ?

**Comment by dosinabox** [comment]
> я прихожу в город. мне надо или посадить Кантара или посадить Сару. я сажаю Кантара :-)

Опять же, не вижу проблемы, потому что он выходит из тюрьмы в третьей главе, как раз когда амулет становится нужным.

**Comment by Kor-Angar** [comment]
> А что дает Серпентес в Г2НВ?

такой амулет даёт Серпентес за выполнение квеста про акции магу огня.

**Comment by Kor-Angar** [comment]
> Опять же, не вижу проблемы, потому что он выходит из тюрьмы в третьей главе, как раз когда амулет становится нужным.

в целом поддерживаю игру можно пройти раздетым героем с дубинкой. у меня лично проблем ни с чем нет. я всё делаю заранее так как мне надо. а если у игроков что то не получается, то это конечно же их вина. что они не подумав сначала сдали лорду Андре Кантару, а потом не подумав убили его в тюрьме. 
уверен что когда нибудь вопрос с амулетом решится сам собой. как нибудь. в рамках например торговли с Пеком или в рамках ещё чего нибудь.

**Comment by dosinabox** [comment]
> такой амулет даёт Серпентес за выполнение квеста про акции магу огня.

Может, давать амулет чуть получше? Раз такой же есть в продаже с первой главы.

> Может, просто дать второй амулет Кроносу в Яркендаре?

Всё же пока поддерживаю такой вариант.

**Comment by Kor-Angar** [comment]
> Может, давать амулет чуть получше? Раз такой же есть в продаже с первой главы.

Лучше этого Амулет, глаз Инноса. У Глаза Инноса защита от магии 15, а у этого 10.

Можно сделать амулет к защите от магии 10 и к защите от огня 10. Не думаю что у этого есть практический смысл, так как против Ищущих и Огенных Ящеров можно ходить с глазом Инноса, а бой с драконом в рукопашку у мага это маловеротяная история. Да и в таком случае выгоднее будет биться с амулетом на силу 😀

**Comment by dosinabox** [comment]
> Может, просто дать второй амулет Кроносу в Яркендаре?

А в какой главе, кстати? Во второй или третьей?

**Comment by Kor-Angar** [comment]
Можно со второй. Смысла ограничивать его продажу нет более поздней главой нет.

**Comment by dosinabox** [comment]
> > Может, просто дать второй амулет Кроносу в Яркендаре?
> 
> Всё же пока поддерживаю такой вариант.

Но он мне совсем не нравится. Это слишком прямолинейное решение для всего одного специфического случая: если Кантар погиб до третьей главы, а ГГ - не маг. На мой взгляд, лучше всё же дать амулет болотному трупу.

**Comment by Kor-Angar** [comment]
>  Это слишком прямолинейное решение для всего одного специфического случая: если Кантар погиб до третьей главы, а ГГ - не маг.

у тебя есть статистика сколько в процентах игроков не магов убивают Кантара? :-)

>  На мой взгляд, лучше всё же дать амулет болотному трупу.

а как же обще-игровой баланс? :-) можно вернуться к тому вопросу куда деваются товары Кантара. изначально когда этот вопрос поднимался предполагалось что товары которые будут у Кантара, в т.ч. и амулет будут переданы другому торговцу. В процессе ты не захотела просто передать эти товары Саре, а стала строить многоходовку. в результате товара Кантара пропадают, Пек контрафакт не продаёт и... какой труп болотный станет обладателем этого амулета :-)

****
самое простой решение это поменять местами амулеты. Кантару дать менее полезный, а Цуриусу этот. 

****

то что Кронос продаёт магические шмотки это нормально. точнее это более нормально чем пират который продаёт кольцо с защитой от магии :-)

**Comment by dosinabox** [comment]
> самое простой решение это поменять местами амулеты. Кантару дать менее полезный, а Цуриусу этот.

Сам знаешь, как игроки относятся к таким изменениям) Но, возможно, это действительно меньшее из зол в данной ситуации. Скорее всего, так и сделаю.

**Comment by Kor-Angar** [comment]
Ну это же от ситуации зависит. Амулет защиты от магии точно в первой главе никому не нужен 😀 кажется и во второй тоже. Можно в случае посадки Кантара просто добавлять его в продажу Цуриусу.   13:19, 9 апреля 2020 г., dosinabox <notifications@github.com>:

самое простой решение это поменять местами амулеты. Кантару дать менее полезный, а Цуриусу этот.

Сам знаешь, как игроки относятся к таким изменениям) Но, возможно, это действительно меньшее из зол в данной ситуации. Скорее всего, так и сделаю.

—You are receiving this because you modified the open/close state.Reply to this email directly, view it on GitHub, or unsubscribe.
-- Отправлено из мобильного приложения Яндекс.Почты

**Comment by dosinabox** [comment]
Короче. Пока будет у Кроноса. Пока всё)
