### ISSUE TITLE
Показ заголовков при обновлении дневника

### ISSUE THREAD

**Issue by dosinabox** [dosinabox/g2nr_unofficial_update#254]
Можно выключать в настройках. Мысли?
![Screenshot_3](https://user-images.githubusercontent.com/39790055/78500447-19ff9480-775f-11ea-81a2-f9bf5dada3d9.jpg)
![Screenshot_1](https://user-images.githubusercontent.com/39790055/78500449-1b30c180-775f-11ea-9da3-d562528ce8e0.jpg)

**Comment by Kor-Angar** [comment]
как то это слишком не по Готически. то есть это "да", так по идеи и должно быть и ElderGamer добавлял такое дело. но вот когда оно появляется на экране кажется будто бы это уже не Готика. 

поэтому я ничего не могу сказать про такое дело. 

кстати а такую настройку в меню игры нельзя добавить? там же где субтитры?

**Comment by dosinabox** [comment]
Мне тоже не нравится) Поэтому по умолчанию будет выключено. Наверное.

> кстати а такую настройку в меню игры нельзя добавить? там же где субтитры?

К сожалению, нет.

**Comment by Kor-Angar** [comment]
Как то неуверенно звучит 😀А вот я обратил внимание в "пробуждение" настройки появляются при нажатие "новая игра". -- Отправлено из мобильного приложения Яндекс.Почты

**Comment by dosinabox** [comment]
А там скриптовые расширители, с ними всё можно) Но я их пока не использую и пока не особо нужно.

**Comment by dosinabox** [comment]
Готово. По умолчанию выключено.
