### ISSUE TITLE
Именное оружие / 	owner = PC_Psionic;

### ISSUE THREAD

**Issue by Kor-Angar** [dosinabox/g2nr_unofficial_update#255]
а в Готики 2 НВ в инстанции оружия "owner" наверное задействовать можно ;-)

![image](https://user-images.githubusercontent.com/49514764/79680123-d6079780-8214-11ea-8a81-e13584a32a78.png)

давай на мече коменданта Гаранта проверим.. он уже по сути получился "именной" :-)

**Comment by dosinabox** [comment]
Это не особо-то и работало в Г1 и приводило к вылетам, но там хотя бы была озвучка под это дело. В Г2 такой озвучки уже нет, нужно придумывать какие-то обходные пути. Пока можно просто прописать владельцев всему именному оружию на будущее и думать дальше.
Альрик - меч Альрика
Гаронд - меч командующего
Феррос - меч Ферроса
Скиннер - Бетти
? - ?...
? - ?...

> коменданта Гаранта

У тебя некоторые имена с каждым упоминанием пишутся по новому)

**Comment by dosinabox** [comment]
Вообще в Г2 проверка C_IsTakenItemMyPossession используется только когда ГГ подбирает какой-либо предмет и фактически применяется только в одном случае: чтобы вызвать реакцию Гарвига на кражу священного молота. В Г1 совсем не так, там люди могут увидеть свою вещь на ГГ и потребовать её вернуть.

**Comment by dosinabox** [comment]
Может быть полезно и для этого:
https://github.com/dosinabox/g2nr_unofficial_update/issues/156
Например, назначаем Лемара владельцем гроссбуха и он будет забирать его у избитого ГГ.

**Comment by dosinabox** [comment]
> Может быть полезно для этого:
> #156

Например, назначаем Лемара владельцем гроссбуха и он будет забирать его у избитого ГГ.

**Comment by Kor-Angar** [comment]
> У тебя некоторые имена с каждым упоминанием пишутся по новому)

это мы можем :-) и автоподстановка нам активно в этом помогает :-)

> Пока можно просто прописать владельцев всему именному оружию на будущее и думать дальше.

понять бы как это может работать в НВ. и с оружием в т.ч. Например может ли торговец одевать "своё" оружие, а не лучшее какое есть в продаже?

**Comment by dosinabox** [comment]
> Например может ли торговец одевать "своё" оружие, а не лучшее какое есть в продаже?

Нет. Движок берет лучшее по урону оружие, которое может поднять персонаж. В скриптах это, вроде, не регулируется никак.
Предлагаю набросать список именных предметов в другой теме: https://github.com/dosinabox/g2nr_unofficial_update/issues/156 А эту пока закрою как повторную.
