### ISSUE TITLE
Большое исцеление Паладина /  (ItRu_PalFullHeal)

### ISSUE THREAD

**Issue by dosinabox** [dosinabox/g2nr_unofficial_update#256]
В Г2 и Г2НВ руна была прописана для изучения у Милтена в шестой главе, но фактически изучить и создать её невозможно - опция диалога недоступна из-за ошибки в условии, а функции создания паладинской руны вообще не существует. Также эту руну нельзя нигде найти.
В неофициальном обновлении полная возможность изучения у Милтена была разблокирована, а саму руну зачем-то дали паладинскому полковнику орков в Хоринисе (глава 4). Что, мягко говоря, очень нарушает баланс.

Предлагаю данную руну у полковника орков забрать.

**Comment by dosinabox** [comment]
> руну зачем-то дали паладинскому полковнику орков в Хоринисе

Вернее, её добавили разработчики, но после смерти орка она по недосмотру исчезала из его инвентаря.

**Comment by Kor-Angar** [comment]
давай с начало. ты говоришь о Паладинских рунах. Милтен в Готики 2  и Готики 2 НВ паладинские руны не давал. так ведь? то есть это было ещё в коде Готике 2, но в НВ эту возможность так и не разблокировали. 

в неофициальном обновление Милтен стал эти руны давать Паладинов. так?

Руна исцеления в Готике 2 была у Орков, в Готике 2 НВ она у него так же осталась но стала пропадать при автоочистки инвентаря. Это момент был пофискин и теперь она не пропадает. Я думал почему то что там должна быть средняя руна лечения, данный вопрос поднимал, в вопросе разобрался и понял что ошибался. 

это вот вводные данные я выше описал. теперь касательно твоего предложения.

> руну зачем-то дали паладинскому полковнику орков в Хоринисе (глава 4). Что, мягко говоря, очень нарушает баланс.
> Предлагаю данную руну у полковника орков забрать.

Давай расскажи мне про баланс. вот такого то числа  ты играла паладином в такой то главе убила полковника орков (усиленного или обычного) каким то оружием(каким?) и получила руну. с этой руной ты пошла куда то там тебя кто-то бил(кто?) и мог бы убить, но ты воспользовалась данной рунной  и герой всех победил. таким образом ты считаешь что данная руна нарушает баланс и предлагаешь её совсем убрать/ поменять на руну среднего лечения / что то ещё.

***

если тебя интересует мой опыт, могу сказать что руна просто прекрасна. восстанавливает Паладину сразу же все жизни одним кастом в 4 главе. ману требует больше чем "легкое лечение", т.е. через легкое лечение лечится выгоднее. но ввиду того что большое лечение получается нахаляву то норм. при игре против супер боссов, типа драконов лечится лучше свитками, свитки стоит копейки продаются у магов так же восстанавливают все жизни(это 4 глава) но при этом будет стоит всего пять маны. 


***

> В Г2 и Г2НВ руна была прописана для изучения у Милтена в шестой главе, но фактически изучить и создать её невозможно - опция диалога недоступна из-за ошибки в условии, а функции создания паладинской руны вообще не существует.

там были прописаны все руны. не понятно почему ты акцент делаешь именно на этой руне.

```
********************************************************
// Talente Runen
//----------------------
// Paladin Runen
//----------------------
//***************************************************************************

FUNC VOID DIA_Milten_DI_TeachMagic_Runen_Paladin ()
{
	Info_ClearChoices 	(DIA_Milten_DI_TeachMagic);
	Info_AddChoice	(DIA_Milten_DI_TeachMagic, DIALOG_BACK, DIA_Milten_DI_TeachMagic_BACK);
	
	if (PLAYER_TALENT_RUNES [SPL_PalLight] == FALSE)
	{
		Info_AddChoice	(DIA_Milten_DI_TeachMagic, B_BuildLearnString ("Licht", B_GetLearnCostTalent (other, NPC_TALENT_RUNES, SPL_PalLight)) ,DIA_Milten_DI_TeachMagic_Runen_Paladin_SPL_PalLight);
	};
	if	(PLAYER_TALENT_RUNES [SPL_PalLightHeal] == FALSE)
	{ 
		Info_AddChoice	(DIA_Milten_DI_TeachMagic, B_BuildLearnString ("Heilung", B_GetLearnCostTalent (other, NPC_TALENT_RUNES, SPL_PalLightHeal)) ,DIA_Milten_DI_TeachMagic_Runen_Paladin_SPL_PalLightHeal);
	};
	if	(PLAYER_TALENT_RUNES [SPL_PalHolyBolt] == FALSE)
	{
		Info_AddChoice	(DIA_Milten_DI_TeachMagic, B_BuildLearnString ("Heiliger Pfeil", B_GetLearnCostTalent (other, NPC_TALENT_RUNES, SPL_PalHolyBolt)) ,DIA_Milten_DI_TeachMagic_Runen_Paladin_SPL_PalHolyBolt);
	};
	if 	(PLAYER_TALENT_RUNES [SPL_PalMediumHeal] == FALSE)
	{
		Info_AddChoice	(DIA_Milten_DI_TeachMagic, B_BuildLearnString ("Grosse Heilung", B_GetLearnCostTalent (other, NPC_TALENT_RUNES, SPL_PalMediumHeal)) ,DIA_Milten_DI_TeachMagic_Runen_Paladin_SPL_PalMediumHeal);
	};
	if (PLAYER_TALENT_RUNES [SPL_PalRepelEvil] == FALSE)
	{
		Info_AddChoice	(DIA_Milten_DI_TeachMagic, B_BuildLearnString ("Bцsem Schaden", B_GetLearnCostTalent (other, NPC_TALENT_RUNES, SPL_PalRepelEvil)) ,DIA_Milten_DI_TeachMagic_Runen_Paladin_SPL_PalRepelEvil);
	};
	if (PLAYER_TALENT_RUNES [SPL_PalFullHeal] == FALSE)
	{
		Info_AddChoice	(DIA_Milten_DI_TeachMagic, B_BuildLearnString ("Vollheilung", B_GetLearnCostTalent (other, NPC_TALENT_RUNES, SPL_PalFullHeal)) ,DIA_Milten_DI_TeachMagic_Runen_Paladin_SPL_PalFullHeal);
	};
	if (PLAYER_TALENT_RUNES [SPL_PalDestroyEvil] == FALSE)
	{
		Info_AddChoice	(DIA_Milten_DI_TeachMagic, B_BuildLearnString ("Bцses Vernichten", B_GetLearnCostTalent (other, NPC_TALENT_RUNES, SPL_PalDestroyEvil)) ,DIA_Milten_DI_TeachMagic_Runen_Paladin_SPL_PalDestroyEvil);
	};
};
FUNC VOID DIA_Milten_DI_TeachMagic_Runen_Paladin_SPL_PalLight()
{
	B_TeachPlayerTalentRunes	(self, other,SPL_PalLight);  
	
};
FUNC VOID DIA_Milten_DI_TeachMagic_Runen_Paladin_SPL_PalLightHeal()
{
	B_TeachPlayerTalentRunes	(self, other,SPL_PalLightHeal);  
	
};
FUNC VOID DIA_Milten_DI_TeachMagic_Runen_Paladin_SPL_PalHolyBolt()
{
	B_TeachPlayerTalentRunes	(self, other,SPL_PalHolyBolt);  
	
};
FUNC VOID DIA_Milten_DI_TeachMagic_Runen_Paladin_SPL_PalMediumHeal()
{
	B_TeachPlayerTalentRunes	(self, other,SPL_PalMediumHeal);  

};
FUNC VOID DIA_Milten_DI_TeachMagic_Runen_Paladin_SPL_PalRepelEvil()
{
	B_TeachPlayerTalentRunes	(self, other,SPL_PalRepelEvil);  
	
};
FUNC VOID DIA_Milten_DI_TeachMagic_Runen_Paladin_SPL_PalFullHeal()
{
	B_TeachPlayerTalentRunes	(self, other,SPL_PalFullHeal);  
	
};
FUNC VOID DIA_Milten_DI_TeachMagic_Runen_Paladin_SPL_PalDestroyEvil()
{
	B_TeachPlayerTalentRunes	(self, other,SPL_PalDestroyEvil);  
	
};

```

что можно сделать: руны эти у Милтена заблокировать,а  перенести возможность их изучения Паладину которые есть на корабле. это будет выглядеть более логично. при этом учить двум рунам: среднему лечение и средней атаке. что бы это всё не усложнять слишком. ну и как бы всё.

***

Пиши подробнее свою мысль. так пока не понятно.

**Comment by dosinabox** [comment]
> Руна исцеления в Готике 2 была у Орков, в Готике 2 НВ она у него так же осталась но стала пропадать при автоочистки инвентаря. Это момент был пофискин и теперь она не пропадает.

Тогда вопросов нет, всё остается как есть.

> Я думал почему то что там должна быть средняя руна лечения, данный вопрос поднимал, в вопросе разобрался и понял что ошибался.

Вот и я твое возмущение помню. Поэтому вопрос снова подняла.

> если тебя интересует мой опыт, могу сказать что руна просто прекрасна. восстанавливает Паладину сразу же все жизни одним кастом в 4 главе.

При этом у Альбрехта в 4 главе можно изучить только малое исцеление, а в 5 появляется среднее. Зачем их учить, спрашивается, если самое крутое выпадает с орка. Но если они выгоднее по мане, то ОК.

> там были прописаны все руны. не понятно почему ты акцент делаешь именно на этой руне.

Этот диалог недоступен из-за кривого условия (нужно одновременно быть и магом, и паладином - что невозможно). А если и был бы доступен, то Милтен просто обучает созданию рун на рунном столе, а не дает их. Создания паладинских рун в оригинале Г2 и Г2НВ нет. Такой вот двойной недосмотр.

> что можно сделать: руны эти у Милтена заблокировать,а перенести возможность их изучения Паладину которые есть на корабле. это будет выглядеть более логично.

Если в команде есть Гирион, то пусть обучает всем паладинским рунам.
Если в команде нет Гириона, то пусть Ватрас обучает среднему лечению и средней атаке.
Если в команде нет Гириона и Ватраса, то пусть Милтен обучает малому лечению и малой атаке.
(?)

**Comment by Kor-Angar** [comment]
> Вот и я твое возмущение помню. Поэтому вопрос снова подняла.

было дело :-) 

> Зачем их учить, спрашивается, если самое крутое выпадает с орка

ну у Орка её ещё нужно забрать;-)

> Этот диалог недоступен из-за кривого условия (нужно одновременно быть и магом, и паладином - что невозможно). А если и был бы доступен, то Милтен просто обучает созданию рун на рунном столе, а не дает их. Создания паладинских рун в оригинале Г2 и Г2НВ нет. Такой вот двойной недосмотр.

это скорее намётки разрабов. которые сначало подумали так, потом вот так, а в итоге сделали вот так. живые черновики проекта ;-) Руну телепорта то паладин всё таки делает :-)


> Если в команде есть Гирион, то пусть обучает всем паладинским рунам.
> Если в команде нет Гириона, то пусть Ватрас обучает среднему лечению и средней атаке.
> Если в команде нет Гириона и Ватраса, то пусть Милтен обучает малому лечению и малой атаке.
> (?)

Давай с другой стороны. Если Гириона нет в команде, то... Герой убил Гириона :-) Если герой убил Гириона, то скорее всего не будет и Ватраса ;-) 
Малая стрела, которой научит Мильтен, вообще никак не поможет на Ирдорате.

как альтернативный вариант Мильтену можно просто дать много свитков лечения и пару свитков паладинских, если нету Паладина на корабле.
