### ISSUE TITLE
Диего. Информация про рудокопов / Миненталь

### ISSUE THREAD

**Issue by Kor-Angar** [dosinabox/g2nr_unofficial_update#26]
возвращаюсь к вопросу Диего, его смерти и инфы для Гаранда.

Может сделать что бы диалог с предложением пойти к выходу был доступен после диалога о руде? 
тогда мы минимизируем вероятность смерти Диего до получение инфы.

**Comment by dosinabox** [comment]
В этом нет необходимости, потому что Диего теперь вообще не обязателен для инфы. В случае его смерти можно найти труп Сильвестро в шахте и прочитать его отчет в записке.
