### ISSUE TITLE
НПС применяет заклинание Исцеление.

### ISSUE THREAD

**Issue by Kor-Angar** [dosinabox/g2nr_unofficial_update#260]
Сейчас НПС применяют закли исцеления во время боя. Т.е. паладины вместо того что сражаться убирают оружие, становясь беззащитными и кастуют заклинание. На практике Паладины и Маги из-за это стали слабее, так как переходя в режим лечения они теряют шанс победить героя. условно в 3 из 10 случаев паладин им шанс победить героя если бы не начал лечится.

Возможно им следует докрутить ИИ. Что бы они лечились после боя, а не во время.
https://github.com/dosinabox/g2nr_unofficial_update/issues/244

**Comment by dosinabox** [comment]
Теперь маги и паладины будут лечиться только если ГГ избит, мертв, находится в состоянии магического сна или дальше дистанции дальнобойного оружия (> 1000 попугаев). Проверишь с новой сборкой.

**Comment by Kor-Angar** [comment]
Ок.

**Comment by Kor-Angar** [comment]
https://github.com/dosinabox/g2nr_unofficial_update/issues/244

**Comment by Kor-Angar** [comment]
работало корректно.

**Comment by dosinabox** [comment]
А лечатся ли в оригинале Ищущие?

**Comment by Kor-Angar** [comment]
нет

**Comment by Kor-Angar** [comment]
точнее ни разу не встречал -)
