### ISSUE TITLE
двуручное оружие. 2 H

### ISSUE THREAD

**Issue by Kor-Angar** [dosinabox/g2nr_unofficial_update#261]
Традиционно напоминаю о том что оружие всё так же продаётся по главам и купить что то полезное невозможно. попытка сделать оружие как луки/арбалеты длится более полутора лет и в связи с этим есть предложение опять же таки опционально вернуть оружие в продажу так как оно было реализовано в Готики 2 НВ у Пираний.

так же обратил внимание что не хватает двуручного оружия с которым у героя был бы суммарный ущерб был 180. например 90/90 или 95/85 или 85/95.

на дубину 110/110 в Ярике в 3 главе силы не хватило. попробовать её в действие не смог.

**Comment by dosinabox** [comment]
Я сейчас в небольшом отпуске. Вернусь и займусь.

**Comment by Kor-Angar** [comment]
отпуск в холодных странах? :-)

**Comment by dosinabox** [comment]
Страна та же, край южный, погода жаркая)

**Comment by Kor-Angar** [comment]
Хитро 😀

**Comment by dosinabox** [comment]
https://github.com/dosinabox/g2nr_unofficial_update/issues/262
