### ISSUE TITLE
Ребаланс одноручного и двуручного оружия в продаже

### ISSUE THREAD

**Issue by dosinabox** [dosinabox/g2nr_unofficial_update#262]

**Comment by dosinabox** [comment]
> не хватает двуручного оружия с которым у героя был бы суммарный ущерб был 180. например 90/90 или 95/85 или 85/95.

**Comment by Kor-Angar** [comment]
по ЛОРу во второй главе городской кузнец заканчивает работу на Палов и делает оружие на продажу (рыночная площадь)

**Comment by Kor-Angar** [comment]
BAU_908_Hodges оказывает не был вооружен двуручным мечём ;-)
https://github.com/Kor-Angar/G2_NotR_MDK/blob/fb531d932179a6f3476ca44f52fc52c38cbffe38/PrjGOTHIC/Story/NPC/BAU_908_Hodges.d#L20

**Comment by Kor-Angar** [comment]
у Тендора в инстанции какой то топор. хотя в оригинале был меч паладина
https://github.com/Kor-Angar/G2_NotR_MDK/blob/fb531d932179a6f3476ca44f52fc52c38cbffe38/PrjGOTHIC/Story/NPC/PAL_260_Tandor.d#L19

**Comment by dosinabox** [comment]
> у Тендора в инстанции какой то топор. хотя в оригинале был меч паладина

потому что он всё равно нацепит топор после торговли

**Comment by Kor-Angar** [comment]
у Скатти одноручное оружие в оригинале 
https://github.com/Kor-Angar/G2_NotR_MDK/blob/fb531d932179a6f3476ca44f52fc52c38cbffe38/PrjGOTHIC/Story/NPC/BDT_1086_Addon_Scatty.d#L19

**Comment by Kor-Angar** [comment]
у ItMw_1H_Blessed  стоит 	flags = ITEM_SWD | ITEM_MISSION;
у ItMw_2H_Blessed  стоит 	flags = ITEM_2HD_SWD;

это значит что одноручный меч паладина можно продавать торговцам, а потом его отбирать? :-)

**Comment by dosinabox** [comment]
да

**Comment by Kor-Angar** [comment]
напомни пожалуйста зачем второй топовый топор был добавлен?

**Comment by dosinabox** [comment]
> напомни пожалуйста зачем второй топовый топор был добавлен?

Во-первых, чтобы задействовать неиспользуемую текстуру.
Во-вторых, чтобы был резон его покупать. Более красивый - в продаже, менее красивый - бесплатно валяется на Ирдорате (и ещё где-то (?)).
