### ISSUE TITLE
Простой Лук и Арбалет на Ирдорате

### ISSUE THREAD

**Issue by Kor-Angar** [dosinabox/g2nr_unofficial_update#265]
Мне кажется надо добавить Диего в продажу самый простой Лук и Арбалет после вот этого диалога 
```
EVT_DIBRIDGE_OPENED == FALSE))
	{
		AI_Output(other,self,"DIA_PC_Thief_DI_RAT_15_04");	//Я сражался с драконом и теперь застрял перед пропастью с подъемным мостом. Этот мост поднят, и я не знаю, как опустить его.
		AI_Output(self,other,"DIA_PC_Thief_DI_RAT_11_05");	//Ммм. А ты не пробовал дальнобойное оружие? Может быть, механизм можно активировать при помощи выстрела.
	}
```

**Comment by Kor-Angar** [comment]
в сундуке возле дракона лук требует 25 ловкости
![image](https://user-images.githubusercontent.com/49514764/86546307-e9392200-bf3c-11ea-94c2-3bcf96f44a16.png)

**Comment by dosinabox** [comment]
А если вставлять самый простой лук, то зачем проверять ловкость ГГ и вставлять зелье ловкости? Тут два варианта:
- вставлять самый простой лук и не вставлять зелье ловкости
- вставлять столько зелий ловкости, сколько не хватает ГГ до 25

**Comment by Kor-Angar** [comment]
вреда от того что у Диего будет в продаже простой Лук нет. это и ЛОРу соответсвует и вытекает из его советов. 

Зелья ловкости вставляется на тот случай, если всё пошло не так : нет ловкости, команда мёртвая/странная и так далее. Такой вариант вполне возможен. Именно ввиду такого маловероятно события и  возник топик. 

Но Лук и Диего это понятный вариант и он в голове у игрока может появится. а вставка зелий, так как на лук в сундуке не хватает ловкости вариант возникающий в голове у автора скриптов, как попытка заделать дырку :-)

**Comment by Kor-Angar** [comment]
И беннету можно добавить пару арбалетов.

**Comment by dosinabox** [comment]
Диего в команде может и не быть) Да и на время атаки орков он смертный.

**Comment by Kor-Angar** [comment]
так про то и речь. у него Диего же диалог про это ловушку для которой лук есть. и он стрелы продаёт. а Лука у него в продаже нет.

**Comment by dosinabox** [comment]
Лук и/или арбалет в продажу я-то добавлю, но это не решит проблему полностью.
Как быть игрокам, которые не взяли в команду Диего и Беннета, и которым не хватит ловкости на лук наемника из сундука даже с учетом халявного зелья?

**Comment by Kor-Angar** [comment]
> Как быть игрокам, которые не взяли в команду Диего и Беннета, и которым не хватит ловкости на лук наемника из сундука даже с учетом халявного зелья?

самый простой способ это добавить куда нибудь арбалет.  например там где стоит ищущий сделать труп с арбалетом и болтами.


> Лук и/или арбалет в продажу я-то добавлю, но это не решит проблему полностью.

можно сделать лук / арбалет квестовый, что бы если Диего / беннета убили орки можно было бы с трупа поднять.

**Comment by dosinabox** [comment]
На корабль добавлен короткий лук 15/10. Стрелы есть в сундуках в пещере огненного дракона.

**Comment by Kor-Angar** [comment]
у Диего был лук в классике. это твои правки? :-)

```D
func void b_givetradeinv_diego_di(var C_NPC slf)
{
	CreateInvItems(slf,itrw_arrow,160);
	CreateInvItems(slf,itrw_bolt,120);
	CreateInvItems(slf,itke_lockpick,20);
	CreateInvItems(slf,itrw_bow_l_01,1);
};

```
