### ISSUE TITLE
Переодевание Грега

### ISSUE THREAD

**Issue by dosinabox** [dosinabox/g2nr_unofficial_update#269]
Проверить, сменит ли Грег (находящийся в городе или у таверны) крестьянскую одежду на одежду капитана, если выкопать его клад в пещере со статуэткой. См. RAKEPLACE[1].

**Comment by Kor-Angar** [comment]
не сменил. Грега надо переодевать в диалоге с Лареса. Что бы он возле Таверны сидел всегда в одежде капитана.

**Comment by Kor-Angar** [comment]
> Грега надо переодевать в диалоге с Лареса. Что бы он возле Таверны сидел всегда в одежде капитана.

это если по уму делать :-)

**Comment by dosinabox** [comment]
> не сменил

И это хорошо.

> Грега надо переодевать в диалоге с Лареса

Для этого Грег должен быть в поле видимости игрока. Иначе в игре доспехи не переодеваются.

**Comment by Kor-Angar** [comment]
так его можно во время диалога с Ларесом в таверне в порту переодеть

```
	AI_Teleport(Greg_NW,"NW_CITY_HABOUR_TAVERN01_02");	
	AI_EquipArmor(Greg_NW,ITAR_PIR_H_Addon);
	AI_Teleport(Greg_NW,"NW_TAVERNE_GREGSBENCH");	
```

**Comment by Kor-Angar** [comment]
неделю пробовал по разному. ничего эффективнее чем переодевание через телепорт не нашёл.

**Comment by dosinabox** [comment]
> так его можно во время диалога с Ларесом в таверне в порту переодеть

этот трюк не сработал с лордом Хагеном

**Comment by Kor-Angar** [comment]
А кого ты хотела переодеть?

**Comment by Kor-Angar** [comment]
напиши плиз ты хотел Хагена переодеть или НПС в диалоге с Хагеным?

**Comment by Kor-Angar** [comment]
сейчас(спустя 10 часов тыканий) точно могу сказать, что если писать с нуля, то проще всего использовать разные инстанции. на разные куски игры. может быть даже для некоторых НПС  типа Лареса или Беннета на разные главы использовать разные Инстанции.
Того же Грега можно просто разделить на инстанцию до Таверны и после :-)
