### ISSUE TITLE
Неиспользуемые тексты книг

### ISSUE THREAD

**Issue by dosinabox** [dosinabox/g2nr_unofficial_update#27]
В скриптах есть пять заготовок под книги в монастырской библиотеке (BookstandKloster.d). Прописаны названия объектов и заголовки:
```
Bookstand_Rune_01 - Рунные камни
Bookstand_Rune_02 - Руны и ингредиенты
Bookstand_Innos_01 - Учение Инноса
Bookstand_Innos_02 - Заповеди Инноса
Bookstand_Rules_01 - Правила
```
Можно придумать тексты для этих книг и где-нибудь их использовать.

**Comment by Kor-Angar** [comment]
можно посмотреть тексты из 1 Готики. может подойдут

**Comment by Kor-Angar** [comment]
Когда Боги решили даровать человечеству магию, они заодно научили их и мастерству изготовления рун. Слуги божьи взяли на себя обязанности по созданию этих могущественных артефактов и их использованию. Каждый из кругов магов определяет для себя, какую магию он может постичь и какой будет пользоваться.

Всякая магия имеет своим началом силу, заключенную в человеке. Человек, имеющий такие силы, называется магом. Каждое заклинание отнимает у мага часть его сил. Эти силы именуются маной.

Некоторые заклинания поглощают определенную часть магической силы. Такие заклинания называют заклинаниями заряда. Другие заклинания продолжают действовать до тех пор, пока маг позволяет им черпать свою энергию. Такие заклинания принято называть заклинаниями покрова.
************

МАГИЯ ТЕЛЕПОРТАЦИИ
Особенностью данных магических формул является то, что хотя они также заключены в рунах, использовать их может любой человек, обладающий магическими больше силами. Формула может быть активирована мгновенно. Никаких ограничений для магии телепортации нет.
************
Секреты Магии

Магия не сокрыта в самом маге, он просто обладает умением работать с ней. Он умеет влиять на магию и направлять ее.
Практикующий это искусство должен быть способен использовать свой дух, как инструмент.
Дух его служит вместилищем для мечущихся во всех направлениях магических сил. Он собирает их, фокусирует и отправляет в том мир, который мы знаем. В такие моменты дух мага воспаряет и видит тот, другой мир, обиталище силы. Помните, маг только приносит ее и придает ей форму.

Бартос Ларанский
************
Могущественное Искусство
Работа мага

Способность мага контролировать божественную энергию способна развиваться. Сначала она появляется, как росток из зерна. Необходимо лелеять его, иначе он погибнет. Но как только побег окрепнет, появятся и первые плоды. С каждым днем эта способность будет расти все быстрее и быстрее. Вначале сила может быть малой, но дайте ей время, и она вырастет до пределов, которые трудно предсказать. Направлять и оттачивать эту способность и эту силу до того момента, как она достигнет совершенства - вот святая обязанность мага. Потому как брошенное богами семя смертному принять и вырастить должно.
************
Основы Магии

Место магии в миропорядке

Чтобы выяснить место магии и ее связь с основными элементами, было проведено много исследований. Все они сходятся в одном: магия стоит выше всех элементов. Она может трансформировать их, изменять форму, то есть повелевать ими. Каждый элемент, если рассматривать его в первородной форме, имеет связь с магией. Подобные связи можно проследить лишь в некоторых местах, и эти места разыскивают многие. Способность мага создавать или призывать элементы, казалось бы, из пустоты, еще раз доказывает, что магия является самой могущественной силой во вселенной.
************
Настоящая Сила

Святая обязанность

Маг не похож на обычных людей. Он обладает способностью влиять на божественную силу, а посему и неподвластен законам природы, которым подчиняется каждый смертный. Когда маг достигает того уровня, позволяющего ему подняться над рамками обычного существования, он может войти в другой мир, неведомый простым смертным. Маг может прорваться через границы времени и пространства, и даже смерть, основа всего сущего, не сумеет остановить его.
************
Дар Богов
Человек на протяжении многих веков пытается понять природу и истоки магии. Но где же начинать поиски? Как вообще описать, что такое магия? Это самая противоречивая сущность во вселенной. Она может убивать и исцелять, создавать и уничтожать. Как она выглядит? Где человек может отыскать ее, невидимую, но удивительно могущественную? Магия - это магия. Это самый удивительный дар богов тем, кто может его использовать. Целительная сила, которую могут контролировать лишь единицы.

Бартос Ларанский
************
Слова Богов - том первый
Услышь же слова Богов, ибо в этом есть Их воля. Прими учение Богов, ибо в этом есть Их воля. Почитай служителей Божьих, ибо избраны они Ими.

Иннос сказал: И если случится так, что не поймете вы слова служителей, не сомневайтесь, потому что они правильны и мудры. Я есть солнце, свет и жизнь. И все, что против солнца - есть против меня, и должно оно быть повергнуто в царство теней на веки вечные.

Аданос сказал: Работайте и живите, ибо создан день, чтобы человек мог работать. Ищите знание, чтобы передавать его детям, ибо для этого были созданы вы. А те, кто праздности и лени предаются, должны быть повергнуты в царство теней на веки вечные.

Белиар сказал: Кто будет делать не так, и вершить дела свои против воли богов, тот будет мной наказан. Я наполню тело его болезнью, страданием и смертью, а дух его присоединится ко мне в царстве теней на веки вечные.

Слова Богов - том второй
О начале времен: Не было ни дня, ни ночи, и не было ни одной твари живой. Потом пришел Иннос, дал жизнь этому миру и принес с собой свет. Но слишком ярок был свет Инноса, а потому породил он Солнце. Однако и это было непереносимо для живых тварей, и тогда Иннос разделил себя и породил Белиара. Белиар породил ночь. Теперь человек мог жить. Тогда Иннос разделил себя вновь и породил Аданоса. Аданос наделил человека подвижностью, жаждой знания, любопытством и смелостью. И посмотрел Иннос на дело рук своих и решил, что это хорошо. После Иннос отдыхал, а Аданос следил за людьми. Люди не поклонялись Белиару, потому что ночью они спали. В гневе и ярости Белиар породил одного человека, чтобы хотя бы он поклонялся ему. Но это был все равно человек, а потому ночью он тоже спал. Белиар убил его и сказал: если они не поклоняются мне, так пусть хотя бы боятся. И породил он смерть, и стали люди умирать.

Слова Богов - том третий
Захотел Иннос, чтобы люди могли слышать его и говорить с ним. И стали они слышать и говорить. Тогда подарил он им способность творить чудеса и назвал это магией. С ее помощью смогли люди сами создавать миры, а Иннос не стал мешать им. Так люди получили в свои руки часть божественной силы. Однако люди оказались разными, а потому некоторые не могли творить великие чудеса и начали роптать. Иннос забрал силу у недовольных и наградил тех, кто поклонялся ему и чтил его. Вскоре люди стали, боятся, и гнать этих немногих, которых назвали священниками. Но и среди священников появились недовольные. Стали они говорить с Аданосом и забыли Истоки. Так разделились священники. Начались войны, и вера в единого бога была утеряна. Пошедшие за Аданосом назвали себя магами круга воды, а священники Инноса назвали себя магами круга огня.

**Comment by Kor-Angar** [comment]
> В скриптах есть пять заготовок под книги в монастырской библиотеке (BookstandKloster.d).

это какая библиотека? внизу или наверху?

смотри сколько текстов есть в Готике 1. есть из чего выбрать. и даже полезная инфа про руны и свитки.

**Comment by Kor-Angar** [comment]
> В скриптах есть пять заготовок под книги в монастырской библиотеке (BookstandKloster.d). 

давай выясним где эти подставки стоят. я так и не понял до сих пор где.

**Comment by dosinabox** [comment]
Нигде, все книжные стенды заняты существующими текстами.
Только в казармах ополчения один пустой стенд, но к нему ничего не привязано.

**Comment by dosinabox** [comment]
```
instance ItWr_Vatras_KDFEmpfehlung_Addon(C_Item)
{
	name = "Рекомендательное письмо Ватраса";
	mainflag = ITEM_KAT_DOCS;
	flags = ITEM_MISSION;
	value = 0;
	visual = "ItWr_Scroll_01.3DS";
	material = MAT_LEATHER;
	on_state[0] = Use_VatrasKDFEmpfehlung_Addon;
	scemeName = "MAP";
	description = name;
	text[0] = "Это письмо поможет мне";
	text[1] = "попасть в монастырь магов Огня,";
	text[2] = "не заплатив за вход.";
	inv_rotz = 180;
	inv_rotx = 90;
	inv_roty = 180;
};

func void Use_VatrasKDFEmpfehlung_Addon()
{
	var int nDocID;
	nDocID = Doc_Create();
	Doc_SetPages(nDocID,1);
	Doc_SetPage(nDocID,0,"letters.TGA",0);
	Doc_SetFont(nDocID,-1,FONT_Book);
	Doc_SetMargins(nDocID,-1,50,50,50,50,1);
	Doc_PrintLine(nDocID,0,"");
	Doc_PrintLine(nDocID,0,"");
	Doc_PrintLine(nDocID,0,"");
	Doc_PrintLines(nDocID,0,"Братья Огня!");
	Doc_PrintLines(nDocID,0,"");
	Doc_PrintLines(nDocID,0,"Мне стало известно, что за вход в ваш монастырь вы требуете плату.");
	Doc_PrintLines(nDocID,0,"С этим письмом я направляю вам молодого человека, который страстно желает присоединиться к вам.");
	Doc_PrintLine(nDocID,0,"");
	Doc_PrintLine(nDocID,0,"     Ватрас");
	Doc_Show(nDocID);
};
```

**Comment by dosinabox** [comment]
Карта Миненталя на стенде используется?
```cpp
func void Bookstand_Milten_01_S1()
{
	var int Document;
	if(C_NpcIsHero(self))
	{
		Document = Doc_CreateMap();
		Doc_SetPages(Document,1);
		Doc_SetPage(Document,0,"Map_OldWorld.tga",TRUE);
		Doc_SetLevel(Document,"OldWorld\OldWorld.zen");
		Doc_SetLevelCoords(Document,-78500,47500,54000,-53000);
		Doc_Show(Document);
	};
};
```

**Comment by Kor-Angar** [comment]
Это которую читает продовец Мент?

**Comment by dosinabox** [comment]
В скриптах прописан стенд с полной картой Миненталя. Он есть в игре?

**Comment by Kor-Angar** [comment]
В тронном зале  одна на столе, а вторая по моему на стене.

**Comment by Kor-Angar** [comment]
по моему это карта Хориноса, а не Миненталя 
https://steamcommunity.com/id/kor_angar/screenshots/

**Comment by Kor-Angar** [comment]
https://steamuserimages-a.akamaihd.net/ugc/1690500029041566125/E8E9FEC9D72FC205F6C9EAFED6847F778C6DD57F/

**Comment by dosinabox** [comment]
Мы как обычно о разном) Я о стенде в комнате Милтена - там вместо книжных страниц карта Миненталя. Поэтому ответ на мой вопрос - да, используется.

**Comment by dosinabox** [comment]
> по моему это карта Хориноса, а не Миненталя

Их, кстати, было бы хорошо заменить на карты Миненталя. Что там делают карты Хориниса - непонятно (скорее всего, просто поленились делать отдельную текстуру).

**Comment by Kor-Angar** [comment]
> Их, кстати, было бы хорошо заменить на карты Миненталя. 

да. или Миненталя или всего острова(такой нет). а какие это текстуры  подгружаются?

**Comment by Kor-Angar** [comment]
а вот опять тот же вопрос. Эти стенды книжные имеют уникальные индификатору? их можно через марвин/консоль как то узнать? 

т.е. в Минентале есть  уникальный текст 
* книжный стенд у мента - список припасов
* книжный стенд, нижний этаж гильдии магов - карта миненталя 
* книжный стенд, верхний этаж гильдии магов - дневник Корристо
* склеп с юнитором - неуникальный текст про алхимию (я бы заменил его чем нибудь уникальным)
* форт с драконом -

**Comment by dosinabox** [comment]
> Эти стенды книжные имеют уникальные индификатору? их можно через марвин/консоль как то узнать?

Есть имена объектов, но не обязательно у всех и не обязательно уникальные. Посмотреть можно в Spacer.

**Comment by dosinabox** [comment]
- книжный стенд, нижний этаж гильдии магов - карта миненталя
- книжный стенд, нижний этаж гильдии магов - дневник Милтена

**Comment by Kor-Angar** [comment]
PrjGOTHIC\Story\Dialog_Mobsis\Bookstand_OldCamp.d

- Bookstand_Engor_01_S1, мент - список припасов 
- Bookstand_Milten_01_S1, нижний этаж гильдии магов - карта миненталя 
- Bookstand_Milten_02_S1, нижний этаж гильдии магов - дневник Милтена 
- Bookstand_Milten_03_S1, верхний этаж гильдии магов - дневник Корристо 

```
		Document = Doc_CreateMap();
		Doc_SetPages(Document,1);
		Doc_SetPage(Document,0,"Map_OldWorld.tga",TRUE);
		Doc_SetLevel(Document,"OldWorld\OldWorld.zen");
		Doc_SetLevelCoords(Document,-78500,47500,54000,-53000);
		Doc_Show(Document);
```
это карта со стрелочкой? :-)

**Comment by Kor-Angar** [comment]
> это карта со стрелочкой? :-)

попробовал освежить :-)
https://www.youtube.com/watch?v=aGmtf7SbX2o

**Comment by dosinabox** [comment]
Стрелочка пропала.
```cpp
Document = Doc_CreateMap();
Doc_SetPages(Document,1);
Doc_SetPage(Document,0,"Map_World_Foki.tga",TRUE);
Doc_SetLevel(Document,"OldWorld\OldWorld.zen");
Doc_SetLevelCoords(Document,-78500,47500,54000,-53000);
Doc_Show(Document);
```

**Comment by Kor-Angar** [comment]
Я её убрал, что бы смотрелось ярче 😀

**Comment by Kor-Angar** [comment]
> Двум книжным стендам в старой башне Ксардаса в Минентале теперь можно прописать тексты. Принимаются предложения.

ну вот текст про телепорт например. там как раз руна телепорта на столе лежит.

> МАГИЯ ТЕЛЕПОРТАЦИИ
> Особенностью данных магических формул является то, что хотя они также заключены в рунах, использовать их может любой человек, обладающий магическими больше силами. Формула может быть активирована мгновенно. Никаких ограничений для магии телепортации нет.

или вот

> Настоящая Сила
> 
> Святая обязанность
> 
> Маг не похож на обычных людей. Он обладает способностью влиять на божественную силу, а посему и неподвластен законам природы, которым подчиняется каждый смертный. Когда маг достигает того уровня, позволяющего ему подняться над рамками обычного существования, он может войти в другой мир, неведомый простым смертным. Маг может прорваться через границы времени и пространства, и даже смерть, основа всего сущего, не сумеет остановить его.

**Comment by Kor-Angar** [comment]
Да.

**Comment by Kor-Angar** [comment]
добавить тексты пустым каменным скрижалям в залах у портала в Яркендаре

**Comment by Kor-Angar** [comment]
> добавить тексты пустым каменным скрижалям в залах у портала в Яркендаре

ну во первых они должны читаться при наличии навыка языка зодчих :-) а во вторых сколько там стоек? четыре?

на один можно карту повесить. дёшево и сердито :-)

**Comment by dosinabox** [comment]
> ну во первых они должны читаться при наличии навыка языка зодчих :-)

конечно

> а во вторых сколько там стоек? четыре?

шесть
