### ISSUE TITLE
Одноручный Коготь Белиара

### ISSUE THREAD

**Issue by dosinabox** [dosinabox/g2nr_unofficial_update#271]
Если навыки 1р и 2р равны, то давать ГГ одноручный Коготь вместо двуручного (?). Вроде, проскакивала такая мысль.

**Comment by Kor-Angar** [comment]
Да. Обсуждали такое. Одноручнымюй. И проверить такое у Лорда Хагена.

**Comment by dosinabox** [comment]
> И проверить такое у Лорда Хагена.

Это про что?

**Comment by Kor-Angar** [comment]
Он даёт доспехи паладина и меч паладина. 1р или 2р в зависимости от навыка.

**Comment by dosinabox** [comment]
Кстати, а в обоих случаях нужно проверять реальный навык или видимый?

**Comment by Kor-Angar** [comment]
мне кажется видимый. так как на видимый навык игрок может влиять и переодевшись помолится повторно, а на реальный не может.

**Comment by dosinabox** [comment]
С другой стороны - Хаген должен проверять реальный навык, потому что на получение оружия можно повлиять случайно, надев что-то с бонусом. А выдача одноразовая.

Так?

**Comment by Kor-Angar** [comment]
Если 1р с бонусами больше чем 2р, значит герой предпочитает 1р и должен получит от Лорда Хагена...

**Comment by Kor-Angar** [comment]
Или герой случайно одевает кольцо и ходит со шпагой, а на самом деле он то любит двуручный топор? 😀

**Comment by Kor-Angar** [comment]
Можно на самом деле подумать и при молитве Белиару давать выбор оружия 1р или 2р. Что бы игрок сам выбрал версию какую хочет.

**Comment by dosinabox** [comment]
В обоих случаях ГГ получит 1р оружие, если навыки 1р и 2р равны. В обоих случаях проверяются видимые навыки.

**Comment by Kor-Angar** [comment]
и это прекрасно :-)
