### ISSUE TITLE
навыки учителя на основе лимитов их обучения

### ISSUE THREAD

**Issue by Kor-Angar** [dosinabox/g2nr_unofficial_update#276]
> такая же ситуация и у Корда и у Рода и у Вульфгара и у Волка и у большинство учителей

Но ведь в крайней версии обновления всем учителям была прописана новая функция, которая ставит им навыки на основе лимитов их обучения:
```
B_SetTeacherFightSkills(self,TeachLimit_1H_Buster,30,30,30);
B_SetTeacherFightSkills(self,50,50,TeachLimit_Bow_Wolf,TeachLimit_Crossbow_Wolf);
B_SetTeacherFightSkills(self,TeachLimit_1H_Cord,TeachLimit_2H_Cord,70,70);
```
> Все учителя владеют своими навыками на уровнях, соответствующим лимитам их обучения;

**B_NewTalentSystem.d**
```
const int TeachLimit_1H_Cavalorn = 30;
const int TeachLimit_1H_Keroloth = 60;
const int TeachLimit_1H_Alrik = 60;
const int TeachLimit_1H_Buster = 60;
const int TeachLimit_1H_Morgan = 75;
const int TeachLimit_1H_Wulfgar = 75;
const int TeachLimit_1H_Girion = 90;
const int TeachLimit_1H_Cedric = 90;
const int TeachLimit_1H_Cord = 90;
const int TeachLimit_1H_Lares = 100;
const int TeachLimit_1H_Hokurn = 100;
const int TeachLimit_1H_Lee = 100;

const int TeachLimit_2H_Keroloth = 60;
const int TeachLimit_2H_Wulfgar = 75;
const int TeachLimit_2H_Babo = 75;
const int TeachLimit_2H_Henry = 90;
const int TeachLimit_2H_Girion = 90;
const int TeachLimit_2H_Rod = 90;
const int TeachLimit_2H_Cord = 90;
const int TeachLimit_2H_Hokurn = 100;
const int TeachLimit_2H_Hagen = 100;
const int TeachLimit_2H_Lee = 100;
const int TeachLimit_2H_Gorn = 100;

const int TeachLimit_Bow_Niclas = 60;
const int TeachLimit_Bow_Bartok = 60;
const int TeachLimit_Bow_AlligatorJack = 75;
const int TeachLimit_Bow_Wolf = 90;
const int TeachLimit_Bow_Cavalorn = 90;

const int TeachLimit_Crossbow_Udar = 60;
const int TeachLimit_Crossbow_Dragomir = 75;
const int TeachLimit_Crossbow_Henry = 80;
const int TeachLimit_Crossbow_Girion = 90;
const int TeachLimit_Crossbow_Ruga = 90;
const int TeachLimit_Crossbow_Wolf = 100;

const int TeachCondition_Cord = 30;
const int TeachCondition_2H_Lee = 75;
const int TeachCondition_2H_Hagen = 90;
```

**Comment by Kor-Angar** [comment]
а у Рода какие параметры получилось?  с ним же тоже дуэль при вступление в Наёмники.

**Comment by dosinabox** [comment]
> а у Рода какие параметры получилось? с ним же тоже дуэль при вступление в Наёмники.

было 50, стало 90

**Comment by Kor-Angar** [comment]
А кто нибудь тестил? 😀

**Comment by Kor-Angar** [comment]
так получается у Каваларона 1р стал 30% ?

**Comment by dosinabox** [comment]
> так получается у Каваларона 1р стал 30% ?

Получается так.
Думаю, в таких случаях можно ничего не менять. Если обучает меньше чем знает - это нормально.

**Comment by Kor-Angar** [comment]
> Думаю, в таких случаях можно ничего не менять.

 это да. но тогда наверное надо добавить проверку в **B_SetFightSkills** что бы навык учителя не снижался до лимита обучения?

**Comment by Kor-Angar** [comment]
**B_NewTalentSystem.d**
const int TeachLimit_1H_Cavalorn = 30;
const int TeachLimit_1H_Keroloth = 60;
const int TeachLimit_1H_Alrik = 60;
const int TeachLimit_1H_Buster = 60;
const int TeachLimit_1H_Morgan = 75;
const int TeachLimit_1H_Wulfgar = 75;
const int TeachLimit_1H_Girion = 90;
const int TeachLimit_1H_Cedric = 90;
const int TeachLimit_1H_Cord = 90;
const int TeachLimit_1H_Lares = 100;
const int TeachLimit_1H_Hokurn = 100;
const int TeachLimit_1H_Lee = 100;

const int TeachLimit_2H_Keroloth = 60;
const int TeachLimit_2H_Wulfgar = 75;
const int TeachLimit_2H_Babo = 75;
const int TeachLimit_2H_Henry = 90;
const int TeachLimit_2H_Girion = 90;
const int TeachLimit_2H_Rod = 90;
const int TeachLimit_2H_Cord = 90;
const int TeachLimit_2H_Hokurn = 100;
const int TeachLimit_2H_Hagen = 100;
const int TeachLimit_2H_Lee = 100;
const int TeachLimit_2H_Gorn = 100;

const int TeachLimit_Bow_Niclas = 60;
const int TeachLimit_Bow_Bartok = 60;
const int TeachLimit_Bow_AlligatorJack = 75;
const int TeachLimit_Bow_Wolf = 90;
const int TeachLimit_Bow_Cavalorn = 90;

const int TeachLimit_Crossbow_Udar = 60;
const int TeachLimit_Crossbow_Dragomir = 75;
const int TeachLimit_Crossbow_Henry = 80;
const int TeachLimit_Crossbow_Girion = 90;
const int TeachLimit_Crossbow_Ruga = 90;
const int TeachLimit_Crossbow_Wolf = 100;

const int TeachCondition_Cord = 30;
const int TeachCondition_2H_Lee = 75;
const int TeachCondition_2H_Hagen = 90;

**Comment by Kor-Angar** [comment]
> const int TeachLimit_2H_Gorn = 100;

это на инстанцию 6 главы или на 2,3, 4 и 5 тоже ?

> const int TeachLimit_1H_Lares = 100;

это на 6 главу? или на первые главы тоже?

**Comment by dosinabox** [comment]
> это на инстанцию 6 главы или на 2,3, 4 и 5 тоже ?
> это на 6 главу? или на первые главы тоже?

Оба на 6.

Предлагаю заполнить: https://docs.google.com/spreadsheets/d/1svDbXAiYe7PLCQ7G0Arjh_njRiDabsRC-9GuLt7APsQ/edit#gid=355758555

**Comment by Kor-Angar** [comment]
надо в файле B_NewTalentSystem.d править. добавить в  TeachLimit_1H_Lee_DI для учителей 6 главы.

**Comment by Kor-Angar** [comment]
а Сержио у тебя в таблице в рамках бонуса сержио? :-)

**Comment by Kor-Angar** [comment]
твою табличку не смог заполнить. но рядом сделал свою и заполнил.

**Comment by Kor-Angar** [comment]
а про Сержио расскажи плиз
	B_SetTeacherFightSkills(self,65,90,65,65);

**Comment by dosinabox** [comment]
> а про Сержио расскажи плиз
> B_SetTeacherFightSkills(self,65,90,65,65);

Он выступает учителем для Бабо, а значит его навык должен быть больше 75 (TeachLimit_2H_Babo).

**Comment by Kor-Angar** [comment]
понятно. а то я уже стал думать что чего то пропустил :-) а тут оказывается просто социальные связи. Сержио повезло :-) 
Ларсу не повезло, Горну не повезло :-)

**Comment by dosinabox** [comment]
Табличка обновлена. Получилось хорошо, по-моему. Исключениями стали только трое: Альрик, Бастер и Род. У остальных навыки не меньше лимитов обучения, а если больше чем в оригинале, то на баланс не особо влияет. У многих вообще без изменений.

Заодно.
Род в Хоринисе: 50% навыков.
Род в Минентале: 70% навыков.
Что делать? Можно ничего не делать)

**Comment by Kor-Angar** [comment]
> Исключениями стали только трое: Альрик, Бастер и Род.

комменты в таблице добавил.

> Что делать? Можно ничего не делать)

я вот разбераюсь. нашёл пачку скриптов из Готики 2 классик немецкой, хочу посмотреть не закралась ли ошибка. так как Род и Сайфер всё таки идут бить драконов. и вообще именные НПС почему то слабее балванок.  я у себя это дело до ума доведу конечно. может ты посмотришь финальную редакцию и внедришь прототипы. тогда станет НПС править проще и ошибок будет меньше, так как у них там сейчас всё скачать :-)

**Comment by Kor-Angar** [comment]
Не пора ли бонус Вульфгара ограничить его лимитом как учителя? :-)

**Comment by dosinabox** [comment]
> Не пора ли бонус Вульфгара ограничить его лимитом как учителя? :-)

Это как? Не давать бонус, если достигнут лимит обучения?

**Comment by dosinabox** [comment]
> Род

Там еще по статам разница:

Хоринис:
```
B_SetAttributesToChapter(self,2);
fight_tactic = FAI_HUMAN_STRONG;
```

Миненталь:
```
B_SetAttributesToChapter(self,4);
fight_tactic = FAI_HUMAN_MASTER;
```

**Comment by Kor-Angar** [comment]
Там надо сделать у Горацио сделано в Готики 1. Если навык 74 давать 1 очко., если 75 то не давать. Есть меньше 74 то давать два. И все таки не давать бонус нашему и ОнД. И я об этом писал сто лет назад на WoP и Димус обращал внимание с пол года назад и на других форумах иногда этот момент поднимают. На баланс это не повлияет так как к 1р бонусов больше всего. А у всех мечей наемов идёт бонус к 1р. Ну и ты сон до восхода добавила, так что теперь этот бонус взять вообще легко. Не надо всю ночь где то бродить 😀23:08, 30 сентября 2020 г., dosinabox <notifications@github.com>:

Не пора ли бонус Вульфгара ограничить его лимитом как учителя? :-)

Это как? Не давать бонус, если достигнут лимит обучения?

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
-- Отправлено из мобильного приложения Яндекс.Почты

**Comment by Kor-Angar** [comment]
Ну вот мне и хотелось посмотреть как там дела в скриптах немецких Готики 2 классик. Не был ли он изначально одинаковый? 😀23:12, 30 сентября 2020 г., dosinabox <notifications@github.com>:

Род

Там еще по статам разница:
Хоринис:
B_SetAttributesToChapter(self,2);
fight_tactic = FAI_HUMAN_STRONG;

Миненталь:
B_SetAttributesToChapter(self,4);
fight_tactic = FAI_HUMAN_MASTER;


—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
-- Отправлено из мобильного приложения Яндекс.Почты

**Comment by dosinabox** [comment]
> Не был ли он изначально одинаковый?

В классике всё точно так же. 2-50-strong / 4-70-master.

**Comment by Kor-Angar** [comment]
Видимо из-за того что ГГ нейтрал должен его побить. Что бы легче было. Там де по квест у Ярвиса надо троих побить из пяти. Это сейчас бьют пятерых из пяти ради интересно, а достаточно побить троих. Трое слабых, два сильных. Но Рода можно бить когда он без меча 😀23:18, 30 сентября 2020 г., dosinabox <notifications@github.com>:

Не был ли он изначально одинаковый?

В классике всё точно так же. 2-50-strong / 4-70-master.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
-- Отправлено из мобильного приложения Яндекс.Почты
