### ISSUE TITLE
Предводители орков

### ISSUE THREAD

**Issue by dosinabox** [dosinabox/g2nr_unofficial_update#28]
- [x] Повысить уровень усиленным предводителям (до какого? 45->50?)
- [x] Сделать настройку выключения усиленных предводителей

**Comment by Kor-Angar** [comment]
я вот как раз до них дошел. еще ни одного не убивал. могу скинуть сейвы.
мне достаточно будет опционального отключения, так как их жёсткость не возможно компенсировать опытом:-) ну и если честно мне логика их ужесточения не понятна, так как в других фракциях противники объективно слабее :

- [ ] - при игре за ОНД появляются люди Ящеры за них дают по  350 опыта. 
- [ ] - при игре за Мага появляются Ищущие за них дают 300 опыта
- [ ] - при игре за Пала появляются Орки Командиры за них дают 450 опыта

очевидно что Орки командиры самый жёсткий вариант, может быть поэтому разработчики и сделали их чуть чуть слабее чем элитных орков.

**Comment by Kor-Angar** [comment]
при этом я конечно понимаю что многие считают что оригинальная игра дескать и так простая, а то что монстры стали послабее это наоборот хорошо и т.д. и т.п.  
но ведь обновление не про то что бы в игре переработать баланс :-) если править баланс то можно начать с драконов :-))

**Comment by dosinabox** [comment]
Готово, но такое переключение возможно только **до** вставки предводителей в мир.

**Comment by Kor-Angar** [comment]
вообщем посмотрел я на этих орков, полностью прокаченным персонажем. они у вас просто не сбалансированы. параметры их не сопоставлялись с ущербом в игре. 
Эти орки убивают с **трех ударов** как одноручным оружием с ущербом 130, так с **трех ударов** и двуручным оружием с ущербом 200.

https://www.twitch.tv/videos/475616577

**Comment by Kor-Angar** [comment]
Орки Предводители не убивается самым сильным заклинанием паладина, а в оригинальной игре убивались

**Comment by Kor-Angar** [comment]
Destroy Evil - 600 ущерба от магии

**Comment by Kor-Angar** [comment]
про 3 диалога Орков Командиров. что бы орки адекватно реагировали на ГГ надо их три раза выслушать?

```
var int AntiPaladinTalkcount;

func void B_AssignORC_AntiPaladinTalk(var C_Npc Antipaladin)
{
	if(AntiPaladinTalkcount == 0)
	{
		AI_Output(self,other,"DIA_ORC_AntiPaladin_18_06");	// ’–ќ √Ќј–! ћы убивать теб¤, паладин.
		AI_Output(self,other,"DIA_ORC_AntiPaladin_18_03");	//’аген и его люди будут уничтожены. ƒаже ты не смочь помочь им.
		B_GivePlayerXP(XP_Ambient);
	}
	else if(AntiPaladinTalkcount == 1)
	{
		AI_Output(self,other,"DIA_ORC_AntiPaladin_18_01");	// ’–ќ √Ќј–! ’оз¤ин говорить ты паладин теперь! ’оз¤ин прав. ’оз¤ин всегда прав.
		AI_Output(self,other,"DIA_ORC_AntiPaladin_18_02");	//ћы, предводители гордой армии орков, теперь сами прийти убивать великий паладин.
	}
	else
	{
		AI_Output(self,other,"DIA_ORC_AntiPaladin_18_05");	//ћы, предводители орков, теперь сами идти убивать теб¤, паладин.
		AI_Output(self,other,"DIA_ORC_AntiPaladin_18_04");	//’оз¤ин говорить предводител¤м орков, принесите голову великого паладина. “ы умирать от моей руки.  ’–ќ √Ќј–!
	};
	AntiPaladinTalkcount += 1;
	TalkedTo_AntiPaladin = TRUE;
	AI_StopProcessInfos(Antipaladin);
	Antipaladin.aivar[AIV_EnemyOverride] = FALSE;
	Npc_SetRefuseTalk(Antipaladin,20);
};
```
в немецкой версии 4 раза?

```
var int AntiPaladinTalkcount;

func void B_AssignORC_AntiPaladinTalk(var C_Npc Antipaladin)
{
	if(AntiPaladinTalkcount == 0)
	{
		AI_Output(self,other,"DIA_ORC_AntiPaladin_18_01");	//KHROKGNAR! Meister sagen, du jetzt Paladin. Meister hatte Recht. Meister hatte immer Recht.
		AI_Output(self,other,"DIA_ORC_AntiPaladin_18_02");	//Wir Anfьhrer der stolzen Orkarmee nun selbst kommen, um groЯen Paladin zu tцten.
		AI_Output(self,other,"DIA_ORC_AntiPaladin_18_03");	//Hagen werden untergehen mit seinen Mannen. Auch du nicht ihnen helfen kцnnen.
		B_GivePlayerXP(XP_Ambient);
	}
	else if(AntiPaladinTalkcount == 1)
	{
		AI_Output(self,other,"DIA_ORC_AntiPaladin_18_04");	//Meister sagen Orkanfьhrer, bringen Kopf von groЯen Paladin. Du jetzt sterben durch meine Hand. KHROKGNAR!
	}
	else if(AntiPaladinTalkcount == 2)
	{
		AI_Output(self,other,"DIA_ORC_AntiPaladin_18_05");	//Wir Ork-Anfьhrer jetzt selbst gekommen, dich zu tцten, Paladin.
	}
	else
	{
		AI_Output(self,other,"DIA_ORC_AntiPaladin_18_06");	//KHROKGNAR! Wir dich tцten, Paladin.
	};
	AntiPaladinTalkcount = AntiPaladinTalkcount + 1;
	TalkedTo_AntiPaladin = TRUE;
	AI_StopProcessInfos(Antipaladin);
	Antipaladin.aivar[AIV_EnemyOverride] = FALSE;
	Npc_SetRefuseTalk(Antipaladin,20);
}; 
```

те орки что сейчас очень несерьезные. раньше в пещере на героя нападало сразу 3-4 орка командира и легко убивали героя. сейчас они стоят и ждут когда ГГ их убьет. это плохо

**Comment by Kor-Angar** [comment]
ссылка на сейвы
https://yadi.sk/d/H2yBCFui18-yVw

**Comment by dosinabox** [comment]
> про 3 диалога Орков Командиров. что бы орки адекватно реагировали на ГГ надо их три раза выслушать?

Все реагируют адекватно. Если неадекватно - то это проблема ИИ или движка.

> раньше в пещере на героя нападало сразу 3-4 орка командира и легко убивали героя. сейчас они стоят и ждут когда ГГ их убьет

Сейчас предводители с диалогами стоят отдельно и им никто не мешает поговорить с ГГ. В оригинале два предводителя стояли в компании других орков, которые агрили их при виде ГГ. Диалоги услышать было нереально. В обновлении два предводителя с диалогами (всего их три) просто поменялись местами с обычными предводителями. Никаких новых орков и никаких изменений восприятия.

Сейчас:
- Предводители с диалогами: стоят отдельно по одиночке, не атакуют первыми, начинают диалог с ГГ в поле зрения, атакуют в ответ.
- Обычные предводители: стоят с орками-воинами, атакуют сразу при виде ГГ.

Предводители с диалогами:
- OrcElite_AntiPaladin1
- OrcElite_AntiPaladin2
- OrcElite_AntiPaladin3

Обычные предводители:
- OrcElite_AntiPaladin

**Comment by Kor-Angar** [comment]
Кажется пираньи забыли добавить Генералу Орков жизней
![image](https://user-images.githubusercontent.com/49514764/64469282-d8125f80-d137-11e9-91c4-b61e6f8d6e3b.png)
![image](https://user-images.githubusercontent.com/49514764/64469284-da74b980-d137-11e9-9f26-3d9dd035a319.png)

**Comment by Kor-Angar** [comment]
а в немецкой версии получается все орки что ли говорили?

**Comment by dosinabox** [comment]
> а в немецкой версии получается все орки что ли говорили?

Нет. Предводителей с диалогами везде 3, а вот диалогов записано 4. Четвертую реплику произносить некому. В обновлении можно услышать все реплики, потому что неиспользуемая реплика DIA_ORC_AntiPaladin_18_06 перенесена в произносимый диалог.

> Кажется пираньи забыли добавить Генералу Орков жизней

В обновлении у него будет 450, если выключены усиленные предводители.

**Comment by Kor-Angar** [comment]
Готика 2 | Готика 2 НВ
300 | 450
400 | X

X =1,5=400=600

**Comment by dosinabox** [comment]
> Готика 2 | Готика 2 НВ
> 300 | 450
> 400 | X
> 
> X =1,5=400=600

Я такой логикой и руководствовалась, поэтому и появились усиленные предводители и полковники с 550 хп. Тебе не понравилось) Поэтому появилась опция отключения усиленных орков.

**Comment by Kor-Angar** [comment]
Так там таких всего два;-) один в хориносе при игре за пала, а второй на Ирдорате

**Comment by Kor-Angar** [comment]
я добрался до компа и попытаюсь расписать свою мысль. так как мне кажется что я не могу её донести.

в игре есть 4 элитных орка:

- Ork Elite
- orkischer Kriegsherr, по сути те же самые Элитный Орк, но с топором. 22(!)  в Хориносе при игре за Пала. И всего один в Хориносе при игре за Мага/ОНД
- orkischer Oberst (Khorinis) полковник орков с крутым топором с уникальными параметрами, встречается при игре за Пала в Хориносе
- orkischer Oberst (Irdorath) полковник орков с крутым топором с уникальными параметрами, встречается при игре за все фракции на Ирдорате

Вот я их всех свёл на одну картинку для наглядности
https://sun9-25.userapi.com/c856016/v856016359/ec2c4/kcDvhmLXEdM.jpg

как я понимаю  Пираньи просто забыли накинуть жизней именно orkischer Oberst (Khorinis) и orkischer Oberst (Irdorath). об этом я писал выше.

orkischer Oberst (Khorinis)
Орк | Готика 2 | Готика 2 НВ
Ork Elite  | 300 | 450
orkischer Oberst (Khorinis) |  400 | X
orkischer Oberst (Irdorath) | 450 | Y
X =1,5*400=600
Y =1.5*450 = 675

в тоже время я писал что усиление orkischer Kriegsherr для Паладина (а это касается по большому счёту только Паладина) ничем необоснованно и несбалансированно. и просил сделать их усиление опциональным.

Если посмотреть на это с чистого листа то возможно блатные доспехи следовала дать только orkischer Oberst, так как это подчеркнёт их уникальность и эксклюзивность :-)  

p.s.
посмотрел на картинку и заметил что orkischer Oberst (Irdorath) так же и силы забыли добавить.

**Comment by Kor-Angar** [comment]
параметры в orkischer Oberst (Irdorath) Готика 2 Классик
![image](https://user-images.githubusercontent.com/49514764/64481064-32193080-d1dd-11e9-9e32-797039f9e989.png)

**Comment by dosinabox** [comment]
Уточняю твои предложения:
- полковнику в Хоринисе повысить здоровье до 600
- полковнику на Ирдорате повысить здоровье до 675 и силу до 175
- предводителей не трогать или сделать настройку у помощника

Правильно?

**Comment by Kor-Angar** [comment]
Так 🙂

**Comment by dosinabox** [comment]
Готово.

**Comment by Kor-Angar** [comment]
Супер. Надо будет протестить

**Comment by Kor-Angar** [comment]
а Полковнику Орков увеличили здоровье, но не увеличили уровень? :-)

**Comment by Kor-Angar** [comment]
увидел. они все были одинакового уровня. вопрос снимается:-)

![image](https://user-images.githubusercontent.com/49514764/76676262-cb812f00-65d2-11ea-8958-fb5d2b3f4605.png)

**Comment by Kor-Angar** [comment]
а что опять Командиры Орков стали глухие? герой подходит к ним в плотную и они никак на это не реагируют:-(

Стрим где всех командиров герой вырезает 
https://www.youtube.com/watch?v=yapHEUMj-7E

**Comment by Kor-Angar** [comment]
Напомни пожалуйста, это происходит из-за того что у Военачальников Орков есть диалоги с героем?

**Comment by Kor-Angar** [comment]
кстати похоже изначально Элитные Орки задумывались с топорами :-)

```
AI_Output(self,other,"DIA_Kjorn_BuyInfos_Orks2_06_01");	//Орков возглавляют элитные воины. Эти воины очень сильны и облачены в хорошие доспехи. Их почти невозможно убить.
AI_Output(self,other,"DIA_Kjorn_BuyInfos_Orks2_06_02");	//Я как-то видел, как один из них срубил большой дуб одним ударом своего топора.
```
а потом им всё таки решили дать мечи :-)

**Comment by Kor-Angar** [comment]
переключатель кажется не работает. надо перепроверить.

**Comment by dosinabox** [comment]
я лучше их вообще сделаю обычными как в оригинале)

**Comment by Kor-Angar** [comment]
я бы и визуально предложил выделить только полковников

OrkElite_AntiPaladinOrkOberst
OrkElite_AntiPaladinOrkOberst_DI

**Comment by dosinabox** [comment]
только если отдельно от, с ещё новой текстурой

**Comment by Kor-Angar** [comment]
это будет слишком сложном.
там по ЛОРу итак Элитные Орки = Орки Предводители орков

**Comment by Kor-Angar** [comment]
это будет слишком сложно. в игре  по ЛОРу итак Элитные Орки = Предводители орков. 
```
//Орков возглавляют элитные воины. Эти воины очень сильны и облачены в хорошие доспехи. Их почти невозможно убить.
```

**Comment by Kor-Angar** [comment]
> OrkElite_AntiPaladinOrkOberst_DI

а этому товарищу или Топор 140/140 надо давать или силу поднимать. а то у него сейчас  урон меньше чем у OrkElite_AntiPaladinOrkOberst

**Comment by dosinabox** [comment]
> //senses = SENSE_HEAR | SENSE_SEE;
>senses = SENSE_HEAR | SENSE_SEE | SENSE_SMELL;

То же самое нужно сделать у орков-шаманов.

**Comment by dosinabox** [comment]
Уровень полковников орков повышен с 45 до 60.
