### ISSUE TITLE
Друзья ГГ / NPCTYPE_FRIEND

### ISSUE THREAD

**Issue by Kor-Angar** [dosinabox/g2nr_unofficial_update#280]
у наёмника Фестера изначально прописано что он друг

https://github.com/dosinabox/g2nr_unofficial_update/blob/aed56ebb175bc52740bf908b2ece4ef16490b17d/PrjGOTHIC/Story/NPC/SLD_816_Fester.d#L9

а по идеи такой статус должен появится после того как герой с Фестером пойдёт бить полевых хишников

**Comment by dosinabox** [comment]
С Фестером понятно, исправлено. Но такая же история и со следующими товарищами:

Кавалорн
Род
Сифер
Ангар (Ирдорат)
Бифф (Ирдорат)
Ксардас
Куарходрон
Радемес
Гирион (Ирдорат)
Горн (везде)
Милтен (везде)
Лестер (везде)
Диего (везде)
Ли (везде)
Беннет (Ирдорат)
Вольф (Ирдорат)
Талбин (Миненталь)
Альрик
Ватрас (Ирдорат)
Ларес (везде)

**Comment by dosinabox** [comment]
Флаг очень полезный) С ним человек:
- не будет обыскивать избитого ГГ
- не будет кричать ГГ убрать оружие
- не будет атаковать ГГ за кражу, убийство, воровство
- не будет реагировать на крадущегося ГГ
- не будет запоминать преступления ГГ
- не будет стрелять в ГГ "стрелой сотрясения", а вместо этого усыпит
- не будет реагировать на ГГ, зашедшего в его дом
- не будет атакован призванными ГГ монстрами

**Comment by Kor-Angar** [comment]
Ага😀 Разве этот флаг не можно назначить позже в процессе, например через диалог? 23:33, 21 сентября 2020 г., dosinabox <notifications@github.com>:
Флаг очень полезный) С ним человек:

не будет обыскивать избитого ГГ
не будет кричать ГГ убрать оружие
не будет атаковать ГГ за кражу, убийство, воровство
не будет реагировать на крадущегося ГГ
не будет запоминать преступления ГГ
будет усыплять ГГ, а не стрелять в него стрелой сотрясения
не будет реагировать на ГГ, зашедшего в его дом
не будет атакован призванными ГГ монстрами


—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
-- Отправлено из мобильного приложения Яндекс.Почты

**Comment by dosinabox** [comment]
> Разве этот флаг не можно назначить позже в процессе, например через диалог?

Можно. Но нужно определиться, кому именно. Некоторые люди изначально относятся к ГГ дружественно и для некоторых это нормально.

**Comment by dosinabox** [comment]
Удаляем, но сначала думаем, зачем это было сделано и какие могут быть последствия:
- Род (?) (Миненталь - добавить обратно для похода к дракону)
- Сифер (?) (Миненталь - добавить обратно для похода к дракону)
- Альрик (?)
- Фестер (?) (добавить обратно для похода в пещеру)
- Талбин (?) (Миненталь - добавить обратно после первого разговора)

Добавляем:
- Ангар (Миненталь и Хоринис - изначально)
- Беннет (Хоринис - после освобождения)
- Талбин (Хоринис - изначально)

Оставляем:
- Кавалорн
- Ангар (Ирдорат)
- Бифф (Ирдорат)
- Ксардас
- Куарходрон
- Радемес
- Гирион (Ирдорат)
- Горн (везде)
- Милтен (везде)
- Лестер (везде)
- Диего (везде)
- Ли (везде)
- Беннет (Ирдорат)
- Вольф (Ирдорат)
- Ватрас (Ирдорат)
- Ларес (везде)

**Comment by Kor-Angar** [comment]
надо всё это загонят в таблицу и группировать.  Скинь пожалуйста ещё  НПС которые с ГГ ходят в команде.  Сделаем большую табличку и сразу станет понятно, кто друг, а кто нет.

> Род (?)
> Сифер (?)
> Альрик (?)
> Фестер (?) (добавить обратно после похода в пещеру)
> Талбин (?) (Миненталь - добавить обратно после первого разговора)

- Род и Сайфер Миненталь в случае похода в команде дракона. Это как защита от Friendly Fire
- Фестер так же на случай Friendly Fire в при походе в пещеру с ползунами
- Талбин тоже видимо Friendly Fire
- Альрик хз

у Грега нет?

**Comment by Kor-Angar** [comment]
у пиратов в Ярике нет ни у кого?
у Магов воды в Ярике?

**Comment by dosinabox** [comment]
> * Род и Сайфер Миненталь в случае похода в команде дракона

Точно. Стало понятнее) Мне казалось, что эти в Хоринисе. Тогда под вопросом только Альрик. Наверное, пусть и останется как есть.

> у Грега нет?
> у пиратов в Ярике нет ни у кого?
> у Магов воды в Ярике?

нет

**Comment by Kor-Angar** [comment]
А как это работает на уровне фракций? Например когда герой паладин, то в 5 главе к нему же меняется отношение паладинов? Или это делается через другую переменную? 😀

**Comment by dosinabox** [comment]
> НПС которые с ГГ ходят в команде

- все возможные из команды на Ирдорате
- Скип
- Мэтт
- Брэндон
- два пирата у ворот лагеря (1360 и 1361)
- два пирата в лагере (1363 и 1364)
- Аллигатор Джек
- Кавалорн
- Логан
- Рози
- Тилл
- Гримбальд
- Род (Миненталь)
- Сифер (Миненталь)
- Ангар (Миненталь)
- Бифф (Миненталь)
- Мика
- Педро (Ирдорат)
- Сержио
- Горн (Миненталь)
- Диего (Миненталь)
- Билгот
- Барток
- Ларес (Хоринис)

**Comment by Kor-Angar** [comment]
членов кольца воды можно добавить

**Comment by dosinabox** [comment]
> членов кольца воды можно добавить

Уже добавляются в функции B_MakeRangerReadyForMeeting:
```
Ranger.npcType = NPCTYPE_FRIEND;
```

**Comment by Kor-Angar** [comment]
ну не знаю. Корд после разговора о КВ, вёл себя не адекватно :-)30.09.2020, 21:56, "dosinabox" <notifications@github.com>:

членов кольца воды можно добавить

Уже добавляются в функции B_MakeRangerReadyForMeeting:
Ranger.npcType = NPCTYPE_FRIEND;

**Comment by dosinabox** [comment]
> Корд после разговора о КВ, вёл себя не адекватно

Это как?

**Comment by Kor-Angar** [comment]
Ночью в том помещение где Ли после драки с Наема и агрится. При этом единственный. Остальным все равно, а корд нападает. Может из-за лута. Не понял я из-за чего. Там Ярвиса надо проверять и Корда. 23:06, 30 сентября 2020 г., dosinabox <notifications@github.com>:

Корд после разговора о КВ, вёл себя не адекватно

Это как?

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
-- Отправлено из мобильного приложения Яндекс.Почты
