### ISSUE TITLE
Пек оружие 3 глава

### ISSUE THREAD

**Issue by Kor-Angar** [dosinabox/g2nr_unofficial_update#281]
Надо наверное добавить Пеку оружие в 3 главе, что бы у него его можно было если что отобрать. то оружие которое он по сюжету отжал у Беннета и даёт ГГ менту.

**Comment by dosinabox** [comment]
в продажу?

**Comment by Kor-Angar** [comment]
а он стал торговать? я думаю просто в ассортимент, что бы можно было отобрать при желание.

**Comment by dosinabox** [comment]
сейчас не торгует

**Comment by Kor-Angar** [comment]
Тогда ещё проще он же по ЛОРу отобрал мечи у Беннета, визуально будет видно что он экипированом новым оружием.  Если герой мегт, то он ему меч даст, если герой не Мент, то не даст. Кому надо тот заберёт силой 😀

**Comment by dosinabox** [comment]
https://github.com/dosinabox/g2nr_unofficial_update/issues/85
