### ISSUE TITLE
Болтан  /  DIA_MIL_313_Boltan

### ISSUE THREAD

**Issue by Kor-Angar** [dosinabox/g2nr_unofficial_update#282]
Что то у меня Болтан не говорит что все камеры пусты :-)

```
	else if(C_PrisonIsEmpty())
	{
		AI_Output(self,other,"DIA_Boltan_Add_05_02");	//Все камеры сейчас пусты.
	}
```

**Comment by dosinabox** [comment]
А кто в это время сидит?

**Comment by Kor-Angar** [comment]
никого

**Comment by dosinabox** [comment]
А кто-нибудь сидел и вышел?
Может, ты кого-то убил?

**Comment by Kor-Angar** [comment]
он видимо из-за Бенета  глючит. надо проверить как работает C_PrisonIsEmpty

**Comment by dosinabox** [comment]
На первый взгляд всё ок. Так Беннет был в камере, но вышел? А где Корнелиус?
