### ISSUE TITLE
Story Helper

### ISSUE THREAD

**Issue by Kor-Angar** [dosinabox/g2nr_unofficial_update#286]
мне кажется надо еще одну веху истории добавить в 3 главау, что то типа предстарта 3 главы которая соответствовала бы

```
	CreateInvItems(self,ItWr_PaladinLetter_MIS,1);
	B_GiveInvItems(self,other,ItWr_PaladinLetter_MIS,1);
	KnowsPaladins_Ore = TRUE;
	B_LogEntry(Topic_MISOLDWORLD,"Командующий Гаронд дал мне письмо. Его должно быть достаточно для подтверждения моих слов. Я могу отнести его лорду Хагену.");
	MIS_ScoutMine = LOG_SUCCESS;
	MIS_ReadyForChapter3 = TRUE;
	B_NPC_IsAliveCheck(OLDWORLD_ZEN);
```

это позволит лучше видеть ситуации(ошибки, баги, сюжетные моменты) при загрузке мира и старте 3 главы

**Comment by dosinabox** [comment]
Наверное, следует блокировать возможность устанавливать у помощника уже прошедшие события (двигаться назад по сюжету), потому что в некоторых случаях это гарантированно ведет к невозможности дальнейшего прохождения.
Также следует расширить перечень "вех" у каждой главы.

**Comment by Kor-Angar** [comment]
про вехи это факт :-)  про прошлое хз, с точки зрения логики да, но это всё таки марвин и может человеку очень надо :-) а тут такие ограничения. можно предупреждение делать перед переключением о том что сюжет игры сломается.

**Comment by dosinabox** [comment]
А давай распишем все вехи сюжета.

Глава 1:
- получен доступ в город
- получен доступ в верхний квартал
- получен доступ к Хагену

Глава 2:
- принятие в Кольцо Воды
- орнамент собран
- начало квеста Гаронда
- собрана информация для Гаронда
- получено письмо для Хагена

Глава 3:
- Ворон убит
- Ватрас может покинуть город
- Глаз восстановлен

Глава 4:
- ...
- ...
- ...

Вехи первой главы вынесла в отдельные функции, которые можно будет вызывать у помощника (B_CityMainGatesPass(), B_UpperCityPass(), B_CityHallPass()).

**Comment by Kor-Angar** [comment]
Глава вторая:
Вступление В КВ, кольцо, броня и квест Ватраса
Три Информации о Рудокопах
Смерть Равена

**Comment by dosinabox** [comment]
Возможно, всё связанное с КВ и Яркендаром стоит выносит в отдельный список между 1 и 2 (или 2 и 3) главами

**Comment by dosinabox** [comment]
или в отдельный список в рамках 2 главы

**Comment by Kor-Angar** [comment]
> всё связанное с КВ и Яркендаром

сейчас это можно добавить во вторую главу, а потом продублировать, в третей если ты решишь прорабатывать третью. 

Просто отдельно выносить не очень хорошо, так как сюжет может багануться, если КВ активировать в 1 главе. если же ставить между 2 и 3 и при этом автоматом включать вторую главу, то.. фиг знает короче.

я предлагаю сделать так: дублировать кв во второй и третей главе, а когда они полностью будут сделаны, подумать как вынести их отдельно, если в этом будет необходимость. 

***

у тебя у CH есть "гильдия" КВ ?

**Comment by Kor-Angar** [comment]
> Глава вторая:
> Три Информации о Рудокопах

DIA_Garond_Success_Info

**Comment by dosinabox** [comment]
> А давай распишем все вехи сюжета.

Вот в Г1 помощник образцово-показательный:

![Screenshot_1](https://user-images.githubusercontent.com/39790055/106389287-9e5c8b80-63f3-11eb-82a7-d2e3198000d8.jpg)

**Comment by Kor-Angar** [comment]
Он прекрасен. Кстати было бы неплохо поменять внешний вид помощника по сюжету и по персонажу. Я у себя сделал помощника по персонажу Диего, а помощника по сюжету Ксардаса. Можно использовать так же и героя но в разных доспехах.

**Comment by Kor-Angar** [comment]
а чётвртую главу в Хориносе ты не убирала? :-) или я как то косо поставил обновление? :-)

![20210201213946_1](https://user-images.githubusercontent.com/49514764/106503251-72fe9d00-64d6-11eb-9183-69d5ff0c31b6.jpg)

**Comment by Kor-Angar** [comment]
я могу протестить что нибудь в любой конфигурации настроек, если есть такая потребность :-)

**Comment by dosinabox** [comment]
> а чётвртую главу в Хориносе ты не убирала? :-) или я как то косо поставил обновление? :-)

По умолчанию включено, что ли? Должно быть выключено. Но сам переключатель пока остается. Потом уберу, наверное.

> я могу протестить что нибудь в любой конфигурации настроек, если есть такая потребность :-)

Пожалуй, необходимость проверки есть только у полного удаления NPC из мира и показа заголовков при обновлении дневника.

**Comment by Kor-Angar** [comment]
> полного удаления NPC из мира

так я с этой опцией постоянно играю :-) там всё ровно.

**Comment by Kor-Angar** [comment]
> я могу протестить что нибудь в любой конфигурации настроек, если есть такая потребность :-)

ну тогда я потестирую ваш альтернативный баланс :-) где можно скачать файл g2a_nr_scriptpatch_v25_wasteland ?

**Comment by dosinabox** [comment]
[g2a_nr_scriptpatch_v25_wasteland.zip](https://github.com/dosinabox/g2nr_unofficial_update/files/5912777/g2a_nr_scriptpatch_v25_wasteland.zip)

**Comment by dosinabox** [comment]
> ну тогда я потестирую ваш альтернативный баланс :-)

Это какой?

**Comment by Kor-Angar** [comment]
С трусость все плохо. Малые гоблины бегут от кваларона и начинается ад, так как бандит на них агрится 😀

**Comment by dosinabox** [comment]
Ну, поэтому по умолчанию и выключено)

**Comment by Kor-Angar** [comment]
Так оно получается в целом не работает 😀 в начале игры, одно ломает, в серидине другое. 23:19, 2 февраля 2021 г., dosinabox <notifications@github.com>:
Ну, поэтому по умолчанию и выключено)

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
-- Отправлено из мобильного приложения Яндекс.Почты

**Comment by dosinabox** [comment]
> баланс Diego1987

Ещё добавляли новое оружие:
Легкая рапира 90/60/+6% - ItMw_Lightrapier
Шпага бойца 110/80/+8% - ItMw_Kampferdegen
Бекки 130/110/+10% - ItMw_Addon_Becky

Заменяют Рапиру, Шпагу мастера и Бетти соответственно, доступны только из консоли.

**Comment by Kor-Angar** [comment]
я помню. но они выпадут из баланса игры, так как есть "альтеративное" обучение у беннета которое даёт ранний доступ к  клинкам  наёмника из Руды;-) 
Для 180 ущерба подойдёт клинок 100 / 80 / 10%.. он же доступен прям в начале второй главы? он лучше Рапиры и не хуже Шпаги Бойца хотя может и показаться на первый взгляд что хуже. дело в шмоте, что бы быстрее надеть ловкостное оружие одеваются вещи к ловкости, а значит не одеваются к силе. т.е. общий ущерб "больше" за счёт большего урона, но 
это тут же "компенсирует упущенная" сила и выравнивает итоговый ущерб :-) зачем собирать ягоды гоблина бегай по всей карте и напрягаться когда можно просто выучить ковку и получит тоже самое но без напряга? :-)
Бекки  же хуже клинка 140/120 /10% который будет доступен уже в 3 главе :-)

таким образом сочетание опцией  "альтеративного обучения" и "игнорирование бонусов" сводит игру к тем самым самокованым клинкам. принципиальная разница от оригинального баланса это уровень ГГ на котором он будет выходить на тот или иной ущерб. будет интересно сравнить грубо говоря
уровень героя / навык 1р / итоговый ущерб

**Comment by Kor-Angar** [comment]
> С трусость все плохо. Малые гоблины бегут от кваларона и начинается ад, так как бандит на них агрится

может лучше снять трусость с молодых животных, так как они появляются в начале игры и своим убеганием не туда просто будут ломать игру. опять же разве хищники (волки, снепперы) должны убегать?

**Comment by Kor-Angar** [comment]
> уровень героя / навык 1р / итоговый ущерб

я же в итоге таки собрался все данные в одну более менее понятную таблицу. будет что с чем сравнить
https://steamcommunity.com/sharedfiles/filedetails/?id=2379834530
тут в спойлере https://rpgrussia.com/resources/rasxody-lp-na-prokachku-lajtovyj-ment-pal-c-1r.3541/

**Comment by Kor-Angar** [comment]
> уровень героя / навык 1р / итоговый ущерб

вот с этим сравнить :-)

LvL | 1h | dmg
-- | -- | --
5 | 35 | 121
15 | 100 | 125
19 | 99 | 180
24 | 100 | 220
28 | 100 | 266
32 | 100 | 310

**Comment by Kor-Angar** [comment]
![image](https://user-images.githubusercontent.com/49514764/107159852-ab551e00-69a3-11eb-8e95-127a173699fd.png)

**Comment by Kor-Angar** [comment]
LvL ОБ | LvL АБ | 1h | dmg
-- | -- | -- | --
22 | 15 | 100 | 105

![image](https://user-images.githubusercontent.com/49514764/107160000-8614df80-69a4-11eb-8a88-0d9203d16d8f.png)

**Comment by Kor-Angar** [comment]
LvL ОБ | LvL АБ | 1h | dmg
-- | -- | -- | --
6 | 6 | 35 | 120
19 | 13 | 100 | 180
24 | 16 | 100 | 211



![image](https://user-images.githubusercontent.com/49514764/107160097-3b479780-69a5-11eb-9546-3a1e78fde934.png)

**Comment by Kor-Angar** [comment]
пока получается так
LvL ОБ | LvL АБ | 1h | dmg
-- | -- | -- | --
6 | 6 | 35 | 120
19 | 13 | 100 | 180
24 | 16 | 100 | 211


а потом наверное будет так

LvL ОБ | LvL АБ | 1h | dmg
-- | -- | -- | --
28 | 17 | 100 | 266

![image](https://user-images.githubusercontent.com/49514764/107160268-5a92f480-69a6-11eb-9331-d414059e6068.png)
