### ISSUE TITLE
DIA_Addon_Constantino_LestersKraeuter

### ISSUE THREAD

**Issue by Kor-Angar** [dosinabox/g2nr_unofficial_update#287]
У Константино опыт пропадал за квест про травки есть начать торговать с ним. это поможет?

https://github.com/Kor-Angar/G2_NotR_Kor_Angar/commit/4cf8f39246620d22db9a22f57a0e14e6497c413e

**Comment by Kor-Angar** [comment]
Нет. Это только усугубидо ситуацию 🙃

**Comment by Kor-Angar** [comment]
наверное просто вот так 

```
instance DIA_Addon_Constantino_LestersKraeuter(C_Info)
{
	npc = VLK_417_Constantino;
	nr = 1;
	condition = DIA_Addon_Constantino_LestersKraeuter_Condition;
	information = DIA_Addon_Constantino_LestersKraeuter_Info;
	permanent = FALSE;
	important = TRUE;
};
```

**Comment by dosinabox** [comment]
Опиши проблему подробнее, пожалуйста. По коду плохо понятно.

**Comment by Kor-Angar** [comment]
у Константино появился новый диалог в Аддоне. Связан он с квестом по попаданию в город. за этот диалог дают опыт.
этот диалог может не воспроизводится, если сначала  торговать с Костей. Оба диалога про торговлю. 

в качестве возможного решения проблемы добавить 	important = TRUE на новый диалог.

**Comment by dosinabox** [comment]
> в качестве возможного решения проблемы добавить important = TRUE на новый диалог.

А разве такие модификации не ограничат количество динамического опыта первой главой? Может кто-то привык ждать до пятой главы, чтобы получить побольше опыта. Это не мешает торговле, опыт блокировался только если попроситься к нему в ученики. Тогда он дает задание принести травы и диалог "Ты покупаешь травы?" перестает иметь смысл.

**Comment by dosinabox** [comment]
А так придется вообще не разговаривать с ним до пятой главы.

**Comment by Kor-Angar** [comment]
> Это не мешает торговле, опыт блокировался только если попроситься к нему в ученики.

видимо я просто в игре неправильно понял условие :-) мне всегда казалось что это связанно именно с торговлей. а оказалось что не сторговлей.

```D
func int DIA_Addon_Constantino_LestersKraeuter_Condition ()
{
	if (MIS_Constantino_BringHerbs == 0)
	&& (MIS_Addon_Lester_PickForConstantino != 0)
		{
			return TRUE;
		};
};
```


> Это не мешает торговле, опыт блокировался только если попроситься к нему в ученики. Тогда он дает задание принести травы и диалог "Ты покупаешь травы?" перестает иметь смысл.

диалог "ты  покупаешь травы" перестаёт иметь смысл в ряде случаев. особенно в пятой главе :-)

**Comment by dosinabox** [comment]
> мне всегда казалось что это связанно именно с торговлей. а оказалось что не сторговлей.

Значит, ничего делать не нужно?

**Comment by Kor-Angar** [comment]
Выходит ничего. В игре ещё раз проверить 😀23:16, 31 марта 2021 г., dosinabox ***@***.***>:

мне всегда казалось что это связанно именно с торговлей. а оказалось что не сторговлей.

Значит, ничего делать не нужно?

—You are receiving this because you modified the open/close state.Reply to this email directly, view it on GitHub, or unsubscribe.
-- Отправлено из мобильного приложения Яндекс.Почты

**Comment by dosinabox** [comment]
А я уже интегрировала фразы про травы и опыт в DIA_Constantino_Hallo:
```cpp
var int SC_AskedConstantinoAboutHerbs;

func int C_CanAskConstantinoAboutHerbs()
{
	if((MIS_Constantino_BringHerbs == FALSE) && (MIS_Addon_Lester_PickForConstantino != FALSE) && (SC_AskedConstantinoAboutHerbs == FALSE))
	{
		return TRUE;
	};
	return FALSE;
};

func void B_AskConstantinoAboutHerbs()
{
	AI_Output(other,self,"DIA_Addon_Constantino_LestersKraeuter_15_00");	//Ты покупаешь травы?
	AI_Output(self,other,"DIA_Addon_Constantino_LestersKraeuter_10_01");	//Ну, если тебе есть, что предложить...
	B_GivePlayerXP(XP_Ambient);
	SC_AskedConstantinoAboutHerbs = TRUE;
};

instance DIA_Constantino_Hallo(C_Info)
{
	npc = VLK_417_Constantino;
	nr = 2;
	condition = DIA_Constantino_Hallo_Condition;
	information = DIA_Constantino_Hallo_Info;
	permanent = FALSE;
	important = TRUE;
};

func int DIA_Constantino_Hallo_Condition()
{
	if(Npc_IsInState(self,ZS_Talk) && (self.aivar[AIV_TalkedToPlayer] == FALSE))
	{
		if(C_CanAskConstantinoAboutHerbs())
		{
			return TRUE;
		};
		if((VisibleGuild(other) != GIL_PAL) && (VisibleGuild(other) != GIL_MIL) && (VisibleGuild(other) != GIL_KDF) && (VisibleGuild(other) != GIL_KDW))
		{
			return TRUE;
		};
	};
};

func void DIA_Constantino_Hallo_Info()
{
	if((VisibleGuild(other) != GIL_PAL) && (VisibleGuild(other) != GIL_MIL) && (VisibleGuild(other) != GIL_KDF) && (VisibleGuild(other) != GIL_KDW))
	{
		AI_Output(self,other,"DIA_Addon_Constantino_Hallo_10_00");	//Что тебе нужно? Я не подаю милостыню.
	};
	if(C_CanAskConstantinoAboutHerbs())
	{
		B_AskConstantinoAboutHerbs();
	};
};

instance DIA_Addon_Constantino_LestersKraeuter(C_Info)
{
	npc = VLK_417_Constantino;
	nr = 5;
	condition = DIA_Addon_Constantino_LestersKraeuter_Condition;
	information = DIA_Addon_Constantino_LestersKraeuter_Info;
	description = "Ты покупаешь травы?";
};

func int DIA_Addon_Constantino_LestersKraeuter_Condition()
{
	if(C_CanAskConstantinoAboutHerbs())
	{
		return TRUE;
	};
};

func void DIA_Addon_Constantino_LestersKraeuter_Info()
{
	B_AskConstantinoAboutHerbs();
};
```
Если так ок, то оставлю.
В принципе, этот вопрос логичен именно при первом разговоре - тогда последующая фраза "Покажи мне свои товары" звучит лаконичнее. А в оригинале можно сначала с Константино поторговать, а потом спросить, покупает ли он травы)

**Comment by Kor-Angar** [comment]
Ну вот и мне так кажется 😀Это в рилизе завтрашнем будет?

**Comment by dosinabox** [comment]
> Ну вот и мне так кажется 😀Это в рилизе завтрашнем будет?

да, в стиме

**Comment by Kor-Angar** [comment]
в стиме?

**Comment by dosinabox** [comment]
в Gothic 2 Steam Fix - туда пошла версия 26 с некоторыми правками после 12.03.2021:
https://github.com/dosinabox/g2nr_unofficial_update/commit/981b746fda7914e23fd24fdf12af3fa0a70fc187
https://github.com/dosinabox/g2nr_unofficial_update/commit/89ecdd796184aa24a5787b4b7e5f6f2b3fa2a23d
