### ISSUE TITLE
Пек в казармах ночью

### ISSUE THREAD

**Issue by dosinabox** [dosinabox/g2nr_unofficial_update#29]
Если Пек вернулся в казармы, то по ночам диалоговое окно с ним будет пустым. Если это правильно, то нужно добавить реплику с отказом ("я занят, приходи позже"). Если неправильно, то сделать все диалоги доступными не только днем за прилавком.

**Comment by Kor-Angar** [comment]
а ночью он спит в казарме?

**Comment by dosinabox** [comment]
> а ночью он спит в казарме?

да

**Comment by Kor-Angar** [comment]
На мой взгляд должно быть единообразие. Если ночью можно поговорить с Мартином, то почему нельзя с Пеком. Тоесть или все перерабатывать с чистого листо, кто должен посылать, а кто нет или просто Пека подогнать под основную массу 🙂

**Comment by dosinabox** [comment]
Исправлено. Будет разговаривать и днем за прилавком, и ночью в казармах.
