### ISSUE TITLE
Охота на Снепперов

### ISSUE THREAD

**Issue by Kor-Angar** [dosinabox/g2nr_unofficial_update#290]
Как то Охотник стал хуже на Снепперов охотится. Помнится раньше его спокойно убивали на охоте. а теперь он как пень стоит. так задумано? :-)
0,28,21
https://youtu.be/KsZsGUFhXGk?t=1701

**Comment by dosinabox** [comment]
Тут сочетание факторов.
- Ты убил одного из снепперов до начала охоты и это могло повлиять на восприятие всей стаи. Возможно, этот снеппер заметил бы Гримбальда и все остальные атаковали бы вместе с ним.
- В обновлении Гримбальд ведет за собой ГГ, а в оригинале - просто бежит на точку. Поэтому возможна ситуация, когда Гримбальд начнет оглядываться в поисках ГГ и отвлечется от стаи.

Тут можно просто вернуть изначальное поведение Гримбальда - бежать на точку не обращая внимания на ГГ. И не хотелось бы отправлять его ближе к стае, потому что тогда ему придется использовать меч вместо лука.

**Comment by Kor-Angar** [comment]
я смотрю у меня в игре всегда идёт исключительно сочетание факторов в рамках неоф. обновления:  всё  я делаю неправильно, никак оно было задумано авторами обновления. 

этим наверное  Готика и хороша, что Пираньи не думали за игрока, а помещали его в ситуацию в которой  любой выбор был правильный и вёл к развитию ситуацию.  А теперь и опыт дают за убийство Снепперов Гримбальдом почему то. Наверное потому что не получить опыт это неправильно? :-)

Я не знаю как тут должно быть. тем более не знаю, как оно правильно, а как не правильно. Поэтому просто обозначил что у тебя сейчас оно вот так.

**Comment by Kor-Angar** [comment]
я помню что в оригинале Гримбальда без помощи ГГ Снепперы убивали. так как он их начинал атаковать из Лука, потом переключался на меч и умирал. поэтому в интересах игрока было поучаствовать в этом процессе.

**Comment by Kor-Angar** [comment]
что в принципе соответствовало  тому что Гримбальд говорил, что ему нужна помощь.

**Comment by dosinabox** [comment]
Так и в оригинале стая снепперов становится разрозненной, если убить одного из них до охоты. И тоже подходили бы по одному.
Так и у тебя Гримбальд переключился на меч. Но сражался он только с одним снеппером вместо целой стаи. И ты оказался рядом и помог ему.

Так что тут вопрос только со способом перемещения Гримбальда (одному или вести ГГ) и с опытом (давать или нет). Поведение стаи и отдельных снепперов в оригинале такое же и там тоже возможна ситуация, когда Гримбальд спокойно переживает охоту.

**Comment by dosinabox** [comment]
> я помню что в оригинале Гримбальда без помощи ГГ Снепперы убивали

Попробовала в оригинале. Первый снеппер убивается с одной стрелы, оставшиеся два добиваются с 1-3 ударов мечом. После охоты у Гримбальда остается 80-90% здоровья. Не похоже, что ему требуется помощь, и не знаю, как он умудрялся умирать)

**Comment by dosinabox** [comment]
В общем, вся охота возвращена к оригиналу:

- Гримбальд не ведет ГГ к точке, а идет независимо от него (влияло на восприятие противников)
- убран опыт за убийства Гримбальда (влияло на дистанцию восприятия противников и баланс)

**Comment by Kor-Angar** [comment]
> Не похоже, что ему требуется помощь, и не знаю, как он умудрялся умирать)

видимо слишком сильный стал в НВ. в Классике снепперы были сильнее,а Гримбальд слабее.

**Comment by dosinabox** [comment]
И ещё. У Гримбальда есть такая реплика:
```
И я не прощу тебе, если ты решишь выйти из игры.
```
Поэтому если ГГ забьет на охоту и уйдет, то теперь через один день Гримбальд возмутится и не будет учить его бесплатно.

**Comment by dosinabox** [comment]
> видимо слишком сильный стал в НВ. в Классике снепперы были сильнее,а Гримбальд слабее.

да, в классике его убивают в два счета

**Comment by Kor-Angar** [comment]
это хорошо. а то иногда мне кажется что я в какую то другую Готику играл в универе.

Может быть имеет смысл охотника ослабить? например порезать ему силу/ловкость и ХП?
