### ISSUE TITLE
Брайн не снимает оружие перед торговлей

### ISSUE THREAD

**Issue by Kor-Angar** [dosinabox/g2nr_unofficial_update#292]
![image](https://user-images.githubusercontent.com/49514764/95146148-cad60300-0785-11eb-82df-02947a21890f.png)

**Comment by dosinabox** [comment]
Сделано специально.
Есть торговцы, которые не специализируются на продаже оружия (маги, алхимики, фермеры). Они имеют в наличии только один экземпляр оружия - которым вооружены сами. Зачем им его предлагать в продажу? Если ГГ купит его, то они останутся без защиты.

**Comment by Kor-Angar** [comment]
И что в таком случае делать если игрок случайно ему продал какою нибудь штуку, а он её одел? 😀16:20, 7 октября 2020 г., dosinabox <notifications@github.com>:
Сделано специально.
Есть торговцы, которые не специализируются на продаже оружия (маги, алхимики, фермеры). Они имеют в наличии только один экземпляр оружия - которым вооружены сами. Зачем им его предлагать в продажу? Если ГГ купит его, то они останутся без защиты.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
-- Отправлено из мобильного приложения Яндекс.Почты

**Comment by dosinabox** [comment]
Конечно, тут бы делать проверку свое/на продажу, но стандартными средствами этого не реализовать.

**Comment by Kor-Angar** [comment]
А если сделать проверку через хозяина предмета. Как в Г1, т.е. Сделать меч ему именной и если это он то не снимать. Так можно? 16:29, 7 октября 2020 г., dosinabox <notifications@github.com>:
Конечно, тут бы делать проверку свое/на продажу, но стандартными средствами этого не реализовать.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
-- Отправлено из мобильного приложения Яндекс.Почты
