### ISSUE TITLE
Список книжных подставок в мире

### ISSUE THREAD

**Issue by Kor-Angar** [dosinabox/g2nr_unofficial_update#293]
а есть список книжных подставок в мире?

**Comment by dosinabox** [comment]
объектов или текстов?

**Comment by Kor-Angar** [comment]
объектов. вот например подставки в минентале в склепе и в старом форте. что бы там что то осмысленное вывести в качестве текста :-)

**Comment by dosinabox** [comment]
такого списка у меня нет
