### ISSUE TITLE
Респаун / Миненталь

### ISSUE THREAD

**Issue by Kor-Angar** [dosinabox/g2nr_unofficial_update#294]
подскажи пожалуйста , а что это такое?

```
		if(Npc_IsDead(DragonSnapper_NC_Cave))
		{
			Wld_InsertNpc(Shadowbeast,"OW_PATH_07_15_CAVE3");
		};
```

**Comment by Kor-Angar** [comment]
и расскажи ещё вот про это пожалуйста

	```
	if(Npc_IsDead(IceGolem_Sylvio1) && Npc_IsDead(IceGolem_Sylvio2))
		{
			SylvioIceGolemsKilledBefore4Chapter = TRUE;
			B_StartOtherRoutine(DJG_731_ToterDrachenjaeger,"IceRegion");
			B_StartOtherRoutine(DJG_732_ToterDrachenjaeger,"IceRegion");
			B_StartOtherRoutine(DJG_733_ToterDrachenjaeger,"IceRegion");
			B_StartOtherRoutine(DJG_734_ToterDrachenjaeger,"IceRegion");
			B_StartOtherRoutine(DJG_700_Sylvio,"IceWait1");
			if(SLD_Bullco_is_alive == TRUE)
			{
				B_StartOtherRoutine(DJG_701_Bullco,"IceWait1");
			};
		};
```

**Comment by dosinabox** [comment]
> if(Npc_IsDead(IceGolem_Sylvio1) && Npc_IsDead(IceGolem_Sylvio2))

Имеются два ледяных голема у входа в бывший Новый лагерь.
Имеются Сильвио, Буллко и отряд охотников на драконов.

По сюжету Сильвио, Буллко и отряд охотников на драконов приходят в ледяной регион и почти всех убивают големы. В живых остаются только Сильвио и Буллко, которые ждут когда големов убьет ГГ. После этого они переходят дальше.

Но что если ГГ убьет этих големов до того, как они попадутся ОнД в четвертой главе?
В старых версиях обновления эти големы просто были бессмертными до четвертой главы - и это плохо.
В актуальных версиях обновления смерть этих големов учитывается с началом четвертой главы - и тогда Сильвио, Буллко и отряд охотников на драконов могут пройти дальше, где всё равно погибают от лап людей-ящеров. Сильвио и Буллко всё равно выживают, но стоят чуть дальше в ледяной области и не упоминают ледяных големов у входа. Следовательно, и квест на убийство несуществующих големов выдан ГГ не будет.

> if(Npc_IsDead(DragonSnapper_NC_Cave))

Что-то связанное с луком в пещере в скале у бывшего Нового лагеря. Мы это с тобой обсуждали когда-то. Вроде, лук перенесли на вторую главу, но тогда в четвертой там становилось пусто.

**Comment by Kor-Angar** [comment]
> Но что если ГГ убьет этих големов до того, как они попадутся ОнД в четвертой главе?

проверить на смерть и вставить новых.

> В актуальных версиях обновления смерть этих големов учитывается с началом четвертой главы - и тогда Сильвио, Буллко и отряд охотников на драконов могут пройти дальше, где всё равно погибают от лап людей-ящеров.

если герой убил Ледянных големов, то он точно убил и всех остальных. Големов то гораздо тяжелее пробить, чем людей ящеров ;-)

Но в целом спасибо, я примерно так и подумал.

> Что-то связанное с луком в пещере в скале у бывшего Нового лагеря. Мы это с тобой обсуждали когда-то. Вроде, лук перенесли на вторую главу, но тогда в четвертой там становилось пусто.

лук перенесли. но тут же проверка на смерть идёт какая то.. вообщем тоже понятно. и с Мракорисами понятно :-)

**Comment by Kor-Angar** [comment]
понял. там не про лук. там про перенос Мракорисов которые должны были бить Орков 
в Лесу но были перенесены туда, так как 
_очень неправильно когда монстры взаимодействуют друг с другом и убивают друг друга (с)_ :-)

**Comment by Kor-Angar** [comment]
те самые 3 мракориса в лесу и орки :-)
1 Час, 03 минуты  https://youtu.be/H2Najc6pJEw?t=3804

**Comment by Kor-Angar** [comment]
не подскажешь как  для теста "заморозить" вставляемых орков и мракорисов, что бы они на что не реагировали, хочу посмотреть изначальную диспозицию?

**Comment by dosinabox** [comment]
Нашлось в моих старых заметках:
> Пустая пещера на склоне горы у Нового лагеря, 4 глава, в пещере только мощный лук. Может быть посадить туда одного из мракорисов? OW_PATH_07_15_CAVE3

**Comment by dosinabox** [comment]
Наверное, нужно выбрать только что-то одно:
```
- Дубовый лук в пещере у замерзшего лагеря охраняет мракорис, если мертв драконий снеппер.
- Дубовый лук в пещере с драконьими снепперами в Рудниковой долине доступен с первой главы.
```

**Comment by Kor-Angar** [comment]
ты можешь просто убрать Мракориса ;-) 
или вставлять туда  а мракориса скелета

**Comment by dosinabox** [comment]
Сначала мы поняли, что если убить снеппера до четвертой главы, то в четвертой главе дубовый лук остается без защиты. Поэтому на этот случай стали вставлять в пещеру мракориса.
Потом решили, что в четвертой главе этому луку там нечего делать и перенести его на первую главу. А про мракориса забыли (?).

Следовательно, можно просто убрать проверку снеппера и вставку мракориса.

**Comment by Kor-Angar** [comment]
про Мракориса я не знал. это видимо до меня было. про лук да, обсуждали. там же не только лук лежит , но и свиток огненного дождя и скрижаль :-)

**Comment by Kor-Angar** [comment]
но в целом да, логика правильная.

**Comment by dosinabox** [comment]
> Следовательно, можно просто убрать проверку снеппера и вставку мракориса.

готово
