### ISSUE TITLE
Старт 4 главы в Хориносе

### ISSUE THREAD

**Issue by Kor-Angar** [dosinabox/g2nr_unofficial_update#295]
В Хориносе не надо делать старт 4 главы. так происходят респауны во всех трех локациях и логичнее и лаконичнее делать их когда герой как бы переходит между локациями.

у нас вопрос был про ассортимент товаров?

**Comment by dosinabox** [comment]
> В Хориносе не надо делать старт 4 главы

Так это же опция в настройках, по умолчанию всё как обычно. Или я не так понимаю вопрос?

**Comment by Kor-Angar** [comment]
но вот то что даже опционально может вызвать больше проблем чем пользы. я даже не знаю с какого конца проверять всё это в таком случае :-)

**Comment by dosinabox** [comment]
Нет никакой разницы - при переходе обратно или с включенной опцией без перехода. В обоих случаях вызывается одна и та же функция.

**Comment by Kor-Angar** [comment]
Есть разница. Если герой забежит в Ярик, а потом зайдёт в Хоринос, произойдёт респаун и там и там.

**Comment by dosinabox** [comment]
Всё равно не понимаю, к каким проблемам может привести респаун живности четвертой главы в Хоринисе без перехода в Миненталь.

**Comment by Kor-Angar** [comment]
> Всё равно не понимаю, к каким проблемам может привести респаун живности четвертой главы в Хоринисе без перехода в Миненталь.

https://www.youtube.com/watch?v=yfuqA5tjdng

**Comment by dosinabox** [comment]
теперь понимаю)

**Comment by Kor-Angar** [comment]
**MIS_ReadyforChapter4**

а свитки то в продаже новые появятся в монастыре? товары на ферме онара(руда)  появляется?

- Беннет ковке учит
- Маг Оня  4 круг учит
- Руны Палу выдают
