### ISSUE TITLE
Освящение клинка BlessSword

### ISSUE THREAD

**Issue by Kor-Angar** [dosinabox/g2nr_unofficial_update#296]
Подскажи пожалуйста , а это что такое?

```
	if(ShrineIsObsessed == TRUE)
	{
		SC_IsObsessed = TRUE;
		PrintScreen(PRINT_SCIsObsessed,-1,-1,FONT_Screen,2);
		Snd_Play("DEM_Die");
	}
```

**Comment by dosinabox** [comment]
Попытка освящения меча на оскверненном алтаре тоже приводит к одержимости ГГ, как и попытка молитвы.

**Comment by Kor-Angar** [comment]
гм... но алтарь же в монастыре не может быть осквернён?

**Comment by dosinabox** [comment]
А разве освятить меч можно только в монастыре?

**Comment by Kor-Angar** [comment]
вроде да. это как перевести на человекопонятный язык?

```
		if(Npc_GetDistToWP(hero,"NW_MONASTERY_CHAPELL_02") <= 500)
		{
			return TRUE;
		};
```

**Comment by Kor-Angar** [comment]
оригинальный код из MDK

```
FUNC INT PC_PrayShrine_BlessSword_Final_Condition ()
{
	if (PLAYER_MOBSI_PRODUCTION	==	MOBSI_PRAYSHRINE)
	&& (hero.guild == GIL_PAL)
	&& (Npc_GetDistToWP (hero,"NW_MONASTERY_CHAPELL_02") <= 500) 
	&& (PAL_KnowsAbout_FINAL_BLESSING == TRUE)  
	&& ((Npc_HasItems (hero,ItMw_1H_Blessed_02) >= 1)
	||  (Npc_HasItems (hero,ItMw_2H_Blessed_02) >= 1))
	{	
		return TRUE;
	};
};
```

**Comment by dosinabox** [comment]
Значит, проверка на оскверненный алтарь здесь лишняя. Можно её убрать. А можно и не убирать.
Возможно, когда-то меч можно было освятить на любом алтаре, а потом разработчики ограничили эту возможность до одного алтаря в монастыре, но старая проверка осталась.

**Comment by Kor-Angar** [comment]
наверное они просто скопировали проверку от первого освящения меча за 5000 золотых. а Димус добавил проверку на Хоринос?

**Comment by dosinabox** [comment]
> а Димус добавил проверку на Хоринос?

Это я. Чтобы дебаггер не спамил ошибку об отсутствии точки NW_MONASTERY_CHAPELL_02.
