### ISSUE TITLE
AIVAR-

### ISSUE THREAD

**Issue by Kor-Angar** [dosinabox/g2nr_unofficial_update#300]
// **************************
// AIVAR-Kennungen fьr Humans 
// **************************

// ------ NEWS und MEMORY Aivars ------
// - NUR Augenzeugen
// - NUR persцnliches News-Gedдchtnis, geregelt ьber die folgenden Aivars
// - schwere Tat ьberschreibt leichte Tat
// - KEINE automatische News-Verbreitung, AIV-Check bei aNSCs in Dialogen = Ersatz fьr News-Verbreitung
// - News-Vergabe ьber Dialog-Module

https://github.com/dosinabox/g2nr_unofficial_update/blob/master/PrjGOTHIC/AI/AI_Intern/AI_Constants.d

***

Проверь у себя
https://github.com/dosinabox/g2nr_unofficial_update/blob/aed56ebb175bc52740bf908b2ece4ef16490b17d/PrjGOTHIC/AI/AI_Intern/AI_Constants.d#L215

https://github.com/dosinabox/g2nr_unofficial_update/blob/aed56ebb175bc52740bf908b2ece4ef16490b17d/PrjGOTHIC/AI/AI_Intern/AI_Constants.d#L528

***

напиши плиз AIV_CommentedPlayerCrime  он про что
```
const int AIV_CommentedPlayerCrime = 90;
const int DRINK_Water = 0;
const int DRINK_Wine = 1;
const int DRINK_Beer = 2;
const int DRINK_Booze = 3;
const int DRINK_Rum = 4;
```

**Comment by dosinabox** [comment]
> Проверь у себя

уже исправлено в work
https://github.com/dosinabox/g2nr_unofficial_update/blob/work/PrjGOTHIC/AI/AI_Intern/AI_Constants.d

> напиши плиз AIV_CommentedPlayerCrime он про что

для системы комментариев преступлений:
"иди к Ли и оплати штраф"
"я слышал, ты всё уладил"
и т.д.
