### ISSUE TITLE
FP_ROAM для мясных жуков

### ISSUE THREAD

**Issue by Kor-Angar** [dosinabox/g2nr_unofficial_update#304]
> не первый раз замечаю что, что то не то стало с мясными жуками.. расскажи что ты с ним сделала? почему они перестали ползать в большинстве своём?

Ничего. Просто не во всех местах их обитания есть точки вида FP_ROAM. Если сделаешь скриншоты таких мест, то добавлю.

_Originally posted by @dosinabox in https://github.com/dosinabox/g2nr_unofficial_update/issues/41#issuecomment-722165679_

**Comment by Kor-Angar** [comment]
а эти места в мире добавляются? т.е. ты файл zen будешь править?

**Comment by dosinabox** [comment]
> а эти места в мире добавляются? т.е. ты файл zen будешь править?

да

**Comment by Kor-Angar** [comment]
миненталь 4 глава жуки в замке.

**Comment by dosinabox** [comment]
В NEWWORLD.ZEN всё ок

**Comment by dosinabox** [comment]
В ADDONWORLD.ZEN всё ок
В DRAGONISLAND.ZEN  жуков нет

**Comment by dosinabox** [comment]
В OLDWORLD.ZEN всем жукам не хватает точек. В коморке Брутуса на трех жуков две точки, которые они сразу занимают и больше не двигаются. Так же и с остальными. Надо всем добавлять.

**Comment by dosinabox** [comment]
https://github.com/dosinabox/g2nr_unofficial_update/issues/49
