### ISSUE TITLE
Секретное  вино Гритты

### ISSUE THREAD

**Issue by Kor-Angar** [dosinabox/g2nr_unofficial_update#307]
> два сейва про вино.

А что там?

_Originally posted by @dosinabox in https://github.com/dosinabox/g2nr_unofficial_update/issues/155#issuecomment-725901184_

**Comment by Kor-Angar** [comment]
подвернулся случай использовать вино. можно время действия эффекта увеличить, что бы герой успевал совершить трюк.

**Comment by Kor-Angar** [comment]
1 час 51 мин
https://youtu.be/u9MKng7mPwM?t=6673

**Comment by dosinabox** [comment]
Время подбиралось так, чтобы его хватило ровно на один прыжок сразу после употребления. Если увеличить, то игрок сможет сделать два прыжка.

**Comment by Kor-Angar** [comment]
ну и пусть прыгает несколько раз :-) можно еще и эффект быстрого бега добавить.  практическая сторона у вина какая? :-) или это просто некий фетишь? :-)

**Comment by Kor-Angar** [comment]
я это вино и специалисту по алкоголю в лагере пиратов относил :-)

**Comment by dosinabox** [comment]
до скольки увеличить?

**Comment by dosinabox** [comment]
сейчас - 10 секунд, включая время на анимацию выпивания

**Comment by dosinabox** [comment]
> я это вино и специалисту по алкоголю в лагере пиратов относил :-)

Это кому?

**Comment by Kor-Angar** [comment]
Не знаю. Я изначально думал что с вином успею и запрвгнуть и выпругнуть. А быстра селёдка сколько действует? А травка с эффектом вскорения? 21:07, 12 ноября 2020 г., dosinabox <notifications@github.com>:
сейчас - 10 секунд

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
-- Отправлено из мобильного приложения Яндекс.Почты

**Comment by Kor-Angar** [comment]
Самуэль 😀21:07, 12 ноября 2020 г., dosinabox <notifications@github.com>:

я это вино и специалисту по алкоголю в лагере пиратов относил :-)

Это кому?

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
-- Отправлено из мобильного приложения Яндекс.Почты

**Comment by dosinabox** [comment]
> А быстра селёдка сколько действует?

2 минуты

> травка с эффектом вскорения?

15 секунд

**Comment by Kor-Angar** [comment]
я честно говоря не знаю. изначально думал что Вино временно повышает максимальную ману :-)

кроме ярика не знаю где может еще пригодится акробатика. что бы использовать там должно хватить времени и что бы запрыгнуть и собрать лут и успеть выпрыгнуть. но мне так кажется :-)

**Comment by dosinabox** [comment]
> кроме ярика не знаю где может еще пригодится акробатика

Рядом с Гриттой перепрыгнуть с крыши на крышу, чтобы пробраться на склад с одеждой)

> что бы использовать там должно хватить времени и что бы запрыгнуть и собрать лут и успеть выпрыгнуть

Уж очень много времени нужно будет. Там каменные стражи, сундуки, травки, магические стрелы. А зачем выпрыгнуть? Если акробатики нет, то у стража будет свиток телепорта. А со временем починим дерево и будем лазить туда как задумывали разработчики.

**Comment by Kor-Angar** [comment]
Так он и обычным прыжком туда запрыгивает с крыши на крышу😀Может и много 😀 но я другое место не нашёл где можно было бы задействовать вино. А у чёрной руды сколько длительность? 20:53, 14 ноября 2020 г., dosinabox <notifications@github.com>:

кроме ярика не знаю где может еще пригодится акробатика

Рядом с Гриттой перепрыгнуть с крыши на крышу, чтобы пробраться на склад с одеждой)

что бы использовать там должно хватить времени и что бы запрыгнуть и собрать лут и успеть выпрыгнуть

Уж очень много времени нужно будет. Там каменные стражи, сундуки, травки, магические стрелы. А зачем выпрыгнуть? Если акробатики нет, то у стража будет свиток телепорта. А со временем починим дерево и будем лазить туда как задумывали разработчики.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
-- Отправлено из мобильного приложения Яндекс.Почты

**Comment by dosinabox** [comment]
> А у чёрной руды сколько длительность?

30 секунд

**Comment by dosinabox** [comment]
Время действия повышено с 10 до 15 секунд. Хватает на 6-7 прыжков.

**Comment by Kor-Angar** [comment]
> Время действия повышено с 10 до 15 секунд. Хватает на 6-7 прыжков.

ну а на практики в чём это выражается? что можно успеть за эти 15 секунд? можно например проскочить мимо варгов, которые внизу лестницы стоят возле круга солнца? или пропрыгать мимо варанов которые там где амулет во второй главе появляется?

я как понимаю ты это позиционируешь как мини бонус на старте. и это по идеи(опять же это я так понимаю) должна быть альтернативой траве снеппера или черной руде для непрокаченного нищего героя.

иначе это просто пасхалка и тогда проще откатиться на тайминг с одним прыжком.

**Comment by dosinabox** [comment]
Это действительно не более чем пасхалка. Просто за 10 секунд можно даже не успеть понять эффект.
А полезное применение только одно - перепрыгнуть с дома Торбена на дом Матео, если по какой-то причине не получается как у "матерых".

**Comment by Kor-Angar** [comment]
Ну так понятнее. Пасхалка. И лучше без отговорок про дом маттео.  Так как если с оговорокой тогда надо что бы времени хватило: выпить у Гритты понять что это,  залезть накрышку и успеть запрвгнуть на дом маттео.  до 21:56, 21 декабря 2020 г., dosinabox <notifications@github.com>:
Это действительно не более чем пасхалка. Просто за 10 секунд можно даже не успеть понять эффект.
А полезное применение только одно - перепрыгнуть с дома Торбена на дом Матео, если по какой-то причине не получается как у "матерых".

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
-- Отправлено из мобильного приложения Яндекс.Почты
