### ISSUE TITLE
сортировка предметов в инвентаре

### ISSUE THREAD

**Issue by Kor-Angar** [dosinabox/g2nr_unofficial_update#31]
можно сделать что бы в инвентаре после колец к ловкости, шло кольцо к силе/ловкости(оно одно в игре), а потом шли кольца к силе?

**Comment by dosinabox** [comment]
Можно, переименовав предметы. Но если предмет есть где-то в мире, то после переименования он исчезнет. Если предмет уже есть в инвентаре, то после переименования он исчезнет.

**Comment by Kor-Angar** [comment]
А как они сортируются?

**Comment by dosinabox** [comment]
> А как они сортируются?

Оружие - по урону.
Доспехи - по защите.
Всё остальное - по названию инстанции в скриптах (ItRi_Str_01, ItRi_Str_02 и т.д.).

**Comment by dosinabox** [comment]
В gothic.ini настраивается порядок категорий:
```
invCatOrder=COMBAT,POTION,FOOD,ARMOR,MAGIC,RUNE,DOCS,OTHER,NONE
; ... determins the inventory item group order.
```

**Comment by Kor-Angar** [comment]
это кольцо ItRi_Str_02  одно  и оно в продаже у Хуно. теоретически его можно переименовать. но наверное оно того не стоит? :-)

**Comment by dosinabox** [comment]
Лучше не надо.
