### ISSUE TITLE
Обучение Альрик

### ISSUE THREAD

**Issue by Kor-Angar** [dosinabox/g2nr_unofficial_update#310]
Видимо Пираньи подразумевали что Альрик будет учить ГГ, если _**Alrik_Kaempfe >0**_ ?

```
FUNC VOID DIA_Alrik_Ausbilden_Info()
{
	AI_Output (other,self ,"DIA_Alrik_Ausbilden_15_00"); //Kannst du mich ausbilden?
	
	if (Alrik_Kaempfe == 0)
	&& (hero.guild == GIL_NONE)
	{
		AI_Output (self ,other,"DIA_Alrik_Ausbilden_09_01"); //Wenn du wirklich kдmpfen lernen willst, dann tritt gegen mich an. (schmunzelt) Die Lektion ist ganz umsonst.
		Alrik_VorausErzaehlt = TRUE; 
	}
	else //>0
	{
		if (Alrik_VorausErzaehlt == TRUE)
		{
			AI_Output (self ,other,"DIA_Alrik_Ausbilden_09_02"); //Ich stehe zu meinem Wort. Ich werde dir alles beibringen, was ich weiЯ - vorausgesetzt, du bringst die nцtige Erfahrung mit.
		}
		else
		{
			AI_Output (self ,other,"DIA_Alrik_Ausbilden_09_03"); //Vorausgesetzt, du bringst die nцtige Erfahrung mit - klar.
		};
		
		
		Alrik_Teach1H = TRUE;
		Log_CreateTopic (Topic_CityTeacher,LOG_NOTE);
		B_LogEntry (Topic_CityTeacher,"Alrik kann mich im Kampf mit einhдndigen Waffen trainieren. Er hдlt sich hinter dem Lagerhaus im Hafenviertel auf.");
	};
};
```

**Comment by dosinabox** [comment]
Так и есть. Если `Alrik_Kaempfe > 0` **или** если ГГ уже не нейтрал. Возможно, условие гильдии было добавлено позже.
В целом, этот комментарий малоинформативен.

**Comment by Kor-Angar** [comment]
> если ГГ уже не нейтрал

фразы становятся аллогичными, поэтому и обратил внимание на это. судя по репликам Альрик учит героя после того как сразится с ним.

**Comment by dosinabox** [comment]
> фразы становятся аллогичными

какие?

**Comment by Kor-Angar** [comment]
да фигня. ничего такого. просто сначала герой говорит с Альриком нейтралом, а в следующий раз не сражаясь говорит уже наёмником/ментом и тот соглашается его учить говоря о неком обещание :)
я в своей сборке просто убрал проверку на нейтрала.

**Comment by dosinabox** [comment]
тогда тоже уберу
