### ISSUE TITLE
Спящие каменные големы

### ISSUE THREAD

**Issue by dosinabox** [dosinabox/g2nr_unofficial_update#311]
всё равно непонятно. вот в скриптах всё понятно написано тут големы бессмертные без фокуса без имени, а тут они оживают получают имя, фокус и становятся смертными. 
какой смысл им убирать бессмертие непонятно. 
все эти попытки исправить эти "фокусы", через "плагины" из-за которых страдает то баланс то механика непонятна. наверное это есть тот самый перфекционизм :-)

_Originally posted by @Kor-Angar in https://github.com/dosinabox/g2nr_unofficial_update/issues/308#issuecomment-732287067_

**Comment by Kor-Angar** [comment]
оригинальный код
```D
func void B_GolemRise ()
{
	if (Npc_GetDistToNpc (self,hero) <= 700)
	&& (Mob_HasItems ("NW_GOLEMCHEST",ItSe_GolemChest_Mis) == 0)
	{
		AI_PlayAni (self,"T_RISE");
		self.NoFocus	= FALSE;
		self.name			=	"Steingolem";
		self.flags				   			= 	0;
		
		AI_StartState 		(self, ZS_MM_Attack, 0, "");
		self.bodyStateInterruptableOverride 	= FALSE;
		self.start_aistate				= ZS_MM_AllScheduler;
		self.aivar[AIV_MM_RestStart] 	= OnlyRoutine;
	};
		
};

//************************************************************************************
//	Shattered_Golem ->liegt am Boden und setzt sich bei Annäherung des Hero zusammen
//************************************************************************************

INSTANCE Shattered_Golem (Mst_Default_StoneGolem)
{
	name							=	"";
	guild							=	GIL_STONEGOLEM;
	aivar[AIV_MM_REAL_ID]			= 	ID_STONEGOLEM;
	level							=	18;
	
	NoFocus	= TRUE;
	
	flags				   			= 	NPC_FLAG_IMMORTAL;
	bodyStateInterruptableOverride = TRUE;
	
	B_SetVisuals_StoneGolem();
	Npc_SetToFistMode	(self);
	
	start_aistate				= ZS_GolemDown;
	
	aivar[AIV_MM_RestStart] 	= OnlyRoutine;
};
```

**Comment by Kor-Angar** [comment]
Големы в пещере с ползунами #238

**Comment by dosinabox** [comment]
Попробую объяснить.

Ни в классике, ни в аддоне не работает флаг npc `noFocus`. Он должен запрещать игроку возможность ударить npc с этим флагом - мечом, кулаком, прицелиться магией или луком. Npc как бы просто сливается с окружающим миром и недоступен для атаки. Это по задумке. А по факту все спящие големы легко берутся в фокус и бесконечно проигрывают анимацию получения урона (флаг `bodyStateInterruptableOverride` тоже не работает?). Поэтому при получении урона им была добавлена реакция - проснуться, снять бессмертие, получить имя и атаковать ГГ. Но из-за прерываемой анимации пробуждения они всё равно беспомощные. Получилось даже хуже, потому что таких беспомощных их теперь можно убить.

При этом, даже с плагином с исправлением флага `noFocus` и бессмертием големы могут проиграть анимацию получения урона от воздействия магии "по области", случайного попадания стрелы или атаки призванных существ. Я считаю, что если игрок увидел такое, то уже нет смысла держать голема спящим - пусть собирается до конца и атакует. Видимо, я считаю неправильно и следует вернуть всё как было)

> а если при старте игры вставить обычных големов и убить их? а при открытие сундука убрать их из мира и вставить уже Shattered_Golem ?

Не големов, потому что их трупы можно обчистить и тогда они пропадут (впрочем, нужно проверить фокус **трупов** с плагином). Лучше **модели** спящих големов. При открытии сундука они удаляются, а на их места вставляются настоящие спящие големы и пробуждаются при приближении игрока. Проблема только одна - один из таких големов находятся прямо около сундука и игрок может заметить его подмену. Также игрок может использовать миры из текстурных паков, где этих заранее вставленных моделей не будет.

**Comment by dosinabox** [comment]
https://github.com/dosinabox/g2nr_unofficial_update/commit/ff3091e736034fb2b47e56070682133b92b6dc1a#diff-a4807d0e9a856c82d99426fc5d37fb3134a6e923e87149afa5ef2d188ba64981

**Comment by dosinabox** [comment]
Пока попробую вставлять мертвых големов

**Comment by Kor-Angar** [comment]
да про ноу фокус я понял -)


> Проблема только одна - один из таких големов находятся прямо около сундука и игрок может заметить его подмену. 

он когда открывает сундук , спиной к голему находится и не видно что там происходит

> Я считаю, что если игрок увидел такое, то уже нет смысла держать голема спящим - пусть собирается до конца и атакует. Видимо, я считаю неправильно и следует вернуть всё как было)

опять же вот если бы ты запустила игру, пришла бы туда например послушником с посохом.. тогда сразу бы стало понятно, что в твоей версии условно их можно будить и по одному убивать без проблем. подло и дерзко. а в том случае они находятся условно по два и два голема убить не так просто как кажется на первый взгляд в теории. там вообще такое дело что когда ты понимаешь первый раз что разбудил големов самая рабочая тактика это просто убежать.

**Comment by dosinabox** [comment]
> тогда сразу бы стало понятно, что в твоей версии условно их можно будить и по одному убивать без проблем. подло и дерзко.

Только если у игрока нет Юниона. Думаю, таких ещё большинство.
Надеюсь, предварительная вставка мертвых големов решит проблему, а плагин не позволит забрать у них монетки.

**Comment by dosinabox** [comment]
И всё же - как быть с уровнями?) Подогнать спящих до 25, немного их ослабить или ничего не делать?

**Comment by Kor-Angar** [comment]
> Только если у игрока нет Юниона. Думаю, таких ещё большинство.

ну начинается.. опять про сегрегацию игроков. я специально в своё время купил стим версию и поставил твой полный стим-фикс что бы стать "правильным" игроком :-) и не могу сказать что с того момента что то принципиально поменялось:-) опять про какие то плагины, которые надо ставить, что бы игра загрузилась.

в последней версии кстати члены кольца-воды после собрания в таверне обратно не переоделись :-)

> И всё же - как быть с уровнями?) Подогнать спящих до 25, немного их ослабить или ничего не делать?

в классике параметры у Големов такие же? только уровни отличаются?

**Comment by dosinabox** [comment]
> опять про какие то плагины, которые надо ставить, что бы игра загрузилась.

Они входят в состав обновления начиная с 25 версии.

> в классике параметры у Големов такие же? только уровни отличаются?

да и да

> в последней версии кстати члены кольца-воды после собрания в таверне обратно не переоделись :-)

Есть сохраненка и/или запись стрима?

**Comment by Kor-Angar** [comment]
> Они входят в состав обновления начиная с 25 версии.

так они же и там убиваются.

> Есть сохраненка и/или запись стрима?

сохранялки у тебя есть. стрима записи тоже есть собрание КВ на третьем видео https://youtu.be/GFVWF7tmHcc?t=12000

**Comment by Kor-Angar** [comment]
>> в классике параметры у Големов такие же? только уровни отличаются?
> да и да

тогда такая задумка у авторов. так как это не ошибка при "спайки" Готики 2 и аддона.

**Comment by Kor-Angar** [comment]
Ссылка на Сейвы в топике про Диего в Минентале. 13:31, 24 ноября 2020 г., dosinabox <notifications@github.com>:

опять про какие то плагины, которые надо ставить, что бы игра загрузилась.

Они входят в состав обновления начиная с 25 версии.

в классике параметры у Големов такие же? только уровни отличаются?

да и да

в последней версии кстати члены кольца-воды после собрания в таверне обратно не переоделись :-)

Есть сохраненка и/или запись стрима?

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.
-- Отправлено из мобильного приложения Яндекс.Почты

**Comment by dosinabox** [comment]
В целом получилось ОК. Только спящие големы при вставке проигрывают анимацию разборки и звук. Из-за звука при открытии сундука нарушается эффект неожиданности при выходе.

**Comment by Kor-Angar** [comment]
Запись есть? 😀

**Comment by dosinabox** [comment]
https://youtu.be/UaXDm1wOLNk

**Comment by Kor-Angar** [comment]
> Только спящие големы при вставке проигрывают анимацию разборки и звук.

а мне кажется даже в тему получилось. звуковой сигнал так сказать предупреждает :-)

**Comment by Kor-Angar** [comment]
а они там случайно повторно не разрушаются.? что то не понял.. выложи сборку, потестирую.

**Comment by dosinabox** [comment]
> а они там случайно повторно не разрушаются.?

Shattered_Golem вставляется в мир в обычном исходном состоянии (стоя). Потом у него сразу начинается состояние "сна" ZS_GolemDown, для которого он должен проиграть анимацию "разрушения" T_DEAD. В одном из кадров анимации проигрывается звук.

**Comment by dosinabox** [comment]
> выложи сборку, потестирую.

https://dropmefiles.com/ZnUJ6
Нужно начало новой игры.

**Comment by dosinabox** [comment]
Проверка была?

**Comment by Kor-Angar** [comment]
только теставая

**Comment by Kor-Angar** [comment]
https://github.com/dosinabox/g2nr_unofficial_update/issues/238

**Comment by Kor-Angar** [comment]
големы прекрасны. в фокус не попадают. только один немного над землёй, ну не критично. на фотке не видно
![20210506195707_1](https://user-images.githubusercontent.com/49514764/117354446-01116780-aeba-11eb-8b24-d27dd9a47f2e.jpg)

**Comment by dosinabox** [comment]
Им бы анимацию сборки ускорить, и пробуждать пораньше. Но это на будущее.

**Comment by Kor-Angar** [comment]
мне кажется они все одновременно должно оживать
