### ISSUE TITLE
Женские голоса из Готики 1.

### ISSUE THREAD

**Issue by Kor-Angar** [dosinabox/g2nr_unofficial_update#314]
Кажется в Готики 1 от снежков были озвучены микроразговоры с женскими репликами.

https://www.youtube.com/watch?v=cY2SW1VZLq8

**Comment by Kor-Angar** [comment]
> Кажется в Готики 1 от снежков были озвучены микроразговоры с женскими репликами.

хотя судя по качеству это из какого то мода наверное

**Comment by dosinabox** [comment]
Из мода. Официально озвучивались только эти реплики:
```cpp
instance SVM_16(C_SVM)
{
	notnow = "SVM_16_NotNow";	//Уходи! Тебе нельзя со мной разговаривать!
	help = "SVM_16_Help";	//
	aargh_1 = "SVM_16_Aargh_1";	//
	aargh_2 = "SVM_16_Aargh_2";	//
	aargh_3 = "SVM_16_Aargh_3";	//
	dead = "SVM_16_Dead";	//
};
```

**Comment by dosinabox** [comment]
Но проблема такая есть. В русской Г2 SVM фразы второго женского голоса отдельно озвучивать не стали, а просто скопировали все фразы первого.
