### ISSUE TITLE
Джо сидит в Башне № 5

### ISSUE THREAD

**Issue by Kor-Angar** [dosinabox/g2nr_unofficial_update#315]
После того как герой открывает башню Джо продолжает сидеть. хотя по идеи должен сам что то сказать герою и быстрее убегать.

https://www.youtube.com/watch?v=EO6gBG4VMuM

**Comment by dosinabox** [comment]
В оригинале - только если ГГ обратится к нему первый. Стоит условие Npc_IsInState(self,ZS_Talk). Наверное, чтобы он не заговорил с ГГ за закрытой дверью.

**Comment by Kor-Angar** [comment]
а если молотку сделать уникальную инстанцию и у Джо сделать проверку на неё?
```D
func int DIA_Joe_Hallo_Condition()
{
	if(Npc_IsInState(self,ZS_Talk))
	{
		return TRUE;
	};
	
	if(Npc_HasItems(other,ItMw_Kriegshammer2_CITY_WEAPON_05))
	{
		return TRUE;
	};
};
```
тогда как только герой схватит молоток Джо с ним тут же заговорит? :-)

**Comment by Kor-Angar** [comment]
а если молотку сделать уникальную инстанцию и у Джо сделать проверку на неё?
```D
func int DIA_Joe_Hallo_Condition()
{
	if(Npc_IsInState(self,ZS_Talk))
	{
		return TRUE;
	};
	
	if(Npc_HasItems(other,ItMw_Kriegshammer2_CITY_WEAPON_05))
	{
		return TRUE;
	};
};
```
тогда как только герой схватит молоток Джо с ним тут же заговорит? :-) https://github.com/Kor-Angar/G2_NotR_Kor_Angar/commit/55b3acd7835990e877b85480cab5374656abc816

**Comment by Kor-Angar** [comment]
и по моему раньше Джо  бежал  в Таверну в порту, а сейчас идёт.. или нет? :-)

**Comment by dosinabox** [comment]
> и по моему раньше Джо бежал в Таверну в порту, а сейчас идёт.. или нет? :-)

Шел в оригинале. В обновлении бежит.

> тогда как только герой схватит молоток Джо с ним тут же заговорит?

Достаточно проверки на расстояние до точки внутри башни. Джо заговорит первый, когда ГГ зайдет к нему.

```cpp
func int DIA_Joe_Hallo_Condition()
{
	if(Npc_IsInState(self,ZS_Talk) || (Npc_GetDistToWP(hero,"NW_CITY_MERCHANT_TOWER_01") <= 210))
	{
		return TRUE;
	};
};
```

**Comment by Kor-Angar** [comment]
Не глюканет с расстоянием, если герой за самогоном полезит или об Каваларона споткнется? 18:00, 4 января 2021 г., dosinabox <notifications@github.com>:

и по моему раньше Джо бежал в Таверну в порту, а сейчас идёт.. или нет? :-)

Шел в оригинале. В обновлении бежит.

тогда как только герой схватит молоток Джо с ним тут же заговорит?

Достаточно проверки на расстояние до точки внутри башни. Джо заговорит первый, когда ГГ зайдет к нему.
func int DIA_Joe_Hallo_Condition()
{
	if(Npc_IsInState(self,ZS_Talk) || (Npc_GetDistToWP(hero,"NW_CITY_MERCHANT_TOWER_01") <= 210))
	{
		return TRUE;
	};
};

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
-- Отправлено из мобильного приложения Яндекс.Почты

**Comment by dosinabox** [comment]
Проверено, слишком далеко. И через стены Джо не видит.
