### ISSUE TITLE
доступ в верхний квартал. Послушник

### ISSUE THREAD

**Issue by Kor-Angar** [dosinabox/g2nr_unofficial_update#316]
Послушника почему то непускают в верхний квартал. так было и в оригинальных скриптах?

**Comment by dosinabox** [comment]
Да. Нейтрал и послушник равны в правах и попадают в верхний квартал только став учеником мастера.

**Comment by dosinabox** [comment]
Но и там на них ругаются уважаемые граждане)

```cpp
func int DIA_Lutero_GetLost_Condition()
{
	if(((other.guild == GIL_NONE) || (other.guild == GIL_NOV)) && Npc_IsInState(self,ZS_Talk))
	{
		return TRUE;
	};
};

func void DIA_Lutero_GetLost_Info()
{
	if(other.guild == GIL_NONE)
	{
		AI_Output(self,other,"DIA_Lutero_GetLost_13_00");	//Проваливай отсюда! Тебе что, нечего делать? Тогда найди себе работу - только где-нибудь еще!
	}
	else
	{
		AI_Output(self,other,"DIA_Lutero_GetLost_13_01");	//Что тебе нужно, послушник? Разве ты не должен быть в монастыре?
	};
	AI_StopProcessInfos(self);
};
```

**Comment by Kor-Angar** [comment]
странно конечно. послушника по идеи должны в верхний квартал пускать. он спокойно и в казарму заходит и в башни. 
а во всяких аи гильдий послушник идёт как мент?

**Comment by dosinabox** [comment]
> а во всяких аи гильдий послушник идёт как мент?

Это как?

**Comment by Kor-Angar** [comment]
Это был вопрос. Послушника не гонят из казармы, не гонят из башен. В связи с этим я и спросил. 0:24, 5 января 2021 г., dosinabox <notifications@github.com>:

а во всяких аи гильдий послушник идёт как мент?

Это как?

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
-- Отправлено из мобильного приложения Яндекс.Почты

**Comment by Kor-Angar** [comment]
Это да. Но и на этот диалог надо смотреть через призму Готики 2 классик. Был ли он там и если был то был  ли только в 1 главе и так далее. 18:30, 4 января 2021 г., dosinabox <notifications@github.com>:
Но и там на них ругаются уважаемые граждане)
func int DIA_Lutero_GetLost_Condition()
{
	if(((other.guild == GIL_NONE) || (other.guild == GIL_NOV)) && Npc_IsInState(self,ZS_Talk))
	{
		return TRUE;
	};
};

func void DIA_Lutero_GetLost_Info()
{
	if(other.guild == GIL_NONE)
	{
		AI_Output(self,other,"DIA_Lutero_GetLost_13_00");	//Проваливай отсюда! Тебе что, нечего делать? Тогда найди себе работу - только где-нибудь еще!
	}
	else
	{
		AI_Output(self,other,"DIA_Lutero_GetLost_13_01");	//Что тебе нужно, послушник? Разве ты не должен быть в монастыре?
	};
	AI_StopProcessInfos(self);
};

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
-- Отправлено из мобильного приложения Яндекс.Почты

**Comment by dosinabox** [comment]
> Это был вопрос. Послушника не гонят из казармы, не гонят из башен. В связи с этим я и спросил.

Это да, но вопрос мне не понятен.

> Но и на этот диалог надо смотреть через призму Готики 2 классик. Был ли он там и если был то был  ли только в 1 главе и так далее.

Был, с таким же условием.

**Comment by Kor-Angar** [comment]
> Это да, но вопрос мне не понятен.

вопрос: героя выгоняют из казарм в зависимости от фракции?
