### ISSUE TITLE
Пабло  объявление о розыске / DIA_Pablo_WANTED

### ISSUE THREAD

**Issue by Kor-Angar** [dosinabox/g2nr_unofficial_update#317]
вчера первый раз встретил Пабло будучи милиционером. Пабло начал говорить мне некорректную чушь из области

	AI_Output(self,other,"DIA_Pablo_WANTED_NOTHING_12_03");	//А чужаки, которые приносят в город проблемы, долго здесь не задерживаются - надеюсь, я ясно выразился.

хотел предложить поставить ограничение на этот диалог, что бы он не был доступен менту и магу огня... открыл код, а там оказывается у пираней изначально было это ограничение

```
func int DIA_Pablo_WANTED_Condition ()
{
	if (hero.guild != GIL_MIL)
	&& (hero.guild != GIL_PAL)
	&& (hero.guild != GIL_KDF)
	{
		return TRUE;
	};	
};
```
а в неофициальном обновление оно было зачем то снято.. не знаешь зачем? :-)

**Comment by dosinabox** [comment]
Диалог полезен в качестве предупреждения. А условия можно перенести в сами реплики, чтобы они не были некорректными:

```cpp
func void DIA_Pablo_WANTED_NOTHING()
{
	AI_Output(other,self,"DIA_Pablo_WANTED_NOTHING_15_00");	//Нет, боюсь, что ты ошибаешься. Со мной все в порядке...
	if((hero.guild != GIL_MIL) && (hero.guild != GIL_PAL) && (hero.guild != GIL_KDF))
	{
		AI_Output(self,other,"DIA_Pablo_WANTED_NOTHING_12_01");	//Как скажешь, чужеземец.
	}
	else
	{
		AI_Output(self,other,"DIA_Pablo_WANTED_NOTHING_12_01_add");	//Как скажешь.
	};
	AI_Output(self,other,"DIA_Pablo_Add_12_00");	//Но если это все же ТВОЯ физиономия - и если у тебя возникнут проблемы - постарайся решать их за городом. Здесь и без того трудностей хватает.
	if((hero.guild != GIL_MIL) && (hero.guild != GIL_PAL) && (hero.guild != GIL_KDF))
	{
		AI_Output(self,other,"DIA_Pablo_WANTED_NOTHING_12_03");	//А чужаки, которые приносят в город проблемы, долго здесь не задерживаются - надеюсь, я ясно выразился.
	};
	Pablo_belogen = TRUE;
	AI_StopProcessInfos(self);
};
```

Возможно, паладина предупреждать об этом уже не нужно: это будет третья глава, а Пабло ниже по иерархии.

**Comment by Kor-Angar** [comment]
Ты думаешь такая реплика допустима по отношению к Магу Огня? :-)

> AI_Output(self,other,"DIA_Pablo_Add_12_00");	//Но если это все же ТВОЯ физиономия - и если у тебя возникнут проблемы - постарайся решать их за городом. Здесь и без того трудностей хватает.

посмотри в том же файле на реплики у Пабло, как он говорит в 3 главе с Наёмом, Ментом и Магом ;-) на то какое разное отношение и реплики у Пабло в зависимости от фракции.

но в целом мне понятен смысл этой правки, на лицо ошибка  разработчиков которую надо исправить :-))

**Comment by dosinabox** [comment]
> Ты думаешь такая реплика допустима по отношению к Магу Огня? :-)

Нет, поэтому можно сделать так:

```cpp
func int DIA_Pablo_WANTED_Condition()
{
	if(hero.guild != GIL_PAL)
	{
		return TRUE;
	};
};

func void DIA_Pablo_WANTED_Info()
{
	AI_Output(self,other,"DIA_Pablo_WANTED_12_00");	//Эй, ты, подожди - мне кажется, я тебя знаю.
	AI_Output(other,self,"DIA_Pablo_WANTED_15_01");	//Что тебе нужно?
	AI_Output(self,other,"DIA_Pablo_WANTED_12_02");	//Я где-то уже видел твое лицо... ах - точно!
	B_UseFakeHeroFace();
	AI_Output(self,other,"DIA_Pablo_WANTED_12_03");	//Вот - мы нашли этот листок у одного из бандитов, на которых наткнулись несколько дней назад - рисунок очень похож на тебя.
	B_GiveInvItems(self,other,ItWr_Poster_MIS,1);
	B_UseFakeScroll_Hero();
	AI_Output(self,other,"DIA_Pablo_WANTED_12_04");	//По-видимому, эти парни искали тебя.
	B_PlayerEnteredCity();
	Info_ClearChoices(DIA_Pablo_WANTED);
	Info_AddChoice(DIA_Pablo_WANTED,"Нет, боюсь, что ты ошибаешься. Со мной все в порядке...",DIA_Pablo_WANTED_NOTHING);
	Info_AddChoice(DIA_Pablo_WANTED,"Хм, я сам бы об этом никогда не догадался.",DIA_Pablo_WANTED_IRONY);
};

func void DIA_Pablo_WANTED_NOTHING()
{
	AI_Output(other,self,"DIA_Pablo_WANTED_NOTHING_15_00");	//Нет, боюсь, что ты ошибаешься. Со мной все в порядке...
	if((hero.guild != GIL_MIL) && (hero.guild != GIL_KDF))
	{
		AI_Output(self,other,"DIA_Pablo_WANTED_NOTHING_12_01");	//Как скажешь, чужеземец.
		AI_Output(self,other,"DIA_Pablo_Add_12_00");	//Но если это все же ТВОЯ физиономия - и если у тебя возникнут проблемы - постарайся решать их за городом. Здесь и без того трудностей хватает.
		AI_Output(self,other,"DIA_Pablo_WANTED_NOTHING_12_03");	//А чужаки, которые приносят в город проблемы, долго здесь не задерживаются - надеюсь, я ясно выразился.
	}
	else
	{
		AI_Output(self,other,"DIA_Pablo_WANTED_NOTHING_12_01_add");	//Как скажешь. Ты можешь рассчитывать на нас.
	};
	Pablo_belogen = TRUE;
	AI_StopProcessInfos(self);
};
```

> посмотри в том же файле на реплики у Пабло, как он говорит в 3 главе с Наёмом, Ментом и Магом ;-) на то какое разное отношение и реплики у Пабло в зависимости от фракции.

При этом с магом или паладином у него может состояться такой диалог:

```cpp
AI_Output(self,other,"DIA_Pablo_Add_12_09");	//А-ГА! Так это все же ТВОЯ физиономия там. А почему ты сразу это не признал, а?
AI_Output(self,other,"DIA_Pablo_Add_12_10");	//(требовательно) За что тебя разыскивают?
AI_Output(other,self,"DIA_Pablo_Add_15_11");	//Я не знаю - честно!
AI_Output(self,other,"DIA_Pablo_Add_12_12");	//Да, да. Конечно. Я хочу, чтобы ты кое-что понял. Если бы я думал, что ты был сообщником этих бандитов, ты бы уже отдыхал за решеткой.
```

> но в целом мне понятен смысл этой правки, на лицо ошибка разработчиков которую надо исправить :-))

В целом мне понятен смысл таких комментариев и можешь не упражняться в острословии - у меня сердце потом болит.

**Comment by Kor-Angar** [comment]
у меня тоже болит сердце от того что происходит. и острословие остаётся единственным приёмом, который помогает абстрагироваться  от происходящего и уменьшить накал. меня это цепляет за живое и я  на это реагирую остро

ну не может мент тыкать магу огня. есть две большие разницы: встретить героя оборванца, предъявить ему, а потом встретить его когда тот стал магом, и в этом случае есть хотя бы некий бэк.

но если он встречает героя первый раз когда тот маг или мент или пал (а мне лично кажется даже послушник), то не может он брать и что то там магу предъявлять, предупреждать его или что то там такое. это социальная иерархия, субординация и так далее. 
он если даже заметит что то, то всё равно не скажут, так как это напрямую может повлиять на него. он же находится по сути на службе у государства, а церковь неотделимая часть этого государство. вот оно про то.

и заметь что та же самая история с Мика, который в упор не понимает кто перед ним стоит. и вот дескать менту он там что то там куда то там. а герой мент просто стуканёт на него Андре и всё. так же как герой может стукануть Андре про Пека. Это как раз те риски/моменты которые и формирует отношения между фракциями.

Вот есть наём/нейтрал это никто и звать их никак.
Маг / Паладин это начальство. Большие люди которые могут повлиять на судьбу мента и в первую очередь отрицательно повлиять. Поэтому надо говорить исключительно уважительно, что бы ни кому не показалось что Милиционер дерзит.
а есть ополченцы  это твои коллеги. с одной стороны они свои в доску ребята, но с другой стороны могут и стукануть начальнику на тебя.

вот это чётко прописано пираньями у ополченцев в скриптах. даже проверка на гильдию паладина на  входе в городе была. Но есть дырки где этого нет, например у то же Мики. исправлять дырки это хорошо. перекраивать уже имеющиеся искажая порой первоначальный посыл это не то. 

Они же по сути просто тормозят героя и начинают ему что то предъявлять. у тебя сейчас вот так:
идёт Маг Огня в верхний квартал и тут к нему подлетает мент, останавливает его и говорит:
AI_Output(self,other,"DIA_Pablo_WANTED_12_00");	//Эй, ты, подожди - мне кажется, я тебя знаю.
или идёт мент в верхний квартал и тут его тормозит коллега и говорит
AI_Output(self,other,"DIA_Pablo_WANTED_12_00");	//Эй, ты, подожди - мне кажется, я тебя знаю.

да можно выдать полезную инфу, прокрутить какой то диалог, который скрыт в условиях, но ведь когда оно начинает нести иной смысл или искажать изначальный, возникает вопрос, а оно того стоит? игра настолько переполнена контентом, что его просто весь не охватить. и он местами всё таки [должен быть взаимоисключающим](https://www.youtube.com/watch?v=c6BhTo2yYxQ), как оно и было задумано авторами.

**Comment by dosinabox** [comment]
Подытожим:

Диалог DIA_Pablo_WANTED можно оставить для ополченца (?).
Диалог DIA_Pablo_MyBandits остается как в оригинале (?).

**Comment by Kor-Angar** [comment]
сложно мне про такое. я вот сейчас играл и опять слушал как Мики какую то дичь втирает Менту :-)

сил на это уходит много, а толку от этого мало :-)

**Comment by dosinabox** [comment]
> Мики какую то дичь втирает Менту

Какую именно?

**Comment by Kor-Angar** [comment]
ну первый диалог  с Микки если герой мент.

**Comment by dosinabox** [comment]
> ну первый диалог с Микки если герой мент.

DIA_Mika_WOHIN?

**Comment by Kor-Angar** [comment]
ага и все что вытекает дальше DIA_Mika_WASGEFAEHRLICH и дальше DIA_Mika_WASKOSTETHILFE
