### ISSUE TITLE
Режим трусости

### ISSUE THREAD

**Issue by Kor-Angar** [dosinabox/g2nr_unofficial_update#318]
Как работает режим трусости?  

Трусость у всех НПС сработает или только у тех у кого 	fight_tactic = FAI_HUMAN_COWARD; ?

**Comment by Kor-Angar** [comment]
https://youtu.be/phWuj4Ge70c?t=1899

**Comment by dosinabox** [comment]
Все условия описаны здесь:
https://github.com/dosinabox/g2nr_unofficial_update/blob/master/PrjGOTHIC/AI/Human/C_Human/C_WantToFlee.d

**Comment by Kor-Angar** [comment]
```
if((slf.fight_tactic == FAI_HUMAN_COWARD) && (slf.attribute[ATR_HITPOINTS] < (slf.attribute[ATR_HITPOINTS_MAX] / 2)))
				{
					return TRUE;	// ...óáåãàåò òðóñ!
				};
				if((slf.fight_tactic == FAI_HUMAN_STRONG) && (slf.attribute[ATR_HITPOINTS] < (slf.attribute[ATR_HITPOINTS_MAX] / 4)))
				{
					return TRUE;	// ...óáåãàåò ñèëüíûé áîåö!
				};
```
а FAI_HUMAN_NORMAL ?

они же так идут COWARD --> NORMAL  -->  STRONG --> Master ?

**Comment by dosinabox** [comment]
Лучше просто заменить здесь FAI_HUMAN_STRONG на FAI_HUMAN_NORMAL, а FAI_HUMAN_STRONG и FAI_HUMAN_MASTER пусть не убегают вовсе.

**Comment by Kor-Angar** [comment]
Я как раз это и хотел предложить 😀 трусость протестить надо. хорошо, особенно в городе на НПС. Так как может кто не трус по сути но у него трусость сработает, как у Константино. 11:41, 10 января 2021 г., dosinabox <notifications@github.com>:
Лучше просто заменить здесь FAI_HUMAN_STRONG на FAI_HUMAN_NORMAL, а FAI_HUMAN_STRONG и FAI_HUMAN_MASTER пусть не убегают вовсе.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
-- Отправлено из мобильного приложения Яндекс.Почты

**Comment by dosinabox** [comment]
Дурацкий режим, на самом деле. Даже если у НПС есть шанс победить ГГ, то в середине боя он прячет оружие и застывает в станлоке, пытаясь убежать. И умирает. А убегающие животные делают жизнь лучника невыносимой. А самый первый волк у башни Ксардаса убегал к Кавалорну, агрил его и гоблинов, и всей толпой они забегали к Браго в пещеру)
Поэтому отключение этого режима было первым, что я сделала когда продолжила работу Димуса.

**Comment by Kor-Angar** [comment]
ну, а если убегать не пряча оружие? :-) в Готике 1 они убегали по моему с вытащенным оружием?
