### ISSUE TITLE
Мика тормозит Мента / Мага / Пала DIA_Mika_WOHIN

### ISSUE THREAD

**Issue by Kor-Angar** [dosinabox/g2nr_unofficial_update#319]
> Мика какую то дичь втирает Менту

https://youtu.be/phWuj4Ge70c?t=3449

**Comment by Kor-Angar** [comment]
второй диалог https://youtu.be/phWuj4Ge70c?t=3493

**Comment by dosinabox** [comment]
Варианты решения? Запретить говорить это магу и паладину?

**Comment by Kor-Angar** [comment]
не знаю. надо осознать. понять что хотели изначально авторы. всё таки подразумевается что герой Маг изначально идёт через город в монастырь и говорить с Мики будучи нейтралом. Ровно как и Паладин не должен по идеи избежать встречи. тут более менее понятно. а вот как Мики должен себя вести по отношению к менту не ясно. с одной стороны он что то может сказать, с другой стороны тормозить товарище на службе который куда то идёт не совсем корректно. тут я не знаю.

кстати Мика тормознёт героя если герой будет бежать с Ларесом?

**Comment by dosinabox** [comment]
> кстати Мика тормознёт героя если герой будет бежать с Ларесом?

Нет:
```cpp
func int DIA_Mika_WOHIN_Condition()
{
	if((Lares.aivar[AIV_PARTYMEMBER] == FALSE) && (Npc_GetDistToWP(self,"NW_CITY_TO_FOREST_01") < 700))
	{
		return TRUE;
	};
};
```

**Comment by Kor-Angar** [comment]
можно учесть это и если ГГ уже ходил мимо него с Ларесом, то Мика не станет тормозить ГГ и спрашивать кто он и откуда пришёл, так как уже видел героя который пробегал мимо с Ларесом :-)

**Comment by dosinabox** [comment]
Ещё нужно учитывать ГГ в тяжелых доспехах ополчения (?), потому что в них ГГ тоже будет старше Мики по иерархии (?). 

> можно учесть это и если ГГ уже ходил мимо него с Ларесом, то Мика не станет тормозить ГГ и спрашивать кто он и откуда пришёл, так как уже видел героя который пробегал мимо с Ларесом :-)

Тогда пропадет возможность взять Мику на разборку с Альваресом и Энгардо на ферме.

**Comment by dosinabox** [comment]
В общем-то, проблема только в начальной реплике и диалоге про опасность. Поэтому можно ограничить эти диалоги для мага и паладина, а реплику "Ну, предположим, я обращусь к тебе за помощью. Сколько это будет мне стоить?" заменить на "Мне нужна твоя помощь" и убрать условие диалога про опасность. Так и дурацких реплик не будет, и возможность помощи не пропадет.

**Comment by Kor-Angar** [comment]
ну и мента туда же к магам и палладинам. это же его коллега :-)

**Comment by dosinabox** [comment]
Вот так:
https://github.com/dosinabox/g2nr_unofficial_update/commit/dca6d829009e37fcdb3615222d3c0d22ff107f26#diff-7553bd33f0f6b9c52e2c07205c89ecc1ec9fcea39b0564ff338de62b7fbbb408

**Comment by Kor-Angar** [comment]
```
	else if((VisibleGuild(other) == GIL_KDF) || (VisibleGuild(other) == GIL_PAL) || ArmorEquipped(other,ITAR_MIL_M))
```
а мент в лёгкой броне?

**Comment by dosinabox** [comment]
Точно нужно? Социальный статус равен, но ГГ - новое лицо в ополчении, и Мика может его задирать а-ля "дедушка".

**Comment by Kor-Angar** [comment]
ну давай диалог попробуем воспроизвести какой будет. Мика тормознёт мента при первой встречи?

**Comment by Kor-Angar** [comment]
так Мика получается всё равно условно Пала остановит?

```D
instance DIA_Mika_WOHIN(C_Info)
{
	npc = MIL_337_Mika;
	nr = 4;
	condition = DIA_Mika_WOHIN_Condition;
	information = DIA_Mika_WOHIN_Info;
	important = TRUE;
};


func int DIA_Mika_WOHIN_Condition()
{
	if	(Lares.aivar[AIV_PARTYMEMBER] == FALSE) 
	&&	(Npc_GetDistToWP(self,"NW_CITY_TO_FOREST_01") < 700))
	{
		return TRUE;
	};
};

func void DIA_Mika_WOHIN_Info()
{
	if(C_Mika_FreeHelp())
	{
		AI_Output(self,other,"DIA_Mika_WOHIN_Bauern_12_01_add");	//Не стоит бродить по этим опасным тропам совсем одному. Если тебе понадобится моя помощь, ты знаешь, где найти меня.
		Mika_Helps = TRUE;
	}
	else
	{
		AI_Output(self,other,"DIA_Mika_WOHIN_12_00");	//Эй, эй! Не так быстро. Прогуливаться здесь одному довольно опасно. Откуда ты идешь?
		Info_ClearChoices(DIA_Mika_WOHIN);
		Info_AddChoice(DIA_Mika_WOHIN,"Это не твое дело.",DIA_Mika_WOHIN_weg);
		if(other.guild == GIL_NONE)
		{
			Info_AddChoice(DIA_Mika_WOHIN,"С одной из ферм.",DIA_Mika_WOHIN_Bauern);
		};
		Info_AddChoice(DIA_Mika_WOHIN,"Из города!",DIA_Mika_WOHIN_stadt);
	};
};
```

**Comment by dosinabox** [comment]
Сборка: https://dropmefiles.com/DlGE4

**Comment by dosinabox** [comment]
```cpp
B_Say(self,other,"$AWAKE");
```
Оказалось чем-то ужасным) Нужна другая реплика с голосом Репетура.

**Comment by Kor-Angar** [comment]
запустил. ужас ужасный. у Мики явно с головой плохо теперь :-) Вроде мальчик, а голова женская :-)



Мальчик на службе должен знать что такое субординация 
```
func int DIA_Mika_WOHIN_Condition()
{
	if(C_Mika_FreeHelp())
	{
		return false;
	};

	if	(Lares.aivar[AIV_PARTYMEMBER] == FALSE) 
	&&	(Npc_GetDistToWP(self,"NW_CITY_TO_FOREST_01") < 700))
	{
		return TRUE;
	};
};
```

а вот отношение внутри коллектива
```
func void DIA_Mika_WOHIN_Info()
{
	//if	(C_Mika_FreeHelp())
	if	(VisibleGuild(other) == GIL_Mil)
	{
		AI_Output(self,other,"DIA_Mika_WOHIN_Bauern_12_01_add");	//Не стоит бродить по этим опасным тропам совсем одному. Если тебе понадобится моя помощь, ты знаешь, где найти меня.
		Mika_Helps = TRUE;
	}
	else
	{
		AI_Output(self,other,"DIA_Mika_WOHIN_12_00");	//Эй, эй! Не так быстро. Прогуливаться здесь одному довольно опасно. Откуда ты идешь?
		Info_ClearChoices(DIA_Mika_WOHIN);
		Info_AddChoice(DIA_Mika_WOHIN,"Это не твое дело.",DIA_Mika_WOHIN_weg);
		if(other.guild == GIL_NONE)
		{
			Info_AddChoice(DIA_Mika_WOHIN,"С одной из ферм.",DIA_Mika_WOHIN_Bauern);
		};
		Info_AddChoice(DIA_Mika_WOHIN,"Из города!",DIA_Mika_WOHIN_stadt);
	};
};
```

***

а вот это всё 

```
func int DIA_Mika_HILFE_Condition()
{
	if(self.aivar[AIV_PARTYMEMBER] == FALSE)
	{
		if(C_Mika_FreeHelp())
		{
			return TRUE;
		};
		if(Npc_KnowsInfo(other,DIA_Mika_WASKOSTETHILFE) && (Mika_Helps == TRUE))
		{
			return TRUE;
		};
	};
};
```
не проще заменить на проверку по Mika_Helps == TRUE?

**Comment by dosinabox** [comment]
> не проще заменить на проверку по Mika_Helps == TRUE?

- Mika_Helps становится TRUE для ополченца в DIA_Mika_WOHIN, который не воспроизводится для мага и паладина
- для мага и паладина Mika_Helps не нужен, помощь берется бесплатно и без других условий
- для всех остальных нужен диалог DIA_Mika_WASKOSTETHILFE и оплата

**Comment by dosinabox** [comment]
```cpp
if(VisibleGuild(other) == GIL_MIL)
{
	AI_Output(self,other,"DIA_Mika_WOHIN_Bauern_12_01_add");	//Не стоит бродить по этим опасным тропам совсем одному. Если тебе понадобится моя помощь, ты знаешь, где найти меня.
	Mika_Helps = TRUE;
}
```
Видимо, здесь Mika_Helps нужно заменить на Mika_FreeHelp, чтобы в дальнейшем брать помощь без диалога DIA_Mika_WASKOSTETHILFE (?). Или DIA_Mika_WASKOSTETHILFE подходит ополченцу в легких доспехах?

**Comment by Kor-Angar** [comment]
мне кажется он получился сильно перекрученный, всякими условиями и избыточными проверками. его проще заново переписать, чётко сформировав мысль:

- Паладин, Маг, Мент в тяжёлых доспехах, вариант 1
- для Мента, Послушика (?) , вариант 2
- Нейтрал, Наём, ОнД - если пробегал мимо с Ларесом, то 3б, если первая встреча вариант 3а

**Comment by dosinabox** [comment]
и в чем должна быть разница между 3б и 3а?

**Comment by Kor-Angar** [comment]
> и в чем должна быть разница между 3б и 3а?

- 3а - DIA_Mika_WOHIN
- 3б - DIA_Mika_WASGEFAEHRLICH
- 3с - DIA_Mika_WASKOSTETHILFE

или как то так. общий смысл в том что в одном случае Мика останавливает героя, а в другом нет.  т.е. если герой(нейтрал, Наём, ОнД) идёт в первый раз  один Мика  его тормозит 3а, а если он уже пробегал мимо с Ларесом, то Мика не тормозит героя, а герой может поговорить с Мика по диалогу 3б. Далее идёт развод на бабки 3с.

***
для Мента, Послушика (?) , вариант 2. Мика тоже тормозит героя, но без развода на бабки. герой может попросить помощи.
```
AI_Output(self,other,"DIA_Mika_WOHIN_Bauern_12_01_add");	//Не стоит бродить по этим опасным тропам совсем одному. Если тебе понадобится моя помощь, ты знаешь, где найти меня.
Mika_Helps = TRUE;
```

***

Паладин, Маг, Мент в тяжёлых доспехах, вариант 1 : Мика не тормозит героя. герой может попросить помощи. 
хоть вариант 1 и самый куций но он крайне маловероятный в игре.
Mika_Helps = TRUE;

**Comment by dosinabox** [comment]
> если он уже пробегал мимо с Ларесом

хз, как такое отслеживать

**Comment by dosinabox** [comment]
хотя есть идеи

**Comment by Kor-Angar** [comment]
через проверку на какой нибудь  Mika_Refuse_lares

```D
func int DIA_Mika_WOHIN_Condition()
{
	if	Mika_Refuse_lares == TRUE		// герой проходил мимо с Ларесом
	||	VisibleGuild(other) == GIL_KDF 	// герой Маг Огня
	||	VisibleGuild(other) == GIL_PAL 	// герой Пал
	||	ArmorEquipped(other,ITAR_MIL_M)	// герой в тяжелых Доспехах Мента
	{
		return false;
	};

	if	(Lares.aivar[AIV_PARTYMEMBER] == FALSE) 
	&&	(Npc_GetDistToWP(self,"NW_CITY_TO_FOREST_01") < 700)
	{
		return TRUE;
	};
};

```

у Ларса
```D
var int  Mika_Refuse_lares;

func void DIA_Lares_GoNow_GoingConditions()
{
	Mika_Refuse_lares = TRUE;
	AI_Output(self,other,"DIA_Lares_GoNow_09_01");	//Пошли... Иди за мной.
	AI_StopProcessInfos(self);
	Lares_Guide = Wld_GetDay();
	Lares_Distracted = FALSE;
	self.aivar[AIV_PARTYMEMBER] = TRUE;
	if(!Npc_KnowsInfo(other,DIA_Moe_Hallo))
	{
		Npc_SetRefuseTalk(Moe,30);
	};
};

```

**Comment by dosinabox** [comment]
Мика не увидит ГГ с Ларесом, если они пойдут ночью, когда он будет спать в казармах

**Comment by Kor-Angar** [comment]
как вариант менять Мики  расписание на ночные сиделки в казармах у Лареса в DIA_Lares_GoNow_GoingConditions, а до этого Мика пусть находится круглосуточно на дежурстве.  

кстати меня пару раз Мика спасал, убивая волка, который за мной погнался когда я шёл в город. это намного позже я стал максимально прижиматься к стене и спокойно проходить мимо волков :-) поэтому Мику загонять в казармы на ночь пока есть живность рядом преждевременно ;-)

**Comment by Kor-Angar** [comment]
правда это было днём

**Comment by Kor-Angar** [comment]
> как вариант менять Мики расписание на ночные сиделки в казармах у Лареса в DIA_Lares_GoNow_GoingConditions, а до этого Мика пусть находится круглосуточно на дежурстве.

а ещё лучше после квеста про бандитов на фермы Акилы. ибо тяжело: сначала ищешь Мики, а потом он тебя посылает у камина на три буквы. после чего надо поспать и только тогда он пойдёт с героем на ферму. ночного нападения не получается сделать.

**Comment by dosinabox** [comment]
Попробуй так:
https://dropmefiles.com/2CQ01
Лареса пока не трогаю

**Comment by dosinabox** [comment]
https://github.com/dosinabox/g2nr_unofficial_update/commit/8aa1a3e1e4c22e14c699e2d6a2c1bf6c8286397f#diff-7553bd33f0f6b9c52e2c07205c89ecc1ec9fcea39b0564ff338de62b7fbbb408

**Comment by Kor-Angar** [comment]
можно зайти к вопросу с  другой стороны:

на время походов с Ларесом ставить Мику в казармы, условно на доклад к Андре :-)

**Comment by Kor-Angar** [comment]
твой код https://www.youtube.com/watch?v=RdxwYlKlbgE&feature=youtu.be

Маг, Пал - Ок
Мент - Ок


можно дать Наёмнику и ОнД вариант "с фермы" так как они идут с фермы, а не из города :-). Сейчас такой вариант доступен только нетрайлу
```
		if(other.guild == GIL_NONE)
		{
			Info_AddChoice(DIA_Mika_WOHIN,"С одной из ферм.",DIA_Mika_WOHIN_Bauern);
		};
```

***

Послушник тоже идёт из монастыря(не из города), а вариант идёт из города
наверное послушника лучше к менту

```
	if(VisibleGuild(other) == GIL_MIL)
	{
		AI_Output(self,other,"DIA_Mika_WOHIN_Bauern_12_01_add");	//Не стоит бродить по этим опасным тропам совсем одному. Если тебе понадобится моя помощь, ты знаешь, где найти меня.
	}
```

**Comment by dosinabox** [comment]
> можно дать Наёмнику и ОнД вариант "с фермы" так как они идут с фермы, а не из города :-)

Ответом будет:
```cpp
AI_Output(self,other,"DIA_Mika_WOHIN_Bauern_12_01");	//Ты фермер, да? Хмм. Тогда тебе не стоит бродить по этим опасным тропам совсем одному. Кто знает, что там может поджидать тебя.
```
Поэтому для наемника/ОнД нужна другая реплика.

**Comment by Kor-Angar** [comment]
Тогда вариант про "иду с фермы" наверное лучше сделать при надетой броне крестьянина. 16:28, 13 января 2021 г., dosinabox <notifications@github.com>:

можно дать Наёмнику и ОнД вариант "с фермы" так как они идут с фермы, а не из города :-)

Ответом будет:
AI_Output(self,other,"DIA_Mika_WOHIN_Bauern_12_01");	//Ты фермер, да? Хмм. Тогда тебе не стоит бродить по этим опасным тропам совсем одному. Кто знает, что там может поджидать тебя.
Поэтому для наемника/ОнД нужна другая реплика.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
-- Отправлено из мобильного приложения Яндекс.Почты

**Comment by dosinabox** [comment]
И ещё раз: если Мика видел ГГ с Ларесом, то что он должен говорить при второй встрече без Лареса?

**Comment by Kor-Angar** [comment]
> И ещё раз: если Мика видел ГГ с Ларесом, то что он должен говорить при второй встрече без Лареса?

просто запретить DIA_Mika_WOHIN


а далее всё так же.

в принципе можно сделать для такого случая новую инстанцию, что бы вариант вопроса ГГ "А что такого опасного здесь?" был более локоничный 
```D
instance DIA_Mika_666(C_Info)
{
	npc = MIL_337_Mika;
	nr = 1;
	condition = DIA_Mika_666_Condition;
	information = DIA_Mika_666_Info;
//	permanent = TRUE;
	important = TRUE;
};


func int DIA_Mika_666_Condition()
{
	if Npc_IsInState(self,ZS_Talk) 
&& ****
	{
			return TRUE;
	};
};

func void DIA_Mika_666_Info()
{
		AI_Output(self,other,"DIA_Mika_WOHIN_Bauern_12_01_add");	//Не стоит бродить по этим опасным тропам совсем одному. Если тебе понадобится моя помощь, ты знаешь, где найти меня.
};
```
