### ISSUE TITLE
Беннет чинит глаз Инноса

### ISSUE THREAD

**Issue by Kor-Angar** [dosinabox/g2nr_unofficial_update#32]
Беннет после того как даёт починенный Глаз Инноса говорит что он делал его всю ночь.

посмотри плиз в скрипте делает он его ночью или дрыхнет? :-)

**Comment by dosinabox** [comment]
Не спит. Между передачей Глаза и завершением его ремонта проходят минимум сутки непрерывной работы в кузнице. Было сделано в прошлой версии.

**Comment by Kor-Angar** [comment]
Гуд 👍
