### ISSUE TITLE
Гаан расписание

### ISSUE THREAD

**Issue by Kor-Angar** [dosinabox/g2nr_unofficial_update#321]
Там Гаан говорит что он в рамках КВ наблюдает за проходом, а после диалога с ГГ уходит на охоту.

Это потому что скрипты из классики и в классике у него не было важной миссии шпионить за проходом

**Comment by dosinabox** [comment]
Как я помню, место его охоты находится не так далеко от прохода и шпионить за ним можно и оттуда.  К тому же, в расписании охоты он стоит неподалеку от фыркающего снеппера и может наблюдать за схваткой ГГ.
Нет?

**Comment by Kor-Angar** [comment]
так то да. но если к нему сразу прийти так он по дороге к месту охоты и на луркеров и падальщиков ещё нарвётся. 

а после вступление в КВ у него какое расписание включается?

**Comment by dosinabox** [comment]
> а после вступление в КВ у него какое расписание включается?

```cpp
if(Gaan.aivar[AIV_TalkedToPlayer] == FALSE)
{
	B_StartOtherRoutine(Gaan,"PreStart");
}
else
{
	B_StartOtherRoutine(Gaan,"Start");
};
```
Если поговорил с ГГ - охота, если нет - стоять у прохода.
