### ISSUE TITLE
Кассия "конец"

### ISSUE THREAD

**Issue by Kor-Angar** [dosinabox/g2nr_unofficial_update#322]
У Касси доступен выход из диалога до того как герой согласится присоединится к Гильдии воров.

Может быть имеет смысл поставить на конец доп условия?

```
func int DIA_Cassia_EXIT_Condition()
{
	if 	Join_Thiefs == TRUE
	{
		return TRUE;
	};
}; 
```

**Comment by dosinabox** [comment]
https://github.com/dosinabox/g2nr_unofficial_update/issues/274
