### ISSUE TITLE
что то там про сердце или любовь

### ISSUE THREAD

**Issue by Kor-Angar** [dosinabox/g2nr_unofficial_update#323]
у меня в этот раз появился дополнительный топик относительно Люсии что то там про любовь

![image](https://user-images.githubusercontent.com/49514764/104269584-b3ef2d00-54a7-11eb-8ba2-07382afffca7.png)

а в этот топике инфы из прощального письма не добавилось

![image](https://user-images.githubusercontent.com/49514764/104269674-e7ca5280-54a7-11eb-80ba-a248b1975e66.png)

**Comment by dosinabox** [comment]
исправлено
