### ISSUE TITLE
VisibleGuild

### ISSUE THREAD

**Issue by Kor-Angar** [dosinabox/g2nr_unofficial_update#324]
я видел пару месяцев назад что ты начало менять проверку с гильдии на VisibleGuild(other) == GIL_KDF

я как понял это проверка на броню? подскажи плиз в каком файле это функция что бы я в свою версию её мог добавить.

**Comment by dosinabox** [comment]
Story\B_Story\B_ArmorChecks.d

**Comment by Kor-Angar** [comment]
https://github.com/dosinabox/g2nr_unofficial_update/blob/work/PrjGOTHIC/Story/B_Story/B_ArmorChecks.d

**Comment by Kor-Angar** [comment]
а если тут делать проверку так?

```D
	if MILArmor_Equipped == TRUE
	//if(ArmorEquipped(npc,ITAR_MIL_L) || ArmorEquipped(npc,ITAR_MIL_M))
	{
		return GIL_MIL;
	};
```

**Comment by dosinabox** [comment]
Можно, если функция проверяет только ГГ. А она проверяет любого переданного ей npc.
