### ISSUE TITLE
мент пришёл на ферму Онара первый раз

### ISSUE THREAD

**Issue by Kor-Angar** [dosinabox/g2nr_unofficial_update#326]
я в своём прохождение за мента специально пришёл на ферму Онара уже ментом. сюжет же это допускает? :-)

У меня получался какой то первый бредо разговор с Ли. это лучше перепроверить, так как мне могло и показаться.

Квест про избить Булко я взял, но у Сильвио  стоит  проверка на квест Ярвиса.  
```
	var int victories;
	victories = 0;
	if (Rod.aivar[AIV_DefeatedByPlayer] == TRUE)		{	victories = victories + 1;	};
	if (Sentenza.aivar[AIV_DefeatedByPlayer] == TRUE)	{	victories = victories + 1;	};
	if (Fester.aivar[AIV_DefeatedByPlayer] == TRUE)		{	victories = victories + 1;	};
	if (Raoul.aivar[AIV_DefeatedByPlayer] == TRUE)		{	victories = victories + 1;	};
	if (Bullco.aivar[AIV_DefeatedByPlayer] == TRUE)		{	victories = victories + 1;	};
	if (MIS_Jarvis_SldKO != FALSE)
	&& (victories >= 2) 
	{
		return TRUE;
	};
```

таким образом если герой пришёл нейтралом, взял квесты, а потом пришёл Ментом/Магом проверку MIS_Jarvis_SldKO 
 пройдёт, а если просто первый раз пришёл Ментом/Магом то не пройдёт.

на эту фразу можно добавить проверку на Гильдию (нейтрал, наём, онд)

```
	if(Lee.aivar[AIV_TalkedToPlayer] == TRUE)
	{
		AI_Output(self,other,"DIA_Sylvio_MenDefeated_09_01");	//Насколько я знаю, ты один из протеже Ли.
	};

```

так же у Сильвио счётчик есть на Sylvio_angequatscht
я как понял там при достижение 3 или 4 что то должно было произойти :-)

**Comment by dosinabox** [comment]
> так же у Сильвио счётчик есть на Sylvio_angequatscht
> я как понял там при достижение 3 или 4 что то должно было произойти :-)

Увеличивается с каждым диалогом с Сильвио.
При достижении 1 становится доступным этот диалог с Сильвио:
```cpp
func void DIA_Sylvio_Asshole_Info()
{
	AI_Output(other,self,"DIA_Sylvio_Asshole_15_00");	//Эй, дерьмо...
	AI_Output(self,other,"DIA_Sylvio_Asshole_09_01");	//Ты что, действительно думаешь, что я вызову тебя на дуэль?
	AI_Output(self,other,"DIA_Sylvio_Asshole_09_02");	//Проваливай туда, откуда ты выполз.
	Sylvio_angequatscht += 1;
	AI_StopProcessInfos(self);
};
```
При достижении 2 становится доступным этот диалог с Буллко:
```cpp
func void DIA_Bullco_Quatscher_Info()
{
	AI_Output(self,other,"DIA_Bullco_Quatscher_06_00");	//Сильвио не любит болтунов. Ты мог бы понять это уже.
	AI_StopProcessInfos(self);
	Npc_ExchangeRoutine(self,"PEE");
	B_Attack(self,other,AR_NONE,1);
};
```

**Comment by dosinabox** [comment]
> если просто первый раз пришёл Ментом/Магом то не пройдёт.

И чем это чревато?

**Comment by Kor-Angar** [comment]
тем что с ГГ не поговорит Сильвио --> булко не даст сутки --> не будет дуэли с Булко --> не сдастся квест Пепе.

или ГГ-Мент может дать люлей Булко без дуэли? то есть если ГГ-мент нападёт на Булко, то все НПС побегут же на помощь Булко?

**Comment by dosinabox** [comment]
> то есть если ГГ-мент нападёт на Булко, то все НПС побегут же на помощь Булко?

Это надо проверить. Но если его побить, то диалога про сутки не будет:
```cpp
func int DIA_Bullco_PleaseLeave_Condition()
{
	if(self.aivar[AIV_DefeatedByPlayer] == FALSE)
	{
		if((self.aivar[AIV_LastFightAgainstPlayer] != FIGHT_NONE) || (Sylvio_MenDefeated == TRUE))
		{
			return TRUE;
		};
	};
};
```

**Comment by dosinabox** [comment]
Во-первых, подсчет избитых лучше вынести в отдельную функцию:
```cpp
func int C_Sylvio_MenDefeated()
{
	var int victories;
	victories = 0;
	if(!Npc_IsDead(Rod))
	{
		if(Rod.aivar[AIV_DefeatedByPlayer] == TRUE)
		{
			victories += 1;
		};
	};
	if(!Npc_IsDead(Sentenza))
	{
		if(Sentenza.aivar[AIV_DefeatedByPlayer] == TRUE)
		{
			victories += 1;
		};
	};
	if(!Npc_IsDead(Fester))
	{
		if(Fester.aivar[AIV_DefeatedByPlayer] == TRUE)
		{
			victories += 1;
		};
	};
	if(!Npc_IsDead(Raoul))
	{
		if(Raoul.aivar[AIV_DefeatedByPlayer] == TRUE)
		{
			victories += 1;
		};
	};
	if(!Npc_IsDead(Bullco))
	{
		if(Bullco.aivar[AIV_DefeatedByPlayer] == TRUE)
		{
			victories += 1;
		};
	};
	return victories;
};
```
```cpp
func int DIA_Sylvio_MenDefeated_Condition()
{
	if((MIS_Jarvis_SldKO != FALSE) && (C_Sylvio_MenDefeated() >= 2))
	{
		return TRUE;
	};
};
```
Во-вторых, из условия DIA_Sylvio_MenDefeated_Condition можно просто убрать проверку MIS_Jarvis_SldKO - тогда Сильвио будет комментировать драки с его людьми независимо от гильдии ГГ и квеста Джарвиса.

**Comment by Kor-Angar** [comment]
Про то и речь :-)

**Comment by dosinabox** [comment]
> не будет дуэли с Булко --> не сдастся квест Пепе

По коду не вижу связи. И вроде за наемников никто не заступается, квест Джарвиса для этого не нужен.

**Comment by Kor-Angar** [comment]
> По коду не вижу связи. И вроде за наемников никто не заступается, квест Джарвиса для этого не нужен.

Не увидишь такой связи в коде :-) в коде её нет. За наёмников заступаются наёмники. 

***

есть квест набить морду Булко. Даёт его крестьянин. Булко сложный боец. Грубо говоря не лох. С ним придётся повозится.

если ГГ-нейтрал пришёл и взял квест Ярвиса, то ГГ-Мент без проблем может попробовать набить морду Булко один на один в рамках дуэли которую инициирует Булко (после разговора  Сильвио с ГГ).
Если ГГ-мент просто пришёл на ферму Онара и взял квест набить морду Булко, то это будет сделать уже намного сложнее, так как в таком случае ГГ придётся напасть первым и в таком случае на ГГ будут агрится и другие наёмники, в т.ч. это может быть и бессмертный Sylvio или бессмертный Беннет. Конечно же Булком можно выманить через пляски с бубнами: провоцировать Булко, через доставания оружия, выводить за амбар и там уже с ним один на один.

с другой стороны решением этой ситуации может быть

> из условия DIA_Sylvio_MenDefeated_Condition можно просто убрать проверку MIS_Jarvis_SldKO - тогда Сильвио будет комментировать драки с его людьми независимо от гильдии ГГ и квеста Джарвиса.

в таком случае ГГ-мент будет иметь возможность (а для этого придётся еще побить других именных наёмников через их маленькие квесты) выйти на диалог с Сильвио, что приведёт дуэли с Булко.

**Comment by dosinabox** [comment]
Из условия DIA_Sylvio_MenDefeated_Condition убрана проверка MIS_Jarvis_SldKO.

**Comment by dosinabox** [comment]
> У меня получался какой то первый бредо разговор с Ли. это лучше перепроверить, так как мне могло и показаться.

В принципе, да:
```cpp
AI_Output(self,other,"DIA_Lee_PETZMASTER_04_00");	//Какого дьявола тебя позволили пустить сюда? (удивленно) Это ТЫ новичок, от которого одни проблемы?
```
Надо обрезать вторую часть.

**Comment by dosinabox** [comment]
```cpp
func void DIA_Lee_PETZMASTER_Info()
{
	Lee_Schulden = 0;
	if(self.aivar[AIV_TalkedToPlayer] == FALSE)
	{
		if(other.guild == GIL_NONE)
		{
			AI_Output(self,other,"DIA_Lee_PETZMASTER_04_00");	//Какого дьявола тебя позволили пустить сюда? (удивленно) Это ТЫ новичок, от которого одни проблемы?
		}
		else
		{
			AI_Output(self,other,"DIA_Lee_Hallo_04_00_add");	//Какого дьявола тебя позволили пустить сюда? (удивленно) Что ты делаешь здесь?
		};
		AI_Output(self,other,"DIA_Lee_PETZMASTER_04_01");	//Я слышал от Горна, что ты все еще жив. Но что ты придешь сюда... А, ладно...
	};
```

**Comment by Kor-Angar** [comment]
там сложнее так как оно накладывается еще на какие то фразы про мента

**Comment by Kor-Angar** [comment]
то есть надо прям в игре проверить. первый разговор с ЛИ герой мент / послушник / маг / паладин

**Comment by Kor-Angar** [comment]
как то увязать DIA_Lee_Hallo_Info и DIA_Lee_KeinSld в одно

**Comment by dosinabox** [comment]
> как то увязать DIA_Lee_Hallo_Info и DIA_Lee_KeinSld в одно

Ага, теперь вижу. Но друг с другом они как-то плохо сочетаются. Лучше вообще запретить Ли комментировать новую гильдию ГГ, если он не видел ГГ нейтралом.

**Comment by Kor-Angar** [comment]
возможно :-)

**Comment by dosinabox** [comment]
так и сделаю

**Comment by Kor-Angar** [comment]
там надо еще  проверить фразы если герой приходит **первый раз**  к Ли в третей главе.

**Comment by dosinabox** [comment]
> там надо еще проверить фразы если герой приходит **первый раз** к Ли в третей главе.

Вот такой диалог будет после завершения (при нажатии на "КОНЕЦ"):

```cpp
func void B_Lee_Teleport()
{
	if((Lee_Teleport == FALSE) && (Kapitel >= 3))
	{
		AI_Output(self,other,"DIA_Lee_Add_04_05");	//Ах. Хорошо, что ты пришел.
		AI_Output(other,self,"DIA_Lee_Add_15_06");	//Что случилось?
		AI_Output(self,other,"DIA_Lee_Add_04_07");	//Я нашел это в старой часовне.
		B_GiveInvItems(self,other,ItRu_TeleportFarm,1);
		AI_Output(self,other,"DIA_Lee_Add_04_08");	//Это магическая руна. Я думаю, она может в любое время перенести тебя сюда, на ферму.
		AI_Output(self,other,"DIA_Lee_Add_04_09");	//Я подумал, что ты сможешь пользоваться ей.
		Lee_Teleport = TRUE;
	};
};
```
Вроде ничего страшного)

**Comment by Kor-Angar** [comment]
> Вот такой диалог будет после завершения (при нажатии на "КОНЕЦ"):

а подрезать фразу DIA_Lee_DoAboutBennet_04_07 нельзя? :-)

```D
		AI_Output(self,other,"DIA_Lee_****");	//Ох, да. Чуть не забыл... 
		AI_Output(self,other,"DIA_Lee_Add_04_07");	//Я нашел это в старой часовне.
		B_GiveInvItems(self,other,ItRu_TeleportFarm,1);
		AI_Output(self,other,"DIA_Lee_Add_04_08");	//Это магическая руна. Я думаю, она может в любое время перенести тебя сюда, на ферму.
		AI_Output(self,other,"DIA_Lee_Add_04_09");	//Я подумал, что ты сможешь пользоваться ей.
```

хотя по русски может вот так даже лучше будет

```D
		AI_Output(self,other,"DIA_Lee_****");	//Ох, да. Чуть не забыл... 
		AI_Output(self,other,"DIA_Lee_Add_04_08");	//Это магическая руна. Я думаю, она может в любое время перенести тебя сюда, на ферму.
		AI_Output(self,other,"DIA_Lee_Add_04_07");	//Я нашел это в старой часовне.
		B_GiveInvItems(self,other,ItRu_TeleportFarm,1);
		AI_Output(self,other,"DIA_Lee_Add_04_09");	//Я подумал, что ты сможешь пользоваться ей.
```

**Comment by dosinabox** [comment]
И пускать подрезанную по той же логике, проверяя знакомство до вступления в гильдию?

**Comment by Kor-Angar** [comment]
ты же про "конец" вроде для третьей главы ?

**Comment by Kor-Angar** [comment]
если речь про B_Lee_Teleport

то можно просто оставить её вызов только в DIA_Lee_EXIT_Info	

поменяв 
```D
func void B_Lee_Teleport()
{
	if((Lee_Teleport == FALSE) && (Kapitel >= 3))
	{
		AI_Output(self,other,"DIA_Lee_****");	//Ох, да. Чуть не забыл... 
		AI_Output(self,other,"DIA_Lee_Add_04_08");	//Это магическая руна. Я думаю, она может в любое время перенести тебя сюда, на ферму.
		AI_Output(self,other,"DIA_Lee_Add_04_07");	//Я нашел это в старой часовне.
		B_GiveInvItems(self,other,ItRu_TeleportFarm,1);
		AI_Output(self,other,"DIA_Lee_Add_04_09");	//Я подумал, что ты сможешь пользоваться ей.
		Lee_Teleport = TRUE;
	};
};
```

тогда проблема будет решена в целом. по смыслу для "конец" она становится более лаконичной

**Comment by Kor-Angar** [comment]
блин тогда с бастером будет как то неудачно сочитаться

**Comment by Kor-Angar** [comment]
диалог про Бастера можно вызывать при следующем "прощание" с Ли, добавив в него проверку на  	(Lee_Teleport == TRUE) 

```D
func void B_Lee_Sends_To_Buster()
{
	if	(Kapitel >= 3) && (Kapitel < 5) 
	&&	(Lee_Teleport == TRUE) 
	&&	(Lee_Sends_To_Buster == FALSE) 
	&&	!Npc_IsDead(Buster) 
	&&	!Npc_KnowsInfo(other,DIA_Buster_SHADOWBEASTS) 
	&& ((hero.guild == GIL_SLD) || (hero.guild == GIL_DJG))
	{
		AI_Output(self,other,"DIA_Lee_DoAboutBennet_04_07");	//Ох, да. Чуть не забыл... Бастер хочет поболтать с тобой. Он не говорит мне, о чем. Может, стоит найти его?
		Lee_Sends_To_Buster = TRUE;
	};
};
```

**Comment by dosinabox** [comment]
А так?
```cpp
func void B_Lee_Teleport()
{
	if((Lee_Teleport == FALSE) && (Kapitel >= 3))
	{
		if(Lee_FirstMetAsGuildless == TRUE)
		{
			AI_Output(self,other,"DIA_Lee_Add_04_05");	//Ах. Хорошо, что ты пришел.
			AI_Output(other,self,"DIA_Lee_Add_15_06");	//Что случилось?
		};
		AI_Output(self,other,"DIA_Lee_Add_04_07");	//Я нашел это в старой часовне.
		B_GiveInvItems(self,other,ItRu_TeleportFarm,1);
		AI_Output(self,other,"DIA_Lee_Add_04_08");	//Это магическая руна. Я думаю, она может в любое время перенести тебя сюда, на ферму.
		AI_Output(self,other,"DIA_Lee_Add_04_09");	//Я подумал, что ты сможешь пользоваться ей.
		Lee_Teleport = TRUE;
	};
};
```

**Comment by Kor-Angar** [comment]
можно и так. мне лично не нравится что B_Lee_Teleport вызывать в куче диалогов. 

я у себя успешно обкатал фичу с  Npc_IsInState(self,ZS_Talk) https://github.com/dosinabox/g2nr_unofficial_update/discussions/354 мне она прям понравилась. 

то есть мне кажется должны быть некие "вехи" и через них как раз происходят обязательные сюжетные диалоги с ключевыми НПС и в рамках них как раз и можно отдавать руны. вот например у Ли обязательный диалог должен быть DIA_Lee_Report, так как это стержень сюжета :-)

**Comment by Kor-Angar** [comment]
> 			AI_Output(self,other,"DIA_Lee_Add_04_05");	//Ах. Хорошо, что ты пришел.

Будет очень странно смотреться если данный диалог сработает в 
func void DIA_Lee_EXIT_Info()
{
	B_Lee_Teleport();
	B_Lee_Sends_To_Buster();
	AI_StopProcessInfos(self);
};

**Comment by Kor-Angar** [comment]
что то в коде не могу найти Lee_FirstMetAsGuildless

**Comment by Kor-Angar** [comment]
а почему руну телепорта просто не вручать в начале диалога? 

```D
instance DIA_Lee_Teleport(C_Info)
{
	npc = SLD_800_Lee;
	nr = 1;
	condition = DIA_Lee_Teleport_Condition;
	information = DIA_Lee_Teleport_Info;
	permanent = false;
	important = TRUE;
};


func int DIA_Lee_Teleport_Condition()
{
	if	(Npc_IsInState(self,ZS_Talk) 
	&&	Kapitel >= 3
	{
		return TRUE;
	};
};

func void DIA_Lee_Teleport_Info()
{
		AI_Output(self,other,"DIA_Lee_Add_04_05");	//Ах. Хорошо, что ты пришел.
		AI_Output(other,self,"DIA_Lee_Add_15_06");	//Что случилось?
		AI_Output(self,other,"DIA_Lee_Add_04_07");	//Я нашел это в старой часовне.
		B_GiveInvItems(self,other,ItRu_TeleportFarm,1);
		AI_Output(self,other,"DIA_Lee_Add_04_08");	//Это магическая руна. Я думаю, она может в любое время перенести тебя сюда, на ферму.
		AI_Output(self,other,"DIA_Lee_Add_04_09");	//Я подумал, что ты сможешь пользоваться ей.
};
```

**Comment by Kor-Angar** [comment]
возможно оно будет даже сочетаться со штрафом. но наверное не будет сочетаться если герой пришёл первый раз :-))

**Comment by Kor-Angar** [comment]
пока самый некосячный вариант это оставить выдачу руну только через "конец" в виде

```D
func void B_Lee_Teleport()
{
	if((Lee_Teleport == FALSE) && (Kapitel >= 3))
	{
		AI_Output(self,other,"DIA_Lee_****");	//Ох, да. Чуть не забыл... 
		AI_Output(self,other,"DIA_Lee_Add_04_08");	//Это магическая руна. Я думаю, она может в любое время перенести тебя сюда, на ферму.
		AI_Output(self,other,"DIA_Lee_Add_04_07");	//Я нашел это в старой часовне.
		B_GiveInvItems(self,other,ItRu_TeleportFarm,1);
		AI_Output(self,other,"DIA_Lee_Add_04_09");	//Я подумал, что ты сможешь пользоваться ей.
		Lee_Teleport = TRUE;
	};
};
```

история "Ах. Хорошо, что ты пришел." при вызове  B_Lee_Teleport  в большенстве диалогов сейчас смотрется по коду  шизойдно. в игре у меня тоже бывало шизойдно, но судя по коду прям шиза. причем такая качественная в стиле Готик Рэп.

	AI_Output(other,self,"DIA_Lee_ArmorH_15_00");	//У тебя есть доспехи получше для меня?
	AI_Output(self,other,"DIA_Lee_ArmorH_04_01");	//Конечно.
		AI_Output(self,other,"DIA_Lee_Add_04_05");	//Ах. Хорошо, что ты пришел.


	AI_Output(other,self,"DIA_Lee_Richter_wieviel_15_00");	//Нет проблем. Сколько?
	AI_Output(self,other,"DIA_Lee_Richter_wieviel_04_01");	//Твоя награда зависит от того, что ты сообщишь мне. Так что постарайся.
		AI_Output(self,other,"DIA_Lee_Add_04_05");	//Ах. Хорошо, что ты пришел.

	AI_Output(self,other,"DIA_Lee_TalkAboutBennet_04_02");	//Как будто мне не хватает проблем с моими людьми - теперь я должен заботиться еще и о паладинах.
		AI_Output(self,other,"DIA_Lee_Add_04_05");	//Ах. Хорошо, что ты пришел.

		AI_Output(self,other,"DIA_Lee_AnyNews_04_02");	//Отличная работа.
		AI_Output(self,other,"DIA_Lee_Add_04_05");	//Ах. Хорошо, что ты пришел.

	AI_Output(self,other,"DIA_Lee_SYLVIO_04_05");	//(облегченно) Ах. Откровенно говоря, я даже рад, что Сильвио наконец ушел с фермы.
		AI_Output(self,other,"DIA_Lee_Add_04_05");	//Ах. Хорошо, что ты пришел.

	AI_Output(self,other,"DIA_Lee_KAP4_Perm_04_04");	//Но это мои проблемы. Я справлюсь.
		AI_Output(self,other,"DIA_Lee_Add_04_05");	//Ах. Хорошо, что ты пришел.

**Comment by dosinabox** [comment]
> пока самый некосячный вариант это оставить выдачу руну только через "конец" в виде

Да, но тогда нужно будет куда-то пристроить DIA_Lee_Add_04_05 и подумать как совместить диалог о руне с диалогом о Бастере.

**Comment by Kor-Angar** [comment]
диалог про руну он обязательный и доступен всем фракциям без каких либо условий. поэтому от него надо плесать.

---

диалог про Бастера есть ряд ограничений и он доступен только наёму / онд.  Я бы диалог про Бастера тупо запихал в DIA_Lee_SYLVIO, оно получилось бы что называется и дёшево и сердито.

**Comment by Kor-Angar** [comment]
> Я бы диалог про Бастера тупо запихал в DIA_Lee_SYLVIO, оно получилось бы что называется и дёшево и сердито.

 монолог выглядит как родной

```D
AI_Output(other,self,"DIA_Lee_SYLVIO_15_00");	//Что произошло за последнее время?
AI_Output(self,other,"DIA_Lee_SYLVIO_04_01");	//Сильвио, ублюдок, прослышал о драконах в Долине Рудников и свел с ума всех здесь на ферме баснями о них.
AI_Output(self,other,"DIA_Lee_SYLVIO_04_02");	//Он пытался уговорить парней пойти с ним в Долину Рудников. Он обещал им славу, почет, золото и еще кучу всяческих благ.
AI_Output(self,other,"DIA_Lee_SYLVIO_04_03");	//Большинство не особенно воодушевилось идеей быть убитым ради Сильвио, но все же нашлось несколько идиотов, которые клюнули на его наживку.
AI_Output(self,other,"DIA_Lee_SYLVIO_04_04");	//Все закончилось тем, что они вооружились у Беннета, а затем свалили.
AI_Output(self,other,"DIA_Lee_SYLVIO_04_05");	//(облегченно) Ах. Откровенно говоря, я даже рад, что Сильвио наконец ушел с фермы.
AI_Output(self,other,"DIA_Lee_DoAboutBennet_04_07");	//Ох, да. Чуть не забыл... Бастер хочет поболтать с тобой. Он не говорит мне, о чем. Может, стоит найти его?
```


***



```D
func void DIA_Lee_SYLVIO_Info()
{
	AI_Output(other,self,"DIA_Lee_SYLVIO_15_00");	//Что произошло за последнее время?
	AI_Output(self,other,"DIA_Lee_SYLVIO_04_01");	//Сильвио, ублюдок, прослышал о драконах в Долине Рудников и свел с ума всех здесь на ферме баснями о них.
	AI_Output(self,other,"DIA_Lee_SYLVIO_04_02");	//Он пытался уговорить парней пойти с ним в Долину Рудников. Он обещал им славу, почет, золото и еще кучу всяческих благ.
	AI_Output(self,other,"DIA_Lee_SYLVIO_04_03");	//Большинство не особенно воодушевилось идеей быть убитым ради Сильвио, но все же нашлось несколько идиотов, которые клюнули на его наживку.
	AI_Output(self,other,"DIA_Lee_SYLVIO_04_04");	//Все закончилось тем, что они вооружились у Беннета, а затем свалили.
	AI_Output(self,other,"DIA_Lee_SYLVIO_04_05");	//(облегченно) Ах. Откровенно говоря, я даже рад, что Сильвио наконец ушел с фермы.
	B_Lee_Sends_To_Buster();
};
```

**Comment by dosinabox** [comment]
> монолог выглядит как родной

Да, но Сильвио уходит с фермы между 3 и 4 главой, а квест Бастера становится доступным с самого начала 3. Надо эту фразу ещё куда-то добавить.

**Comment by Kor-Angar** [comment]
но ведь Ли не даёт квест. Бастер даёт квест, а если герой по каким то причинам его не взял квест у Бастера, то Ли ему как бы напоминает. Так что если Ли напомнить герою в конце третей главы страшного ничего не будет.
кстати а почему не делается соответствующая запись в дневник? ;-)

**Comment by dosinabox** [comment]
Квест Ли не дает, но авторская задумка по "рекламе" Бастера будет нарушена. Не узнает игрок про квест и всю третью главу будет убивать мракорисов и продавать рога)

**Comment by Kor-Angar** [comment]
надо определится с диалогом о выдаче руны: в самое начало его ставить или в самый конец. и тогда уже можно понять что делать с диалогом про Бастера.  Стремление навязчиво всовывать пользователю контент всегда будет приводить к сбоям. Диалог про Бастера прекрасно смотрелся в "родном" диалоге про беннета, там где он и был изначально. если игрок  "пропустил" это диалог, то есть намеренно его проигнорировал, можно его ещё разок прокрутить например в диалоге про DIA_Lee_SYLVIO_Info.
тут вот что важно на мой взгляд понимать: диалог этот фракционный, для наёмника. Лидер наёмников - Ли, герой должен общаться с Ли. если герой-наёмник игнорит Ли, то он не получает от него квестов / инфы.  Это понятная логика отлично работала как в Готике так и в Морровинд :-)

но первично конечно диалог про руну. если из-за Бастера начинает страдать руна это не хорошо.

> AI_Output(other,self,"DIA_Lee_ArmorH_15_00");	//У тебя есть доспехи получше для меня?
> AI_Output(self,other,"DIA_Lee_ArmorH_04_01");	//Конечно.
> AI_Output(self,other,"DIA_Lee_Add_04_05");	//Ах. Хорошо, что ты пришел.

**Comment by dosinabox** [comment]
Прошу оценить итог: https://github.com/dosinabox/g2nr_unofficial_update/blob/work/PrjGOTHIC/Story/Dialoge/DIA_SLD_800_Lee.d
https://dropmefiles.com/I2tTs
Требуется начало новой игры, потому что был возвращен диалог DIA_Lee_Teleport.

**Comment by dosinabox** [comment]
[DIA_SLD_800_Lee.d.txt](https://github.com/dosinabox/g2nr_unofficial_update/files/7094468/DIA_SLD_800_Lee.d.txt)

**Comment by Kor-Angar** [comment]
мне твоё решение вынести руны в начало для Наёмника/ОнД и в конец очень понравилось.

- Наёмник / ОнД уже многократно общался с Ли. Им диалог проигрывается вначале через important = TRUE. Если по каким то причинам этот диалог не воспроизвёлся, его ГГ-наёмник так же может прослушать через "конец".
- **Всё фракции**: диалог вынесен в конец и с фразой "Чуть не забыл...".

***

информация про Бастера, доступная Наёмнику/ОнД, вернулась в диалог про Беннета, так же на тот случай если Наёмник не общался с Ли до освобождения Беннета, продублирована в диалоге про Сильвио.

**Comment by Kor-Angar** [comment]
> Требуется начало новой игры, потому что был возвращен диалог DIA_Lee_Teleport.

[g2a_nr_scriptpatch_v27_test_02.09.2021.zip](https://github.com/dosinabox/g2nr_unofficial_update/files/7117036/g2a_nr_scriptpatch_v27_test_02.09.2021.zip)
