### ISSUE TITLE
B_MakeRangerReadyToLeaveMeeting

### ISSUE THREAD

**Issue by Kor-Angar** [dosinabox/g2nr_unofficial_update#327]
подскажи пожалуйста, а почему в  func void **B_MakeRangerReadyToLeaveMeeting**(var C_Npc Ranger)
не используется _AI_EquipBestArmor(Ranger);_  ?

**Comment by dosinabox** [comment]
Потому что в этой func каждый Ranger переодевается в его родную Armor, но не для всех его родная Armor является Best. Например, Мартин не сможет переодеться в доспехи ополчения, а Кавалорн в рабочую одежду. Поэтому каждому Ranger принудительно прописывается его индивидуальный Armor.

**Comment by Kor-Angar** [comment]
ясно.  прошлый раз у этих доспехов была защита по 0.  пропустил когда у них защита увеличилась :-)

**Comment by dosinabox** [comment]
С защитой 0 половину рейнджеров у таверны могли убить падальщики)

**Comment by Kor-Angar** [comment]
Ну это наврядли. Ищущие вполне могли :-) но они и в той броне легко могут ;-)

а в целом конечно было бы понятнее в B_RangerMeeting.d  поменять ITAR_Fake_RANGER на ITAR_RANGER_Addon. что бы  название  отображало суть и не вводило в заблуждение ;-)

а я то всё думал почему  Ларес  в прошлых годах стал неожиданно ходить раздетым :-)
