### ISSUE TITLE
Пираты идут за ГГ на пляж с огненными варанми

### ISSUE THREAD

**Issue by Kor-Angar** [dosinabox/g2nr_unofficial_update#328]
в рамках квеста про каньон  можно пойти с напарниками на пляж с огненными варанами
https://youtu.be/xNrw7mfbhgQ?t=4464

**Comment by dosinabox** [comment]
И на пляж с мракорисом тоже?

**Comment by Kor-Angar** [comment]
По моему квет про каньен нельзя взять пока не сдан квест про пляж. 14:18, 25 февраля 2021 г., dosinabox <notifications@github.com>:
И на пляж с мракорисом тоже?

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
-- Отправлено из мобильного приложения Яндекс.Почты

**Comment by Kor-Angar** [comment]
> По моему квест про каньон нельзя взять пока не сдан квест про пляж. 

хотя нет. ограничений нет

```D
instance DIA_Addon_Greg_JoinPirates(C_Info)
{
	npc = PIR_1320_Addon_Greg;
	nr = 5;
	condition = DIA_Addon_Greg_JoinPirates_Condition;
	information = DIA_Addon_Greg_JoinPirates_Info;
	permanent = FALSE;
	description = "Что нужно сделать?";
};


func int DIA_Addon_Greg_JoinPirates_Condition()
{
	if(Npc_KnowsInfo(other,DIA_Addon_Greg_ImNew))
	{
		return TRUE;
	};
};
```

**Comment by dosinabox** [comment]
Следует ли запрещать пиратам ходить с ГГ и на северный пляж с луркерами?

**Comment by Kor-Angar** [comment]
мне кажется нет. а квест про этот пляж не отменяется случайно при появление Грега? 25.02.2021, 20:37, "dosinabox" <notifications@github.com>: Следует ли запрещать пиратам ходить с ГГ и на северный пляж с луркерами?—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by dosinabox** [comment]
> мне кажется нет

А почему?

> а квест про этот пляж не отменяется случайно при появление Грега?

Не отменяется.

**Comment by dosinabox** [comment]
ГГ зовет всех именно в каньон, а не на пляж или куда-то ещё:
```cpp
AI_Output(other,self,"DIA_Addon_Brandon_FollowMe_15_02");	//Так решил Грег. Мы должны истребить бритвозубов в каньоне.

AI_Output(other,self,"DIA_Addon_Skip_Anheuern_15_00");	//Ты должен мне помочь.
AI_Output(self,other,"DIA_Addon_Skip_Anheuern_08_01");	//Каким образом?
AI_Output(other,self,"DIA_Addon_Skip_Anheuern_15_01");	//Нас ждет каньон.

AI_Output(self,other,"DIA_Addon_Skip_Anheuern_08_04");	//В каньоне чертовски опасно!

AI_Output(other,self,"DIA_Addon_Bones_Anheuern_15_01");	//Нас ждет каньон.

AI_Output(other,self,"DIA_Addon_BenchPirate_ComeOn_15_01");	//Нас ждет каньон.

AI_Output(other,self,"DIA_Addon_Brandon_FollowMe_15_02");	//Так решил Грег. Мы должны истребить бритвозубов в каньоне.
AI_Output(self,other,"DIA_Addon_Brandon_Anheuern_04_03");	//(усмехается) Наконец-то здесь хоть что-нибудь происходит!
AI_Output(self,other,"DIA_Addon_Brandon_Anheuern_04_04");	//Что ж, пойдем. Чем скорее мы разделаемся с ними, тем скорее можно будет вернуться.

AI_Output(other,self,"DIA_Addon_Matt_FollowMe_ClearCanyon_15_00");	//Мы должны очистить каньон от зверей.
AI_Output(self,other,"DIA_Addon_Matt_FollowMe_ClearCanyon_10_01");	//Ты рехнулся. Там их полно! А с этими бритвозубами шутки плохи.

```

Брендон говорит, чтобы ГГ не жадничал)
```cpp
AI_Output(self,other,"DIA_Addon_Brandon_TooFar_04_00");	//Достаточно! Ты что, хочешь истребить всех зверей на острове?
```

**Comment by dosinabox** [comment]
Плохо дело) Точки на пляже с огненными варанами никак не соединены с точками в лагере, зато почему-то соединены с точкой у башни с бандитами - прямо наверх через скалу. Пираты доходят до пляжа, объявляют что дальше не пойдут и... идут прямо через весь пляж через всех монстров, потому что маршрут прокладывается по именно такому пути.

С пляжем с луркерами просто - там прямая дорога без воды и скал. Там поход ограничивается без проблем.

**Comment by Kor-Angar** [comment]
можно попробовать делать так: после диалога, пирата отправлять ко входу в каньон. у пирата делать проверку на чекпойнт, если пират на чекпойнте то менять расписание на следовать за ГГ.25.02.2021, 21:38, "dosinabox" <notifications@github.com>:
Плохо дело) Точки на пляже с огненными варанами никак не соединены с точками в лагере, зато почему-то соединены с точкой у башни с бандитами - прямо наверх через скалу. Пираты доходят до пляжа, объявляют что дальше не пойдут и... идут прямо через весь пляж через всех монстров, потому что маршрут прокладывается по именно такому пути.
С пляжем с луркерами просто - там прямая дорога без воды и скал. Там поход ограничивается без проблем.

**Comment by dosinabox** [comment]
> Точки на пляже с огненными варанами никак не соединены с точками в лагере, зато почему-то соединены с точкой у башни с бандитами - прямо наверх через скалу.

Было исправлено в версии 26, поэтому теперь можно будет попробовать что-то сделать.

**Comment by dosinabox** [comment]
Ну что, запрещаем водить пиратов на оба пляжа?

**Comment by Kor-Angar** [comment]
там надо посмотреть на диалог после убийства "бритвы". По моему скип говорить что теперь когда задание выполнено они могут погулять или что то в этом духе.

**Comment by dosinabox** [comment]
```cpp
func void DIA_Addon_Skip_AllRazorsDead_Info()
{
	AI_Output(self,other,"DIA_Addon_Skip_Add_08_03");	//Похоже, мы перебили всех бритвозубов.
	AI_Output(self,other,"DIA_Addon_Skip_Add_08_04");	//Если хочешь, мы можем побродить здесь еще.
	AI_Output(self,other,"DIA_Addon_Skip_Add_08_05");	//Только не выходи из каньона.
	AI_StopProcessInfos(self);
};
```

**Comment by Kor-Angar** [comment]
тогда смело запрещай все  пляжи.

***

я бы сделал еще жоще: 
промежуточное расписание для тех кого берёт ГГ в команду, что бы они просто были на точки перед каньоном

```D
FUNC VOID Rtn_PreFollow_хххх ()
{	
	TA_Stand_Drinking (08,00,20,00, "ADW_CANYON_TELEPORT_****");
	TA_Stand_Drinking (20,00,08,00, "ADW_CANYON_TELEPORT_****");
};

```
а расписание на **Follow** менял бы у НПС на точке возле каньона, условия проверки есть у Скипа
```D
	if((self.aivar[AIV_PARTYMEMBER] == TRUE) && (Npc_GetDistToWP(self,"ADW_CANYON_TELEPORT_PATH_06") <= 800) && !C_AllCanyonRazorDead())
	{
		return TRUE;
	};
```

 таким образом можно полностью заблокировать каньон со стороны пиратов.

**Comment by dosinabox** [comment]
> тогда смело запрещай все пляжи.

запрещены
