### ISSUE TITLE
карта в хижине Грега

### ISSUE THREAD

**Issue by Kor-Angar** [dosinabox/g2nr_unofficial_update#329]
![20210116053943_1](https://user-images.githubusercontent.com/49514764/104799450-495c2b00-57e0-11eb-9e91-5e7a7c8ce9e4.jpg)

**Comment by dosinabox** [comment]
Как минимум, Грег мог использовать её чтобы планировать перевозки для бандитов. Также в Хоринисе был Скип.

Кстати, в замке Миненталя теперь такие карты вместо карт Хориниса:
![Screenshot_11](https://user-images.githubusercontent.com/39790055/104808514-d52d8180-57f7-11eb-8ee2-7165ac039176.jpg)

**Comment by Kor-Angar** [comment]
Страшенькая 😀12:39, 16 января 2021 г., dosinabox <notifications@github.com>:
Как минимум, Грег мог использовать её чтобы планировать перевозки для бандитов. Также в Хоринисе был Скип.
Кстати, в замке Миненталя теперь такие карты вместо карт Хориниса:


—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
-- Отправлено из мобильного приложения Яндекс.Почты

**Comment by dosinabox** [comment]
Есть такое. Главное, что теперь есть новая модель и она вставлена в мир, а её текстуру легко заменить на любую другую.

**Comment by Kor-Angar** [comment]
Это да. А у Грега как? Отдельная модель? 12:52, 16 января 2021 г., dosinabox <notifications@github.com>:
Есть такое. Главное, что теперь есть новая модель и она вставлена в мир, а её текстуру легко заменить на любую другую.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
-- Отправлено из мобильного приложения Яндекс.Почты

**Comment by dosinabox** [comment]
нет, такая же как и везде
