### ISSUE TITLE
zParserExtender.zip

### ISSUE THREAD

**Issue by Kor-Angar** [dosinabox/g2nr_unofficial_update#330]
..

**Comment by dosinabox** [comment]
GothicStarter_mod.exe?

**Comment by Kor-Angar** [comment]
Наверное это было из-за zParserExtender

**Comment by UnresolvedExternal** [comment]
С последней версией zParserExtender баг воспроизводится?

**Comment by Kor-Angar** [comment]
А скиньте ещё раз  последний версию.

**Comment by UnresolvedExternal** [comment]
[zParserExtender.zip](https://github.com/dosinabox/g2nr_unofficial_update/files/5873820/zParserExtender.zip)

**Comment by Kor-Angar** [comment]
![image](https://user-images.githubusercontent.com/49514764/105857939-d92d8080-5ffb-11eb-8e70-c8d6ff98bfed.png)

**Comment by UnresolvedExternal** [comment]
Надо Юнион версии 1.0i устанавливать. Поэтому наверное не грузится.
