### ISSUE TITLE
Откаты к оригиналу

### ISSUE THREAD

**Issue by dosinabox** [dosinabox/g2nr_unofficial_update#332]
Здесь перечисляются правки, которые никому не нравятся и которые следует отменить, вернув всё как в оригинале.

- [x] вернуть оригинальных предводителей орков и вообще убрать опцию усиленных
- [x] вернуть цену в 250 золотых гоблинским ягодам
- [x] вернуть оригинальные цены свитков превращения
- [x] вернуть оригинальный меч в награду за квест Кантара
- [x] вернуть скелета в замок Миненталя или отрегулировать параметры зомби (OC_EBR_DARK_FLOOR)
- [x] убрать анимации размахивания рук в диалогах (T_DIALOGGESTURE_04 / T_DIALOGGESTURE_05)
- [x] сделать модель меча Альрика менее примечательной и более старой

**Comment by Kor-Angar** [comment]
а ты цену зелий изменяла? ягод гоблина в продаже много и это чувствуется, а вот зелий в продаже мало и это не заметно было :-)

**Comment by dosinabox** [comment]
Цены эликсиров ловкости и силы были увеличены с 800 до 1600 золотых. Чтобы не было ниже себестоимости (500 царский щавель + 500 драконий корень/новая гоблинская ягода) и чтобы не было дешевле эликсиров жизни и духа (1500).

**Comment by Kor-Angar** [comment]
цену экспериментального эликсира из яйца дракона тоже можно поправить

**Comment by dosinabox** [comment]
> цену экспериментального эликсира из яйца дракона тоже можно поправить

На какую? Сейчас 50.

**Comment by Kor-Angar** [comment]
затрудняюсь определить цену. можно её просто убрать или поставить какую то символическую :-)

**Comment by dosinabox** [comment]
Поставлю 300, потому что яйцо стоит 200

**Comment by Kor-Angar** [comment]
это один из ингредиентов ;-) там наверняка какая нибудь черная демчужина использовалась или что то такое. у зелья из кучи яиц цена есть?26.01.2021, 13:42, "dosinabox" <notifications@github.com>:
Поставлю 300, потому что яйцо стоит 200

**Comment by dosinabox** [comment]
Отменено в связи с переработкой системы воровства:
- Дневник Корнелиуса можно украсть только после получения от лорда Хагена информации о свидетеле убийства.
- Украсть ключ у стражника у главных ворот замка можно только после получения от Торлофа задания открыть эти ворота.

**Comment by dosinabox** [comment]
Похоже, что родные звуки ранений и смерти ГГ SVM_15 никому не нравятся, поэтому я верну оригинальные SVM_2. В классике тоже.

Оставляю код для личного пользования, чтобы вернуть родные SVM_15:
```cpp
META
{
	Parser = SFX;
	MergeMode = true;
	Engine = G2A;
};

instance SVM_15_AARGH(C_SFX_DEF)
{
	file = "svm_15_aargh_1.wav";
	vol = 107;
};

instance SVM_15_AARGH_1(C_SFX_DEF)
{
	file = "svm_15_aargh_2.wav";
	vol = 107;
};

instance SVM_15_AARGH_2(C_SFX_DEF)
{
	file = "svm_15_aargh_3.wav";
	vol = 107;
};

instance SVM_15_AARGH_3(C_SFX_DEF)
{
	file = "svm_15_aargh_3.wav";
	vol = 107;
};

instance SVM_15_AARGH_4(C_SFX_DEF)
{
	file = "svm_15_aargh_3.wav";
	vol = 107;
};

instance SVM_15_DEAD(C_SFX_DEF)
{
	file = "svm_15_dead.wav";
	vol = 120;
};
```

**Comment by Kor-Angar** [comment]
хорошее дело :-)
