### ISSUE TITLE
Mdl_SetModelFatness(self,-1)

### ISSUE THREAD

**Issue by dosinabox** [dosinabox/g2nr_unofficial_update#334]
Параметр NPC `Mdl_SetModelFatness(self,-1)` приводит к разрыву в поясе у некоторых моделей доспехов. Например, у Фортуно:
![image](https://user-images.githubusercontent.com/39790055/106923829-85b7e280-671f-11eb-8c95-629b563990aa.png)

Нужно проверить все NPC с таким параметром.

**Comment by Kor-Angar** [comment]
в своей сборки встречал такое у некоторых рудокопов/рабов в Ярике

**Comment by dosinabox** [comment]
Исправлено у Фортуно. У других такого нет. Если найдете - переоткройте топик.
