### ISSUE TITLE
IGARAZ_ISPARTNER

### ISSUE THREAD

**Issue by Kor-Angar** [dosinabox/g2nr_unofficial_update#338]
IGARAZ_ISPARTNER == LOG_SUCCESS

а это альтеративный квест был в рамках документов Бабо?

**Comment by dosinabox** [comment]
Неизвестно, потому что в оригинале переменная никогда не получает какого-либо значения:
![image](https://user-images.githubusercontent.com/39790055/109836615-62685080-7c55-11eb-98c3-2d6fd73aee37.png)

В результате чего все эти реплики недоступны и в классике, и в аддоне:

```cpp
func void DIA_Babo_Kap3_HaveYourDocs_KeepThem_Partner()
{
	AI_Output(other,self,"DIA_Babo_Kap3_HaveYourDocs_KeepThem_Partner_15_00");	//Игарац и я теперь партнеры.
	AI_Output(self,other,"DIA_Babo_Kap3_HaveYourDocs_KeepThem_Partner_03_01");	//(ошеломленно) Что? Ты не можешь поступить со мной так.
	AI_Output(other,self,"DIA_Babo_Kap3_HaveYourDocs_KeepThem_Partner_15_02");	//А я думаю, что могу. Я придержу у себя эти бумаги, пусть все пока останется так, как есть.
	AI_Output(other,self,"DIA_Babo_Kap3_HaveYourDocs_KeepThem_Partner_15_03");	//Я должен обговорить финансовую часть с Игарацем.
	AI_Output(other,self,"DIA_Babo_Kap3_HaveYourDocs_KeepThem_Partner_15_04");	//А ты пока занимайся своими растениями.
	AI_Output(self,other,"DIA_Babo_Kap3_HaveYourDocs_KeepThem_Partner_03_05");	//Ты свинья. Презренная жадная свинья. Иннос покарает тебя.
	Info_ClearChoices(DIA_Babo_Kap3_HaveYourDocs);
	Info_AddChoice(DIA_Babo_Kap3_HaveYourDocs,Dialog_Ende,DIA_Babo_Kap3_HaveYourDocs_End);
	Info_AddChoice(DIA_Babo_Kap3_HaveYourDocs,"Придержи язык.",DIA_Babo_Kap3_HaveYourDocs_KeepThem_Partner_KeepCalm);
	Info_AddChoice(DIA_Babo_Kap3_HaveYourDocs,"Тебе что, нечем заняться?",DIA_Babo_Kap3_HaveYourDocs_KeepThem_Partner_NothingToDo);
};
```

```cpp
func void DIA_Babo_Kap3_HaveYourDocs_KeepThem_Partner_KeepCalm()
{
	AI_Output(other,self,"DIA_Babo_Kap3_HaveYourDocs_KeepThem_Partner_KeepCalm_15_00");	//Придержи язык.
	AI_Output(self,other,"DIA_Babo_Kap3_HaveYourDocs_KeepThem_Partner_KeepCalm_03_01");	//Я буду вежлив как всегда.
	AI_StopProcessInfos(self);
};
```

```cpp
func void DIA_Babo_Kap3_HaveYourDocs_KeepThem_Partner_NothingToDo()
{
	AI_Output(other,self,"DIA_Babo_Kap3_HaveYourDocs_NothingToDo_15_00");	//Тебе что, нечем заняться?
	AI_Output(self,other,"DIA_Babo_Kap3_HaveYourDocs_NothingToDo_03_01");	//Я все понимаю, но, поверь мне, ты пожалеешь об этом.
	AI_StopProcessInfos(self);
};
```

**Comment by Kor-Angar** [comment]
Ну это как раз про то что Бабо должен работать в саду и выращивать дурь😀 19:21, 3 марта 2021 г., dosinabox <notifications@github.com>:
Closed #338.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
-- Отправлено из мобильного приложения Яндекс.Почты

**Comment by Kor-Angar** [comment]
при игре не за мага, Бабо можно поставить в сад, а Агона в библиотеку.

тогда квест про бабо и Игараца будет более лаконичный так как судя по репликам Игараца Бабо должен в саду работать :-)

**Comment by dosinabox** [comment]
В обновлении работа Бабо проверяется. Если он не работает в саду, то ГГ не говорит про растения.

**Comment by dosinabox** [comment]
А сама реплика про растения перенесена в другой диалог:

```cpp
func void DIA_Babo_Kap3_Perm_Info()
{
	AI_Output(other,self,"DIA_Babo_Kap3_Perm_15_00");	//Ты доволен своей работой?
	if(hero.guild == GIL_KDF)
	{
		AI_Output(self,other,"DIA_Babo_Kap3_Perm_03_01");	//(неубедительно) Да, конечно. Моя вера в мудрость и силу Инноса придает мне силы.
		if(MIS_HelpBabo == LOG_SUCCESS)
		{
			AI_Output(other,self,"DIA_Babo_Kap3_HaveYourDocs_KeepThem_Partner_15_04");	//А ты пока занимайся своими растениями.
		}
		else
		{
			AI_Output(self,other,"DIA_Babo_Kap3_Perm_03_02");	//(уклончиво) Я не хочу показаться невежливым, но у меня много дел сегодня.
			AI_Output(other,self,"DIA_Babo_Kap3_Perm_15_03");	//Можешь продолжать.
		};
		AI_Output(self,other,"DIA_Babo_Kap3_Perm_03_04");	//(облегченно) Спасибо.
	}
	else
	{
		AI_Output(self,other,"DIA_Babo_Kap3_Perm_03_05");	//Все хорошо, но мне нужно возвращаться к работе, иначе мне ни за что не закончить ее сегодня.
		AI_Output(self,other,"DIA_Babo_Kap3_Perm_03_06");	//Я не хочу опять трудиться до полуночи, чтобы выполнить свою работу и не быть наказанным.
	};
	AI_StopProcessInfos(self);
};
```

**Comment by Kor-Angar** [comment]
Там дело в том что работать в саду он может при игре за мага, если герой его туда отправить. А квест про картинки  магу не доступен. Про сад говорит Игарац. При игре за мага нету квеста про доки, но можно Бабо отправить в сад. А за прочие фракции, где квест есть, Бабо находится не в саду 😀Поэтому я и менял у себя расписание жизни в монастыре, что бы при игре не за мага квест был понетнее. А то вроде Игарац там суетился что бы Бабо в сад пристроить, а в саду Агон трудится. В то время как для Агона при игре не за мага, более подходящее место в библиотеке.   пол подметать вместо Бабо может тот которого при игре за мага должны были выгнать из Монастыря 😀22:25, 3 марта 2021 г., dosinabox <notifications@github.com>:
В обновлении работа Бабо проверяется. Если он не работает в саду, то ГГ не говорит про растения.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
-- Отправлено из мобильного приложения Яндекс.Почты

**Comment by Kor-Angar** [comment]
я про этот диалог :-)
```D
	AI_Output(other,self,"DIA_Igaranz_BabosJob_15_00");	//Что Бабо должен делать для тебя?
	AI_Output(self,other,"DIA_Igaranz_BabosJob_13_01");	//Если бы я знал, что этот слизняк наложит в штаны из-за нескольких кустов болотной травы, я бы давно позаботился, чтобы кто-нибудь другой занял его место в монастырском саду.
	AI_Output(other,self,"DIA_Igaranz_BabosJob_15_02");	//Он должен выращивать болотную траву?
	AI_Output(self,other,"DIA_Igaranz_BabosJob_13_03");	//Конечно. Так как она больше не поступает из-за Барьера, цена на травку в городе выросла втрое.
	AI_Output(self,other,"DIA_Igaranz_BabosJob_13_04");	//Мы могли бы хорошо заработать на этом. Но Бабо отказывается сотрудничать.
```

![20210303225727_1](https://user-images.githubusercontent.com/49514764/109865053-ac146380-7c74-11eb-84f1-08718edb766a.jpg)

https://www.youtube.com/watch?v=ghu3F3LQQog

**Comment by dosinabox** [comment]
Т.е. при вступлении в ополчение или наемники нужно отправлять Бабо в сад, а реплику вернуть где была?

**Comment by Kor-Angar** [comment]
> Т.е. при вступлении в ополчение или наемники нужно отправлять Бабо в сад,

у меня так стоит. но может быть разумнее менять расписание Бабо/Агону при вступление в послушники.

> реплику вернуть где была?

не могу по тексту понять. надо в игре послушать как оно будет звучать. может будет хорошо и в тему, а может выбиваться.

**Comment by dosinabox** [comment]
> но может быть разумнее менять расписание Бабо/Агону при вступление в послушники.

А вот тут не понятно. Ведь отправить Бабо в сад можно попросив Пирокара, и о нем рассказывает Ополос:
```cpp
AI_Output(self,other,"DIA_Opolos_Agon_12_02");	//Бабо пришел в монастырь незадолго до тебя. И сначала он помогал Агону в саду.
AI_Output(self,other,"DIA_Opolos_Agon_12_03");	//Похоже, они что-то там не поделили, и с тех пор Бабо подметает двор.
```

**Comment by Kor-Angar** [comment]
видимо там был какой то ещё диалог у Игараца который вытекал из dia_igaraz_babosjob_info на тему что ГГ шантажем заставить Бабо выращивать болотник 

```
var int Parlan_DontTalkToNovice;	//Rede nicht mit den Novizen
var int NeorasBrewsForYou;			//Neoras braut Trдnke fьr dich!
var int BabosDocsOpen;				//Player hat sich Babos Schmuddelhelt angeguckt
var int Igaraz_ISPartner;			//igaraz und Player erpressen babo
```

**Comment by Kor-Angar** [comment]
> но может быть разумнее менять расписание Бабо/Агону при вступление в послушники.

имею ввиду по дефауту сделать расписание Бабо в Саду, Агон в библиотеке. при вступление в послушники Бабо подметает, Агон в саду.


> А вот тут не понятно. Ведь отправить Бабо в сад можно попросив Пирокара, и о нем рассказывает Ополос:

там много не понятно. понятно что сценарии когда герой в монастыре отличается от того когда он состоит в другой фракции :-)

если герой будет просить за Бабо и сад, то Агон если будет жив отправится в верхний квартал.

у Пирокара четыре варианта
- Дуриана невыгоняют, он идёт в сад(?)
- Дуриана выгоняют, Бабо в сад
- Дуриана выгоняют, Opolos в библиотеку // за овцами кто смотрит в таком случае? :-)
- Дуриана выгоняют

***

> имею ввиду по дефауту сделать расписание Бабо в Саду, Агон в библиотеке. 

или например Бабо в Саду, Агон в подвале с алхимиком Неорас.
