### ISSUE TITLE
Ультар про очистку статуй инноса / Мент

### ISSUE THREAD

**Issue by Kor-Angar** [dosinabox/g2nr_unofficial_update#34]
```
instance DIA_Ulthar_WARN(C_Info)
{
	npc = KDF_502_Ulthar;
	nr = 30;
	condition = DIA_Ulthar_WARN_Condition;
	information = DIA_Ulthar_WARN_Info;
	important = TRUE;
};


func int DIA_Ulthar_WARN_Condition()
{
	if((Pedro_Traitor == TRUE) && (hero.guild != GIL_PAL) && (Kapitel == 3))
	{
		return TRUE;
	};
};

func void DIA_Ulthar_WARN_Info()
{
	AI_Output(self,other,"DIA_Ulthar_SCHREINEVERGIFTET_05_08");	//Еще одно. Держись подальше от придорожных алтарей. Мы слышали, что некоторые из них были осквернены.
	AI_Output(self,other,"DIA_Ulthar_SCHREINEVERGIFTET_05_09");	//Никто не знает, как теперь они действуют.
	AI_Output(self,other,"DIA_Ulthar_SCHREINEVERGIFTET_05_10");	//Тебя не должна волновать эта проблема. О ней позаботятся паладины.
	AI_StopProcessInfos(self);
};
```
есть предложение не воспроизводить фразу _Тебя не должна волновать эта проблема. О ней позаботятся паладины._ если герой Милиционер, так как когда герой станет Паладином Ультар даст ему задание очистить статуи Инноса.

**Comment by dosinabox** [comment]
> есть предложение не воспроизводить фразу _Тебя не должна волновать эта проблема. О ней позаботятся паладины._ если герой Милиционер, так как когда герой станет Паладином Ультар даст ему задание очистить статуи Инноса.

Не соглашусь, потому что Ультар ещё не знает, что ГГ станет паладином. Сейчас всё правильно.

**Comment by Kor-Angar** [comment]
это уже наши правки. в оригинальной игре Ультар давал задание по очистке статуй и милиционеру и паладину. 

а сейчас он милиционеру говорит что этим вопросом будут заниматься паладины(может тот пал что при монастыре?). а потом герою паладину говорит что ему надо очистить статую. 
даже вступление в диалогах одинаковое начинается с "еще одно дело".

т.е. внеся изменения в оригинальный скрипт, как обычно, не было проверено как это звучит в игре. а в игре это звучит глупо. поэтому я и написал про это.

можно вообще милиционеру ничего не говорит про эти оскверненные статуи, а паладину проиграть полноценный диалог.

**Comment by Kor-Angar** [comment]
и надо вернутся к вопросу получения опыта за **очистку каждой** статуи. сейчас опыта начисляется согласно в которой статуя очищена:

- если в 3 главе 150
- в 4 200
- в 5 250

Надо его зафиксировать на 150

**Comment by dosinabox** [comment]
> а сейчас он милиционеру говорит что этим вопросом будут заниматься паладины(может тот пал что при монастыре?). а потом герою паладину говорит что ему надо очистить статую.

Мне это не кажется нелогичным.

> можно вообще милиционеру ничего не говорит про эти оскверненные статуи

Но тогда теряется предупреждение. По идее, Ультар должен рассказывать об опасности всем. И игрок тоже должен узнавать о изменении правил игры.

**Comment by dosinabox** [comment]
> и надо вернутся к вопросу получения опыта за **очистку каждой** статуи. сейчас опыта начисляется согласно в которой статуя очищена

Возможно, лучше сделать как с Гарвеллом: чем раньше очищаем, тем больше опыта получаем.

3 - 150
4 - 100
5 - 50

**Comment by Kor-Angar** [comment]
> Но тогда теряется предупреждение. По идее, Ультар должен рассказывать об опасности всем. И игрок тоже должен узнавать о изменении правил игры.

у него этот диалог привязан к сдаче письма от Лорда Хагена Пирокару. т.е. если прийти например магом в начале 3 главы в монастырь то Ультар не предупредить ГГ об опасности.

**Comment by dosinabox** [comment]
> у него этот диалог привязан к сдаче письма от Лорда Хагена Пирокару. т.е. если прийти например магом в начале 3 главы в монастырь то Ультар не предупредить ГГ об опасности.

Возможно, следует это поправить и предупреждать всех об опасности сразу по факту её появления в третьей главе.

**Comment by Kor-Angar** [comment]
```
instance DIA_Ulthar_WARN(C_Info)
{
	npc = KDF_502_Ulthar;
	nr = 30;
	condition = DIA_Ulthar_WARN_Condition;
	information = DIA_Ulthar_WARN_Info;
	important = TRUE;
};


func int DIA_Ulthar_WARN_Condition()
{
	if((Pedro_Traitor == TRUE) && (hero.guild != GIL_PAL) && (Kapitel == 3))
	{
		return TRUE;
	};
};

func void DIA_Ulthar_WARN_Info()
{
	AI_Output(self,other,"DIA_Ulthar_SCHREINEVERGIFTET_05_08");	//Еще одно. Держись подальше от придорожных алтарей. Мы слышали, что некоторые из них были осквернены.
	AI_Output(self,other,"DIA_Ulthar_SCHREINEVERGIFTET_05_09");	//Никто не знает, как теперь они действуют.
	AI_Output(self,other,"DIA_Ulthar_SCHREINEVERGIFTET_05_10");	//Тебя не должна волновать эта проблема. О ней позаботятся паладины.
	AI_StopProcessInfos(self);
};

```

условие поменять с Pedro_Traitor == TRUE на то говорил ли ГГ в 3 главе с Пирокаром
Я пришел из старой Долины Рудников. DIA_Pyrokar_BACKFROMOW
или
Я пришел, чтобы забрать Глаз Инноса. DIA_Pyrokar_GIVEINNOSEYE 


```

if((Npc_KnowsInfo(hero,DIA_Pyrokar_GIVEINNOSEYE ) || Npc_KnowsInfo(hero,DIA_Pyrokar_BACKFROMOW)) && (hero.guild != GIL_PAL) && (Kapitel == 3))

```

так?

**Comment by Kor-Angar** [comment]
```
func void DIA_Ulthar_WARN_Info()
{
	AI_Output(self,other,"DIA_Ulthar_SCHREINEVERGIFTET_05_08");	//Еще одно. Держись подальше от придорожных алтарей. Мы слышали, что некоторые из них были осквернены.
	AI_Output(self,other,"DIA_Ulthar_SCHREINEVERGIFTET_05_09");	//Никто не знает, как теперь они действуют.
	AI_Output(self,other,"DIA_Ulthar_SCHREINEVERGIFTET_05_10");	//Тебя не должна волновать эта проблема. О ней позаботятся паладины.
	AI_StopProcessInfos(self);
};
```

вот эту фразу 
_AI_Output(self,other,"DIA_Ulthar_SCHREINEVERGIFTET_05_10");	//Тебя не должна волновать эта проблема. О ней позаботятся паладины._
не надо показывать милиционеру

так как потом Ултар даст задание когда герой станет Паладином.

**Comment by Kor-Angar** [comment]
можно во время сдачи квеста Ультару убирать у героя "святою воду Ультара"? :-)

**Comment by dosinabox** [comment]
> не надо показывать милиционеру так как потом Ултар даст задание когда герой станет Паладином.

Не соглашусь. Уже обсуждали. Ультар не знает, что милиционер перед ним обязательно станет паладином.

**Comment by Kor-Angar** [comment]
изначально эту реплику Ультар вообще не произносил Милиционеру. Он милиционеру давал задание.

Мы используем эту реплику которую Ультар говорит магу и наёму. 

Сейчас Ультар говорит милиционеру что этой проблемой займутся паладины. При этом когда приходит герой Паладин он даёт ему задание и святую воду.
Я предлагаю для милиционера убрать одну реплику, что бы Ультар сначала предупредил Милиционера о такой проблеме, а потом дал задание Пала. 

Это общая проблема в модах. Есть сюжет игры. Общий сюжет, и в этом сюжете есть герой. Вот например послушника выгоняют из монастыря после испытания огнём. испытания огнём проходит если герой играет за мага. если герой играет не за мага , то испытание не проходит, соответственно все ждут испытания и послушник тоже ждёт его. а в неофициальном обновление его выгоняют из монастыря при игре за мента.

То же самое и с очисткой статуй. Их чистят в течение 3 главы паладины. Если мы прорабатываем сценарий при котором Ультар не даёт задание по очистки менту, давай это делать как то.. проработано и всесторонне.

> Ультар не знает, что милиционер перед ним обязательно станет паладином.

тогда если Ультар говорит менту  что этим займутся Паладины, то этим займутся Паладины. и когда герой Паладин прийдет к Ультару, Ультар ему наверное должен сказать что статуи уже очистили Паладины? ;-) нет? Ультар скажет Менту что этим займутся Паладины и будет сидеть ждать когда милиционер станет Паладином, потому что Ультар знает, что милиционер перед ним обязательно станет паладином?:-)

**Comment by dosinabox** [comment]
> Я предлагаю для милиционера убрать одну реплику, что бы Ультар сначала предупредил Милиционера о такой проблеме, а потом дал задание Пала.

Готово.
