### ISSUE TITLE
Бессмертные нпс

### ISSUE THREAD

**Issue by Kor-Angar** [dosinabox/g2nr_unofficial_update#37]
Ларес бессмертный до конца игры. Наверное надо его сделать смертным после того как ГГ вступил в КВ.

**Comment by dosinabox** [comment]
Нет, потому что он входит в команду корабля. И вроде бы по канону доживает до третьей части.

**Comment by Kor-Angar** [comment]
Он в Готике 2 Оригинал был смертным. а в Ночь ворона стал бессмертным потому в рамках основного квеста аддона ходит с ГГ.

**Comment by Kor-Angar** [comment]
а кто ещё по канону доживает до третей готики? им бессмертия случайно дать не надо, например Ангару или Горну или Торлофу или Волку?;-)

Так же бессмертны:
- Судья (нужен Наёмнику что бы получит документы на корабль)
- Ли (наёмнику даёт квест про судью)

**Comment by Kor-Angar** [comment]
а какое минимальное кол-во персонажей, кроме капитана, надо взять на корабль, что бы поплыть? 5?

`AI_Output(self,other,"DIA_Torlof_LOSFAHREN_01_06");	//Мне нужно, по крайней мере, пять человек, готовых встать под мое начало.`
const int Min_Crew = 5;

1. Мильтен (бессмертный)
2. Лестер (бессмертный)
3. Диего   (бессмертный)
4. Ли (бессмертный)
5. Беннет   (бессмертный)
6. Ларес   (бессмертный), в Готике 2 оригинал смертный
7. Марио    бессмертный?
8. Ватрас (бессмертный), но может отказаться (становится смертный). как с ним в Готике 2 оригинал обстоя дела, он там по моему не отказывается?

**Comment by Kor-Angar** [comment]
вообщем с правками что Марио и Гирион не считается мы опять сломали логику авторов. Марио и Гирион должны учитываться как в оригинальных скриптах, так как дело не только в максимальном кол-ве членов экипажа, но и в **минимальном**.

а так будет получится что герой взял капитана + 5 человек(учитывая Марио и Гириона) а уплыть не может. И капитан при этом будет говорит что ему надо пять человек.

**Comment by dosinabox** [comment]
> а так будет получится что герой взял капитана + 5 человек(учитывая Марио и Гириона) а уплыть не может. И капитан при этом будет говорит что ему надо пять человек.

Совершенно не проблема, легко исправлено.

**Comment by dosinabox** [comment]
> 7\. Марио    бессмертный?

Да.

**Comment by dosinabox** [comment]
> а какое минимальное кол-во персонажей, кроме капитана, надо взять на корабль, что бы поплыть? 5?

Да.

**Comment by Kor-Angar** [comment]
а Марио смертным становится если его несколько раз взять/отказаться?

**Comment by dosinabox** [comment]
> а Марио смертным становится если его несколько раз взять/отказаться?

Становится, если обижается и атакует ГГ.

**Comment by Kor-Angar** [comment]
а Беннет? Беннет бессмертный?

**Comment by dosinabox** [comment]
> а Беннет? Беннет бессмертный?

Да, всегда. Никогда не становится смертным и даже никогда не обижается на ГГ, который несколько раз выгоняет его из команды.

**Comment by Kor-Angar** [comment]
а в Готике 2 оригинал Ватрас становился смертным?

**Comment by Kor-Angar** [comment]
получается что авторы на случай если герой начнёт убивать всё и вся сделали ряд бессмертных НПС, что бы было с кем уплыть на остров

- Мильтен (бессмертный) 
- Лестер (бессмертный)
- Диего (бессмертный)
- Ли (бессмертный)
- Беннет (бессмертный)
- Ларес (бессмертный) в Готике 2 НВ, в Готике 2 оригинал смертный
- Ватрас в Готике 2 оригинал бессмертный (?) в Готике 2 НВ смертный

Капитан из Монастыря бессмертный. Торлоф и капитан из города смертные.

Я это пишу что бы просто зафиксировать логику авторов. что бы так сказать не наводить тень на плетень и ничего не надумывать.

**Comment by dosinabox** [comment]
> * Ватрас в Готике 2 оригинал бессмертный (?)

Да, всегда. В Г2 без аддона он не обижается ни на исключение из команды, ни на геноцид населения.

**Comment by Kor-Angar** [comment]
Это я опять же таки отмечаю для понимания общего, авторской мысли. Что откуда вытекает и куда течёт :-)

Готика 2 оригинал
1. Мильтен (бессмертный)
2. Лестер (бессмертный)
3. Ли (бессмертный)
4. Беннет (бессмертный)
5. Ватрас в Готике 2 оригинал (бессмертный)

Готика 2 НВ
1. Мильтен (бессмертный)
2. Лестер (бессмертный)
3. Диего (бессмертный)
4. Ли (бессмертный)
5. Беннет (бессмертный)
6. Ларес (бессмертный)

**Comment by Kor-Angar** [comment]
можно снять бессмертие с капитана из монастыря (Иорган?) если взят в капитаны Торлоф или Джек

**Comment by Kor-Angar** [comment]
с Паладина который стоит на входе к Лорду Хагуну в 5 главе можно снимать бессмертие

https://youtu.be/6vgE0pURYL4?t=10268

**Comment by Kor-Angar** [comment]
с Боспера бессмертие сняли в последней версии? у кого в Хориносе стоит бессмертие ещё?

**Comment by Kor-Angar** [comment]
а Орлан смертный?

```D
	if(!Npc_IsDead(Orlan))
	{
		CreateInvItem(Orlan,ItMW_Addon_Stab03);
	};
```

**Comment by dosinabox** [comment]
> а Орлан смертный?

становится смертным в DIA_Addon_Orlan_WhenRangerMeeting_Info
