### ISSUE TITLE
Штраф у Ли

### ISSUE THREAD

**Issue by dosinabox** [dosinabox/g2nr_unofficial_update#372]
> Когда ГГ сначала накосячит на ферме Онара, а потом вступает в монастырь и все его прегрешения прощаются, то при приходе к Ли и первом диалоге с ним после спича Ли о том, что никаких прегрешений за ГГ более не числится и штраф ему платить не надо - ГГ выкидывает в меню диалога про штраф. И без нелогичных реплик выйти из оного не удается. С лордом Андрэ в этом плане все в порядке, а вот Ли подкачал. Думаю, стоит это как-то поправить.

**Comment by Kor-Angar** [comment]
в твоей версии при вступление в монастырь грехи обнуляются же. вроде мы про это говорили в позапрошлом году и ты это правила.

**Comment by dosinabox** [comment]
Просто переношу из своих заметок, чтобы не потерялось. Может и исправлено. А может и не исправлено в именно такой комбинации. Надо проверить.

**Comment by dosinabox** [comment]
исправлено
относилось к Андрэ, Хагену, Гаронду, Парлану и Ли
