### ISSUE TITLE
еда к силе

### ISSUE THREAD

**Issue by Kor-Angar** [dosinabox/g2nr_unofficial_update#381]
у тебя наверное тут 
https://github.com/dosinabox/g2nr_unofficial_update/blob/7f3f46065207609f9d794dd37a01200104199ce0/PrjGOTHIC/Items/IT_Addon_Food.d#L261

проверка на IgnoreBonuses  лишняя.

лучше ItFo_Addon_FireStew , ItFo_Addon_Meatsoup и ItFo_XPStew собрать в одном месте друг под другом.

**Comment by Kor-Angar** [comment]
```D
func void Use_MeatSoup()
{
	Npc_ChangeAttribute(self,ATR_HITPOINTS,HP_Stew);
	if(Npc_IsPlayer(self))
	{
		B_RaiseAttribute(self,ATR_STRENGTH,STR_MeatSoup);
	};
};
```

**Comment by Kor-Angar** [comment]
```D
func void Use_FireStew()
{
	var string concatText;
	B_RaiseAttribute(self,ATR_HITPOINTS_MAX,HP_FireStew);
	self.attribute[ATR_STRENGTH] += STR_FireStew;
	if(IgnoreBonuses == FALSE)
	{
		B_RaiseRealAttributeLearnCounter(self,ATR_STRENGTH,STR_FireStew);
	};
	concatText = ConcatStrings(PRINT_LearnSTR,IntToString(STR_FireStew));
	PrintScreen(concatText,-1,53,FONT_Screen,2);
};
```

**Comment by dosinabox** [comment]
> проверка на IgnoreBonuses лишняя.

почему?

**Comment by Kor-Angar** [comment]
неправильно посмотрел код. привык что у тебя проверка на IgnoreBonuses  происходит в B_RaiseAttribute
