### ISSUE TITLE
B_StartOtherRoutine у мёртвых НПС

### ISSUE THREAD

**Issue by Kor-Angar** [dosinabox/g2nr_unofficial_update#385]
Мёртвые НПС дёргаются при смене расписания так как  сила скрипта B_StartOtherRoutine   сначала их поднимает , а потом делает проверку на то мертвы они или нет. 
```D
func void B_StartOtherRoutine(var C_Npc slf,var string newRoutine)
{
	AI_Standup(slf);
	if(Hlp_GetInstanceID(self) != Hlp_GetInstanceID(slf))
	{
		if(Hlp_IsValidNpc(slf) && !Npc_IsDead(slf))
		{
			Npc_ExchangeRoutine(slf,newRoutine);
			AI_ContinueRoutine(slf);
		};
	}
	else
	{
		Npc_ExchangeRoutine(slf,newRoutine);
	};
};
```

Ты на это многократно обращала внимания на моих стримах во время диалога с Эстебаном. полагаю что 	AI_Standup(slf); можно просто пронести под проверку и ешё раз продублировать после else.

```D
func void B_StartOtherRoutine(var C_Npc slf,var string newRoutine)
{
	AI_Standup(slf);
	if(Hlp_GetInstanceID(self) != Hlp_GetInstanceID(slf))
	{
		if(Hlp_IsValidNpc(slf) && !Npc_IsDead(slf))
		{
			AI_Standup(slf);
			Npc_ExchangeRoutine(slf,newRoutine);
			AI_ContinueRoutine(slf);
		};
	}
	else
	{
		AI_Standup(slf);
		Npc_ExchangeRoutine(slf,newRoutine);
	};
};
```

**Comment by dosinabox** [comment]
В актуальной версии как раз так: https://github.com/dosinabox/g2nr_unofficial_update/blob/master/PrjGOTHIC/Story/B_Story/B_StartOtherRoutine.d

**Comment by Kor-Angar** [comment]
зер гуд. а я смотрел в архиве от 2021_09_18_g2nr_unofficial_update-master там еще не исправлен был.
