### ISSUE TITLE
Воровство Ингмар

### ISSUE THREAD

**Issue by Kor-Angar** [dosinabox/g2nr_unofficial_update#39]
у Ингмара в описание воровства было написано что похищается **свиток**
```
instance DIA_Ingmar_PICKPOCKET(C_Info)
{
	npc = PAL_201_Ingmar;
	nr = 900;
	condition = DIA_Ingmar_PICKPOCKET_Condition;
	information = DIA_Ingmar_PICKPOCKET_Info;
	permanent = TRUE;
	description = "(украсть его свиток практически невозможно)";
};
```
фактически похищается "**текст песни**"

```

instance ItWr_Manowar(C_Item)
{
	name = "Текст песни";
	mainflag = ITEM_KAT_DOCS;
	flags = ITEM_MISSION;
	value = 0;
	visual = "ItWr_Scroll_02.3DS";
	material = MAT_LEATHER;
	on_state[0] = UseManowar;
	scemeName = "MAP";
	description = name;
};

```

**Comment by dosinabox** [comment]
Это нормально, потому что текст песни написан на свитке :)
![image](https://user-images.githubusercontent.com/39790055/64090900-3d400c80-cd56-11e9-890b-f0b9723d09b8.png)

**Comment by Kor-Angar** [comment]
у паладинов в замке можно украсть свитки заклинаний
```
instance DIA_Oric_PICKPOCKET(C_Info)
{
	npc = PAL_251_Oric;
	nr = 900;
	condition = DIA_Oric_PICKPOCKET_Condition;
	information = DIA_Oric_PICKPOCKET_Info;
	permanent = TRUE;
	description = "(украсть его свиток будет чертовски трудно)";
};
```
немецкая версия Ингмар **Schriftrolle** 
Немецкая версия Орик **Spruchrolle** 

```
instance DIA_Ingmar_PICKPOCKET(C_Info)
{
	npc = PAL_201_Ingmar;
	nr = 900;
	condition = DIA_Ingmar_PICKPOCKET_Condition;
	information = DIA_Ingmar_PICKPOCKET_Info;
	permanent = TRUE;
	description = "(Es wдre fast unmцglich seine Schriftrolle zu stehlen)";
};

```

```
instance DIA_Oric_PICKPOCKET(C_Info)
{
	npc = PAL_251_Oric;
	nr = 900;
	condition = DIA_Oric_PICKPOCKET_Condition;
	information = DIA_Oric_PICKPOCKET_Info;
	permanent = TRUE;
	description = "(Es wдre verdammt schwierig seine Spruchrolle zu stehlen)";
};

```

таким образом либо там надо "свиток" переименовать в "свиток заклинания", либо тут переименовать "свиток" в "записку", "документ" или что то там еще.

**Comment by dosinabox** [comment]
Принято, переименовано в "(украсть его документ практически невозможно)".

**Comment by Kor-Angar** [comment]
привет. как то поднимал вопрос о том что бы давать бонус за прочтение сворованного документа у Ингмара.. и тут неожиданно обнаружил что в скриптах Готике 2 оригинал идёт двойной опыт за воровство у Ингмара
```
func void dia_ingmar_pickpocket_doit()
{
	if(other.attribute[ATR_DEXTERITY] >= 105)
	{
		b_giveinvitems(self,other,itwr_manowar,1);
		self.aivar[AIV_PLAYERHASPICKEDMYPOCKET] = TRUE;
		b_giveplayerxp(XP_AMBIENT * 2);
		Info_ClearChoices(dia_ingmar_pickpocket);
	}
	else
	{
		AI_StopProcessInfos(self);
		b_attack(self,other,AR_THEFT,1);
	};
};
```
предлагаю эту информацию перепроверить. т.е. это авторский ход или Акелла что то намутила. если авторская история то так  же проверить как обстоят дела в НВ, куда делся этот бонус, т.е. кто его убрал, авторы или локализаторы.

общая мысль такая, что сворованный текст не имеет практического значение, это не материальная ценность, соответственно тогда она должна давать какой то бонус.

**Comment by dosinabox** [comment]
Получилось что-то странное.

Чистый оригинал Г2 (немецкий и Акелла):
**XP_AmbientKap6 * 2**

Чистый оригинал Г2НВ (немецкий и Акелла):
**стандартный прогрессивный опыт за кражу**

Мод для Г2НВ для отключения аддона (немецкий и мой g2_classic):
**XP_AMBIENT * 2**

То есть немецкие модеры решили, что 600 опыта за кражу это слишком жирно и урезали до 50-500 в зависимости от главы. Я это изменение не заметила и оно перешло и в мой мод. Конечно, верну как было в чистом оригинале. Не помешает и проверка - как оно в чистом оригинале 1.30 без модов.

> общая мысль такая, что сворованный текст не имеет практического значение, это не материальная ценность, соответственно тогда она должна давать какой то бонус.

Это пасхалка такая) Вроде уже обсуждали - там переделанный текст песни группы Manowar.

**Comment by dosinabox** [comment]
> Чистый оригинал Г2 (немецкий и Акелла):
> **XP_AmbientKap6 * 2**

Могу ошибаться. Нужна помощь.

**Comment by Kor-Angar** [comment]
> Это пасхалка такая) Вроде уже обсуждали - там переделанный текст песни группы Manowar.

это да. это я понял. я про то что авторы предусмотрели бонус - двойной опыт.


> Могу ошибаться. Нужна помощь.

надо в игре в немецкой версии Готика 2 оригинал  проверить?

**Comment by dosinabox** [comment]
> надо в игре в немецкой версии Готика 2 оригинал проверить?

да, или в Акелле

**Comment by dosinabox** [comment]
> я про то что авторы предусмотрели бонус - двойной опыт.

в любом случае, в аддоне разработчики от него отказались.

**Comment by Kor-Angar** [comment]
в немецкой версии Готика 2  дают двойной опыта. т.е. в первой главе 25*2=50 опыта

**Comment by dosinabox** [comment]
> в немецкой версии Готика 2  дают двойной опыта. т.е. в первой главе 25*2=50 опыта

серьезно? чистый немецкий оригинал 1.30, без модов и патчей?

**Comment by Kor-Angar** [comment]
> в любом случае, в аддоне разработчики от него отказались.

а вот отказались ли? или может просто когда меняли код воровства пропустили.

**Comment by Kor-Angar** [comment]
> серьезно? чистый немецкий оригинал 1.30, без модов и патчей?

чистый немец (1,30). с немецких дисков установленный без русификаторов и чего то там ещё. специально под это дело у меня папочка имеется
![image](https://user-images.githubusercontent.com/49514764/69220010-1b03a100-0b85-11ea-90af-886670e396d4.png)

**Comment by Kor-Angar** [comment]
> в любом случае, в аддоне разработчики от него отказались.

а вот отказались ли? или может просто когда меняли код в аддоне бонус воровства у Ингмара пропустили..

**Comment by dosinabox** [comment]
> чистый немец (1,30). с немецких дисков установленный без русификаторов и чего то там ещё. специально под это дело у меня папочка имеется

Поделись файлом gothic.dat - буду смотреть, откуда тогда взялось 600 опыта в моих декомпилированных скриптах.

**Comment by dosinabox** [comment]
> а вот отказались ли? или может просто когда меняли код в аддоне бонус воровства у Ингмара пропустили..

как знать, как знать...

**Comment by Kor-Angar** [comment]
> как знать, как знать...

вот вот:-) хотелось бы понять как то.  

а можно тебя попросить дать код воровства Ингмара **из оригинальной** Готика 2 НВ.

**Comment by dosinabox** [comment]
```
func void DIA_Ingmar_PICKPOCKET_DoIt()
{
	if(other.attribute[ATR_DEXTERITY] >= 105)
	{
		B_GiveInvItems(self,other,ItWr_Manowar,1);
		self.aivar[AIV_PlayerHasPickedMyPocket] = TRUE;
		B_GiveThiefXP();
		Info_ClearChoices(DIA_Ingmar_PICKPOCKET);
	}
	else
	{
		B_ResetThiefLevel();
		AI_StopProcessInfos(self);
		B_Attack(self,other,AR_Theft,1);
	};
};
```

**Comment by dosinabox** [comment]
Прояснилось. Во всех доступных мне скриптах 1.30 всех языковых версий, а также в немецком моде за кражу у Ингмара дается двойной динамический опыт (XP_AMBIENT * 2).
Оказалось, что фиксированный опыт (XP_AmbientKap6 * 2) дается только в ранней версии мод-фикса для оригинальной Г2 от Desomorphine. Его скрипты затерялись в моей папке с проектами. Перепроверила все изменения своего мода g2_classic - всё правильно, за основу взят чистый оригинал Акеллы, изменений мод-фикса сейчас нет. Поэтому опыт за кражу остается как был в оригинале (XP_AMBIENT * 2), а папку со старыми исходниками мод-фикса я удаляю, чтобы не мешалась.

Теперь, что касается Г2НВ. В обновлении можно восстановить историческую справедливость и вернуть дополнительный опыт за кражу свитка. Однако, предлагаю сделать получение опыта в момент чтения текста, а сам опыт - динамическим наоборот, как было сделано у Гарвелла. Чем раньше ГГ наберет 105 ловкости и сможет ограбить Ингмара, тем больше опыта получит.

**Comment by Kor-Angar** [comment]
>  Однако, предлагаю сделать получение опыта в момент чтения текста, а сам опыт - динамическим наоборот, как было сделано у Гарвелла. Чем раньше ГГ наберет 105 ловкости и сможет ограбить Ингмара, тем больше опыта получит.

по ощущением это 3 глава, может быть и 2 глава, если прям задаться такой целью и максимально прокачиваться. 105 ловкости это много, значит до него будет обворовано уже много НПС и соответственно за воровству у Ингмара дадут опыта 200-250.
![image](https://user-images.githubusercontent.com/49514764/69284629-1e883e00-0c00-11ea-833f-742b95985e55.png)
https://youtu.be/WM9byYr6kd8?t=3791
соответственно за чтение текста можно давать максимум например 250 опыта

надо ещё и необходимое кол-во ловкости для кражи посмотреть. т.е. грубо говоря сделать табличку и посмотреть сколько необходимо  было Ловкости в Готике 2 оригинал и сколько в НВ: у Кассии, Рамиреза, Пирокара, Ватраса, Диего, Декстера, Орик, Парсеваля и Ингмара. что бы увидеть повышалось ли кол-во ловкости необходимое для кражи и если повышалось то насколько.

**Comment by dosinabox** [comment]
Разница в опыте незначительная, поэтому будет просто фиксированные 200.

> посмотреть сколько необходимо было Ловкости в Готике 2 оригинал и сколько в НВ

У Ингмара не менялось - и там и там 105.

**Comment by Kor-Angar** [comment]
Тогда не проще просто давать двойной опыт за воровство?

**Comment by dosinabox** [comment]
Значительно сложнее)
И по моему опыт лучше давать за чтение, когда игрок видит, что украл.
