### ISSUE TITLE
Точки нахождения рыцарей у ратуши смещены

### ISSUE THREAD

**Issue by LDS1** [dosinabox/g2nr_unofficial_update#405]
![Screen Shot 2021-12-08 at 12 36 59 AM](https://user-images.githubusercontent.com/8604295/145116700-ebb8e7bd-1f9d-4226-a84a-c7b2ee6b30fb.jpeg)

**Comment by dosinabox** [comment]
Иногда случается. С точками всё в порядке, с остальным мало что можно сделать.
![Screenshot_1](https://user-images.githubusercontent.com/39790055/145483711-253d486e-6f02-4bdf-a3ca-fdd3cb4acabe.jpg)
