### ISSUE TITLE
NPC не подсвечиваются на близком расстоянии

### ISSUE THREAD

**Issue by LDS1** [dosinabox/g2nr_unofficial_update#409]
Без геймпада.

В зависимости от положения нпс, метре-полуметре может быть мертвая зона, в которой он не подсвечивается для взаимодействия.

Насколько помню, та же ситуация с предметами.

PS  год назад этого бага не было

**Comment by dosinabox** [comment]
А без zHumansRemaster?

**Comment by LDS1** [comment]
Без него только если совсем вплотную встать

**Comment by dosinabox** [comment]
Значит, копать нужно в его сторону

**Comment by LDS1** [comment]
@dosinabox у него гитхаб есть с этим проектом?

**Comment by dosinabox** [comment]
вроде нет
