### ISSUE TITLE
Люди блокируют мечи голыми руками

### ISSUE THREAD

**Issue by LDS1** [dosinabox/g2nr_unofficial_update#413]
Уходящий в блок безоружный NPC блокирует урон от холодного оружия

**Comment by Kor-Angar** [comment]
они всегда его блокировали. с самой первой версии второй части.

**Comment by dosinabox** [comment]
не исправимо на уровне скриптов

**Comment by Kor-Angar** [comment]
можно это можно исправить через юнион на уровне движка.
