### ISSUE TITLE
Смещение текста на высоком разрешении экрана

### ISSUE THREAD

**Issue by LDS1** [dosinabox/g2nr_unofficial_update#415]
Разрешение 2160p. Смещение так же есть в главном меню, имена над персонажами и предметами и тд

![Screen Shot 2021-12-11 at 3 45 25 AM](https://user-images.githubusercontent.com/8604295/145684927-e0019191-ad47-4824-abd7-6541e62e42af.jpeg)

**Comment by dosinabox** [comment]
не имеет отношения к обновлению
