### ISSUE TITLE
Учет временных бонусов при обучении

### ISSUE THREAD

**Issue by LDS1** [dosinabox/g2nr_unofficial_update#427]
Кольцо предводителя орков(-20 силы) не снижает затраты на обучение

Персонаж 90 силы одевает кольцо, итого 70 силы. Обучение все так же стоит 20 очков за 5 поинтов.
Такая же проблема с дубинками бури (-10 одноруч или двуруч).
Раньше кольцо точно позволяло качаться дешевле.

-------------------------------------------------------------------------

Учитель делает проверку не по базовой характеристике, а учитывает бонусы

Приходится раздеваться, чтобы учитель увидел, что может учить.
Пример:
Сила 70(база) + 20(с вещей) => учитель с макс 90 отказвает в обучении.

**Comment by dosinabox** [comment]
> Раньше кольцо точно позволяло качаться дешевле.

Не позволяло. Дубинки и кольцо нужны чтобы качаться свыше лимитов учителей.

> Пример:
> Сила 70(база) + 20(с вещей) => учитель с макс 90 отказвает в обучении.

Другой пример:
Имеем 90 силы и учителя с лимитом 90. Надев кольцо (-20), у него можно прокачаться до 110. Для реализации этой механики учителя учитывают временные бонусы для лимитов, но не для расчета стоимости.
