### ISSUE TITLE
Ватрас без паствы

### ISSUE THREAD

**Issue by Kor-Angar** [dosinabox/g2nr_unofficial_update#43]
Ватрас после того с корабля возвращается в город стоит без паствы. не рассказывает гражданам о том как устроен мир

**Comment by dosinabox** [comment]
Выглядит как баг, но им не является. Разработчики прописали Ватрасу отдельный распорядок дня на случай возвращения - в г2 он просто молится, а в г2нв там появляется Миксир и молятся они по очереди.

**Comment by Kor-Angar** [comment]
гм.. прям отдельная тема про Готика 2 оригинал и Готика 2 Аддон. столько нестыковок вылазит :-)

так может пусть дальше Ватрас рассказывает людям как устроен мир или Миксира убрать что бы он не мешал?

**Comment by dosinabox** [comment]
Миксир и Ватрас теперь по очереди молятся. Можно вместо стояния перед площадью отправлять их на скамейку рядом, но там сидит Рози, если привести её в город. Надо подумать. Собирать паству слишком сложно.

**Comment by dosinabox** [comment]
> - Если Ватрас уходит из команды корабля обратно на площадь, то не конфликтует с распорядком дня Миксира.

**Comment by dosinabox** [comment]
На потом:

```
if(Vatras_SchickeLeuteWeg == TRUE)
{
	B_StartOtherRoutine(VLK_455_Buerger,"VATRASAWAY");
	B_StartOtherRoutine(VLK_454_Buerger,"VATRASAWAY");
	B_StartOtherRoutine(VLK_428_Buergerin,"VATRASAWAY");
	B_StartOtherRoutine(VLK_450_Buerger,"VATRASAWAY");
	B_StartOtherRoutine(VLK_426_Buergerin,"VATRASAWAY");
	B_StartOtherRoutine(VLK_421_Valentino,"VATRASAWAY");
	Vatras_SchickeLeuteWeg = FALSE;
};
```
