### ISSUE TITLE
статуи белиара не отнимает ману

### ISSUE THREAD

**Issue by Kor-Angar** [dosinabox/g2nr_unofficial_update#442]
при пожертвование маны статуям белиара, золото даётся, а мана не отнимается. 

3000 золото за жизни
1000 золото за 0 маны
![20220514004324_1](https://user-images.githubusercontent.com/49514764/168398011-491bbb37-e415-4691-8d7a-8d2e131f8853.jpg)

**Comment by dosinabox** [comment]
Воспроизводится? Есть сохраненка?

**Comment by Kor-Angar** [comment]
Это была новая игра, последняя версия 17:12, 14 мая 2022 г., dosinabox ***@***.***>:
Воспроизводится? Есть сохраненка?

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>
-- Отправлено из мобильного приложения Яндекс Почты

**Comment by dosinabox** [comment]
Амулеты, кольца? Какая статуя? Какой день? Какая глава?

**Comment by Kor-Angar** [comment]
Я до компа дойду и скину сейв. По моему без колец и амулетов. Мана поднята была за счёт бонусов на 4. Глава 1.17:24, 14 мая 2022 г., dosinabox ***@***.***>:
Амулеты, кольца? Какая статуя? Какой день? Какая глава?

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>
-- Отправлено из мобильного приложения Яндекс Почты

**Comment by Kor-Angar** [comment]
1 час 13 минут на стриме https://youtu.be/aGhKu3ex58Q?t=4350

**Comment by Kor-Angar** [comment]
сейв [savegame1.zip](https://github.com/dosinabox/g2nr_unofficial_update/files/8693173/savegame1.zip)

**Comment by Kor-Angar** [comment]
@dosinabox  ты просто проверь. если у тебя в твоей версии работает всё нормально и мана отнимается, то может и проблемы как таковой нет, и это появляется из-за какого то подключенного плагина или мини-мода.

**Comment by Kor-Angar** [comment]
нашёл
```D
	else if(attribute = ATR_MANA_MAX)
```

**Comment by Kor-Angar** [comment]
> нашёл

да, это было оно. теперь работает.

***

а почему компилятор ошибку не выдал?

**Comment by dosinabox** [comment]
А технически это и не ошибка. Но напишу авторам Сурсера, чтобы присвоение в условии считалось ошибкой синтаксиса.

Исправлено.
