### ISSUE TITLE
Дубль / Шмотки влияют на обучение

### ISSUE THREAD

**Issue by Kor-Angar** [dosinabox/g2nr_unofficial_update#45]
Надо понять что со шмотками. или влияют на обучение или не влияют. если не влияют то и кольцо орков будет не работать для прокачки силы со скидкой.

а если работают тогда нужно учитывать и бонусы/штрафы к 1р/2р.

в Готике 2 оригинал эта система работала(штраф от кольца орков и бонус от оружия) при прокачке за ЛП.

в Готике 2 ночь ворона это уже не работало.

**Comment by dosinabox** [comment]
https://github.com/dosinabox/g2nr_unofficial_update/issues/187
