### ISSUE TITLE
B_ENTER_NEWWORLD_Kapitel_5  Salandril

### ISSUE THREAD

**Issue by Kor-Angar** [dosinabox/g2nr_unofficial_update#470]
> Возвращается. Но в 2012 году кто-то поменял проверку расстояния на проверку переменной. Изменение правильное, вот только переменная неправильная) MIS_Serpentes_BringSalandril_SLD == LOG_SUCCESS возможна только для наемников, а значит в обновлении он возвращается только при игре за наемника. Исправлю.

в B_ENTER_NEWWORLD_Kapitel_5  ему можно менять расписание вообще без проверки :-)

**Comment by dosinabox** [comment]
исправлено и загружено вчера

**Comment by Kor-Angar** [comment]
дай пожалуйста ссылку

**Comment by dosinabox** [comment]
https://github.com/dosinabox/g2nr_unofficial_update/commit/09e3da6ca392a69584b6a62d33736caddd3a9d2e

**Comment by Kor-Angar** [comment]
у меня есть предложение для неоф. обновления. по **Salandril**. 

в `DIA_Salandril_KLOSTER_Info` добавить перенос эликсира Ловкости другому торговцу
```D
if (Npc_KnowsInfo(hero,DIA_Salandril_Trank) && Npc_HasItems(self,ItPo_Perm_DEX))
|| !Npc_KnowsInfo(hero,DIA_Salandril_Trank)
{
	Npc_RemoveInvItems(self,ItPo_Perm_DEX,1);
    CreateInvItems(***,ItPo_Perm_DEX,1);
};
```

в качестве другого торговца может быть Лютеро, Цуриус, Константино.

**Comment by Kor-Angar** [comment]
* !Npc_KnowsInfo(hero,DIA_Salandril_Trank) - такое на уровне скриптов не должно произойти, но в игре почему то бывает.
* (Npc_KnowsInfo(hero,DIA_Salandril_Trank) && Npc_HasItems(self,ItPo_Perm_DEX)) - в принципе достаточно проверки на `Npc_HasItems(self,ItPo_Perm_DEX)`

***

общий смысл этого заключается в том что герой может прийти к Саландрилу по миссии и в таком случае может получится так что игрок не выкупит сразу зелье и оно пропадёт после избиения Саландрила. то есть что бы оно не пропало нужно знать что оно у него будет в продаже. появится в продаже после диалога с Хагеным, иметь на него бабки или не выполнять квест по Саландрилу пока не произойдут выкуп.

**Comment by Kor-Angar** [comment]
> возвращается в город в 4 и 5 главе. Видимо, в монастыре штраф дали и простили грехи.

можно в принципе вообще все товары перекинуть в продажу магу огня в монастыре. в таком случае по ЛОРу получится что маги огня у него конфисковала товары в пользу церкви Инноса.

**Comment by Kor-Angar** [comment]
вот такое вот предложение :-)
