### ISSUE TITLE
Ключ от ворот замка Миненталя

### ISSUE THREAD

**Issue by dosinabox** [dosinabox/g2nr_unofficial_update#48]
Сейчас какая-то путаница. Разобраться позже.

**Comment by Kor-Angar** [comment]
может про отменить правки и вернуться к оригинальным условиям?;-)

**Comment by dosinabox** [comment]
Ещё бы точно знать, как было в оригинале...

**Comment by Kor-Angar** [comment]
В оригинале в 5 главе ключ можно было украсть / отобрать у ополченца. Каких то дополнительных условий не было.

**Comment by dosinabox** [comment]
Отменено в связи с переработкой системы воровства:
- Украсть ключ у стражника у главных ворот замка можно только после получения от Торлофа задания открыть эти ворота.
