### ISSUE TITLE
Правки миров // zen

### ISSUE THREAD

**Issue by dosinabox** [dosinabox/g2nr_unofficial_update#49]
Здесь будут перечисляться все найденные косяки миров, а также предложения по улучшению.

**Comment by dosinabox** [comment]
Хоринис (NEWWORLD.ZEN):

- [x] отключенные шипы в тайнике воров срабатывают, если изучена акробатика
- [x] щит в кузнице казармы висит в воздухе
- [ ] сделать новую модель больших щитов
- [ ] повернуть точки для предводителей орков у Ксардаса и около пещеры бандитов Малета
- [ ] сделать кровати в тюрьме, можно взять новую модель коек с цепями
- [ ] модель STARGATE_EDGES.3DS не существует
- [ ] проницаемые книжные стенды
- [x] стенд в казармах без текста - придумать новый или использовать существующий
- [x] стенд в казармах без подписи
- [x] изучить ошибки анализатора (повторные имена точек, пустые объекты и т.д.)
- [x] тарелка в доме Саландрила торчит в шкафу
- [x] за скалой в порту около корабля паладинов очень много объектов
- [ ] открытая решетка тайной комнаты Ксардаса торчит через башню
- [x] исправить все BOOK_BLUE.ASC на динамическую модель, чтобы листались страницы
- [x] шкафы у Неораса торчат друг в друге
- [x] подвинуть точку с ключом в таверне Орлана ближе к краю шкафа или вставлять сам ключ
- [x] заполнить комнату Онара редкими или красивыми предметами, о которых говорит Василий
- [x] заменить картины в тайнике воров на новые уникальные модели
- [x] добавить сундук Сифера и кровать для Бодо
- [x] повернуть паладинов около Альбрехта и Хагена
- [x] сундуки бандитов около Элвриха висят в воздухе
- [x] задействовать рудные жилы
- [x] что-то на полу в доме Эдды и комнате в борделе с Пеком
- [x] всем фонарям города добавить требование факела для зажигания
- [x] проницаемая статуя орка в пещере около города
- [x] незапертый сундук на первом этаже маяка Джека с замком
- [x] незапертый сундук в тайнике воров с замком
- [x] три травы под текстурами у лагеря бандитов за фермой Секоба
- [x] два серафиса у палатки на месте раскопок магов воды
- [x] лечебная трава в долине Лестера (около пещеры с крысами в камнях)
- [x] неправильные названия надгробных плит (см. [комментарий](https://github.com/dosinabox/g2nr_unofficial_update/issues/49#issuecomment-626289878))
- [x] проницаемые шкафы в монастыре
- [x] точка для спауна моллюска за текстурой в скале в гавани
- [x] сундукам на ферме Онара прописана неправильная гильдия GIL_GRD
- [x] царский щавель над пещерой мракориса у маяка немного торчит в земле
- [x] сундук в маяке Джека - починить комбинацию или оставить незапертым как в оригинале?

**Comment by dosinabox** [comment]
Миненталь (OLDWORLD.ZEN):

- [x] стенды в старой башне Ксардаса
- [x] повернуть сундук около пещеры орков за мостом
- [x] WAY: Ladder highpoint error OC_GUARD_FLOOR_UP_02/OC_GUARD_FLOOR_UP_03
- [x] убрать сыр из сундука около Талбина
- [x] задействовать рудные жилы
- [x] vobFarClipZScale=float:20901890
- [x] заменить руну телепорта к проходу на точку для вставки предмета
- [ ] добавить точки FP_ROAM в местах обитания мясных жуков
- [x] переименовать FP_GUARD_OC_THRONE_0* в FP_STAND_OC_THRONE_0*
- [x] добавить точки для отдыха каторжников-рабочих на стене

**Comment by dosinabox** [comment]
Яркендар (ADDONWORLD.ZEN):

- [x] в сундуках Скипа и за домом Фиска - несуществующий предмет itfo_meat (заменить на itfomutton)
- [x] щель в земле около гробницы Куарходрона (закрыта камнем, но лучше поправить меш)
- [x] Марус застревает в котле, когда отходит помочиться
- [x] кривая баночка itpo_littlemana в библиотеке
- [x] добавить служебный сундук для отслеживания версий D36_SECRET_DEV_CHEST
- [x] удалить руну огненной стрелы и добавить точку для вставки другого предмета (FP_ITEM_SWAMP_RUNE_01)
- [x] добавить тексты пустым скрижалям (Use_BookstandMayaCommon_01)
- [x] повторные FP_STAND_MINEGUARD_01 и FP_STAND_MINEGUARD_02
- [x] добавить точки для рабов в домах у золотой шахты
- [x] табак в доме Грега
- [x] приподнять точки для вставки орков у библиотеки
- [x] повернуть и чуть подвинуть BL_DOWN_CENTER_07_B
- [x] заменить стул Скиннера на обычную модель или модель черепа на предмет
- [ ] реализовать падение шатающегося дерева
- [x] разъединить лишнюю связь между точками у башни бандитов и на пляже с огненными ящерами
- [x] приподнять точку FP_ADW_GREGSBOTTLE

**Comment by Kor-Angar** [comment]
Миненталь (OLDWORLD.ZEN):

в старой башне ксардаса нет алхимического стола ;-)

**Comment by dosinabox** [comment]
Если его не было там в Г1, то не должно быть и в Г2.

**Comment by Kor-Angar** [comment]
А на алхимический стол новой башни Ксардаса(где стартует герой) можно добавить минзурку? 😀

**Comment by dosinabox** [comment]
На первом этаже есть.

**Comment by Kor-Angar** [comment]
Всё то ты знаешь 😀 в сундук? 20:50, 6 февраля 2020 г., dosinabox <notifications@github.com>:На первом этаже есть.

—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or unsubscribe.
-- Отправлено из мобильного приложения Яндекс.Почты

**Comment by dosinabox** [comment]
На полках рядом с сундуком. Там ещё факелы и бутылки с водой.

**Comment by Kor-Angar** [comment]
А все равно не хватает минзурки на алхимическом столе 😀

**Comment by dosinabox** [comment]
> Добрый день. Все функции, которые вызываются в Mobsi объектах надо в скриптах прописать заглавными буквами.
> Недавно делал функцию для двери, и пока не написал заглавными буквами, код не работал:confused:
> Например книжные стенды, или triggerscript
> Для простоты, сохрани миры не в скомпилированном варианте.
> В notepad++ делаешь поиск по этим мирам написав scriptFunc=string:
> Сразу будет видно, какие скрипты надо прописать большой буквой.
> Также onStateFunc=string:
> В некоторых mobsi прописано с маленькой буквы - надо исправить на большую.

**Comment by dosinabox** [comment]
Надгробные плиты:

Неиспользуемые:

- MOBNAME_GRAVE_01 "Барон Генрих фон Сталь 551-589 - 'Пришел, увидел и упал замертво'"; _//применено_
- MOBNAME_GRAVE_02 "Бертран 465-480 - 'Я всегда любил есть поганки'"; _//применено_
- MOBNAME_GRAVE_05 "Декс Кантионис 325-431 - 'Я уже несколько дней ничего не ел'"; _//применено_
- MOBNAME_GRAVE_06 "Утар Лайтбрингер 205-532"; _//применено_
- MOBNAME_GRAVE_08 "Онурб 634-579 - 'Дерепан модаз'"; _//применено_

У двух плит одинаковое название (в пещере в долине Лестера и на кладбище за таверной "Мертвая гарпия"):

- MOBNAME_GRAVE_18 "Иотар 721-762" (в пещере надо MOBNAME_GRAVE_08); _//исправлено_

![20200504190703_1](https://user-images.githubusercontent.com/39790055/81494098-aba67880-92ae-11ea-9d74-63a3b7794d0d.jpg)
![20200504190627_1](https://user-images.githubusercontent.com/39790055/81494097-aa754b80-92ae-11ea-8f16-4033c64a03b8.jpg)

Плиты без названий:

- 1 в Яркендаре (большая пещера с ползунами); _//применено MOBNAME_GRAVE_06_
- 1 на Ирдорате (комната рядом с Педро);
- 3 в восточном лесу Хориниса; _//применены MOBNAME_GRAVE_01, MOBNAME_GRAVE_02 и MOBNAME_GRAVE_05_
- 1 у прохода Хориниса (надо MOBNAME_GRAVE_09); _//исправлено_

![20200504204432_1](https://user-images.githubusercontent.com/39790055/81494086-9893a880-92ae-11ea-8fb9-40fd0fc839ba.jpg)
![20200504190147_1](https://user-images.githubusercontent.com/39790055/81494087-99c4d580-92ae-11ea-9999-e894075d63d1.jpg)

**Comment by dosinabox** [comment]
> * 'Дерепан модаз'

Для справки: изначальный перевод Акеллы 'Этлемеркегму красный', но тут всё проще, если посмотреть другие языковые версии и учесть, что русский перевод производился с английского:
'Этлемеркегму красный' (рус.) = 'Etlepmerkegmu red' (англ.) = 'Etlepmerkegmu red' (нем.)

'Etlepmerkegmu red' задом наперед это 'Der umgekrempelte', что в переводе с немецкого значит 'задом наперед' / 'вверх ногами'. Теперь понятно, почему первая дата на плите больше второй. А Онурб - это Бруно.

В общем, при переводе на английский с адаптацией не заморочились, а на русский просто перевели в лоб. А вот поляки молодцы: 'Dózrp an łyt' - 'Tył na przód'.

Но, впрочем, эта надпись в игре всё равно не используется.

**Comment by dosinabox** [comment]
![Screenshot_2](https://user-images.githubusercontent.com/39790055/83284124-f5ff8300-a1e4-11ea-832c-2b3d93050003.jpg)

**Comment by Kor-Angar** [comment]
в хориносе в пещере с гоблинами возле пирамиды сундук без замка визуально выглядит как с замком
![image](https://user-images.githubusercontent.com/49514764/86546383-446b1480-bf3d-11ea-83fb-de34764d70ea.png)

**Comment by dosinabox** [comment]
Неправильный динамический свет:
![Screenshot_1](https://user-images.githubusercontent.com/39790055/87079048-2e579f80-c22e-11ea-992b-89c768163a22.jpg)
![Screenshot_2](https://user-images.githubusercontent.com/39790055/87079054-2f88cc80-c22e-11ea-9b28-dcb4623bcd91.jpg)

**Comment by dosinabox** [comment]
> Я обнаружил, что в Oldworld дохрена объектов имеют
vobFarClipZScale=float:20901890
Когда vobFarClipZScale принимает значения от 0.0 до 1.0
Нужно исправлять. В других мирах все ок.

**Comment by dosinabox** [comment]
<img width="1258" alt="Screenshot_2" src="https://user-images.githubusercontent.com/39790055/99902193-047ab300-2ccd-11eb-9208-da12c1ddb57c.png">

**Comment by Kor-Angar** [comment]
в минентале в разрушенной башни ксардаса если сундук в воде

**Comment by Kor-Angar** [comment]
герой там периодически подвисает после "выхода" из сундука

**Comment by dosinabox** [comment]
Двум книжным стендам в старой башне Ксардаса в Минентале теперь можно прописать тексты. Принимаются предложения.

**Comment by Kor-Angar** [comment]
отсюда ничего не подходит? https://github.com/dosinabox/g2nr_unofficial_update/issues/27

**Comment by Kor-Angar** [comment]
> герой там периодически подвисает после "выхода" из сундука

хотя может это только потому что я из сундука выхожу через вытаскивание оружия

**Comment by dosinabox** [comment]
Именно поэтому. И передвигать этот сундук не хочется, он там удачно спрятан)

**Comment by dosinabox** [comment]
![39510_screenshots_20210202202240_1](https://user-images.githubusercontent.com/39790055/106922884-8bf98f00-671e-11eb-9e63-9f51264b383f.jpg)

**Comment by dosinabox** [comment]
Проблемы мешей:

Хоринис:
<img width="1486" alt="8 (2)" src="https://user-images.githubusercontent.com/39790055/108719495-ad38e880-7530-11eb-9379-863a69ad3392.png">

Яркендар:
<img width="860" alt="45 (1)" src="https://user-images.githubusercontent.com/39790055/108719533-ba55d780-7530-11eb-85c4-041b94dd4d48.png">
<img width="1101" alt="Screenshot_3" src="https://user-images.githubusercontent.com/39790055/108719539-bc1f9b00-7530-11eb-83de-0cb1097d683d.png">
<img width="630" alt="Screenshot_10" src="https://user-images.githubusercontent.com/39790055/108719540-bcb83180-7530-11eb-8890-f6a669109058.png">

**Comment by dosinabox** [comment]
autoCamPlayerMovable = 0 (FALSE)
autoCamPlayerMovable - can the Player move around while the camera is running
1 / TRUE - The player will be able to move
0 / FALSE - The player is motionless

**Comment by Kor-Angar** [comment]
@dosinabox  а у тебя в ярике нет где нибудь заныканной точки откуда можно перейти в Миненталь? 

***
после вчерашних скитаний решил дописать руны телепортации и пока перемещаюсь в Миненталь "тразнитом" через Хоринос :-)

**Comment by Kor-Angar** [comment]
> а у тебя в ярике нет где нибудь

случайно :-)

**Comment by dosinabox** [comment]
> а у тебя в ярике нет случайно где нибудь заныканной точки откуда можно перейти в Миненталь?

нет

**Comment by dosinabox** [comment]
Поиграв в Архолос, появилась мысль на будущее: сделать канализацию Хориниса отдельной локацией с точками загрузки в порту и в подвале гостиницы. Это как минимум улучшит производительность в городе. Что думаешь?

**Comment by Kor-Angar** [comment]
она не такая большая и транзитная. т.е. герой заходит в канализацию (взять квест), город (на квест), канализация(сдать квест). в самой канализации квестов нет и она маленькая. еще в канализации можно поучиться, но получится такая штука что я забегаю туда загрузка мира, бегу к Кассии тренировать ловкость и выбегаю, опять загрузка.

можно храм в котором равен сделать отдельным миром. от этого будет толк так в храм герой идёт единовременно и проводит там много времени. плюс тогда освещение мира не будет влиять(?) на освещение в храме и ночью и днем там будет одинакова темно.(или нет?).

**Comment by Kor-Angar** [comment]
а в Архолесе очень жаль что золотую шахту не сделали отдельным миром :-(

**Comment by Kor-Angar** [comment]
> можно храм в котором равен сделать отдельным миром. от этого будет толк так в храм герой идёт единовременно и проводит там много времени. плюс тогда освещение мира не будет влиять(?) на освещение в храме и ночью и днем там будет одинакова темно.(или нет?).

и лагерь бандитов разгрузит наверное.

**Comment by dosinabox** [comment]
> Это как минимум улучшит производительность в городе.

Это главная задумка, потому что место самое нагруженное в игре. А если не улучшит, то и смысла нет.
Из других плюсов: никого нельзя будет выманить на улицу (и наоборот), запрет на проникновение превращением через потолок, исправление реакций граждан через текстуры (сейчас костыль в восприятиях), ускорение загрузки сохранений в Хоринисе (незначительное).

**Comment by Kor-Angar** [comment]
не знаю, что тут сказать :-)  я понимаю эти плюсы и если бы канализация была полноценной локацией в которое герой проводил хоть какое то время, а не забегал туда на одну минуты я бы был двумя руками за. но учитывая что канализация забежал/убежал и это длится буквально пару минут, то не могу сказать точно да.

но можно думать глобальнее, а если попытаться отделить весь город Хоринос? :-)

**Comment by Kor-Angar** [comment]
> но можно думать глобальнее, а если попытаться отделить весь город Хоринос? :-)

хотя это нереализуемо.

**Comment by dosinabox** [comment]
> плюс тогда освещение мира не будет влиять(?) на освещение в храме и ночью и днем там будет одинакова темно.(или нет?).

Там всё нормально. У самого входа начинается зона с фиксированным освещением:
![Screenshot_1](https://user-images.githubusercontent.com/39790055/148441961-505af272-2d65-4df9-b75e-04c2aee41dcf.jpg)

**Comment by Kor-Angar** [comment]
>  У самого входа начинается зона с фиксированным освещением

и это прекрасно :-)

**Comment by Kor-Angar** [comment]
сундукам можно дать уникальное имена, что бы можно было в случае необходимости делать проверки на уровне скриптов и менять лут:

- [ ] сундук Игарацио
- [ ] сундук Дарона (в доме Зуриуса)
- [ ] сундук в пещере для испытания огня
- [ ]

**Comment by dosinabox** [comment]
> сундук в пещере для испытания огня

MAGICCHEST

**Comment by Kor-Angar** [comment]
конвертируй плиз в дискуссию
