### ISSUE TITLE
Паладины-зомби

### ISSUE THREAD

**Issue by Kor-Angar** [dosinabox/g2nr_unofficial_update#50]
На ирдорате есть два зомби не переодетых в старые доспехи пала

**Comment by dosinabox** [comment]
Вроде бы, это те, которые спаунятся бесконечно при неправильной комбинации кнопок. В связи с этим вопрос: а могут ли быть зомби-паладины бесконечными? Это же единичные случаи, а не низшие миньоны (которых действительно может быть очень много). Много ли паладинов существует в ордене? Много ли паладинов добралось до Ирдората? Много ли погибло и стало нежитью? Ответив на все три вопроса "нет", получается, что зомби-паладинов может быть только ограниченное число, считанные единицы.

**Comment by Kor-Angar** [comment]
я про считанные единицы и говорю. там их два + скелет
https://youtu.be/IlXlw6RtjDg?t=3558 59 минутая

**Comment by Kor-Angar** [comment]
или там они все появляются через один алгоритм и нет разницы между первыми , теми которая при нажатие первой кнопки  и теми которые идут при нажатие неправильной кнопки?

**Comment by dosinabox** [comment]
Неправильной комбинацией можно вызвать только 9 зомби, поэтому они будут переодеты в старые доспехи паладинов.

**Comment by Kor-Angar** [comment]
касательно зомби в замке в Минентале. он получился совсем крепкий, нельзя ли ему снизить броню и довести его до уровня скелета? я Миненталь спокойно проходил с ущербом в 120 и того скелета, что ранее появлялся убивал.

у твоих зомби что ты вставляешь ешь же собственная защита + защита брони. это касается и зомби паладинов. проверь пожалуйста  какая у них общая защита выходит. не забывай про оригинальный баланс, если игрок играет без дополнительно мира и у него не стоит "игнорирование бонусов" при прокачке то ущерб и в Минентале и ущерб на Ирдорате будет не такой высокий. это так же касается и твоих орков-полковников.
