### ISSUE TITLE
Опыт за квесты в зависимости от главы

### ISSUE THREAD

**Issue by Kor-Angar** [dosinabox/g2nr_unofficial_update#51]
Очистка статуй Инноса - Пал

Поддельный Акции - Маг

исходи из того что это квест 1-2 главы. есть там таблиц а в которой я пытался несколько раз обосновано расписать сколько опыта должно начисляться за тот или иной квест:-) 
[ ![image](https://user-images.githubusercontent.com/49514764/74594735-b30d0b80-504a-11ea-9ae3-facf5fd43bbb.png)](https://docs.google.com/spreadsheets/d/1svDbXAiYe7PLCQ7G0Arjh_njRiDabsRC-9GuLt7APsQ/edit#gid=1998166737)

**Comment by Kor-Angar** [comment]
> Возможно, лучше сделать как с Гарвеллом: чем раньше очищаем, тем больше опыта получаем.
> 
> 3 - 150
> 4 - 100
> 5 - 50

Давай. Давай сразу и акции поправим

**Comment by Kor-Angar** [comment]
еще мне очень хочется решить вопрос с опытом в Ярике.
так как разница между 2 главой в Ярике и 3 главой Ярика набегает приличная больше 1000 опыта.

- За прочтение книг в библиотеке Ярика
- За использование телепортов
- за выкапывание сокровищ
- за инфу о Вороне для Сатурасу
- еще за что то.

где то я уже писал эти моменты. этот опыт можно усреднить. давать например (100+150)/2 =125 опыта. Либо давать за одни моменты 100 опыта, а за другие 150.  

мне лично как игроку непринципиально как оно будет так как я всегда ходил во 2 главе в ярик( у нас так принято было с 2004 года было). а в ярик стал в 3 главе ходить в рамках этого обновления что бы в логике авторов разобраться :-)

**Comment by Kor-Angar** [comment]
разобраться в логике авторов не смог, но нашел ответ в затраченном времени в главах. если Ярик весь пройти во 2 главе, то 3 глава получается очень коротка. а если весь ярик перенести на 3 главу, то 2 глава получается маленькая. видимо авторы предполагали что в какой то момент ярик может стать сложным и тогда герой уйдёт в  3 главу по основному сюжету и в 3 главе сможет доиграть Ярик в доспехах Пала/ОНД.
тут в принципе все логично так как для первого прохождения без знания всех бонусов, нычек, оружия и прочего, Ярик может быть достаточно сложен.

**Comment by dosinabox** [comment]
Хотелось сделать с Джо как с инфой для Гарвелла (чем раньше найдем, тем больше опыта получаем), но получается как-то слишком для первой главы.

Сейчас:
1 - 200
2 - 400
3 - 600
4 - 800
5 - 1000

Хочется:
1 - 1000
2 - 800
3 - 600
4 - 400
5 - 200

**Comment by Kor-Angar** [comment]
исходи из того что это квест 1-2 главы. есть там таблиц а в которой я пытался несколько раз обосновано расписать сколько опыта должно начисляться за тот или иной квест:-) 1 глава - 2002 глава - 400 (200+400)/2 = 300 можно просто сделать фиксированные 300 опыта. нашёл в первой главе вместо 200 получил 300. нашёл во второй вместо 400 получил 300 :-) нашёл позже, всё равно получил 300.  Про Джо рассказывает торговец на рыночной площаде. он тоже даёт опыт, если у него спросить о пропавшихСейчас:1 - 502 - 1003 - 1504 - 2005 - 250   15.02.2020, 22:40, "dosinabox" <notifications@github.com>:Хотелось сделать с Джо как с инфой для Гарвелла (чем раньше найдем, тем больше опыта получаем), но получается как-то слишком для первой главы.
Сейчас:
1 - 200
2 - 400
3 - 600
4 - 800
5 - 1000
Хочется:
1 - 1000
2 - 800
3 - 600
4 - 400
5 - 200

**Comment by Kor-Angar** [comment]
исходи из того что это квест 1-2 главы. есть там таблиц а в которой я пытался несколько раз обосновано расписать сколько опыта должно начисляться за тот или иной квест:-) 
[ ![image](https://user-images.githubusercontent.com/49514764/74594735-b30d0b80-504a-11ea-9ae3-facf5fd43bbb.png)](https://docs.google.com/spreadsheets/d/1svDbXAiYe7PLCQ7G0Arjh_njRiDabsRC-9GuLt7APsQ/edit#gid=1998166737)
исходил из такой логики 1 глава - 200, 2 глава - 400, значит (200+400)/2 = 300. 300 можно просто сделать фиксированным. нашёл в первой главе вместо 200 получил 300. нашёл во второй вместо 400 получил 300 :-) нашёл позже, всё равно получил 300.  

Кстати, про Джо рассказывает торговец на рыночной площаде. он тоже даёт опыт, если у него спросить о пропавших
Сейчас:
- 1 - 50
- 2 - 100
- 3 - 150
- 4 - 200
- 5 - 250   

Но это же вовсе не значит что разговор с ним в 1 главе надо давать 250 опыта. или значит?:-)  его бы зафиксировать в размере 50 опыта. ну или 75 :-)

всё сводится к тмоу какая мысль была авторов игры. Я так понял что это было сделано из экономии времени. если это так то всё достаточно просто, если квест 1 главы то фиксируется опыт соответствующей первой главе. если какой-то квест спорный, то ли 2 главы, то ли 3 главы, то среднеарифметическое. и вот таким образом ручками его просто фиксировать. но это мне так видится. 

заметь что самая простая история с квестами 5 главы, там вообще никаких вариантов нет :-) или с НПС которые есть только во 2 главе, например Мильтен, Горн, Диего в Минентале :-) или Горн наём в 3 главе в Хориносе. или Горн ОНД в 4 главе в Минентале. если ориентироваться на них становится намного понятнее сколько и за что давать опыта :-)

**Comment by Kor-Angar** [comment]
таким образом, если этот вопрос пытаться прорабатывать то лучше начать с  конца, т.е. с квестов 4 главы  :-)

**Comment by Kor-Angar** [comment]
опыт за пожертвования Дарона тоже привязан к Главе? :-)
```
	else if((Daron_Spende < 500) && (Bonus_2 == FALSE))
	{
		B_GivePlayerXP(XP_Ambient);
		Bonus_2 = TRUE;
	}
```

**Comment by dosinabox** [comment]
> опыт за пожертвования Дарона тоже привязан к Главе? :-)

Получается, так.

> исходи из того что это квест 1-2 главы.

Ну да. И не хочется, чтобы игроки откладывали его на пятую, чтобы получить больше опыта. Сейчас получается так, что игрока поощряют за то, что он забивает на поиски Джо. А человек может быть в опасности.

С Гарвеллом такое изменение прокатило, потому что там разница в опыте минимальна. А тут разбег аж от 200 до 1000 - или теряешь 800 в пятой, или получаешь 800 в первой (что очень много для этой стадии).

**Comment by dosinabox** [comment]
> А тут разбег аж от 200 до 1000

Возможное решение:

1 - 200 -> 600
2 - 400 -> 550
3 - 600 -> 500
4 - 800 -> 450
5 - 1000 -> 400

**Comment by Kor-Angar** [comment]
> Возможное решение:

плохо решение. не понимаю зачем ты пытаешь в первой главе накачать героя опытом холявным.

авторы игры не подразумевали что герой за  этот квест поучит 1000 опыта. возможность получить за этот квест столько опыта это  следствие работы скрипта.

если мы говорим о авторской логике, то получаемое кол-во опыта привязано к главе. за квесты 1 главы 50 опыта, 2 глава 100 опыта и так далее.

получение большего кол-во опыта или меньшего кол-ва опыта за один и тот же квест это плохая история в целом.

**Comment by Kor-Angar** [comment]
Джо это квест 1-2 главы. опыт за Джо это 200 или 400. среднеарифметическое это 300.

и возможно стоит подумать о том что бы сделать невозможным выполнения это квеста в поздних главах. не может же Джо сидеть там до 4-5 главы :-)

**Comment by Kor-Angar** [comment]
Давай возьмем два одинаковых простых квеста. например про то что у рыбака забирают рыбу и про чувака который стучит по дому.

оба эти квесты доступны с 1 главы. НО за один получаемый опыт привязан к главе игры, а другой нет. 

вопрос: чем они отличаются? в чём разницу? где ошибка? ;-)

**Comment by Kor-Angar** [comment]
const int XP_Addon_FarimSchutz = 50;
const int XP_Addon_Farim_PaladinFisch = 100;

**Comment by dosinabox** [comment]
> и возможно стоит подумать о том что бы сделать невозможным выполнения это квеста в поздних главах. не может же Джо сидеть там до 4-5 главы :-)

Удалять Джо из мира и добавлять в башню модель скелетика?)

В общем, конкретно за Джо ты предлагаешь фиксированные 300 опыта независимо от главы?

**Comment by Kor-Angar** [comment]
> В общем, конкретно за Джо ты предлагаешь фиксированные 300 опыта независимо от главы?

да.я так же предлагаю это и для большинства других квестов :-)
вот даже в позапрошлом году таблицу начал делать
https://docs.google.com/spreadsheets/d/1svDbXAiYe7PLCQ7G0Arjh_njRiDabsRC-9GuLt7APsQ/edit#gid=1998166737

> Удалять Джо из мира и добавлять в башню модель скелетика?)

я бы просто в портовую таверну отправлял его в 3 главе, после освобождения Беннета, так как его  мог кто то и другой выпустить. в конце концов он член организации и они бы наверняка его нашли :-)

**Comment by dosinabox** [comment]
> вот даже в позапрошлом году таблицу начал делать

Знаю, но Джо там нет.

**Comment by dosinabox** [comment]
> я бы просто в портовую таверну отправлял его в 3 главе

Или в тюрьму, потому что его могли найти не воры, а ополчение)

**Comment by Kor-Angar** [comment]
> Или в тюрьму, потому что его могли найти не воры, а ополчение)

Логично. тогда с начало третей главы, в этом момент Пек идёт в казарму ополчения из Барделя и у него как раз ключ от Башни в которой сидит Джо :-)

**Comment by Kor-Angar** [comment]
> Знаю, но Джо там нет.

нету. там что то для начало было набросано, что бы обсудить это и выработать некие правила :-)

**Comment by Kor-Angar** [comment]
я бы точечно начал правки делать по опыту. с 4 главу. и с опыта за квесты в Ярике.

**Comment by Kor-Angar** [comment]
ну **вот хотя бы** для начало в Ярике опыт за

- использование телепортов
- прочтение книг
- выкапывание кладов

я во второй главе когда опыт получаю за это дело прям напрягаюсь, что в 3 главе дают больше :-)

**Comment by Kor-Angar** [comment]
Квесты который можно выполнить в первой главе:

![image](https://user-images.githubusercontent.com/49514764/93693161-ae3e9780-fb04-11ea-9c14-b8f3df8241fc.png)
![image](https://user-images.githubusercontent.com/49514764/93693132-6455b180-fb04-11ea-92c3-1f1633ac6e14.png)
![image](https://user-images.githubusercontent.com/49514764/93693120-37090380-fb04-11ea-8795-a84595ee3e1d.png)
![image](https://user-images.githubusercontent.com/49514764/93693092-d2e63f80-fb03-11ea-96a7-93b2c5316410.png)

**Comment by Kor-Angar** [comment]
квесты которые не выполняет нейтрал в 1 главе
![image](https://user-images.githubusercontent.com/49514764/93693173-ce6e5680-fb04-11ea-8e65-555e5d502a2f.png)

**Comment by Kor-Angar** [comment]
можно поменять  XP_Ambient в файлах

evt_teleportstation_func.d - XP_AmbientKap2
Bookstand_Addon.d - XP_AmbientKap2
DIA_SLD_805_Cord.d -  XP_AmbientKap2
DIA_VLK_422_Salandril.d - XP_AmbientKap3
DIA_VLK_409_Zuris.d - XP_AmbientKap3
DIA_VLK_404_Lutero.d - XP_Ambient3
DIA_VLK_424_Alwin.d - XP_AmbientKap1
DIA_VLK_417_Constantino.d - XP_AmbientKap1
DIA_MIL_337_Mika.d  -  XP_AmbientKap2
DIA_PIR_1301_Addon_Skip_NW.d  -  XP_AmbientKap2



***
DIA_VLK_407_Hakon.d
AI_Output(self,other,"DIA_Hakon_Minenanteil_12_01");	//Извини, но я не могу сказать тебе этого. Это слишком опасно для меня.
	B_GivePlayerXP(XP_AmbientKap3);
***
DIA_NOV_612_Babo.d
(XP_Ambient * 2)  на  (XP_AmbientKap1* 2)
(XP_Ambient) на (XP_AmbientKap3) 
***


https://github.com/Kor-Angar/G2_NotR_Kor_Angar/commit/1ccf818070847119d7d91b569e67f689551eeb0b

**Comment by dosinabox** [comment]
> DIA_VLK_407_Hakon.d
> AI_Output(self,other,"DIA_Hakon_Minenanteil_12_01"); //Извини, но я не могу сказать тебе этого. Это слишком опасно для меня.
> B_GivePlayerXP(XP_AmbientKap3);

Разве "Поддельные акции" нельзя выполнить в 4 главе?


> DIA_NOV_612_Babo.d
> (XP_Ambient * 2) на (XP_AmbientKap1* 2)

Можно получить хоть в 5 главе.

> (XP_Ambient) на (XP_AmbientKap3)

Доступно в 3, 4 и 5 главах.

**Comment by Kor-Angar** [comment]
всё верно, сейчас квест из 1 главы можно как взять так и выполнить в 5 главы и получить 250 опыта так как  переменная динамичная XP_Ambient.

а это тема как раз об обратном.  о том что если квест первой главы, то и опыт за него не должен быть динамический. 

поддельные акции квест 3 главы, получается "автоматически"
задания про Бабо квест 1 главы, доступный только Послушнику
и так далее.

если это править, то править исходя из какой то логики. в прошлом году я делал таблицу в который отмечал в какой главе квест берется, в какой его можно сдать, насколько квест сложен / важен и сомневаясь вручную прописывал опыт. в этом году я выполнил все задания которые можно выполнить в 1 главе, не убивая всех монстров, посмотрел на уровень, оценил баланс и пришёл к выводы что такая ювелирная работа правильна по смыслу но бессмысленная с точки зрения практики и не будет никогда реализована. 
в связи с этим я решил расставить всё по нижней планке, если квест из 1 главы то XP_AmbientKap1 из второй XP_AmbientKap2 и так далее. а потом на уровне скриптов сделать переключалку:
в одном случае XP_AmbientKap1  = 50, а в другом XP_AmbientKap1  = XP_Ambient

таким образом будет возможность получать опыт как в оригинальной игре так и  включить честный расчёт опыта. я это в своей сборке реализуя и потестирую.

**Comment by Kor-Angar** [comment]
даже так? :-)
https://github.com/dosinabox/g2nr_unofficial_update/blob/aed56ebb175bc52740bf908b2ece4ef16490b17d/PrjGOTHIC/Story/Dialoge/DIA_NONE_100_Xardas.d#L581

**Comment by Kor-Angar** [comment]
ну тут точно только 4 глава :-)
![image](https://user-images.githubusercontent.com/49514764/94353334-c1a7b080-0078-11eb-962a-e870e8bb662c.png)

**Comment by Kor-Angar** [comment]
Еще пару правок
https://github.com/Kor-Angar/G2_NotR_Kor_Angar/commit/e811397267b646db69af8ec1278267a13bc3e370

**Comment by Kor-Angar** [comment]
> на уровне скриптов сделать переключалку:
> в одном случае XP_AmbientKap1 = 50, а в другом XP_AmbientKap1 = XP_Ambient

https://github.com/Kor-Angar/G2_NotR_Kor_Angar/commit/09d4f4077c683da5dcf28b04c51656d087944cf3

вроде работает.
https://www.youtube.com/watch?v=5UsuDMJdrtI

завтра поправлю оставшиеся XP_Ambient  и можно будет смело начинать новое прохождение

**Comment by Kor-Angar** [comment]
первые правки
https://github.com/Kor-Angar/G2_NotR_Kor_Angar/commit/1ccf818070847119d7d91b569e67f689551eeb0b

второй массив правок
https://github.com/Kor-Angar/G2_NotR_Kor_Angar/commit/e811397267b646db69af8ec1278267a13bc3e370

третья порция правок (28,09,2020)
https://github.com/Kor-Angar/G2_NotR_Kor_Angar/commit/2cc56e5b08b62557cfe6bf62f28a622bc91e407d

теперь вроде всё, XP_Ambient был побеждён как класс :-) остались только  которые стали динамическими :-)
```
XP_AmbientKap1;
XP_AmbientKap2;
XP_AmbientKap3;
XP_AmbientKap4;
XP_AmbientKap5;
XP_AmbientKap6;
```
есть так же  возможность включить / выключить динамическое начисление опыта, 
https://github.com/Kor-Angar/G2_NotR_Kor_Angar/commit/09d4f4077c683da5dcf28b04c51656d087944cf3
т.е. за квест 1 главы XP_AmbientKap1 (например разговор с Ксардасом о табличке) [можно получить 150 опыта в 3 главе](https://www.youtube.com/watch?v=5UsuDMJdrtI). или за поддельные акции XP_AmbientKap3 получить 250 опыта в 5 главе и т.д.

в практическом плане это хорошо для каких то игроков которых чувство жадности заставляло переносить сдачу квестов на поздние главы. в принципе эту задачу оно и должно было решать в конечном счёте :-)
возможно конечно где то в правках мною было допущены ошибка и квест 1 главы я пометил неосознанно XP_AmbientKap2 но это человеческий фактор, такое можно выявить/исключить только коллективным трудом.

**Comment by Kor-Angar** [comment]
единственно что не получилось мне разделить за нычки Грега в Хориносе (первая глава) и Ярике (вторая-третья главы). можно было что то сочинить, но я решил что это излишне и просто сделал XP_AmbientKap2.

upd 
так и оказалось :-) Мика
https://github.com/Kor-Angar/G2_NotR_Kor_Angar/commit/0872cb769ca025f500b61a32ccb5446f143da748

**Comment by Kor-Angar** [comment]
Прошёл так игру  не сколько раз. Никакого дисбаланса не обнаружил.
