### ISSUE TITLE
Кольца к Силе

### ISSUE THREAD

**Issue by Kor-Angar** [dosinabox/g2nr_unofficial_update#52]
я тут логику попытаюсь расписать. не уверен что получится но как намётка для темы

Готика 2 -- > Готика 2 НВ
Кольцо силы +5 -- > Кольцо силы +3   / валяется возле ворот Хориноса
Кольцо силы +5 -- > Кольцо силы +3  / валяется в пещере в Минентале
Кольцо ловкости +5 -- > Кольцо ловкости +3 / даёт Ватрас на выбор
Кольцо ловкости +10 -- > Кольцо ловкости +5 / валяется за старой Башней Ксардаса
**************
в НВ добавили еще 

- два кольца к ловкости +5 (в продаже в Хориносе и Ярике)
- одно кольцо к силе +5 (в продаже в Ярике)
- одно кольцо к силе +4 и ловкости +4 (в продаже в Хориносе), 3 глава

Готика 2 классик максимальный бонус от шмоток к Ловкости +30, к Силе +25
Готика 2 НВ максимальный бонус от шмоток к Ловкости +30, к Силе +29

сейчас в НВ 3 кольца к ловкости +5 и всего одно к силе +5.

**Comment by Kor-Angar** [comment]
вообщем всё вот это я пишу к том что бы добавить еще одно кольцо к силе +5, например в продажу кузнецу Беннету, так как сейчас в НВ 3 кольца к ловкости +5 и всего одно к силе +5.

**Comment by dosinabox** [comment]
> добавить еще одно кольцо к силе +5, например в продажу кузнецу Беннету

В какой главе?

**Comment by Kor-Angar** [comment]
Можно в первой. Можно во второй

**Comment by Kor-Angar** [comment]
А по колечку как? Добавляем, не добавляем? :-)
