### ISSUE TITLE
Убийство Дракона во 2 главе

### ISSUE THREAD

**Issue by Kor-Angar** [dosinabox/g2nr_unofficial_update#55]
Мы там на стриме вопрос по дракону поднимали. можно сделать его убийство опциональным? хочу попробовать его убить во второй главе и посмотреть что из этого получится в 4 :-)

**Comment by dosinabox** [comment]
Опциональной настройкой нельзя. Можно пересобрать скрипты под себя (заменив у дракона флаг NPC_FLAG_IMMORTAL на 0) и начать новую игру или убить его читом.

**Comment by Kor-Angar** [comment]
а как же тогда через скрипты у него меняется флаг в 4 главе?

**Comment by dosinabox** [comment]
При диалоге. А для диалога нужен Глаз Инноса. Опять же, ничего не мешает убить его читом когда захочется и проверить что нужно.
