### ISSUE TITLE
Гильдия воров и воровство

### ISSUE THREAD

**Issue by Kor-Angar** [dosinabox/g2nr_unofficial_update#56]
Может сделать возможность украсть у Андре пакет травы который сдаёт ГГ мент? :-)

**Comment by dosinabox** [comment]
Я против. Лучше попробовать добавить где-нибудь в казармах охраняемый сундук, куда будут добавляться конфискованные предметы. Нужно поэкспериментировать.

**Comment by Kor-Angar** [comment]
Там вроде есть сундук, там где тюрьма и мент.

Кстати конфскат кто продавать будет? Пек? 🙂

**Comment by dosinabox** [comment]
> Кстати конфскат кто продавать будет? Пек?

Это нужно тщательно продумать и проверить. Думаю, да, Пек. Но не думаю, что это вообще обязательно.

**Comment by dosinabox** [comment]
Нужна проверка. Попробуй **неудачно** украсть ключ у Горакса, заплатить штраф и начать торговлю с ним. Будет ли в продаже ключ?

**Comment by Kor-Angar** [comment]
Так ключ у Горкаса который воруются от сокровещницы. А тот что в продаже от Монастыря. Или я не про то?

**Comment by dosinabox** [comment]
Вот и посмотреть надо - что появится в продаже при неудачной краже (в обновлении г2нв).

**Comment by Kor-Angar** [comment]
А у него этот ключ отобрать можно?

**Comment by dosinabox** [comment]
Это тоже должно выясниться при проверке.

**Comment by Kor-Angar** [comment]
> Вот и посмотреть надо - что появится в продаже при неудачной краже (в обновлении г2нв).

при неудачной краже ключ от сокровищницы появляется в продаже
![image](https://user-images.githubusercontent.com/49514764/64740119-f17f2700-d4fc-11e9-8dd9-f7274eaac5ba.png)

https://www.youtube.com/watch?v=A3Y7UPdnlKk&feature=youtu.be

а зачем у Горакса изъяли из продажи ключ от монастыря?  как теперь герою выбираться из монастыря?:-)

**Comment by dosinabox** [comment]
> при неудачной краже ключ от сокровищницы появляется в продаже

Спасибо, исправлю.

> а зачем у Горакса изъяли из продажи ключ от монастыря? как теперь герою выбираться из монастыря?:-)

А нечего забираться) Борьба (не моя) с абьюзами и получитерскими механиками. Разработчики сделали бы так же.

**Comment by Kor-Angar** [comment]
у послушника Дуриана есть свиток "сон", можно сделать возможность украсть у него. а можно и не делать  :-)

**Comment by Kor-Angar** [comment]
Сделать возможность у Хуана в Ярике украсть мешочек перца, вместо золота(?) которое идёт сейчас.

Сейчас без торговли с Хуаном теряется только мешочек с перцем. Если сделать возможность красть этот мешочек то Хуана можно будет убивать до разговора с Томом(?). 

В оригинальной игре Хуан же торговал с ГГ без каких то условий?

**Comment by Kor-Angar** [comment]
может Джесперу добавить "знак вора" и через это давать квест про сундук Фингерса?

**Comment by dosinabox** [comment]
Что должно происходить, если ГГ вступил в гильдию воров и сдал Халвора, Нагура и/или Ренгару?

**Comment by Kor-Angar** [comment]
Запости плиз сюда правила которые рассказывает Кассия

**Comment by dosinabox** [comment]
```
func void DIA_Cassia_Regeln_Info()
{
	AI_Output(other,self,"DIA_Cassia_Regeln_15_00");	//Что у вас за правила?
	AI_Output(self,other,"DIA_Cassia_Regeln_16_02");	//Первое правило: никому ни слова о нас. Никогда.
	AI_Output(self,other,"DIA_Cassia_Regeln_16_03");	//Второе: не попадайся.
	AI_Output(self,other,"DIA_Cassia_Regeln_16_04");	//Третье: если ты обнажишь оружие здесь, чтобы напасть на кого-нибудь, мы убьем тебя.
	AI_Output(self,other,"DIA_Cassia_Regeln_16_05");	//И четвертое - последнее правило: тот, кто хочет присоединиться к нам, должен доказать серьезность своих намерений.
};
```

**Comment by Kor-Angar** [comment]
Значит это не нарушение правил :-)

**Comment by Kor-Angar** [comment]
> Что должно происходить, если ГГ вступил в гильдию воров и сдал Халвора, Нагура и/или Ренгару?

ты хочешь что бы Кассия убила героя? или потребовала что бы он заплатил "штраф"? :-)

**Comment by Kor-Angar** [comment]
если сдать гильдию воров Андре, то не получится с трупов снять шпаги мастеров

**Comment by Kor-Angar** [comment]
Мне первый раз за все время игры удалось обокрасть Бладвина 😎

Про то что Бладвина нельзя обокрасть я уже писал несколько лет 😀

Оказывается можно, если с ним поговорить, потом усыпить, а потом разбудить и обокрасть 😀

**Comment by Kor-Angar** [comment]
> а как проверить есть ли навык воровства у героя?

```
if(!Npc_GetTalentSkill(other,NPC_TALENT_PICKPOCKET) || (self.aivar[AIV_PlayerHasPickedMyPocket] == TRUE) || (other.attribute[ATR_DEXTERITY] < x))
```
Это условие "ГГ не обучен воровству" **или** "ГГ уже обокрал собеседника" **или** "у ГГ мало ловкости для диалога воровства", где x это требование к краже из return C_Beklauen минус 10.

**Comment by dosinabox** [comment]
> - Диалог с Рамирезом о секстанте доступен не со второй главы, а после принятия в гильдию воров.
> - Диалог с Джеспером о закрытой комнате доступен не с третьей главы, а после принятия в гильдию воров.

Наверное, всё же неудачные правки. Лучше их отменить, как думаешь?

**Comment by Kor-Angar** [comment]
почему неудачные? можно привязать эти диалоги к знаку вора. вот герой узнал вора, вот он им показал знак вора и произошло событие, они дали квест.
