### ISSUE TITLE
Пожертвования Дарону

### ISSUE THREAD

**Issue by Kor-Angar** [dosinabox/g2nr_unofficial_update#58]
сейчас в пожертвованиях есть варианты

- 50
- 100
- 200
- нет бабла 
- назад

"нет бабла" и "назад" выполняют одно и то же действие

вчера  обратил внимание что  в классик варианты "нет бабла" и "назад" объедены в один
![image](https://user-images.githubusercontent.com/49514764/64488626-cb365e80-d252-11e9-94d3-d69ab65034bc.png)

**Comment by dosinabox** [comment]
Вариант "НАЗАД" заменен на "Я должен еще подумать", добавлена реплика ГГ.

**Comment by Kor-Angar** [comment]
Так теперь сколько вариантов 4 или 5?

**Comment by dosinabox** [comment]
- 200
- 100
- 50
- Но у меня недостаточно золота...
- Я должен еще подумать.

> "нет бабла" и "назад" выполняют одно и то же действие

На самом деле вариант "Но у меня недостаточно золота..." не приводит к выходу из диалога, а только воспроизводит эти две реплики:
```
AI_Output(other,self,"DIA_Daron_Spende_BACK_15_00");	//Но у меня недостаточно золота...
AI_Output(self,other,"DIA_Daron_Spende_BACK_10_01");	//Это не имеет значения, сын мой. Ты можешь принести пожертвование позже.
```
