### ISSUE TITLE
"Где Пек". 3 глава

### ISSUE THREAD

**Issue by Kor-Angar** [dosinabox/g2nr_unofficial_update#59]
что происходит с квестом "Где Пек" в 3 главе? Диалог про меч у пека остаётся?

**Comment by dosinabox** [comment]
Пишу, как в обновлении Г2НВ.

> что происходит с квестом "Где Пек" в 3 главе?

Пек сам возвращается в казармы с началом третьей главы. Говорим с ним, говорим Андре "Мне удалось найти Пека", а он отвечает ополченцу:

> Я даже задавался вопросом: осмелишься ли ты появиться здесь?!
> Ты глубоко разочаровал меня!

И паладину:

> А я-то думал, где ты был все это время!
> С этого времени ты должен докладывать непосредственно лорду Хагену. Иди, поговори с ним.

Квест помечается как проваленный.


> Диалог про меч у пека остаётся?

Да. Он даст ополченцу Рубиновый клинок:

> Хорошо, что ты спросил. Нам досталось несколько очень хороших клинков от наемников Онара.
> Они им больше не понадобятся. (грязный смех)
> Вот, возьми.

**Comment by Kor-Angar** [comment]
`Да. Он даст ополченцу Рубиновый клинок`

а в оригинале какие условия на Рубиновый клинок? он даёт его в любом случае?

**Comment by dosinabox** [comment]
**Сдаем** Пека - получаем **ItMw_1h_MISC_Sword** и на этом всё.
**Покрываем** Пека - получаем **ItMw_Schwert1** - ждем третьей главы - получаем **ItMw_Rubinklinge**.
**Забиваем** на Пека - ждем третьей главы - проваливаем квест - получаем **ItMw_Rubinklinge**.

**Comment by dosinabox** [comment]
> а в оригинале какие условия на Рубиновый клинок? он даёт его в любом случае?

В оригинале Пек дает **ItMw_Rubinklinge** в третьей главе, если ГГ покрыл его перед Андрэ и получил **ItMw_Schwert1** ранее.
В оригинале возможность получить **ItMw_Rubinklinge** в третьей главе блокировалась, если ГГ не получил **ItMw_Schwert1** ранее. В обновлении ГГ сразу получит **ItMw_Rubinklinge** в третьей главе (пропуская **ItMw_Schwert1**), если покрыл Пека перед Андрэ.

**Comment by dosinabox** [comment]
> **Забиваем** на Пека - ждем третьей главы - проваливаем квест - получаем **ItMw_Rubinklinge**.

Вот в этом случае нужно что-то другое давать. Что-то хуже **ItMw_Rubinklinge** (потому что Пек вернулся в казармы сам и ГГ ничего не докладывал Андрэ), но лучше **ItMw_Schwert1** (потому что в нем нет смысла в третьей главе).

**Comment by dosinabox** [comment]
Предлагаю давать ГГ улучшенное оружие не только в третьей главе, но и при выполнении условий по покупке тяжелых доспехов ополчения.

**Comment by Kor-Angar** [comment]
> Предлагаю давать ГГ улучшенное оружие не только в третьей главе, но и при выполнении условий по покупке тяжелых доспехов ополчения.

там контекст есть: ItMw_Rubinklinge  Пек отжал у Беннета(3 глава). в тоже время покупка тяжелого доспеха подразумевает что ГГ нашёл Пека в 1 или 2 главе и уже получил от него ItMw_1h_MISC_Sword  или ItMw_Schwert1 

если хочешь дать плюшку за покупку доспеха, то Пек теоретически может отдать ГГ ключ от центровой башни где лежит супер молоток, но на это нет подходящей фразы. Сейчас этот ключ у него можно украсть или отобрать.

**Comment by dosinabox** [comment]
Не совсем это имела в виду. Если ГГ уже может купить улучшенный доспех, значит, дослужился до определенного ранга в ополчении. Значит, заслуживает и новое оружие. Иначе получится странно: доспех Пек продаст, а на просьбу о новом оружии пошлет. Надо подумать, но в целом неважно.

**Comment by dosinabox** [comment]
Какие товары мог бы продавать Пек? 
- амулет Кантара
- косяки Борки
- тюк травы
- ?
