### ISSUE TITLE
Стража не пускает ГГ в город из-за преступлений

### ISSUE THREAD

**Issue by Kor-Angar** [dosinabox/g2nr_unofficial_update#60]
стража (ополчение) не пускает ГГ в город когда он совершил преступление, нужно давать взятку в 100 золотых.

хотел уточнить это касается всех фракций? и мента, мага, пала?

**Comment by dosinabox** [comment]
> хотел уточнить это касается всех фракций? и мента, мага, пала?

Да.

**Comment by Kor-Angar** [comment]
отсюда вытекает вопрос, а нормально что Мага/Пала менты не пускают в город?:-)

**Comment by dosinabox** [comment]
Нормально, потому что в верхний квартал тоже не пускают)

**Comment by Kor-Angar** [comment]
Ну с верхним кварталом то понятно, там палы стоят 🙂

**Comment by Kor-Angar** [comment]
не успел написать. суть взятка. там 100 получается что Пал/Маг даёт взятку в 100 золотых. По идеи такое не должно происходить. а не пускать их в город тоже странно, так как это вроде как не их ума дела.

в целом то это не проблема так герой к тому времени телепортируется. маг опять же может скаставать страх, что бы дойти до Андре и заплатить штраф.

**Comment by Kor-Angar** [comment]
В этот раз играл и Мага в городьпускали, а в верхний квартал пускали :-)
