### ISSUE TITLE
Информации по молитвам

### ISSUE THREAD

**Issue by Kor-Angar** [dosinabox/g2nr_unofficial_update#61]
возможно ли где то в дневнике сделать информацию по молитвам. например когда молился ГГ и что получил? 

молитвы вещь такая муторная, не знаю как другие, а я их осуществляю в несколько заходов. и иногда путается в голове это дело что давал Иннос/Белиар, а чего не давал  :-)

**Comment by dosinabox** [comment]
Возможно. Набросай примерный формат, как это должно выглядеть.

> День 1 - молитва за A золотых. Получен бонус: B.
> День 2 - молитва за C золотых. Получен бонус: D.

**Comment by Kor-Angar** [comment]
- День 1, Помолился Инносу/Белиару и пожертвовал x золота/здоровья/маны, Иннос/Белиар даровал 1 силу/ловкость/здоровье/ману.
- День 1, Пожертвовал Инносу/Белиару x золота/здоровья/маны, Иннос/Белиар даровал 1 силу/ловкость/здоровье/ману.
- День 1, Молился Инносу/Белиару и пожертвовал x золота/здоровья/маны, Иннос/Белиар даровал 1 силу/ловкость/здоровье/ману.

**Comment by Kor-Angar** [comment]
Гильдию наверное тоже надо указывать? или не надо?

**Comment by dosinabox** [comment]
Думаю, надо.

**Comment by Kor-Angar** [comment]
День 1. Будучи ополченцем, молился Инносу/Белиару и пожертвовал x золота/здоровья/маны, Иннос/Белиар даровал 1 силу/ловкость/здоровье/ману.

**Comment by Kor-Angar** [comment]
а как нейтрала назвать? :-) странник? оборванец? :-)

**Comment by dosinabox** [comment]
Думаю, нужно вообще исключительно техническая информация, как у кражи. Не "сегодня солнечным днем я ограбил Лемара", а "Лемар - кража удалась".

> День: 1, гильдия: без гильдии, молитва Инносу, пожертвование: нет, бонус: нет.

**Comment by dosinabox** [comment]
Наверное, можно даже без звука добавления в дневник и без надписи на экране.

**Comment by Kor-Angar** [comment]
> Наверное, можно даже без звука добавления в дневник и без надписи на экране.

можно попробовать и так и так. посмотреть как в игре смотреться будет. без записи в дневник игроки не узнают о том что это инфа есть в дневнике.

с другой стороны это вообще не принципиально

**Comment by Kor-Angar** [comment]
в Готике 1 по моему много было информации в дневнике. надо будет посмотреть как она организованна

**Comment by Kor-Angar** [comment]
А эту штуку реализовали? *😀

**Comment by dosinabox** [comment]
https://github.com/dosinabox/g2nr_unofficial_update/issues/107
