### ISSUE TITLE
Настройка неофициального Мода

### ISSUE THREAD

**Issue by Kor-Angar** [dosinabox/g2nr_unofficial_update#63]
Ты кажется хотела настройки воткнуть в статую Белиара?

**Comment by dosinabox** [comment]
Да. Как думаешь, хорошая идея? Или лучше оставить только с помощью читов?

**Comment by Kor-Angar** [comment]
Идея отличная👍

**Comment by dosinabox** [comment]
> Идея отличная👍

А мне не нравится, погружение нарушает)
Можно ограничить доступ через статуи первым днем, а далее пускать только читами через помощника.

**Comment by Kor-Angar** [comment]
можно сделать доступ одноразовый. 

Про погружение это конечно да, но мод как то надо настраивать. Через помошника мне кажется для большинства будет не очевидно

**Comment by dosinabox** [comment]
> для большинства будет не очевидно

Может, это и хорошо)

**Comment by Kor-Angar** [comment]
> Может, это и хорошо)

ну как сказать :-)  а как же люди которые скачали обновления под стим версии и которые вообще далеки от форумов и всего такого? ;-) а тут есть вероятность что они это увидят и проявит интерес: что то включать, что то выключат. смогут ходить без шлема :-)

с точки зрения ЛОРа игры за баланс отвечает Аданос. Но делать настройки мода у НПС, будьте то  Ватрас или Ксардас это вообще как то стрёмно. статуя Белиара это меньшее из возможных зол.

**Comment by dosinabox** [comment]
> а как же люди которые скачали обновления под стим версии и которые вообще далеки от форумов и всего такого? ;-)

Ну вот за них и опасаюсь больше всего. Подойдет такой новичок, впервые запустивший игру, к статуе в самом начале игры, а там куча настроек. Не разберется и сломает что-нибудь. Или психанет, что отсебятину подсунули, и всё удалит.

**Comment by dosinabox** [comment]
> Не разберется и сломает что-нибудь.

Например, включит "прохождение без аддона" и пропустит огромный кусок контента.
Например, включит "прохождение нейтралом" и пойдет по потенциально нарушенному сюжету.
Нужно просто грамотно описать возможности помощника в теме на форуме и в readme с перечнем изменений. Тогда можно оставить только через читы.

**Comment by Kor-Angar** [comment]
а ведь настройку неоф обновления можно перенести в книгу реализовав диалог.
это будет очень круто так как в книге можно показывать активные настройки + краткое описание а в диалоге  тут же сделать переключатель.  плюс это реализовать достаточно нетрудоёмко. предлагаю подумать.
