### ISSUE TITLE
Учет фактически существующих в команде

### ISSUE THREAD

**Issue by dosinabox** [dosinabox/g2nr_unofficial_update#64]
вообщем с правками что Марио и Гирион не считается мы опять сломали логику авторов. Марио и Гирион должны учитываться как в оригинальных скриптах, так как дело не только в максимальном кол-ве членов экипажа, но и в **минимальном**.

а так будет получится что герой взял капитана + 5 человек(учитывая Марио и Гириона) а уплыть не может. И капитан при этом будет говорит что ему надо пять человек.

_Originally posted by @Kor-Angar in https://github.com/dosinabox/g2nr_unofficial_update/issues/37#issuecomment-527284545_

**Comment by dosinabox** [comment]
Готово, нужно будет проверить.

**Comment by dosinabox** [comment]
> Ли не дал опыта когда я позвал его на корабль

Исправлено (добавлено?).

**Comment by Kor-Angar** [comment]
там не только Ли. надо всю команду перепроверить

**Comment by dosinabox** [comment]
На самом деле всё интереснее. Опыт за любого члена команды дается только если сразу взять их в команду. Если брать время на подумать, то не дается. На примере Ли:
**Пакуй свои вещи!** - опыт есть
**Я дам тебе знать, если ты мне понадобишься.** -> **Ты мне все-таки нужен!** - опыта нет
Так же со всеми остальными.

**Comment by dosinabox** [comment]
На примере Диего:
**Почему бы тебе не отправиться в путь со мной? Встретимся в гавани.** - опыт есть
**Возможно, я дам тебе знать, когда придет время.** -> **Возвращайся. Я хочу, чтобы ты сопровождал меня.** - опыта нет

**Comment by dosinabox** [comment]
На примере Ангара:
**Иди в гавань. Встретимся там.** - опыт есть
**Возможно, я обращусь к тебе позже.** -> **Возвращайся на борт.** - опыта нет

**Comment by Kor-Angar** [comment]
гм.. может так было задумано? 

а с капитаном как? :-)

**Comment by dosinabox** [comment]
Думаю да, похоже на обдуманное решение.
А опыт за капитана дается только тогда, когда он становится капитаном, а других взять уже нельзя.

**Comment by Kor-Angar** [comment]
Может просто давать в два раза меньше опыта?

**Comment by dosinabox** [comment]
за что и почему?

**Comment by Kor-Angar** [comment]
> Думаю да, похоже на обдуманное решение.

а может потому что  **Возвращайся на борт.** - опыта нет, так как подразумевается что Герой взял его на борт, получил опыт, отказался от него и теперь повторно берет не борт.

?

**Comment by dosinabox** [comment]
Ну, можно (и, наверное, нужно) фразы менять. С опытом не знаю как быть.

**Comment by Kor-Angar** [comment]
> Фразы, если персонаж не был в команде:

так в этом случае опыт будет доваться ?

**Comment by Kor-Angar** [comment]
> Фразы, если персонаж не был в команде:

так в этом случае опыт будет даваться ?

> С опытом не знаю как быть.

можно на форуме спросить. может подскажут

**Comment by dosinabox** [comment]
> так в этом случае опыт будет даваться ?

Пока нет. Спорно.

**Comment by Kor-Angar** [comment]
> Пока нет. Спорно.

чисто теоретически я могу за всю команду получить 0 опыта. это не спорно, это не нормально ;-)

**Comment by dosinabox** [comment]
Твое предложение - полный опыт при откладывании вопроса или половина?

**Comment by Kor-Angar** [comment]
раньше я сомневался, думал что это авторская задумка,  и в качестве "штрафа" предложил половину опыта.

НО после того как ты сделала фразы 
- Фразы, если персонаж был в команде:
- Фразы, если персонаж не был в команде:

стал склоняюсь к мысли что Пираньи просто неучли такой вариант, когда герой не сразу скажет "да" или "нет", а по сути возьмет время подумать и потом скажет "да".
таким образом теперь получается три варианта:

- сразу да
- подумал и да 
- нет

у капитана на самом деле такая же история. можно сразу сказать "да", а можно взять паузу, подумать, а потом сказать "да". но при этом опыт дают в любом случае :-)

ситуация очень редкая, за сотни прохождений, я её "ловил" буквально пару раз.


я предлагаю эту тему помусолить на форуме.

**Comment by Kor-Angar** [comment]
но отсюда вытекает новый вопрос: 
если я возьму к примеру 5 человек, возьму опыт c них, а потом их выгоню. 
потом возьми других пять, возьму опыт и их выгоню. и так далее и так далее.

таким образом я получу сверх положенного опыта? т.е. получу опыт не за фактическое членов команды.

**Comment by dosinabox** [comment]
это и в оригинале можно сделать

**Comment by dosinabox** [comment]
получается такой квест "найди всех друзей")

**Comment by Kor-Angar** [comment]
так может быть сделать счётчик и после того как герой получит опыт за такое то кол-во человек, больше опыта не давать?

**Comment by Kor-Angar** [comment]
> получается такой квест "найди всех друзей")

если взять всех НПС из Готики 1 будет еще одно лишнее место ;-)

**Comment by dosinabox** [comment]
> так может быть сделать счётчик и после того как герой получит опыт за такое то кол-во человек, больше опыта не давать?

По-моему, это лишнее. Опыт дается за дело: обойти две карты и перебрать кучу человек. Опыт в обмен на игровое время это нормально.

**Comment by Kor-Angar** [comment]
гуд

**Comment by dosinabox** [comment]
Фух, готово. Нужно **очень** тщательно проверить, потому что многое пришлось перелопатить. В идеале вообще всех возможных соратников перебрать, с присоединением и отсоединением. Посмотреть, кто когда обижается, кто когда атакует. Как опыт дается. Записи в дневнике. Озвучка реплик, субтитры и строки диалогов. Перемещения в гавань и на корабль.
[g2a_nr_scriptpatch_v22_hotfix_10.10.zip](https://github.com/dosinabox/g2nr_unofficial_update/files/3714250/g2a_nr_scriptpatch_v22_hotfix_10.10.zip)
Новая игра не нужна.

**Comment by Kor-Angar** [comment]
> Фух, готово. Нужно очень тщательно проверить, потому что многое пришлось перелопатить. В идеале вообще всех возможных соратников перебрать, с присоединением и отсоединением. Посмотреть, кто когда обижается, кто когда атакует.

вроде проверял. давай всех разгоню и попробую опять собрать. напиши кого несколько раз нужно выгнать(Ли?, Волк?), что бы они окончательно обиделись на героя :-)

**********
Ссылки по теме
https://github.com/dosinabox/g2nr_unofficial_update/issues/193
https://github.com/dosinabox/g2nr_unofficial_update/issues/122
https://github.com/dosinabox/g2nr_unofficial_update/issues/38
https://github.com/dosinabox/g2nr_unofficial_update/issues/37

**Comment by Kor-Angar** [comment]
таки [несмог уплыть ](https://youtu.be/KLzt9TrjFNc?t=5983) :-D

- [x] - Мильтен (бессмертный) в команде
- [ ] - Лестер (бессмертный) ушел в отказ
- [x] - Диего (бессмертный) в команде
- [ ] - Ли (бессмертный) ушел в отказ
- [x] - Беннет (бессмертный) в команде
- [ ] - Ларес (бессмертный) ушел в отказ
- [ ] - остальные НПС погибли

Сейв
https://yadi.sk/d/8UGOonInboMuGg

**Comment by Kor-Angar** [comment]
может добавить возможность вернуть Лестера, Ли, Лареса,Волка и Марио в команду через заклинание "забыть"?

**Comment by dosinabox** [comment]
> таки [несмог уплыть ](https://youtu.be/KLzt9TrjFNc?t=5983) :-D

Возможна ли такая ситуация в оригинале Г2НВ?

**Comment by Kor-Angar** [comment]
Скорей всего.

**Comment by Kor-Angar** [comment]
> Возможна ли такая ситуация в оригинале Г2НВ?

проверить?

**Comment by dosinabox** [comment]
было бы шикарно

**Comment by Kor-Angar** [comment]
после просмотра карты можно набирать команду в 5 главе. код карты ItWr_Seamap_Irdorath

**Comment by Kor-Angar** [comment]
NPC которые могут погибнуть в 4 главе
- Ангару
- Горну
- Биффу

**Comment by Kor-Angar** [comment]
Отказываются плыть
-  Лестер (бессмертный)
-  Ли (бессмертный)
-  Ларес (бессмертный)
-  Волк
-  Марио 
-  Ватрас

**Comment by Kor-Angar** [comment]
Всегда плывут + бессмертные

-  Мильтен (бессмертный) в команде
-  Диего (бессмертный) в команде
-  Беннет (бессмертный) в команде

**Comment by Kor-Angar** [comment]
после просмотра карты можно набирать команду в 5 главе. код карты ItWr_Seamap_Irdorath

**Всегда плывут + бессмертные**
-  Мильтен (бессмертный) в команде
-  Диего (бессмертный) в команде
-  Беннет (бессмертный) в команде

**Могут, отказаться плыть**
-  Лестер (бессмертный)
-  Ли (бессмертный)
-  Ларес (бессмертный)
-  Волк
-  Марио
-  Ватрас

Всегда плывут, но смертные 
- Ангару // высокая вероятность что погиб в 4 главе
- Горну // высокая вероятность что погиб в 4 главе

Прочие смертные(проверить)
- Бифф // высокая вероятность что погиб в 4 главе
- Гирион

**Comment by dosinabox** [comment]
Должен ли счетчик членов команды уменьшаться при смерти кого-либо смертного из команды?

**Comment by Kor-Angar** [comment]
> Должен ли счетчик членов команды уменьшаться при смерти кого-либо смертного из команды?

уточни, про что именно ты говоришь. на сколько я понял после того как НПС становится членом команды, он становится бессмертным(по крайней мере так было у Горна и Ангара).

Т.е. в итоге счётчик нам нужен для того что бы в сухом остатке на корабле на Ирдорате был капитан + пять человек + герой.

**Comment by dosinabox** [comment]
> после того как НПС становится членом команды, он становится бессмертным

Тогда вопрос снимается.

**Comment by Kor-Angar** [comment]
это тоже надо перепроверить на всех НПС.

**Comment by Kor-Angar** [comment]
смотрю не забыл ли я про кого нибудь случайно :-)
**MIS_ReadyforChapter6**
![image](https://user-images.githubusercontent.com/49514764/74334763-9606dd00-4dab-11ea-9828-707a0f6c5486.png)

**Crewmember_Count**
![image](https://user-images.githubusercontent.com/49514764/74334805-ac149d80-4dab-11ea-86a6-79cf9fc46628.png)

**Comment by Kor-Angar** [comment]
> Возможна ли такая ситуация в оригинале Г2НВ?
> 
> проверить?
> 
> было бы шикарно

тогда предлагаю такой сценарий

**Убиваю в 4 главе:**
- Ангару
- Горну
- Бифф

**Беру с собой**
- Мильтен (бессмертный) всегда  в команде
- Диего (бессмертный) всегда  в команде
- Беннет (бессмертный) всегда в команде
- Лестер (бессмертный)
- Ли (бессмертный)
- Ларес (бессмертный)
- Волк
- Марио
- Ватрас
- Гирион

Делаю контрольный сейв и смотрю чем дело заканчивается -)

**Comment by Kor-Angar** [comment]
И Ватрас надо будет еще отдельно проверить, когда он находясь в команде посылает героя и когда он уже поднявшись на борт посылает героя 😀

**Comment by Kor-Angar** [comment]
не нашел топик про Гириона в команде. пишу здесь свои правки https://github.com/Kor-Angar/G2_NotR_Kor_Angar/commit/1c90964afae279bd9cb1c79bb6474266dce1df74 Правка простая: добиться что бы Гирион появлялся в порту вовремя  и не опаздывал на корабль :-)

если в порту есть пару человек то Гириону меняется расписание в  B_JoinShip.d
```D
	if 	Crewmember_Count > 2
	{
		B_StartOtherRoutine(Girion,"WaitForShip");
	};
```

у Гириона проверку на MIS_ShipIsFree   из Condition перенёс в реплики.
```D
func int DIA_Girion_CATCHPLAYERSTOLENSHIP_Condition()
{
	if	(Kapitel >= 5) 
	//&&	(MIS_ShipIsFree == TRUE) 
	&&	(Npc_GetDistToWP(self,"NW_CITY_WAY_TO_SHIP_25") < 1000)
	{
		return TRUE;
	};
};

func void DIA_Girion_CATCHPLAYERSTOLENSHIP_Info()
{
	AI_Output(self,other,"DIA_Girion_CATCHPLAYERSTOLENSHIP_08_00");	//Эй! Ты можешь сказать мне, что ты делаешь здесь?
	Info_ClearChoices(DIA_Girion_CATCHPLAYERSTOLENSHIP);
	if	(MIS_ShipIsFree == TRUE) 
	{
		Info_AddChoice(DIA_Girion_CATCHPLAYERSTOLENSHIP,"Я не знаю, о чем ты говоришь.",DIA_Girion_CATCHPLAYERSTOLENSHIP_no);
	};
	Info_AddChoice(DIA_Girion_CATCHPLAYERSTOLENSHIP,"Прочь с моей дороги, или мне придется убить тебя.",DIA_Girion_CATCHPLAYERSTOLENSHIP_weg);
	Info_AddChoice(DIA_Girion_CATCHPLAYERSTOLENSHIP,"Мне нужен этот корабль. Поэтому я забираю его.",DIA_Girion_CATCHPLAYERSTOLENSHIP_ship);
};

func void DIA_Girion_CATCHPLAYERSTOLENSHIP_no()
{
	AI_Output(other,self,"DIA_Girion_CATCHPLAYERSTOLENSHIP_no_15_00");	//Я не знаю, о чем ты говоришь.
	AI_Output(self,other,"DIA_Girion_CATCHPLAYERSTOLENSHIP_no_08_01");	//Я говорю о том, что ты сделал с корабельной стражей. Это дело плохо пахнет.
	if((hero.guild == GIL_KDF) && !Npc_IsDead(Schiffswache_212) && !Npc_IsDead(Schiffswache_213))
	{
		AI_Output(self,other,"DIA_Girion_CATCHPLAYERSTOLENSHIP_no_08_02");	//Даже несмотря на то, что ты маг, я не доверяю тебе.
	};
};


var int Girion_WantstoKillSC;

func void DIA_Girion_CATCHPLAYERSTOLENSHIP_weg()
{
	AI_Output(other,self,"DIA_Girion_CATCHPLAYERSTOLENSHIP_weg_15_00");	//Прочь с моей дороги, или мне придется убить тебя.
	if	!Npc_IsDead(Schiffswache_212) 
	&&	!Npc_IsDead(Schiffswache_213)
	&&	MIS_ShipIsFree == TRUE
	{
		AI_Output(self,other,"DIA_Girion_CATCHPLAYERSTOLENSHIP_weg_08_01");	//Возможно, тебе удалось обмануть охрану корабля, но со мной тебе так просто не справиться, мой маленький друг.
		if(hero.guild == GIL_PAL)
		{
			AI_Output(self,other,"DIA_Girion_CATCHPLAYERSTOLENSHIP_weg_08_02");	//Даже хотя ты один из нас, это не дает тебе права воровать собственность короля. Умри, проклятый предатель.
		};
	}
	else
	{
		AI_Output(self,other,"DIA_Girion_Verrat_08_00");	//Предатель!
	};
	AI_StopProcessInfos(self);
	B_Attack(self,other,AR_KILL,1);
	Girion_WantstoKillSC = TRUE;
};
```
Гирион приходит в порт и в ранних главах, если герой проник на корабль. что он там будет делать я пока не придумал. при следующем прохождение  буду думать :-)
```D
MIS_ShipIsFree = TRUE;
	B_CheckLog();
	if(Kapitel == 5)
	{
		B_StartOtherRoutine(Girion,"WaitForShip");
	}
	else
	{
		B_StartOtherRoutine(Girion,"WaitFor");
	};
```

**Comment by Kor-Angar** [comment]
конвертируй плиз в дискуссию
