### ISSUE TITLE
"Божественная Сила Звезд" + Рецепты: "Чистое здоровье / Чистая Манна"

### ISSUE THREAD

**Issue by Kor-Angar** [dosinabox/g2nr_unofficial_update#65]
я уже писал как то. напомню

можно ли сделать проверку и если у Сагитты/Констанино нет в продаже _Чистого Здоровья / Чистой Манны_, добавлять в продажу.

так же рассмотреть возможность добавить _Чистого Здоровья / Чистой Манны_ Гораксу в продажу.

так же можно снять флаг миссии с книги "Божественная Сила Звезд" и добавлять его в продажу в случае отсутствия Цуриусу / Константино. в принципе эту книгу так же можно добавить и Сагите. Сейчас эту книгу можно продавать, а потом отбирать, я как понял ты с этим явлением борешься :-)

**Comment by dosinabox** [comment]
> можно ли сделать проверку и если у Сагитты/Констанино нет в продаже _Чистого Здоровья / Чистой Манны_, добавлять в продажу.

Как ни странно, это будет сложно. Может, просто добавить им несколько дополнительных бутылочек?


> так же можно снять флаг миссии с книги "Божественная Сила Звезд" и добавлять его в продажу в случае отсутствия Цуриусу / Константино.

Окей. Мне кажется, что её и так продают несколько человек.

**Comment by dosinabox** [comment]
Если у Константино и Сагитты каждую главу будут появляться дорогие рецепты, то каждую главу их и будут избивать именно ради этих рецептов.

> можно добавить в продажу Кроносу в Яркендаре

А это уже интереснее и полезнее.

**Comment by Kor-Angar** [comment]
Не будут. С рецептов сняли флаг для миссии, они теперь пропадают. Именно поэтому я и поднял этот вопрос

**Comment by dosinabox** [comment]
А как отследить причину отсутствия рецептов? ГГ может их просто купить и не избивать торговца.

**Comment by Kor-Angar** [comment]
Можно причину отсутствия не отслеживать. Есть в продаже и есть. Если герой их уже выкупил, то у продовца просто будет ассортимент шире 🙂

**Comment by Kor-Angar** [comment]
Давай хотя бы в этой версии Кронусу в Ярике добавим в продажу.

**Comment by Kor-Angar** [comment]
> я давно хочу сделать им новую модель,

какие есть варианты?

**Comment by dosinabox** [comment]
Что-то вроде свитка с печатью (см. письмо Гаронда), но вместо печати что-то другое. Или как я делала модели рецептов для мод-фикса - схематичное изображение бутылочки с изготавливаемым зельем.

**Comment by dosinabox** [comment]
Рецепты добавлены Кроносу в Яркендаре. Что если они будут у него только в третьей главе?

**Comment by Kor-Angar** [comment]
> Что если они будут у него только в третьей главе?

а какой практический смысл в этом? у Сагиты и Константино с 1 главы

**Comment by dosinabox** [comment]
Тогда вопрос закрыт

**Comment by Kor-Angar** [comment]
если книгу "Божественная Сила Звезд" добавить в продажу Кронусу(бессмертный НПС) в Хориносе/Ярике, тогда  с неё можно снять флаг "для" миссии.

Сейчас её можно отобрать у Константино, продавать торговцам за золотом, потом её отбирать и так далее.

Книжка нужна для квеста в третьей главе в Монастыре при игре за все фракции

**Comment by Kor-Angar** [comment]
обрати внимание как я подаю дурной пример на стриме и в 1 главе уже 3-5 раз продал "Божественную Силу Звезд".

> если книгу "Божественная Сила Звезд" добавить в продажу Кронусу(бессмертный НПС) в Хориносе/Ярике, тогда с неё можно снять флаг "для" миссии.

**Comment by dosinabox** [comment]
Продают Константино и Зурис. Поэтому можно просто снять флаг.

**Comment by Kor-Angar** [comment]
давай с другого конца пойдем. зачем нужен этот флаг? этот флаг ставится на квестовые предметы, что бы они не пропали из игрового мира и можно было выполнить квест. 
Есть квесты воров. Они касаются и Константино и Зуриуса. Выполняя их герой может подраться с Константино и Зуриусом. таким образом пропадет квестовая книга, которая понадобится в 3 главе. можно просто оттырить Константино и Зуриуса и книга пропадет. с этой целью авторы игры сделали флаг квестовых предметов, что бы игрок не терял возможность закрывать квесты в будущем. попровь меня если я не прав.

Вам идея флагов не нравится так как это позволяет дополнительно(не честно) получать бесконечные деньги. Есть разные варианты(компромиссные) которые позволяют сохранить задумку авторов и при этом исключить возможность нечестно получать деньги. а есть варианты бескомпромиссные, когда "одно лечим, а другое калечим". просто снять флаг с книги это как раз такой вариант. игрок при определенных событиях в игре не сможет выполнить квест. 

у тебя есть наработанная методика с добавлением необходимого товара при определенных условиях (пиво в Ярике, болотная рава в 3 главе, свитки для изготовление рун). как раз тут можно использовать эту методику, например при получение этого квеста в 3 глава добавлять книгу Константину и Зуриусу.

**Comment by dosinabox** [comment]
https://github.com/dosinabox/g2nr_unofficial_update/issues/266

**Comment by Kor-Angar** [comment]
а "Божественная Сила Звезд" добавляли Кронусу в Ярике?

**Comment by dosinabox** [comment]
нет
