### ISSUE TITLE
Пояса на Ирдорате

### ISSUE THREAD

**Issue by Kor-Angar** [dosinabox/g2nr_unofficial_update#66]
на Ирдорате нет в продаже поясов. можно добавить с защитой от магии/огня например Милтену или Ватрасу. а от оружия например Беннету.

это я пишу не потому что они нужны, а потому что мне кажется что разработчики про них просто забыли, так как поясами торгует и в Хориносе и в Минентале и в Ярике. а на Ирдорате не торгуют. Хотя Беннет в Хориносе продавал.

**Comment by dosinabox** [comment]
> на Ирдорате нет в продаже поясов. можно добавить с защитой от магии/огня например Милтену или Ватрасу. а от оружия например Беннету.

Окей.

**Comment by dosinabox** [comment]
Милтен - пояс огненного человека
Ватрас - пояс магической защиты
Беннет - пояс силы
Диего - пояс ловкости

**Comment by Kor-Angar** [comment]
а пояс к защите от оружия? :-)

**Comment by dosinabox** [comment]
А кому его? Больше торговцев нет.

**Comment by Kor-Angar** [comment]
Беннету

**Comment by dosinabox** [comment]
Это пояс, который +10 к защите от оружия?

**Comment by Kor-Angar** [comment]
Ага

**Comment by dosinabox** [comment]
добавлено

**Comment by Kor-Angar** [comment]
проверил. были
