### ISSUE TITLE
Дар. Болотный табак

### ISSUE THREAD

**Issue by Kor-Angar** [dosinabox/g2nr_unofficial_update#67]
Можно подумать что бы Дар за болотный табак давал что нибудь. 
например давал нейтралу 10 косяков для квеста Сайфера.

**Comment by dosinabox** [comment]
Ты про грибной табак? Там дается опыт. 
Или сделать возможность дать болотный табак? Надо посмотреть, найдутся ли подходящие реплики.

**Comment by dosinabox** [comment]
Нет подходящей озвучки. Да и незачем, наверное.
