### ISSUE TITLE
Доспехи из Готики 1

### ISSUE THREAD

**Issue by Kor-Angar** [dosinabox/g2nr_unofficial_update#68]
напомни пожалуйста у тебя легкие доспехи призрака добавлены в неофициальной сборке? а легкие доспехи стражника СЛ из Г1?

я помню что ты писала про какие то доспехи какие добавила, а про какие не помню :-)

**Comment by Kor-Angar** [comment]
Не помню скидывал или нет. В прошлом году переодевал бандитов которые в кожанных доспехах в доспехи призраки https://www.youtube.com/watch?v=_jtb9QnQHPQ&feature=youtu.be

**Comment by Kor-Angar** [comment]
так в сборке оказываются есть тяжелые доспехи наёмника из Готики 1 и они задействованы в игре.
а средние доспехи наёмника из Готики 1 есть? а легкие доспехи стражника?

**Comment by dosinabox** [comment]
> а средние доспехи наёмника из Готики 1 есть? а легкие доспехи стражника?

нет

**Comment by dosinabox** [comment]
Это нужно конвертировать модели из Г1 и включать новые файлы в мод. А зачем увеличивать размер мода, если сейчас эти доспехи нигде не используются?

**Comment by Kor-Angar** [comment]
Про размер мода это сильно конечно😀 тем более что в моде уже какие то доспехи есть Если добавить средние доспехи Наёмников, то можно будет переключать вид между доспехами из Готики 2 и Готики 1. Хочешь такие, хочешь такие. Те же доспехи призрака тоже можно задействовать опционально передевая бандитов из кожаных доспехов в доспехи призрака 😀Мне кстати травы из Готики 1 до сих пор глаза режут, хотя я уже сними на играл наверное часов 150.16.10.2019, 16:52, "dosinabox" <notifications@github.com>:Это нужно конвертировать модели из Г1 и включать новые файлы в мод. А зачем увеличивать размер мода, если сейчас эти доспехи нигде не используются?

**Comment by dosinabox** [comment]
> Мне кстати травы из Готики 1 до сих пор глаза режут

Это какие?

> Те же доспехи призрака тоже можно задействовать опционально передевая бандитов из кожаных доспехов в доспехи призрак

Ну, это можно. И по лору подходит. А средние доспехи наемника из Г1 не знаю зачем)

**Comment by Kor-Angar** [comment]
Слева доспех из Готики 1. Справа доспех ITAR_SLD_S из неофициально обновления
![image](https://user-images.githubusercontent.com/49514764/77831232-fe810200-713e-11ea-9666-44c9b14ed677.png)

**Comment by dosinabox** [comment]
Угу, нужно править руки.

**Comment by Kor-Angar** [comment]
Не факт что нужно. Этот доспех по сути тот же самый тяжёлый доспех😀 он вставлен в игру просто так. Смысла никакого он несёт и сам по себе противоричет логики.

Проще выкуп Горна для Наемника сделать дороже и давать обычный тяжёлый доспех.

**Comment by Kor-Angar** [comment]
ты добавила доспехи Магов Огня из Готики 1 ?

**Comment by dosinabox** [comment]
Да, ITAR_KDF_M и ITAR_KDF_S. Доступны только через консоль.

**Comment by Kor-Angar** [comment]
Надо будет как нибудь сделать сводный список. По моему доспехов из Готики 1 которые не переехали в проект скоро можно будет пересчитать по пальцам 😀

**Comment by dosinabox** [comment]
Имеет ли теперь смысл переодеть Милтена в его старую мантию из Г1 (ITAR_KDF_M)?

**Comment by Kor-Angar** [comment]
А почему именно мильтена? У всех магов огня доспехи одинаковые ;-) Это доспехи  пираньи обновили. И доспехи Наёмника отличаются, хотя фактически это один и тот же доспех. 9:37, 4 августа 2020 г., dosinabox <notifications@github.com>:
Имеет ли теперь смысл переодеть Милтена в его старую мантию из Г1 (ITAR_KDF_M)?

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
-- Отправлено из мобильного приложения Яндекс.Почты

**Comment by Kor-Angar** [comment]
Давай запишем для себя какие доспехи Пираньи визуально изменили в Готике 2
- Доспехи Магов Огня
- Доспехи Наёмников
- Доспехи Ополчения (легкие стражи в старом лагере)
- Одежда повара (Снаф выглядит иначе, но может он просто переоделся)
- Магов Воды?
- Средние доспехи воров Г1

Не меняли
- Магов Воды?
- Некроманта
- из брони краулеров
- доспехи призраков из Старого Лагеря
- доспехи братства спящего
- воров из Нового Лагеря
- рудникового борона

**Comment by dosinabox** [comment]
> * воров из Нового Лагеря

Поменяли на бандитов, синяя расцветка изменилась на коричневую

> * Доспехи Ополчения (легкие стражи в старом лагере)

Я всё же считаю, что это разные доспехи

> * Магов Воды?

Вроде, немного изменились сами модели, но не текстуры

> Не меняли

+ тяжелые доспехи стражника
+ штаны рудокопов

> какие доспехи Пираньи визуально изменили

+ одежда повара (Снаф выглядит иначе, но может он просто переоделся)

**Comment by Kor-Angar** [comment]
>> Доспехи Ополчения (легкие стражи в старом лагере)

> Я всё же считаю, что это разные доспехи

с точки зрения ЛОРа одинаковые, это же доспехи ополчения, которые отжали себя уголовники после бунта. визуально конечно же разные. или тебе кажется что с точки зрения ЛОРа это разные доспехи? 

Пирокар из Ролика Г1
![image](https://user-images.githubusercontent.com/49514764/89347863-3a5f4180-d6b4-11ea-9ae1-5fde9b537ef8.png)

ролик лёгкие доспехи, старый лагерь Готика 1
![image](https://user-images.githubusercontent.com/49514764/89347986-74c8de80-d6b4-11ea-9810-ee56ad1395b8.png)


ролик лёгкие доспехи ополчения, старый лагерь Готика 2 
![image](https://user-images.githubusercontent.com/49514764/89348511-5d3e2580-d6b5-11ea-8bb1-abb4aa344857.png)

ролик средние доспехи наёмника в Готика 2
![image](https://user-images.githubusercontent.com/49514764/89348278-f456ad80-d6b4-11ea-8c3e-6295353a1e66.png)

редкий кадр. "тяжелые доспехи ополчения" из ролика Готика 2.
![image](https://user-images.githubusercontent.com/49514764/89348728-bb6b0880-d6b5-11ea-9d2b-a7010989c89d.png)

"тяжелые доспехи ополчения" из ролика Готика 1
![image](https://user-images.githubusercontent.com/49514764/89348898-fec57700-d6b5-11ea-98cf-e59df4e18903.png)
![image](https://user-images.githubusercontent.com/49514764/89348961-18ff5500-d6b6-11ea-8a72-d5c4a4a33a90.png)
![image](https://user-images.githubusercontent.com/49514764/89349067-43511280-d6b6-11ea-9260-0bf57e707fbb.png)


p.s.
а в Готике 2 на стойках в Минентале висят доспехи из Готики 1 или из Готики 2?

**Comment by dosinabox** [comment]
> ролик средние доспехи наёмника в Готика 2

Следует отметить, что интро было создано ещё во времена разработки Сиквела, когда и концепт игры был другим. Потом текстуры доспехов поменяли, а видео переделывать не стали. Там ещё текстура тела ГГ другая)

> с точки зрения ЛОРа одинаковые, это же доспехи ополчения, которые отжали себя уголовники после бунта. визуально конечно же разные. или тебе кажется что с точки зрения ЛОРа это разные доспехи?

Ополчение - городское, в городе Хоринис. А уголовники отжали себе доспехи тюремных стражников.

> а в Готике 2 на стойках в Минентале висят доспехи из Готики 1 или из Готики 2?

В Г2 на всех стойках висят только доспехи стражников из Г1. Даже в казармах городского ополчения везде висят красные доспехи стражников колонии, которые никто в городе не носит.

![image](https://user-images.githubusercontent.com/39790055/89376782-36094780-d6f9-11ea-868a-ef5aa56a0562.png)

В обновлении была сделана новая модель:

> заменена модель доспехов, висящих на стене в казарме: теперь это действительно доспехи ополчения (спасибо D36);

**Comment by Kor-Angar** [comment]
> Ополчение - городское, в городе Хоринис. А уголовники отжали себе доспехи тюремных стражников.

по такой логике у тех ребят что ушли в миненталь должны быть доспехи №3? :-)

если говорить про ЛОР игры на видео видно и тяжелые доспехи 

> Ополчение - городское, в городе Хоринис. А уголовники отжали себе доспехи тюремных стражников.

тогда почему тяжёлые доспехи совпадают? доспехи на момент когда делали ролики к Готике 2 были одинаковые. даже были тяжелые доспехи (на видео из 5 главы выше видно) и в локациях висят доспехи такие же. а потом как обычно пираньи решили подулучшить доспехи. и доспехи наёмников, магов и ментов стали отличаться.
