### ISSUE TITLE
Игра за Мага / оффтоп

### ISSUE THREAD

**Issue by Kor-Angar** [dosinabox/g2nr_unofficial_update#70]
Я планирую на днях поиграть за Мага. может сделать тестовую сборку и проверить правки. 

так же можно ещё раз посмотреть на историю с шлемами.

**Comment by dosinabox** [comment]
Готово:
https://github.com/dosinabox/g2nr_unofficial_update/releases/tag/v23test1

**Comment by dosinabox** [comment]
Настройка шлемов доступна у помощника, модели присутствуют.
Файл g2a_nr_scriptpatch_v22_hotfix.mod скопировать в Data/ModVDF.

**Comment by Kor-Angar** [comment]
после выхода из игры файл g2a_nr_scriptpatch_v22_hotfix пропадает

**Comment by dosinabox** [comment]
> после выхода из игры файл g2a_nr_scriptpatch_v22_hotfix пропадает

Если запуск происходит из мод-стартера, то файл обязательно нужно копировать в Data/ModVDF. Не в Data.

**Comment by Kor-Angar** [comment]
я туда и скопировал

**Comment by Kor-Angar** [comment]
так же как и 21.

21 запускаю, выхожу из игры, всё ок.
22 запускаю, выхожу из игры, 22_hotfix пропадает

**Comment by dosinabox** [comment]
Ничего не понимаю. Сделай скриншоты окна мод-стартера и содержимого папок Data и Data/ModVDF.

**Comment by dosinabox** [comment]
У меня не пропадает.

**Comment by dosinabox** [comment]
Вообще, мод-стартер копирует файлы модов из Data/ModVDF в Data на врем работы игры, а после входа удаляет их из папки Data. Может, это твой случай?

**Comment by Kor-Angar** [comment]
а теперь не пропадает. чертовщина какая то :-/

**Comment by dosinabox** [comment]
Создай себе в начале игры амулет тестировщика и поглядывай иногда, чтобы не отвалилось ничего)

**Comment by Kor-Angar** [comment]
подскажи пожалуйста почему у меня опять меню уменьшилось? :-)
![image](https://user-images.githubusercontent.com/49514764/64924661-a9f3e600-d7ef-11e9-9d03-6be9690ac971.png)
![Uploading image.png…]()

**Comment by dosinabox** [comment]
Забыл выбрать при установке? Скопируй в Data/ModVDF:
[g2a_nr_scriptpatch_v22_autoscale.zip](https://github.com/dosinabox/g2nr_unofficial_update/files/3613991/g2a_nr_scriptpatch_v22_autoscale.zip)

**Comment by Kor-Angar** [comment]
наоборот, при установке галочку не ставил. а g2a_nr_scriptpatch_v22_autoscale откуда то взялся.

вообщем удалил файл "g2a_nr_scriptpatch_v22_autoscale" и меню стало большим:-)
![image](https://user-images.githubusercontent.com/49514764/64925042-9ea2b980-d7f3-11e9-93fc-69cb5ab817c5.png)

**Comment by dosinabox** [comment]
![image](https://user-images.githubusercontent.com/39790055/64925070-f4776180-d7f3-11e9-911f-08348929f1c3.png)

**Comment by dosinabox** [comment]
Возможно, что-то всё же сломалось. Поэтому:

> Сделай скриншоты окна мод-стартера и содержимого папок Data и Data/ModVDF.

**Comment by Kor-Angar** [comment]
![image](https://user-images.githubusercontent.com/49514764/64925155-2937e880-d7f5-11e9-88a9-f08088459d3d.png)
![image](https://user-images.githubusercontent.com/49514764/64925159-39e85e80-d7f5-11e9-9bbf-7e6fab22a235.png)
![image](https://user-images.githubusercontent.com/49514764/64925169-5ab0b400-d7f5-11e9-8008-7623c807b5c6.png)
я вспомнил. мы про меню уже несколько раз общались.

**Comment by dosinabox** [comment]
Как в этом прохождении поступил со статуэткой Дарона?

**Comment by Kor-Angar** [comment]
> Готово:
> https://github.com/dosinabox/g2nr_unofficial_update/releases/tag/v23test1

а все файлы от 29.08 идут
![image](https://user-images.githubusercontent.com/49514764/65075128-f0d40e00-d99e-11e9-86b3-2b224156cf65.png)

**Comment by dosinabox** [comment]
Это что, исходники? Забыла перед релизом ветки смержить, только после релиза work слилась с develop. Скачай заново не со страницы релизов.
