### ISSUE TITLE
Сержио и Бабо. Тренировка

### ISSUE THREAD

**Issue by Kor-Angar** [dosinabox/g2nr_unofficial_update#75]
Мне кажется или в д воём не помещаются? 

https://www.youtube.com/watch?v=eWxLRxO6rNI

**Comment by dosinabox** [comment]
Места и правда маловато, но легких решений здесь нет. Нужны правки мира и добавления новых точек, но всё равно поможет мало, потому что там ограниченная область.

**Comment by Kor-Angar** [comment]
Можно сделать что бы Сержио стоял, а Бабо тренировался. Он же как бы его учит 🙂

Жаль что их тренировку впроходит очень рано и ее с утра не зостать
