### ISSUE TITLE
Тренировки с мечём / атмосфера

### ISSUE THREAD

**Issue by Kor-Angar** [dosinabox/g2nr_unofficial_update#76]
я так понимаю это все НПС которые тренируются с мечём?
![image](https://user-images.githubusercontent.com/49514764/64978736-dcb8df80-d8be-11e9-80d7-866d2da55ad2.png)

в списке есть даже Ангар. О том что он тренируется с мечем я даже и не знал :-(

может посмотреть и подвигать расписание чуть чуть что бы герой проснувшись с утра мог увидеть того же Ангара махающего мечём?

**Comment by Kor-Angar** [comment]
Ангра красавчик :-)
https://www.youtube.com/watch?v=-RXNX_gQShc

**Comment by dosinabox** [comment]
> может посмотреть и подвигать расписание чуть чуть что бы герой проснувшись с утра мог увидеть того же Ангара махающего мечём?

Я против)
