### ISSUE TITLE
Дар. лишние косяки

### ISSUE THREAD

**Issue by Kor-Angar** [dosinabox/g2nr_unofficial_update#78]
у меня глюканул Дар. у него было с собой 55 косяков. вроде ничего такого не правил. надо как то перепроверить? :-)

**Comment by dosinabox** [comment]
Есть видео?

**Comment by Kor-Angar** [comment]
![image](https://user-images.githubusercontent.com/49514764/65072861-65587e00-d99a-11e9-8ad1-35261f48c513.png)

https://youtu.be/0blG1zx1w0Q?t=12208

может быть это связано с тем что прошло много дней от начало игры?
![image](https://user-images.githubusercontent.com/49514764/65072969-933dc280-d99a-11e9-94c5-5688afeb8179.png)

**Comment by dosinabox** [comment]
Требуются правки на уровне движка, пока закрыто

**Comment by dosinabox** [comment]
У Кардифа может появиться 200 отмычек.
