### ISSUE TITLE
Кантар в тюрьме

### ISSUE THREAD

**Issue by Kor-Angar** [dosinabox/g2nr_unofficial_update#79]
Кантар находясь в тюрьме после избиения вымогает бабло
Кантара в тюрьме нельзя обокрасть

**Comment by dosinabox** [comment]
Исправлено.

**Comment by Kor-Angar** [comment]
и обворовать можно? :-)

**Comment by dosinabox** [comment]
Да.

**Comment by Kor-Angar** [comment]
Кантар в тюрьме торгует с ГГ

**Comment by dosinabox** [comment]
Исправлено. Это из-за разблокировки кражи. Нужно следить, какие диалоги у него ещё могут появиться.

**Comment by dosinabox** [comment]
Наверное, придется вообще отменить изменение с разблокировкой кражи, потому что возможны проблемы. Можно мотивировать тем, что у Кантара конфисковали всё золото и воровать нечего)

**Comment by Kor-Angar** [comment]
А та проверка что у Беннета стоит не подойдет?

**Comment by dosinabox** [comment]
> А та проверка что у Беннета стоит не подойдет?

Нет, у него проверяется глава и статус квеста "Беннет в тюрьме".
