### ISSUE TITLE
Монстры. Нежить

### ISSUE THREAD

**Issue by Kor-Angar** [dosinabox/g2nr_unofficial_update#80]
Можно тебя попросить сюда запостить скелетов Лордов и уникальных скелетов Лордов. 

кажется я писал как то что у одного из них должен быть иммунитет от стрел и предлагал какие то такие правки. хочу перепроверить ни из Готики 2 классик это всё тянется. 

******************

Г2:
Теневой воин | Архол
STRENGTH = 100 | 150
HITPOINTS = 250 | 400

Г2 НВ
Теневой воин | Архол
STRENGTH = 105 | 150
HITPOINTS = 400 | 400

Г2 НВ Неоф обновление
Теневой воин | Архол
STRENGTH = 105 | 150
HITPOINTS = 400 | 600

**Comment by dosinabox** [comment]
Г2НВ:

```
prototype Mst_Skeleton_Lord(C_Npc)
{
	name[0] = "Теневой воин";
	guild = GIL_SKELETON;
	aivar[AIV_MM_REAL_ID] = ID_SKELETON;
	level = 40;
	attribute[ATR_STRENGTH] = 105;
	attribute[ATR_DEXTERITY] = 100;
	attribute[ATR_HITPOINTS_MAX] = 400;
	attribute[ATR_HITPOINTS] = 400;
	attribute[ATR_MANA_MAX] = 200;
	attribute[ATR_MANA] = 200;
	protection[PROT_BLUNT] = 100;
	protection[PROT_EDGE] = 100;
	protection[PROT_POINT] = 100;
	protection[PROT_FIRE] = 100;	//16;
	protection[PROT_FLY] = 100;
	protection[PROT_MAGIC] = 0;
	damagetype = DAM_EDGE;
	fight_tactic = FAI_HUMAN_STRONG;
	EquipItem(self,ItMw_Zweihaender2);
	senses = SENSE_HEAR | SENSE_SEE | SENSE_SMELL;
	senses_range = PERC_DIST_MONSTER_ACTIVE_MAX;
	aivar[AIV_MM_FollowTime] = FOLLOWTIME_MEDIUM;
	aivar[AIV_MM_FollowInWater] = FALSE;
	start_aistate = ZS_MM_AllScheduler;
	aivar[AIV_MM_RestStart] = OnlyRoutine;
};

func void B_SetVisuals_Skeleton_Lord()
{
	Mdl_SetVisual(self,"HumanS.mds");
	Mdl_ApplyOverlayMds(self,"humans_1hST1.mds");
	Mdl_ApplyOverlayMds(self,"humans_2hST2.mds");
	Mdl_ApplyOverlayMds(self,"humans_BowT1.mds");
	Mdl_ApplyOverlayMds(self,"humans_CBowT1.mds");
	B_SetNpcVisual(self,MALE,"Ske_Head",0,0,ITAR_PAL_Skel);
};


instance Skeleton_Lord(Mst_Skeleton_Lord)
{
	B_SetVisuals_Skeleton_Lord();
};

instance Crypt_Skeleton_Lord(Mst_Skeleton_Lord)
{
	name[0] = "Теневой лорд Инубис";
	B_SetVisuals_Skeleton_Lord();
	CreateInvItems(self,ItMi_Gold,500);
	CreateInvItems(self,ItPo_Mana_03,2);
	CreateInvItems(self,ItPo_Health_03,2);
};

instance Skeleton_Lord_Archol(Mst_Skeleton_Lord)
{
	name[0] = "Теневой лорд Архол";
	level = 60;
	attribute[ATR_STRENGTH] = 150;
	attribute[ATR_DEXTERITY] = 150;
	attribute[ATR_HITPOINTS_MAX] = 400;
	attribute[ATR_HITPOINTS] = 400;
	attribute[ATR_MANA_MAX] = 0;
	attribute[ATR_MANA] = 0;
	B_SetVisuals_Skeleton_Lord();
	CreateInvItems(self,ItMi_Gold,650);
	CreateInvItems(self,ItKe_EVT_UNDEAD_01,1);
};
```

**Comment by dosinabox** [comment]
Инубис равен обычным теневым воинам.
Архол сильнее и жирнеее.
Иммунитета от стрел у них нет.

**Comment by dosinabox** [comment]
Г2:
```
prototype MST_SKELETON_LORD(C_NPC)
{
	name[0] = "Теневой воин";
	guild = GIL_SKELETON;
	aivar[AIV_MM_REAL_ID] = ID_SKELETON;
	level = 40;
	attribute[ATR_STRENGTH] = 100;
	attribute[ATR_DEXTERITY] = 100;
	attribute[ATR_HITPOINTS_MAX] = 250;
	attribute[ATR_HITPOINTS] = 250;
	attribute[ATR_MANA_MAX] = 0;
	attribute[ATR_MANA] = 0;
	protection[PROT_BLUNT] = 0;
	protection[PROT_EDGE] = 0;
	protection[PROT_POINT] = 1000;
	protection[PROT_FIRE] = 0;
	protection[PROT_FLY] = 0;
	protection[PROT_MAGIC] = 0;
	damagetype = DAM_EDGE;
	fight_tactic = FAI_HUMAN_STRONG;
	EquipItem(self,itmw_zweihaender2);
	senses = SENSE_HEAR | SENSE_SEE | SENSE_SMELL;
	senses_range = PERC_DIST_MONSTER_ACTIVE_MAX;
	aivar[AIV_MM_FOLLOWTIME] = FOLLOWTIME_MEDIUM;
	aivar[AIV_MM_FOLLOWINWATER] = FALSE;
	start_aistate = zs_mm_allscheduler;
	aivar[AIV_MM_RESTSTART] = ONLYROUTINE;
};

func void b_setvisuals_skeleton_lord()
{
	Mdl_SetVisual(self,"HumanS.mds");
	Mdl_ApplyOverlayMds(self,"humans_1hST1.mds");
	Mdl_ApplyOverlayMds(self,"humans_2hST2.mds");
	Mdl_ApplyOverlayMds(self,"humans_BowT1.mds");
	Mdl_ApplyOverlayMds(self,"humans_CBowT1.mds");
	b_setnpcvisual(self,MALE,"Ske_Head",0,0,itar_pal_skel);
};


instance SKELETON_LORD(MST_SKELETON_LORD)
{
	b_setvisuals_skeleton_lord();
};

instance CRYPT_SKELETON_LORD(MST_SKELETON_LORD)
{
	name[0] = "Теневой лорд Инубис";
	b_setvisuals_skeleton_lord();
	CreateInvItems(self,itmi_gold,500);
	CreateInvItems(self,itpo_mana_03,2);
	CreateInvItems(self,itpo_health_03,2);
};

instance SKELETON_LORD_ARCHOL(MST_SKELETON_LORD)
{
	name[0] = "Теневой лорд Архол";
	level = 60;
	attribute[ATR_STRENGTH] = 150;
	attribute[ATR_DEXTERITY] = 150;
	attribute[ATR_HITPOINTS_MAX] = 400;
	attribute[ATR_HITPOINTS] = 400;
	attribute[ATR_MANA_MAX] = 0;
	attribute[ATR_MANA] = 0;
	protection[PROT_BLUNT] = 10;
	protection[PROT_EDGE] = 20;
	protection[PROT_POINT] = 1000;
	protection[PROT_FIRE] = 10;
	protection[PROT_FLY] = 10;
	protection[PROT_MAGIC] = 10;
	b_setvisuals_skeleton_lord();
	CreateInvItems(self,itmi_gold,650);
	CreateInvItems(self,itke_evt_undead_01,1);
};
```

**Comment by dosinabox** [comment]
Инубис равен обычным теневым воинам.
Архол сильнее и жирнеее.
Иммунитета от стрел у них нет.

Зато в Г2 у них есть защита в 1000, которую в Г2НВ снизили до 100, забыв про Архола (у которого осталось 1000). Сейчас в обновлении всё в порядке.

**Comment by Kor-Angar** [comment]
Г2:
Теневой воин     | Архол   
STRENGTH = 100  | 150          
HITPOINTS = 250  | 400         

Г2 НВ
Теневой воин    |   Архол  
STRENGTH = 105   | 150
HITPOINTS = 400  | 400    

> Архол сильнее и жирнеее. Сейчас в обновлении всё в порядке.

Г2 НВ Неоф обновление
Теневой воин    |   Архол  
STRENGTH = 105   | ???
HITPOINTS = 400  |  ???

Хотел проверить убъёт его самое мощное заклинание Паладина 
![image](https://user-images.githubusercontent.com/49514764/66506905-de994b80-ead6-11e9-8984-497e00c75ef2.png)

**Comment by dosinabox** [comment]
Г2:
Теневой воин | Архол
STRENGTH = 100 | 150
HITPOINTS = 250 | 400

Г2 НВ
Теневой воин | Архол
STRENGTH = 105 | 150
HITPOINTS = 400 | 400

Г2 НВ Неоф обновление
Теневой воин | Архол
STRENGTH = 105 | 150
HITPOINTS = 400 | 400

Хм, не жирнее. Лишний параметр. Возможно, разрабы забыли повысить.

**Comment by Kor-Angar** [comment]
а почему не жирнее? может сделать ему 600 жизней?

**Comment by dosinabox** [comment]
> может сделать ему 600 жизней?

Можно. Сделать?

**Comment by Kor-Angar** [comment]
сделай. мы это обсуждали

**Comment by Kor-Angar** [comment]
они же его просто забыли поправить и он в Г2Ориганл=Г2НВ

**Comment by dosinabox** [comment]
готово

**Comment by Kor-Angar** [comment]
зер гуд

**Comment by Kor-Angar** [comment]
может ему и меч помощнее дать?

**Comment by dosinabox** [comment]
Вообще надо бы 640.
250 * 1.6 = 400
400 * 1.6 = 640

> может ему и меч помощнее дать?

Да ну.

**Comment by Kor-Angar** [comment]
> Вообще надо бы 640.

ага. но если сделать ему 640 его самое мощное заклинание Паладина не возъмёт

**Comment by dosinabox** [comment]
И как быть?

**Comment by Kor-Angar** [comment]
ну тут всё дело в этом заклинание. если ему дать 640 то он его выдержит, хотя по идеи не должен. если 600 то оно его убъёт.

**Comment by Kor-Angar** [comment]
я не знаю как правильно. иногда мне кажется так, а иногда иначе.

**Comment by dosinabox** [comment]
а в г2 умирает с одного каста заклинания?

**Comment by Kor-Angar** [comment]
да
![image](https://user-images.githubusercontent.com/49514764/66509322-7b5de800-eadb-11e9-9980-657cbeb6dcfe.png)

но в Готике 2 такие свитки мартин не продаёт. хотя такой свиток можно украсть у палов.

**Comment by dosinabox** [comment]
пока ставлю 600 и закрываем вопрос

**Comment by Kor-Angar** [comment]
хор. про меч что думаешь? может ему паладинский дать?
![image](https://user-images.githubusercontent.com/49514764/66509449-bcee9300-eadb-11e9-930f-80467d5ab506.png)

**Comment by dosinabox** [comment]
не, не надо
можно было бы новый какой-нибудь, уникальный

**Comment by Kor-Angar** [comment]
большинство мечей в игре не задействовано никак. зачем делать уникальные если и таких полно?

**Comment by Kor-Angar** [comment]
вот например меч из руды
![image](https://user-images.githubusercontent.com/49514764/66509664-2d95af80-eadc-11e9-9780-cd3e3a35de3f.png)
