### ISSUE TITLE
Румболд и Рик

### ISSUE THREAD

**Issue by Kor-Angar** [dosinabox/g2nr_unofficial_update#83]
**При вступлении в послушники или ополчение:**
невыполненный квест будет провален (квест противоречит интересам церкви и ополчения)
Рик и Румболд уйдут к таверне (их прогоняют наемники без участия ГГ)

**Наёмник, 3 глава**
невыполненный квест будет провален в диалоге с Бенгаром (ГГ пришел слишком поздно)
Рик и Румболд уйдут к таверне (их прогоняют наемники без участия ГГ или они получили ренту) как только гильдия ГГ изменится на ОнД
_(с) dosinabox_ 

По моему тут всё, от самого начал до самого конца неправильно
https://www.twitch.tv/videos/482808127

**Comment by dosinabox** [comment]
А что делать?

**Comment by dosinabox** [comment]
Что с озвучкой?) Половина на русском, половина на немецком...

**Comment by Kor-Angar** [comment]
> А что делать?

тезисы:
- этот квест Наёмников (обязанности наёмника), выполнить его можно по сюжету нейтралом(1 глава)/наёмником(2 глава)
- этот квест можно выполнить через Корда (быстрое вступление в Наёмники)
- для выполнения этого квеста Ополченцем / Магом Огня нет подходящих диалогов.  

я сам "за" контент. Но без порнографии. Этот квест можно было бы сделать выполняемым Магом Огня/Ментом по игровой логики, но на это нужны другие диалоги. Типа пришел Маг Огня наехал на ментов и они тут же собрались и ушли. С ополчением так же но уже не так официально :-) 
**но реплик нету**. а что то лепить это в большинстве случаев залепа.
пример от Пираней диалога с Пабло в зависимости от фракции(акцент на Мага Огня, а то бытует мнение в сети что Маг Огня это как волшебник в Скайриме. в то время как Маг Огня это представитель святой Церковь Инноса и есть чёткая/жёсткая социальная иерархия в игровом мире).

```
if((hero.guild == GIL_MIL) || (hero.guild == GIL_PAL))
	{
		AI_Output(self,other,"DIA_Pablo_Perm_12_01");	//Я всегда говорил, что этим наемникам нельзя доверять.
		AI_Output(self,other,"DIA_Pablo_Perm_12_02");	//Пришло время преподать этому сброду урок. Беннет не мог провернуть все это в одиночку.
	}
	else if(hero.guild == GIL_KDF)
	{
		AI_Output(self,other,"DIA_Pablo_Perm_12_03");	//Я глубоко потрясен убийством достопочтенного паладина Лотара.
		AI_Output(self,other,"DIA_Pablo_Perm_12_04");	//Но я знаю, что церковь подберет справедливое наказание для этого злодея.
	}
	else
	{
		AI_Output(self,other,"DIA_Pablo_Perm_12_05");	//Что ты тут ошиваешься? Если ты собираешься освободить своего дружка наемника, лучше тебе забыть об этом.
	};
```

Подитог:
сам квест придётся проваливать в случае вступления в Послушники / Ополчение.

Ну а теперь что должно происходить в игровом мире:
**если квест взят, а ГГ вступил в Ополчение / Маги Огня**
**если квест взят + взят квест Корда, а ГГ вступил в Ополчение / Маги Огня**
что должно произойти во второй главе? должны ли быть на ферме Румболд и Рик? На мой взгляд(суровый оборот, ИМХО было лучше) нет, потому что наёмники должны были уже закрыть вопрос. Возможно Румболд и Рик ушли по хорошему и находятся в таверне "Мертвая Гарпия", возможно их убил Корд. Можно сделать вариант когда они живы и вариант когда они мертвы, в зависимости от того был взят квест Корда или нет. При этом лично мне не понятно в каком случае они должны быть убиты, в полне возможно что Корд их мог развести по фене и они ушли, а мог и убить.
что должно произойти в первой главе? должны ли быть на ферме Румболд и Рик? на мой взгляд да, ведь можно поставить пару Наёмников которые будут говорить с ними. Или поставить Корда, который будет говорить с ними.

**Comment by Kor-Angar** [comment]
Про Нейтрала/ Наёмника
у Торлофа стоит проверка на то выполнен квеста Корда. 
При этом не учитывается вариант кода герой сам выполнил квест(Румболд и Рик) + выполнил квест Корда(Декстер). такой вариант  надо проработать так как сейчас герой теряет голоса.
```
if((MIS_Torlof_HolPachtVonSekob != LOG_SUCCESS) && (MIS_Torlof_BengarMilizKlatschen != LOG_SUCCESS))
	{
		AI_Output(self,other,"DIA_Torlof_RUF_01_23");	//Большинство из них просто ждет, пройдешь ли ты испытание.
	}
	else
	{
		AI_Output(self,other,"DIA_Torlof_RUF_01_24");	//Ты убедил большинство из них, пройдя испытание.
		if(Cord_RangerHelp_TorlofsProbe == TRUE)
		{
			AI_Output(self,other,"DIA_Addon_Torlof_RUF_01_00");	//(усмехается) Пусть Корд в этом и поучаствовал...
			Points_Sld += 4;
		}
		else if(MIS_Torlof_HolPachtVonSekob == LOG_SUCCESS)
		{
			AI_Output(self,other,"DIA_Torlof_RUF_01_25");	//Хотя многие считают, что заставить фермера заплатить ренту было слишком легко, чтобы считать это испытанием.
			Points_Sld += 3;
		}
		else
		{
			Points_Sld += 5;
		};
		AI_Output(self,other,"DIA_Torlof_RUF_01_26");	//В любом случае, ты можешь рассчитывать на мой голос.
		if(GotTorlofVote == FALSE)
		{
			if(Torlof_GenugStimmen == FALSE)
			{
				Log_CreateTopic(TOPIC_SLDRespekt,LOG_MISSION);
				Log_SetTopicStatus(TOPIC_SLDRespekt,LOG_Running);
			};
			B_LogEntry(TOPIC_SLDRespekt,"Торлоф считает, что я могу выполнять обязанности наемника.");
			GotTorlofVote = TRUE;
		};
		Points_Sld += 1;
	};
```
возможно(?) вот так правильнее
```

if(MIS_Torlof_BengarMilizKlatschen == LOG_SUCCESS)
{
Points_Sld += 5;
}
else if(MIS_Torlof_HolPachtVonSekob == LOG_SUCCESS)
{
AI_Output(self,other,"DIA_Torlof_RUF_01_25");	//Хотя многие считают, что заставить фермера заплатить ренту было слишком легко, чтобы считать это испытанием.
Points_Sld += 3;
}
else if(Cord_RangerHelp_TorlofsProbe == TRUE)
{
AI_Output(self,other,"DIA_Addon_Torlof_RUF_01_00");	//(усмехается) Пусть Корд в этом и поучаствовал...
Points_Sld += 4;
};
```


что происходит с Румболд и Рик, если нейтрал сдал квест Корду про Декстера, но ещё не поговорил с Торлофом?

**Comment by dosinabox** [comment]
> что происходит с Румболд и Рик, если нейтрал сдал квест Корду про Декстера, но ещё не поговорил с Торлофом?

Такая ситуация невозможна: для начала квеста про Патрика нужно взять испытание у Торлофа:
```
AI_Output(other,self,"DIA_Addon_Cord_RangerHelp2GetSLD_15_00");	//Помоги мне стать наемником.
AI_Output(self,other,"DIA_Addon_Cord_RangerHelp2GetSLD_14_01");	//Надо подумать... Хм-м. Если ты хочешь чего-то здесь добиться, тебе нужно поговорить с Торлофом.
AI_Output(self,other,"DIA_Addon_Cord_RangerHelp2GetSLD_14_02");	//Ты уже встречался с ним?
```
```
AI_Output(other,self,"DIA_Addon_Cord_RangerHelp2GetSLD_15_03");	//Еще нет.
AI_Output(self,other,"DIA_Addon_Cord_ComeLaterWhenDone_14_00");	//Так что вперед. Сделаешь это, и возвращайся ко мне.
```
```
AI_Output(other,self,"DIA_Addon_Cord_RangerHelp2GetSLD_15_04");	//Да. Он рассказал мне об испытании и прочем...
AI_Output(self,other,"DIA_Addon_Cord_RangerHelp2GetSLD_14_05");	//Ага. И какое же задание тебе дали?
AI_Output(other,self,"DIA_Addon_Cord_RangerHelp2GetSLD_15_08");	//Я должен избавить Бенгара от солдат ополчения.
AI_Output(self,other,"DIA_Addon_Cord_IDoItForYou_14_00");	//Понятно. Что ж, это просто. Возвращайся завтра, и все будет сделано.
AI_Output(self,other,"DIA_Addon_Cord_IDoItForYou_14_01");	//Но за это тебе придется кое-что для меня сделать.
AI_Output(other,self,"DIA_Addon_Cord_IDoItForYou_15_02");	//И что же именно?
AI_Output(self,other,"DIA_Addon_Cord_IDoItForYou_14_03");	//Недалеко отсюда, в холмах на юго-востоке, расположен небольшой бандитский лагерь.
AI_Output(self,other,"DIA_Addon_Cord_IDoItForYou_14_04");	//Если отсюда ты пойдешь на юго-восток, ты вскорости увидишь их башню.
AI_Output(self,other,"DIA_Addon_Cord_IDoItForYou_14_05");	//Один из моих людей, Патрик, несколько дней назад отправился туда, чтобы заключить сделку с этими подонками.
AI_Output(self,other,"DIA_Addon_Cord_IDoItForYou_14_06");	//Я говорил ему, что это плохая мысль, но этот идиот меня не послушал.
AI_Output(self,other,"DIA_Addon_Cord_IDoItForYou_14_07");	//Думаю, они расправились с ним. Но не уверен.
AI_Output(self,other,"DIA_Addon_Cord_IDoItForYou_14_08");	//Ты должен выяснить, что с ним случилось.
```

> сам квест придётся проваливать в случае вступления в Послушники / Ополчение.

Соглашусь. Более того, конфликт с ополчением не имеет смысла ни у ополченца, ни у служителя монастыря, а между взятием квеста нейтралом и вступлением в другую гильдию проходит какое-то время, за которое проблема может решится сама усилием самих наемников. Поэтому квест будет провален, а Рик и Румболд отправятся в таверну. Если ГГ просил помощи Корда, то это он разобрался, а если не просил, то разобрались другие наемники, потому что Бенгар просил помощи у Онара:
```
AI_Output(self,other,"DIA_Bengar_MILIZ_10_05");	//Я сказал об этом Онару еще пару дней назад. И за что я плачу свою ренту?!
```

**Comment by dosinabox** [comment]
А что если:
ГГ взял испытание с рентой, выполнил его, вступил к наемникам, получил задание с ополчением, забил на него и стал охотником на драконов? Должны ли Рик и Румболд ждать, пока ГГ соизволит их прогнать в таком случае?

**Comment by Kor-Angar** [comment]
> забил на него и стал охотником на драконов? Должны ли Рик и Румболд ждать, пока ГГ соизволит их прогнать в таком случае?

проваливать в начале 3 главы.

**Comment by Kor-Angar** [comment]
> что происходит с Румболд и Рик, если нейтрал сдал квест Корду про Декстера, но ещё не поговорил с Торлофом?

_взял задание у Торлофа --> взял задание у Корда --> сдал задание Корду_
вот в это момент что происходит с Румболд и Рик? в этот момент они должны уйти в Таверну?

**Comment by dosinabox** [comment]
> _взял задание у Торлофа --> взял задание у Корда --> сдал задание Корду_
> вот в это момент что происходит с Румболд и Рик? в этот момент они должны уйти в Таверну?

Уходят. Реализовано в 22 версии обновления:
```
- Рик и Румболд уйдут с фермы Бенгара, если ГГ попросил Корда о помощи с квестом 'Прогнать ополчение'.
```

**Comment by dosinabox** [comment]
> проваливать в начале 3 главы.

Этим недугом болеет мод Возвращение 2.0) Причина провала квеста должна быть понятна игроку и напрямую зависеть от его намеренных **действий**, а не **бездействия**. Квест не должен проваливаться по истечении времени или по какому-то событию незаметно от игрока. Здесь нужно сделать провал не в начале третьей главы, а у Бенгара, если ГГ пришел к нему, став охотником на драконов. Примерно так:
```
AI_Output(other,self,"DIA_Bengar_MILIZKLATSCHEN_15_00");	//Ну и где твое ополчение, я готов разобраться с ними!
AI_Output(self,other,"DIA_Bengar_MILIZ_10_01");	//Что?! Я сказал Онару, чтобы он прислал своих НАЕМНИКОВ.
AI_Output(self,other,"DIA_Bengar_MILIZ_10_08_add");	//Ты пришел слишком поздно!
```

**Comment by Kor-Angar** [comment]
Про возвращение ничего не знаю. не играл.

> Причина провала квеста должна быть понятна игроку и напрямую зависеть от его намеренных действий, а не бездействия.

в начале третей главы везде ищущие. убит Паладин. Беннет в тюрьме. все крестьяне свалили с фермы Бенгара. у секоба дом оккупирован. у Бенгара новые квесты. 
и в связи с этим у Бенгара уже новые проблемы. он просит героя обеспечить ему защиту и срастить Наёмников. а тут герой спрашивает про каких то ментов?:-)

сделай как ты предлагаешь, я прокручу диалог в игре и посмотрим насколько он будет лаконичен :-)

Но из этого вытекает следующий вопрос. о продаже Ли доспехов ГГ. что с этим? ;-)

**Comment by dosinabox** [comment]
> Но из этого вытекает следующий вопрос. о продаже Ли доспехов ГГ. что с этим? ;-)

А что там? Тяжелые доспехи наемника может купить только наемник и только в третьей главе.

**Comment by Kor-Angar** [comment]
Там условия на средние доспехи, условие что выполнен квест Торлофа.

**Comment by dosinabox** [comment]
Получить возможность купить средние доспехи можно только во второй главе. В третьей главе ГГ уже просит у Ли тяжелые доспехи.

**Comment by Kor-Angar** [comment]
Давай подитожим по правкам

**Comment by dosinabox** [comment]
При вступлении в послушники или ополчение:
- невыполненный квест будет провален (квест противоречит интересам церкви и ополчения)
- Рик и Румболд уйдут к таверне (их прогоняют наемники без участия ГГ)

При вступлении в охотники на драконов:
- невыполненный квест будет провален в диалоге с Бенгаром (ГГ пришел слишком поздно)
- Рик и Румболд уйдут к таверне (их прогоняют наемники без участия ГГ или они получили ренту) как только гильдия ГГ изменится на ОнД

**Comment by Kor-Angar** [comment]
> При вступлении в охотники на драконов

Будет стремно так как может у ГГ-Наемника наложится на квест про Волка и наемников. В результате получится толпа наемников и два ополченца.

**Comment by dosinabox** [comment]
Тогда нужно уводить их с фермы с началом третьей главы.

**Comment by Kor-Angar** [comment]
Может их в третей главе вообще убирать? А то получается два НПС без диалогов

**Comment by Kor-Angar** [comment]
Или в казармы в третей главе их ставить на тренировку к Вульфгару

**Comment by dosinabox** [comment]
> Или в казармы в третей главе их ставить на тренировку к Вульфгару

Надо посмотреть, есть ли для них места в казармах. С третьей главы им нечего делать у таверны.

**Comment by Kor-Angar** [comment]
касательно Таверны, они стоят  возле того места где появляются падальщики. скорее всего будут агрится. нельзя их во внутрь Таверны поместить?

> Надо посмотреть, есть ли для них места в казармах. С третьей главы им нечего делать у таверны.

можно поставить их возле  Руга, там много места и в тоже время вроде как "на стене" стоят, контролирует обстановку :-)

**Comment by dosinabox** [comment]
Что произойдет, если Бенгар погибнет до того, как ГГ выполнит квест "Прогнать ополчение" (он становится смертным при появлении в мире Румболда и Рика)? Заблокируется ли возможность вступления к наемникам?

**Comment by dosinabox** [comment]
> Заблокируется ли возможность вступления к наемникам?

Нет, потому что Бенгар вообще не нужен для выполнения квеста. Можно сразу топать к Торлофу.

**Comment by dosinabox** [comment]
> ГГ бъется с ментами сам, а крестьяне смотрят.

В твоем видео все напали на мага) Или у наемника и нейтрала не будет такой проблемы?

**Comment by dosinabox** [comment]
> Надо посмотреть, есть ли для них места в казармах.

Места полно. Могут патрулировать что-нибудь ночью, а днем спать.
Может, вставлять их в мир в третьей главе, даже если ГГ не брал квест? А то тогда непонятно, где они.

**Comment by Kor-Angar** [comment]
> В твоем видео все напали на мага) Или у наемника и нейтрала не будет такой проблемы?

Когда ГГ нейтрал/наем, все Ок 🙂

> Может, вставлять их в мир в третьей главе, даже если ГГ не брал квест? 

Можно 🙂

**Comment by dosinabox** [comment]
Готово. Протестируешь с новым прохождением и новой сборкой.

**Comment by Kor-Angar** [comment]
https://youtu.be/joPymg0uJVw?t=6095

**Comment by Kor-Angar** [comment]
ты же кажется их в Город отправляла? :)

**Comment by dosinabox** [comment]
- Рик и Румболд вернутся в Хоринис в третьей главе и не будут стоять у таверны до конца игры.
- Рик и Румболд появятся в Хоринисе в третьей главе, даже если ГГ не начал квест 'Прогнать ополчение'.

**Comment by Kor-Angar** [comment]
> Рик и Румболд вернутся в Хоринис в третьей главе и не будут стоять у таверны до конца игры.

а их во внутрь Таверны нельзя поставить? не очень понятно чего они на улице делают. и на падальщиков агрятся.

**Comment by dosinabox** [comment]
> а их во внутрь Таверны нельзя поставить?

Вроде как места нет. А на улице у них именные точки от разработчиков:
NW_RUMBOLD_FLUCHT3
NW_RUMBOLD_FLUCHT2

**Comment by Kor-Angar** [comment]
> Вроде как места нет.

Как нет? 😀 В 3 главе туда же сбежавший заключённые вставляются при игре за Наема.

**Comment by Kor-Angar** [comment]
> На улице у них именные точки от разработчиков:
> NW_RUMBOLD_FLUCHT3
> NW_RUMBOLD_FLUCHT2

Давай их на эти точки поставим со старта игры.

**Comment by dosinabox** [comment]
> Давай их на эти точки поставим со старта игры.

Тогда их можно будет убить или они сами погибнут от монстров поблизости. И испытания Торлофа окажутся под вопросом.

**Comment by Kor-Angar** [comment]
От монстров не погибнут. Теоретически герой может их убить. У Торлофа можно сделать проверку на их смерть, если мертвы то давать квест про Секоба. Но это маловероятно сценарий. Это возможно если игрок намеренно прокачается заранее и сделает так 😀А во второй главе их можно отправлять в город, если квест не будет выполнен.

**Comment by Kor-Angar** [comment]
как я понял ты добавила возможность прогнать Румболда и Рика с помощью заклинания страх, который добавила в продажу Игнацу. Квест про Румболда и Рика на вступление в наёмники самый сложный и даёт 5 голосов за Наёмника. Ты его свела к покупке свитка за 75 золотых? :-)

**Comment by dosinabox** [comment]
Ещё для Энгардо и Альвареса, но да, лучше уберу.

https://www.youtube.com/watch?v=9yAygB37sWQ

**Comment by Kor-Angar** [comment]
Добавь в Монастырь в продажу Магу в библиотеку. Маг Огня сможет воспользоваться против наёмников на ферме Акилла.

**Comment by dosinabox** [comment]
если Гораксу, то тогда сможет и послушник

**Comment by Kor-Angar** [comment]
Тому что в библиотеку. Он с магом торгует.

**Comment by dosinabox** [comment]
добавлено

**Comment by Kor-Angar** [comment]
а что то ты им AIV_DropDeadAndKill  не меняла, хотя где то в скриптах видел.. может не в том диалоге меняется? :-) https://github.com/Kor-Angar/G2_NotR_Kor_Angar/commit/2f0a2bf0b2df013019fe000fafa680fd6e780cb9

**Comment by dosinabox** [comment]
а зачем это?

**Comment by Kor-Angar** [comment]
Румбольду и Рику  AIV_DropDeadAndKill надо менять если они уходят по хорошему в город / таверну. по аналогии с тем как это происходит с Атилла.

self.aivar[AIV_DropDeadAndKill] = FALSE;

**Comment by dosinabox** [comment]
Если уходят в город - меняется (B_ENTER_NEWWORLD_Kapitel_3()).
Если уходят в таверну - не меняется. Добавить?

**Comment by Kor-Angar** [comment]
добавь. вот прям в диалоге у Румболда добавь после

Npc_ExchangeRoutine(self,"Flucht3");
B_StartOtherRoutine(Rick,"Flucht3");

**Comment by Kor-Angar** [comment]
если их игрок по привычке побьет, то  они не умрут и он уже сможет заметить изменения в игре. я вчера прям на стриме скрипты правил, ради них :-)

**оффтоп**
немогу найти топик про книгу лемара

**Comment by dosinabox** [comment]
> добавь. вот прям в диалоге у Румболда добавь после

Добавлено, но нужно не только там) https://github.com/dosinabox/g2nr_unofficial_update/commit/e189cba01c49226535bc63a070099e738a3080e5

**Comment by Kor-Angar** [comment]
Ты про свиток страх? 😀

**Comment by dosinabox** [comment]
`aivar[AIV_DropDeadAndKill] = FALSE;`

Было:
- при переходе в город в третьей главе

Добавлено:
- при переходе в таверну после использования свитка страха
- при переходе в таверну после принятия в ополчение
- при переходе в таверну после принятия в послушники
- при переходе в таверну в диалоге с Румболдом
- при переходе в таверну в диалоге с Кордом

**Comment by Kor-Angar** [comment]
> при переходе в таверну после принятия в послушники

гм.. а мы решили квест отменять если герой становится послушником? может лучше когда герой становится магом? что бы послушник мог довыполнять квест.

**Comment by dosinabox** [comment]
> может лучше когда герой становится магом?

Может. По сути послушник это ещё нейтрал в первой главе. Только после испытания он становится равным ополчению или наемникам.

**Comment by Kor-Angar** [comment]
не совсем конечно нейтрал, но менты вполне могут ему грубить и хамить :-)

**Comment by dosinabox** [comment]
> может лучше когда герой становится магом? что бы послушник мог довыполнять квест.

готово

**Comment by Kor-Angar** [comment]
Рик и Румболд. 2 глава https://www.youtube.com/watch?v=k8mJDVSHnok&feature=youtu.be
