### ISSUE TITLE
Хоринос 4 глава без перехода в Миненталь MIS_ReadyforChapter4

### ISSUE THREAD

**Issue by Kor-Angar** [dosinabox/g2nr_unofficial_update#89]
> MIS_ReadyforChapter4

Если это TRUE, то глава 4 начнется при входе в Миненталь. MIS_ReadyforChapter4 это такая глава 4 на время пребывания ГГ в Хоринисе.

_Originally posted by @dosinabox in https://github.com/dosinabox/g2nr_unofficial_update/issues/88#issuecomment-533786511_

**Comment by Kor-Angar** [comment]
Важная штука в плане торговцев и ковки. 

Можно крепко подумать где это можно, а где нужно использовать🙂

**Comment by dosinabox** [comment]
Наверное, лучше нигде не использовать, потому что в Хоринисе глава 4 не объявляется и не начинается. MIS_ReadyforChapter4 - "игрок восстановил Глаз, готов к началу четвертой главы". Это не равносильно новой главе.

**Comment by Kor-Angar** [comment]
Да. Но что делать игроку? Переходить в миненталь что бы роявилась заставка и тут же возвращатся в Хоринос что бы купить свитки? 🙂

**Comment by Kor-Angar** [comment]
То же самое с ковкой новых мечей у Беннета. Магу же дают выучить четвертый круг, а ОНД не дают выковать новый меч 🙂

**Comment by dosinabox** [comment]
> То же самое с ковкой новых мечей у Беннета. Магу же дают выучить четвертый круг, а ОНД не дают выковать новый меч 🙂

Можно начать с этого)

**Comment by dosinabox** [comment]
> То же самое с ковкой новых мечей у Беннета. Магу же дают выучить четвертый круг, а ОНД не дают выковать новый меч 🙂

Оказывается, уже дают:
```
else if((MIS_ReadyforChapter4 == TRUE) && (Kapitel < 5) && (Bennet_Kap4Smith == FALSE))
{
	AI_Output(self,other,"DIA_Bennet_TeachSmith_06_03");	//Это лучшее, что я умею ковать сейчас.
	Bennet_Kap4Smith = TRUE;
}
```

**Comment by dosinabox** [comment]
А вот фактически выучить их нельзя - нужна именно четвертая глава:
```
if((PLAYER_TALENT_SMITH[WEAPON_1H_Special_03] == FALSE) && (Kapitel >= 4))
{
	Info_AddChoice(DIA_Bennet_TeachSmith,B_BuildLearnString(NAME_ItMw_1H_Special_03,B_GetLearnCostTalent(other,NPC_TALENT_SMITH,WEAPON_1H_Special_03)),DIA_Bennet_TeachSmith_1hSpecial3);
};
if((PLAYER_TALENT_SMITH[WEAPON_2H_Special_03] == FALSE) && (Kapitel >= 4))
{
	Info_AddChoice(DIA_Bennet_TeachSmith,B_BuildLearnString(NAME_ItMw_2H_Special_03,B_GetLearnCostTalent(other,NPC_TALENT_SMITH,WEAPON_2H_Special_03)),DIA_Bennet_TeachSmith_2hSpecial3);
};
```
Исправлено!

**Comment by Kor-Angar** [comment]
Руны "первого уровня" у Пала давай на всякий случай ещё проверим:-)

**Comment by dosinabox** [comment]
> Руны "первого уровня" у Пала давай на всякий случай ещё проверим:-)

Даются при MIS_ReadyforChapter4 == TRUE, четвертую главу начинать не нужно:
```
func void DIA_Albrecht_TEACHPalRunes_Heal()
{
	AI_Output(other,self,"DIA_Albrecht_TEACHPalRunes_Heal_15_00");	//Я выбираю путь исцеления.
	if((PLAYER_TALENT_RUNES[SPL_PalLightHeal] == FALSE) && (MIS_ReadyforChapter4 == TRUE))
	{
		Info_ClearChoices(DIA_Albrecht_TEACHPalRunes);
		Info_AddChoice(DIA_Albrecht_TEACHPalRunes,Dialog_Back,DIA_Albrecht_TEACHPalRunes_BACK);
		Info_AddChoice(DIA_Albrecht_TEACHPalRunes,B_BuildLearnString(NAME_SPL_PalLightHeal,B_GetLearnCostTalent(other,NPC_TALENT_RUNES,SPL_PalLightHeal)),DIA_Albrecht_TEACHPalRunes_PalLightHeal);
	}
...
};

func void DIA_Albrecht_TEACHPalRunes_Combat()
{
	AI_Output(other,self,"DIA_Albrecht_TEACHPalRunes_Combat_15_00");	//Я выбираю путь битвы.
	if((PLAYER_TALENT_RUNES[SPL_PalHolyBolt] == FALSE) && (MIS_ReadyforChapter4 == TRUE))
	{
		Info_ClearChoices(DIA_Albrecht_TEACHPalRunes);
		Info_AddChoice(DIA_Albrecht_TEACHPalRunes,Dialog_Back,DIA_Albrecht_TEACHPalRunes_BACK);
		Info_AddChoice(DIA_Albrecht_TEACHPalRunes,B_BuildLearnString(NAME_SPL_PalHolyBolt,B_GetLearnCostTalent(other,NPC_TALENT_RUNES,SPL_PalHolyBolt)),DIA_Albrecht_TEACHPalRunes_PalHolyBolt);
	}
...
};
```

**Comment by Kor-Angar** [comment]
Тогда что у нас получается в сухом остатке

MIS_ReadyforChapter4:

- Маг - учит 4 круг в конце 3 главы
- Пал- получает руны  в конце 3 главы
- ОнД- учит ковку рудного меча (был баг)  в конце 3 главы

****************

добавления товаров (свитки/оружие/травы) через MIS_ReadyforChapter4 под вопросом. 


****************

от себя добавлю что мне очень нравится переменная MIS_ReadyforChapter4, так как она даёт понимание что авторы понимали что в конце 3 главы надо зарядить героя по полной, что бы он не возвращался в Хоринос не успев его покинуть :-) т.е. они видели  эту проблему(или в этой ситуации видели проблему) и решали её.

**Comment by dosinabox** [comment]
Собственно, у помощника теперь есть такая настройка.

**Comment by Kor-Angar** [comment]
Напомни пожалуйста ты какую задачу хотела решить таким образом? 21:08, 25 сентября 2020 г., dosinabox <notifications@github.com>:
Собственно, у помощника теперь есть такая настройка.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
-- Отправлено из мобильного приложения Яндекс.Почты

**Comment by dosinabox** [comment]
Чтобы не приходилось делать так:

> Переходить в миненталь что бы роявилась заставка и тут же возвращатся в Хоринос что бы купить свитки? 🙂
