### ISSUE TITLE
Руна Телепортации. Хаген

### ISSUE THREAD

**Issue by Kor-Angar** [dosinabox/g2nr_unofficial_update#93]
Лорд Хаген даёт руну телепортацию после того как ГГ отдаёт письмо. 
Возможно  давать руну телепортацию как даёт Ли и Пирокар. просто так :-)

**Comment by dosinabox** [comment]
Пусть дает после получения письма ИЛИ если ГГ разоблачил Корнелиуса.

**Comment by Kor-Angar** [comment]
можно и так :-)

**Comment by dosinabox** [comment]
> Пусть дает после получения письма ИЛИ если ГГ разоблачил Корнелиуса.

Готово.
