### ISSUE TITLE
Фернандо. Улики. Кольцо

### ISSUE THREAD

**Issue by Kor-Angar** [dosinabox/g2nr_unofficial_update#97]
Подскажи пожалуйста где кольцо которое идёт как улика против Фернандо. Я думал оно у одного из Бандитов в лагере бандитов между фермой Бенгара и Секоба

Уже второй раз найти не могу.

**Comment by dosinabox** [comment]
Мда. Случайно удалила его из инвентаря бандита, когда меняла им шпаги. Исправлено.
Можешь вставить себе читом: ItRi_Addon_BanditTrader.

**Comment by Kor-Angar** [comment]
Вставлял уже. Пару раз 🙂

Труп бандита пропадет, если колько не поднять?

**Comment by dosinabox** [comment]
> Труп бандита пропадет, если колько не поднять?

Пропадет, потому что кольцо не считается квестовым. Можно сделать кольцо квестовым или добавить этому бандиту старую золотую монетку.

> Вставлял уже. Пару раз 🙂

Помогло?)

**Comment by Kor-Angar** [comment]
> Помогло?)

конечно:-) вставил через консоль и сдал Фернандо.

> Пропадет, потому что кольцо не считается квестовым. Можно сделать кольцо квестовым или добавить этому бандиту старую золотую монетку.

наверное бандиту лучше добавить старую монетку. если кольцо будет квестовым это плохо так как кольцо можно будет сначала отдать как улику Фернандо, а потом Фернандо избить и кольцо забрать.

**Comment by dosinabox** [comment]
> если кольцо будет квестовым это плохо так как кольцо можно будет сначала отдать как улику Фернандо, а потом Фернандо избить и кольцо забрать.

Мыслишь верно, но кольцо не передается в инвентарь ни Мартину, ни Фернандо - оно просто удаляется у ГГ. Поэтому можно обойтись квестовым флагом.

**Comment by Kor-Angar** [comment]
может сделать что бы кольцо давало какой то символический бонус? например +10 к жизни?
