### ISSUE TITLE
Эликсир Духа. Константино.

### ISSUE THREAD

**Issue by Kor-Angar** [dosinabox/g2nr_unofficial_update#98]
У Константино появился эликсир духа(маны) +3 к мане. Раньше у него такого не было. Нововведение ? 🙂

https://github.com/dosinabox/g2nr_unofficial_update/issues/62

**Comment by dosinabox** [comment]
Ага. Для мага/послушника. Такая компенсация за необходимость продажи грибов повышающих ману. Может, неудачная.

**Comment by Kor-Angar** [comment]
Так я их выкупаю 🙂 продаю все грибы и выкупаю черные. Можно черные скинуть перед сдачей.

Если очень хочется давать бонус то тогда логично это делать в рамках диалога про Грибы, когда Константин рассказывает  про их магический эффект. 

Посмотри плиз при каких условиях идет диалог.

**Comment by Kor-Angar** [comment]
Может быть проще что бы Константино в рамках этого диалога "научил" ГГ (ученика) делать вытяжку из этих грибов. Или герой после того как послушал как бы сам научился этому? 
Таким обращом не надо съедать по 50 грибов, а их можно будет перегнать на алхимическом столе в эликсир +5 к мане.

**Comment by dosinabox** [comment]
> Может быть проще что бы Константино в рамках этого диалога "научил" ГГ (ученика) делать вытяжку из этих грибов. Или герой после того как послушал как бы сам научился этому?
> Таким обращом не надо съедать по 50 грибов, а их можно будет перегнать на алхимическом столе в эликсир +5 к мане.

Мне очень нравится эта идея. Нужно подумать, как её реализовать. Новый платный рецепт за копейки? Монтаж диалогов? Автоматическая запись в дневник? Просто новая опция для алхимического стола?

**Comment by Kor-Angar** [comment]
Давай для начало будем после этого диалога делать запись в дневнике в разделе алхимия.

Далее давай подумаем над компонентами, что нужно по мимо 50 грибов? можно взять те же компоненты что нужны для "чистой маны" + 50 грибов

Ввиду того что герой как бы сам пытается приготовить этот эликсир можно сделать несколько вариантов в алхимическом столе с разными компонентами. тогда герой сварит сначала два слабых эликсира которые повысят ману на +1, а потом  "поймёт" правильный рецепт и сможет делать эликсир на +5 к мане.

Монтаж диалогов вроде как и не нужен в данном случае. мне так кажется :-)

Давай добавим дополнительную опцию в алхимическом столе, но что бы она появлялась только после диалога с Константино.

Можно сделать так что бы когда герой выпивал эликсир он узнавал рецепт второго? а когда выпивал второй узнавал рецепт третьего?

**Comment by Kor-Angar** [comment]
> несколько вариантов в алхимическом столе с разными компонентами. тогда герой сварит сначала два слабых эликсира которые повысят ману на +1, а потом "поймёт" правильный рецепт и сможет делать эликсир на +5 к мане.

> Можно сделать так что бы когда герой выпивал эликсир он узнавал рецепт второго? а когда выпивал второй узнавал рецепт третьего?


Название | Компоненты | даёт | условия изучения 
-- | -- | -- | -- 
Эликсир чего то там 1 | 3 эссенции маны, 1 луговой горец, 10 грибов | +1 к макс. мане | рассказ Кости о грибах 
Эликсир чего то там 2 | 2 экстракта маны, 1 луговой горец, 20 грибов | +2 к макс. мане | выпить "Эликсир чего то там 1"
Эликсир чего то там 3 | 1  Эликсир маны, 1 луговой горец,   50 грибов | +5 к макс. мане | выпить "Эликсир чего то там 2"

предлагаю сделать так же  что бы он восстанавливал всю ману, как молитвы Инносу

**Comment by dosinabox** [comment]
Может, не надо так сложно? По-моему, достаточно просто иметь возможность применить все 50 грибов разом. И зелье +5 макс. маны уже существует. Или лучше что-то новое, с другим названием и моделью?
Думаю, что после диалога о свойствах грибов в продажу Константино можно добавить рецепт грибной вытяжки. Стоить она будет мало (каких-нибудь 50 золотых), а дополнительный ингредиент будет простым (какая-нибудь луговая ягода). Также грибная вытяжка полностью восстановит ману, так как не равняется 50 съеденным грибам.

Получится выбор:
- грызть 50 грибов долго и бесплатно
- купить рецепт за 50 золотых и сварить зелье из 50 грибов и луговой ягоды, чтобы получить бонус к мане быстрее и ещё полностью восстановить её

**Comment by dosinabox** [comment]
> * рецепт за 50 золотых и сварить зелье из 50 грибов и луговой ягоды, чтобы получить бонус к мане быстрее и ещё полностью восстановить её

Фактически получается ограниченная серия "Чистой маны", состоящая из одной только луговой ягоды)

**Comment by Kor-Angar** [comment]
Можно и так. Просто мысль развернул 😀

**Comment by Kor-Angar** [comment]
Наверное все таки с другим названием и моделью, что бы можно протестить и был задел на будущее.Тогда это зелье можно в "особые добавить".

**Comment by Kor-Angar** [comment]
Может экстракт маны + 50 грибов?

**Comment by dosinabox** [comment]
> Может экстракт маны + 50 грибов?

Слишком "дорого". Нужно просто заткнуть игровую условность.

Предлагаю продумать текст рецепта.
А диалог про грибы доступен только ученику Константино?
А если я добавлю такой рецепт, то нужно ли будет убрать из продажи эликсир духа? Сейчас он доступен магу и послушнику, который является учеником Константино.

**Comment by Kor-Angar** [comment]
Ягоду обычно всю съедаю так как стала давать  +5 к мане. Или ты про "луговой горец"?

**Comment by Kor-Angar** [comment]
> А диалог про грибы доступен только ученику Константино?

Да

**Comment by dosinabox** [comment]
> Ягоду обычно всю съедаю так как стала давать +5 к мане. Или ты про "луговой горец"?

Это для примера. Можно репу какую-нибудь или вообще сорняки)

**Comment by Kor-Angar** [comment]
> Слишком "дорого". Нужно просто заткнуть игровую условность.

Как это дорого?

**Comment by Kor-Angar** [comment]
Может тогда сделать

1 экстракта маны +100 грибов
И получать вытяжку +10 к мане?

**Comment by Kor-Angar** [comment]
> А если я добавлю такой рецепт, то нужно ли будет убрать из продажи эликсир духа?

Вообщем то да

**Comment by dosinabox** [comment]
> Как это дорого?

Ну вот предлагаю луговую ягоду, а ты говоришь что их все съедаешь. А экстракты не выпиваешь? По идее, они важнее и нужнее, чем ягоды.

> И получать вытяжку +10 к мане?

Нет смысла, потому что 10 это два раза по 5)

**Comment by Kor-Angar** [comment]
> Ну вот предлагаю луговую ягоду, а ты говоришь что их все съедаешь. А экстракты не выпиваешь? По идее, они важнее и нужнее, чем ягоды.

От стиля игры зависит. У меня экстрактом много, они есть в продаже. А ягоды в начале игры поедаю 😀

Я думаю это в целом не принципиально 😀 просто мы же делаем ещё так же эффект восстановить ману полностью, поэтому я и предлагаю вариант который схож с "чистой манной".

**Comment by dosinabox** [comment]
Нужно продавать этот рецепт всем ученикам или только послушнику и магу?

**Comment by Kor-Angar** [comment]
Всем. Мы же делаем это на основе рассказа Константино, а его диалог доступен ученику 😀

**Comment by dosinabox** [comment]
Готово всё, кроме модели зелья и текста рецепта.
Для новой опции алхимических столов требуется начало новой игры.

**Comment by Kor-Angar** [comment]
Модель наверное можно использовать обычную пока.

**Comment by Kor-Angar** [comment]
так же можно добавить счётчик и считать сколько черных грибов продал герой Константина. 
Если к примеру он продал больше 100 черных грибов, то в 3 главе в продажу к Константина можно добавлять 1 "грибной эликсир" или рецепт.

**Comment by Kor-Angar** [comment]
Закончилась у меня это трава. смог сварить только пару Грибных Эликсиров.

Может его делать всё таки на основе экстракта маны или огненной травы? они хотя бы есть в продаже ;-)

**Comment by dosinabox** [comment]
Давай текст рецепта продумаем)
