### ISSUE TITLE
Храм Аданоса. Комнаты с сундуком

### ISSUE THREAD

**Issue by Kor-Angar** [dosinabox/g2nr_unofficial_update#99]
Когда открывается сундук, включается анимация и каменные стражи оживают. 

Когда же все каменные стражи убиты, эта анимация становится бесмысленна. 

Так же в конце стрима видно, что если убивать с одного удара каменного стража, соседние не включаются.

**Comment by dosinabox** [comment]
> Когда же все каменные стражи убиты, эта анимация становится бесмысленна.

Исправлено.

**Comment by Kor-Angar** [comment]
закрываем? :-)

**Comment by dosinabox** [comment]
Пока пусть повисит, не знаю как пробуждать других при убийстве с одного удара. Ещё подумаю.

**Comment by dosinabox** [comment]
>  если убивать с одного удара каменного стража, соседние не включаются

Получилось исправить. За обе реакции (на смерть и урон соседа) отвечает одна и та же функция B_MM_AssessOthersDamage().
